"use client";

import { Trash2 } from "lucide-react";
import type { StudentSpreadsheetPreview } from "../../core/student-spreadsheet-import";

export function StudentImportPreview({ preview, contextLabel, onChange, onCancel, onConfirm }: { preview: StudentSpreadsheetPreview; contextLabel: string; onChange: (preview: StudentSpreadsheetPreview) => void; onCancel: () => void; onConfirm: () => void }) {
  const columnCount = Math.max(...preview.rows.map((row) => row.length), 0);
  const options = Array.from({ length: columnCount }, (_, index) => <option key={index} value={index}>{index + 1}. sütun • {preview.columnLabels[index] || "Başlıksız"}</option>);
  const studentRows = preview.rows.slice(preview.headerRow + 1).filter((row) => preview.numberColumn >= 0 && preview.nameColumn >= 0 && (row[preview.numberColumn] || row[preview.nameColumn])).slice(0, 5);
  return <section className="import-preview" data-testid="student-import-preview" aria-labelledby="shared-import-preview-title"><div className="import-preview-heading"><div><strong id="shared-import-preview-title">İçe aktarma önizlemesi</strong><span>{preview.fileName} • {contextLabel} • Henüz öğrenci listesine uygulanmadı</span></div><button type="button" className="row-delete" onClick={onCancel} aria-label="İçe aktarma önizlemesini iptal et"><Trash2 size={15}/></button></div><div className="import-mapping-grid"><label className="field"><span>Öğrenci numarası sütunu</span><select value={preview.numberColumn} onChange={(event)=>onChange({ ...preview, numberColumn:Number(event.target.value) })}><option value={-1}>Sütun seçin</option>{options}</select></label><label className="field"><span>Ad-soyad sütunu</span><select value={preview.nameColumn} onChange={(event)=>onChange({ ...preview, nameColumn:Number(event.target.value) })}><option value={-1}>Sütun seçin</option>{options}</select></label><label className="field"><span>E-Okul toplam puanı (isteğe bağlı)</span><select value={preview.totalColumn} onChange={(event)=>onChange({ ...preview, totalColumn:Number(event.target.value) })}><option value={-1}>Toplam puanı alma</option>{options}</select></label></div><div className="import-preview-table import-preview-table--scores" role="table" aria-label="İlk beş öğrenci satırı önizlemesi"><div role="row"><strong role="columnheader">Öğrenci numarası</strong><strong role="columnheader">Ad soyad</strong><strong role="columnheader">E-Okul toplamı</strong></div>{studentRows.map((row,index)=><div role="row" key={index}><span role="cell">{row[preview.numberColumn]||"Eksik"}</span><span role="cell">{row[preview.nameColumn]||"Eksik"}</span><span role="cell">{preview.totalColumn>=0?row[preview.totalColumn]||"Boş":"Alınmayacak"}</span></div>)}</div><div className="import-preview-actions"><span>Önizlemede yalnız numara ve ad-soyad gösterilir; E-Okul toplamı ayrı bir kontrol değeridir. Toplam puan soru puanlarına dağıtılmaz.</span><button type="button" className="primary-button" disabled={preview.numberColumn<0||preview.nameColumn<0||preview.numberColumn===preview.nameColumn} onClick={onConfirm}>Eşlemeyi onayla ve içe aktar</button></div></section>;
}
