import type { Focus, Task } from './philosophy-early-units-2026.ts';
import { task, W } from './philosophy-grade11-units-2026.ts';

// FEL.11.2 — Teknoloji ve Hayat. Özgün iki vaka (düşünür adı ve alıntı yok); ikisi de Aytekin tarafından onaylandı.
// Vaka 1 (ontolojik problemler: anlam kaybı, yabancılaşma, zaman ve mekân) → FEL.11.2.1.
//   Ali: teknoloji tarafsız bir araçtır (teknoloji taraftarlığı); Büşra: teknoloji yaşantının anlamını götürür (teknoloji karşıtlığı);
//   Cenk: araç tarafsız değildir ama vazgeçmek çözüm değildir. Yükler: aracın tarafsızlığı, ekranlı yaşantının anlamsızlığı, ölçütün belirsizliği.
// Vaka 2 (aksiyolojik problemler: güvenlik, değerlerin tahribatı, ahlaki eylemin imkânı) → FEL.11.2.2.
//   Emre: güvenlik önce gelir; Fatma: izlenme davranışı ve güveni bozar; Gökhan: karar makineye bırakılırsa sorumluluk belirsizleşir.
// Kapsam dışı: simülasyon kuramı, sosyal medya, afet ve salgın projeleri, tüketim-konfor tartışması, robot tarihi.
// 11.2.2 c: yazım görevinin ölçütü, programın 7 ölçütlü 100 puanlık Felsefi Metin Yazımı anahtarının 32/32/36 gruplamasıdır (bkz. 11.1).
const ontological = 'Bir ilçede aileler, bayram ziyaretleri yerine görüntülü görüşmeyi tercih etmeye başladı. Üç öğrenci bunu tartışıyor. Ali: “Teknoloji amaçlarımız için bir araçtır; uzaktakilere kolayca ulaşmamızı sağlıyor. Kötü olan araç değil, kullanım biçimidir.” Büşra: “Ziyaretin yolu, sofrası, bekleyişi onun anlamının parçası. Ekrandan görüşmek bu anlamı götürür; teknoloji insanı yaşadığı şeyden uzaklaştırır.” Cenk: “Aracın değişmesi, buluşmanın ne olduğuna dair algımızı da değiştiriyor. Teknoloji tarafsız bir araç değil ama hepsinden vazgeçmek de çözüm olmaz.” Öğretmen, tartışmanın teknolojinin “amaç için araç” olup olmadığı ve insan hayatındaki anlamı nasıl etkilediği sorularına dayandığını belirtir.';
const axiological = 'Bir belediye, kentin kavşaklarına yüz tanıyan güvenlik kameraları kurmayı planlıyor; kameralar suçları azaltacak, görüntüleri saklayacak ve şüpheli davranışları bir yazılım işaretleyecek. Üç öğrenci tartışıyor. Emre: “Can güvenliği her şeyden önce gelir; kişisel bilgiler önlemlerle korunabilir.” Fatma: “Sürekli izlenen insan davranışını değiştirir; güven yerini kuşkuya bırakır. Güvenlik uğruna vazgeçtiğimiz değerleri kaybederiz.” Gökhan: “Yazılım yanlış kişiyi işaretlerse kim sorumlu? Karar bir makineye bırakılırsa ahlaki sorumluluk kime ait olur?” Öğretmen, tartışmanın teknolojinin güvenliği ve değerleri nasıl etkilediğine ve kararların sorumluluğunun kime ait olduğuna dayandığını belirtir.';

// ---------- FEL.11.2.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: teknoloji yalnız amaç için tarafsız bir araç mıdır; bu soru teknolojinin kendisinin insan hayatında bir etkisi olup olmadığını sorgular. İkinci soru: teknoloji, insanın yaşadığı şeyin anlamını nasıl etkiler; bu soru anlamın yaşantının kendisine mi yoksa onu mümkün kılan araca mı bağlı olduğunu sorgular.',
    ['“Amaç için araç” sorusunun açıklanması', 'teknolojinin tarafsız bir araç olup olmadığını ve kendi başına bir etkisinin bulunup bulunmadığını sorguladığını belirtir'],
    ['Anlam sorusunun açıklanması', 'teknolojinin yaşantının anlamını nasıl etkilediğini ve anlamın neye bağlı olduğunu sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması (teknoloji)', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Ali, Büşra ve Cenk’in sözlerinin her birinin teknolojinin “amaç için araç” olup olmadığı sorusuna nasıl bir cevap verdiğini belirtiniz.',
    'Ali teknolojiyi tarafsız bir araç sayar; iyi ya da kötü olanın kullanım olduğunu söyler. Büşra teknolojinin araç olmaktan öte, yaşantının anlamını götürdüğünü söyler. Cenk teknolojinin tarafsız bir araç olmadığını, buluşma algımızı da değiştirdiğini ama vazgeçmenin çözüm olmadığını söyler.',
    ['Ali’nin cevabının belirlenmesi (teknoloji)', 'Ali’nin teknolojiyi tarafsız bir araç saydığını belirtir'],
    ['Büşra’nın cevabının belirlenmesi (teknoloji)', 'Büşra’nın teknolojinin yaşantının anlamını götürdüğünü söylediğini belirtir'],
    ['Cenk’in cevabının belirlenmesi (teknoloji)', 'Cenk’in aracın tarafsız olmadığını ama vazgeçmenin çözüm olmadığını söylediğini belirtir']),
  task('apply', '“Ontolojik anlam” ve “yabancılaşma” kavramlarını metindeki duruma uygulayarak her birinin bu durumda neyi gösterdiğini açıklayınız.',
    'Ontolojik anlam: bir şeyin ne olduğunu ve nasıl bir değer taşıdığını belirleyen bütünlük; bayram ziyaretinin yolu, sofrası ve bekleyişiyle taşıdığı anlam. Yabancılaşma: insanın yaşadığı şeyden ya da başkalarından uzaklaşması; Büşra’ya göre ekrandan görüşmek insanı ziyaretin yaşantısından uzaklaştırır. İki kavram aynı şey değildir: biri şeyin anlamını, diğeri insanın ona olan uzaklığını gösterir. Kavramları duruma doğru bağlayan eşdeğer açıklamalar kabul edilir.',
    ['Ontolojik anlamın durumda gösterilmesi', 'ziyaretin yol, sofra ve bekleyişle taşıdığı anlamı belirtir'],
    ['Yabancılaşmanın durumda gösterilmesi', 'insanın yaşadığı şeyden ya da başkalarından uzaklaşmasını durumla ilişkilendirir'],
    ['İki kavramın ayrılması (anlam ve yabancılaşma)', 'anlam ile yabancılaşma arasındaki farkı korur']),
  task('apply', '“Zaman ve mekân” kavramını metindeki duruma uygulayarak görüntülü görüşmenin zaman ve mekân algısını nasıl değiştirebileceğini açıklayınız.',
    'Görüntülü görüşme mekân uzaklığını ortadan kaldırır: uzaktaki aileyle aynı anda buluşmak mümkün olur. Yolculuk ve bekleyiş gibi zaman da kalmaz ya da kısalır; buluşma kısa ve her an yapılabilir hâle gelir. Böylece ziyaretin ne zaman ve nerede gerçekleştiğine dair algı değişir. Bu değişimin kazanç mı kayıp mı olduğu ayrıca tartışılır; açıklamada bu değişimi doğru gösteren her cevap kabul edilir.',
    ['Mekân algısının değişiminin gösterilmesi', 'uzaklığın ortadan kalktığını ve buluşmanın mekâna bağlılığının azaldığını belirtir'],
    ['Zaman algısının değişiminin gösterilmesi', 'yolculuk ve bekleyiş zamanının kalktığını ya da kısaldığını belirtir'],
    ['Değişimin yargıdan ayrı gösterilmesi', 'değişimin kazanç ya da kayıp olduğu yargısını betimlemeden ayırır']),
  task('analyze', 'Üç öğrencinin teknolojiye bakışını “teknoloji taraftarlığı” ve “teknoloji karşıtlığı” kavramlarıyla ayırarak karşılaştırınız.',
    'Ali teknoloji taraftarıdır: teknolojiyi ulaşımı kolaylaştıran tarafsız bir araç sayar. Büşra teknoloji karşıtıdır: teknolojinin yaşantıdan uzaklaştırdığını ve anlamı götürdüğünü savunur. Cenk ikisinden de ayrılır: teknolojinin etkisini kabul eder ama vazgeçmeyi savunmaz. Ortak soru, teknolojinin yaşantıyı nasıl etkilediğidir; üçü de bu soruya farklı bir tutumla cevap verir.',
    ['Ali ile Büşra’nın bakışlarının ayrılması', 'Ali’nin taraftarlığını ve Büşra’nın karşıtlığını gerekçeleriyle ayırır'],
    ['Cenk’in bakışının ayrılması', 'Cenk’in iki bakışın da dışında üçüncü bir tutum aldığını gösterir'],
    ['Ortak sorunun belirlenmesi (teknoloji)', 'üç sözün de teknolojinin yaşantıyı nasıl etkilediği sorusuna cevap olduğunu belirtir']),
  task('analyze', 'Ali “Kötü olan araç değil, kullanım biçimidir” der. Bu söz aracın tarafsız olduğunu varsayar; bu varsayımın hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Ali’nin sözü, teknolojinin yalnız kullanıcının amacını gerçekleştirdiğini ve başka bir etkisi olmadığını varsayar. Bu varsayım, aracın kendisinin alışkanlıkları, buluşmanın ne olduğuna dair algıyı ve zaman-mekân deneyimini değiştirip değiştirmediği sorusunu görünmez kılar. Cenk’in itirazı tam bu soruya yöneliktir. Kullanımı kötü olmayan bir araç da yaşantının biçimini değiştirebilir.',
    ['Ali’nin varsayımının gösterilmesi', 'aracın tarafsız olduğu ve yalnız kullanımın etkili olduğu varsayımını gösterir'],
    ['Görünmez kalan sorunun adlandırılması (araç)', 'aracın kendi başına yaşantıyı değiştirip değiştirmediği sorusunu belirtir'],
    ['Cenk’in itirazıyla ilişkilendirilmesi', 'Cenk’in itirazının bu soruya yöneldiğini gösterir']),
  task('evaluate', 'Büşra’nın “Ekrandan görüşmek ziyaretin anlamını götürür” iddiasını metne dayanarak değerlendiriniz.',
    'İddia kısmen savunulabilir: ziyaretin anlamı yolu, sofrası ve bekleyişiyle birlikte taşınıyorsa ekran bunları taşımaz. Ancak Büşra anlamın yalnız bu öğelere bağlı olduğunu ve ekranlı görüşmenin kendine özgü bir anlam kuramayacağını göstermemiştir; uzakta yaşayan biri için görüşme ile hiç görüşmeme arasındaki fark da hesaba katılmalıdır. İddia bu yüzden gerekçesiyle sınırlanmış biçimde kabul edilebilir. Gerekçeli karşı değerlendirme de kabul edilir.',
    ['İddianın savunulabilir yanının gösterilmesi', 'ziyaretin anlamının yol ve sofra gibi öğelere bağlı olabileceğini kabul eder'],
    ['İddianın eksik gerekçesinin belirtilmesi', 'anlamın yalnız bu öğelere bağlı olduğunun ve ekranın yeni anlam kuramayacağının gösterilmediğini belirtir'],
    ['Gerekçeli değerlendirme yargısı (anlam iddiası)', 'iddiayı gerekçesiyle sınırlı ya da değil olarak değerlendirir']),
  task('evaluate', 'Cenk’in “Teknoloji tarafsız bir araç değil ama hepsinden vazgeçmek çözüm olmaz” tutumunun Ali ve Büşra’ya karşı bir güçlü ve bir zayıf yanını değerlendiriniz.',
    'Güçlü yan: Cenk, Ali’nin tarafsızlık varsayımını ve Büşra’nın vazgeçme sonucunu birlikte sınar; iki görüşün haklı yanını alır. Zayıf yan: hangi teknolojiden vazgeçilip hangisine kalınacağını belirleyecek bir ölçüt vermez; tutum bu yüzden kararsız kalabilir. Güçlü ve zayıf yanı Cenk’in sözüne dayanarak gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın gösterilmesi', 'Cenk’in iki görüşün sınırlarını birlikte gösterdiğini belirtir'],
    ['Zayıf yanın gösterilmesi', 'Cenk’in ölçüt vermediğini ya da kararsız kaldığını belirtir'],
    ['Değerlendirmenin metne dayanması', 'her iki yanı Cenk’in sözüne bağlayarak gerekçelendirir']),
  task('create', 'Metindekilerden farklı, teknolojiyle ilgili bir felsefi soru yazınız ve bu sorunun neden felsefi olduğunu açıklayınız.',
    'Örnek soru: Teknoloji insanın zaman algısını değiştirebilir mi? Neden felsefi: zaman ve algı kavramlarının anlamını ve teknolojinin bunlara etkisini sorgular; ölçümle ya da kayıtla cevaplanmaz. Teknolojiyle ilgili, metindekilerden farklı ve bir kavram ya da kabulü sorgulatan her gerekçeli soru kabul edilir.',
    ['Metindekilerden farklı bir sorunun yazılması (teknoloji)', 'teknolojiyle ilgili, metindekilerden farklı bir soru yazar; yalnız durum anlatmak bu ölçütü karşılamaz'],
    ['Sorunun kavram ya da kabulü sorgulattığının gösterilmesi (teknoloji)', 'sorunun hangi kavramı ya da kabulü (anlam, zaman, araç gibi) sorgulattığını belirtir'],
    ['Sorunun neden felsefi sayıldığının gerekçelendirilmesi (teknoloji)', 'sorunun olgusal ya da ölçümle cevaplanan bir soru olmadığını gerekçeyle gösterir']),
  task('create', 'Metindekilerden farklı, teknolojiyle ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun (anlam kaybı, yabancılaşma, aracın tarafsızlığı gibi) bulunduğunu belirtiniz.',
    'Örnek durum: Bir aile, fotoğrafı anıyı yaşamak yerine paylaşmak için çekiyor; anının yaşanması ile paylaşılması arasındaki ilişki değişiyor. Felsefi sorun: teknolojinin yaşantının anlamını etkileyip etkilemediği ve insanı yaşadığı şeyden uzaklaştırıp uzaklaştırmadığı. Durumu ve sorunu tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün ve teknolojiyle ilgili bir durumun yazılması', 'metindekilerden farklı, teknolojiyi içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi (teknoloji)', 'durumda anlam kaybı, yabancılaşma ya da araçlık sorusunun nerede ortaya çıktığını belirtir'],
    ['Sorunun durumla tutarlı açıklanması (teknoloji)', 'belirttiği felsefi sorunun yazdığı durumdan gerçekten çıktığını gösterir']),
];

// ---------- FEL.11.2.1 b: hayatla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın gündelik yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: arkadaşla buluşmak yerine mesajlaşmak; bir tatili yaşamak yerine fotoğraflayıp paylaşmak. Tartışmayla aynı soruyu (teknoloji araç mı, anlamı değiştiriyor mu) gündeme getiren her örnek kabul edilir.',
    ['Gündelik yaşamdan örneğin verilmesi (teknoloji)', 'öğrencinin çevresinde karşılaşabileceği somut bir durum belirtir'],
    ['Örneğin tartışmayla ilişkilendirilmesi (teknoloji)', 'örnekte teknolojinin araç olması ile yaşantının anlamı arasındaki gerilimi gösterir'],
    ['Açıklamanın anlaşılır olması (teknoloji)', 'örneği ve bağlantıyı anlaşılır biçimde yazar']),
  task('understand', 'Ali, Büşra ve Cenk’in görüşlerinden birinin günlük yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Örnek (Ali): teknolojiye amaca ulaşmak için başvurulur; kullanımın amacı sorgulanır, aracın kendisi sorgulanmaz. Örnek (Büşra): bazı etkinlikler bilerek teknolojisiz yapılır, ekransız zaman ayrılır. Örnek (Cenk): hangi aracın hangi anlamı koruduğuna bakılarak seçici davranılır. Görüşle tutarlı doğru bir tutum açıklanırsa tam puan verilir.',
    ['Görüşün belirtilmesi (teknoloji)', 'üç görüşten birini adıyla belirtir'],
    ['Görüşten çıkan tutumun açıklanması (teknoloji)', 'görüşün günlük yaşamda yol açabileceği somut bir tutumu yazar'],
    ['Tutumun görüşle tutarlı olması (teknoloji)', 'tutumu görüşün dayandığı iddiayla (araç, anlam kaybı, seçicilik) ilişkilendirir']),
  task('apply', 'Kendi hayatınızdan (okul, aile, arkadaşlık) teknolojinin bir şeyin anlamını değiştirdiği bir durum seçiniz ve metindeki iki görüşün bu duruma nasıl yaklaşacağını yazınız.',
    'Örnek: sınıfta tahta yerine ekranda ders işlemek. Ali aracın amacı gerçekleştirmesine bakar; Büşra yazma ve bekleme gibi öğelerin anlamının kaybolup kaybolmadığını sorar; Cenk aracın dikkat ve algıyı değiştirdiğini ama vazgeçmenin çözüm olmadığını söyler. Seçilen durum gerçek olmalı ve iki görüşün yaklaşımı kendi ölçütleriyle tutarlı yazılmalıdır; iki görüşün aynı sonuca varması zorunlu değildir.',
    ['Durumun belirtilmesi (teknoloji)', 'kendi hayatından teknolojinin anlamı değiştirdiği somut bir durum seçer'],
    ['İki görüşün duruma uygulanması (teknoloji)', 'seçtiği iki görüşün duruma nasıl yaklaşacağını kendi ölçütleriyle tutarlı yazar'],
    ['Görüşlerin ayrımının korunması (teknoloji)', 'iki görüşü birbirinin yerine koymaz; yaklaşımların farkını gösterir']),
  task('apply', 'Bir arkadaş buluşmasının mesajlaşma yoluyla yapılması örneğine metindeki üç görüşün nasıl yaklaşacağını yazınız.',
    'Ali: mesajlaşma amaca (haberleşmeye) ulaşmanın kolay bir aracıdır; sorun kullanımda olabilir. Büşra: buluşmanın yüz yüze olmanın taşıdığı anlam kaybolur, insanlar birbirinden uzaklaşır. Cenk: mesajlaşma buluşmanın ne olduğuna dair algıyı da değiştirir; ama tümüyle bırakmak çözüm değildir, yüz yüze buluşma ile birlikte kullanılabilir.',
    ['Ali’nin yaklaşımının uygulanması (teknoloji)', 'mesajlaşmayı amaca ulaşmak için bir araç olarak değerlendirir'],
    ['Büşra’nın yaklaşımının uygulanması (teknoloji)', 'yüz yüze buluşmanın anlamının kaybı ve uzaklaşma kaygısını belirtir'],
    ['Cenk’in yaklaşımının uygulanması (teknoloji)', 'aracın algıyı değiştirdiğini ama vazgeçmenin çözüm olmadığını belirtir']),
  task('analyze', 'Telefonunuzu günlük yaşamda kullanma biçiminizi, teknolojinin bir araç olması ve anlam taşıması bakımından çözümleyiniz.',
    'Örnek: telefonu haber almak ve haberleşmek için kullanmak aracın amaç için kullanımıdır. Aynı telefon dikkati sürekli bölüyor ve bir anı yaşamak yerine paylaşmaya çağırıyorsa, aracın yaşantıyı etkilediği görülür. İki yönü ayırarak çözümleyen ve hangi kullanımın hangi yönü gösterdiğini belirten cevaplar kabul edilir.',
    ['Aracın amaç için kullanımının belirtilmesi', 'telefonun araç olarak karşıladığı amacı belirtir'],
    ['Anlam ve yaşantıya etkisinin belirtilmesi', 'telefonun dikkat ya da anı yaşama biçimini etkilediğini belirtir'],
    ['İki yönün ayrılması ve ilişkilendirilmesi', 'araçlık ile anlama etkiyi ayırır ve aralarındaki ilişkiyi gösterir']),
  task('analyze', 'Harita uygulamasıyla yol bulmanın kolaylığı ile yolu keşfetmenin anlamı arasında hangi değerlerin çatıştığını çözümleyiniz.',
    'Çatışan değerler: kolaylık, hız ve güvenlik ile deneyimin ve yolu tanımanın anlamı. Uygulama yolu bulmayı kolaylaştırır; ama kişi yolu keşfetmenin ve çevresini tanımanın yaşantısını yitirebilir. Bu çatışma yalnız kullanışlılık hesabıyla çözülmez, çünkü hangi değerin öne alınacağı bir değer ve anlam sorusudur.',
    ['Kolaylık tarafının belirlenmesi', 'kolaylık, hız ya da güvenlik gibi yararları belirtir'],
    ['Anlam tarafının belirlenmesi', 'yolu keşfetme ve çevreyi tanıma yaşantısının anlamını belirtir'],
    ['Çatışmanın felsefi niteliğinin gösterilmesi (teknoloji)', 'çatışmanın yalnız kullanışlılık hesabıyla çözülemeyeceğini, değer ve anlam sorusu içerdiğini gösterir']),
  task('evaluate', '“Teknolojisiz yaşamak artık imkânsız; bu yüzden anlam kaybı kaygısı gereksizdir” yargısını günlük yaşamla ilişkilendirerek değerlendiriniz.',
    'Yargı kısmen doğrudur: teknolojiden tümüyle vazgeçmek günlük yaşamda çoğu zaman olanaksızdır. Ancak vazgeçilemez olması, teknolojinin yaşantının anlamını etkileyip etkilemediği sorusunu ortadan kaldırmaz; anlam kaybı kaygısı vazgeçmeyi değil, nasıl kullanılacağını sorgular. Bu ayrımı gerekçeleyen değerlendirmeler kabul edilir.',
    ['Yargının doğru yanının belirlenmesi (teknoloji)', 'teknolojiden tümüyle vazgeçmenin güç olduğunu kabul eder'],
    ['Yargının sınırının günlük yaşamla gösterilmesi (teknoloji)', 'vazgeçilemezliğin anlam sorusunu ortadan kaldırmadığını gösterir'],
    ['Gerekçeli değerlendirme yargısı (teknoloji)', 'zorunluluk ile anlam sorusunu ayırarak gerekçeli yargıya varır']),
  task('evaluate', 'Metindeki üç görüşten hangisinin günlük yaşamdaki bir teknoloji kararında en savunulabilir olduğunu, bir güçlü ve bir zayıf yanıyla gerekçelendirerek değerlendiriniz.',
    'Her görüş gerekçeyle seçilebilir. Ali: güçlü yan, teknolojiyi amaca bağlayarak karar vermeyi kolaylaştırması; zayıf yan, aracın tarafsız olduğunu göstermemesi. Büşra: güçlü yan, yaşantının anlamını görmesi; zayıf yan, ekranlı yaşantının anlamsız olduğunu göstermemesi. Cenk: güçlü yan, iki görüşün haklı yanını alması; zayıf yan, ölçüt vermemesi.',
    ['Görüşün ve kararın belirtilmesi (teknoloji)', 'bir görüşü ve günlük yaşamdan bir teknoloji kararını belirtir'],
    ['Güçlü ve zayıf yanın gösterilmesi (teknoloji)', 'seçtiği görüşün bir güçlü ve bir zayıf yanını kararla ilişkilendirerek gösterir'],
    ['Savunulabilirlik yargısının gerekçelendirilmesi (teknoloji)', 'görüşün neden en savunulabilir olduğunu zayıf yanını da hesaba katarak gerekçelendirir']),
  task('create', 'Günlük yaşamınızdan bir teknoloji kullanımı seçiniz; bunun hangi felsefi soruyu gündeme getirdiğini yazınız ve bu soruya gerekçeli bir yanıt oluşturunuz.',
    'Örnek: bir anıyı yaşarken sürekli video çekmek; teknolojinin anıyı yaşama biçimini etkileyip etkilemediği sorusunu gündeme getirir. Örnek yanıt: Evet, çünkü kayıt amacı dikkatini yaşantıdan ayırır ve anının anlamı kaydedilmesine bağlanır. Soruyu doğru kuran ve yanıtını gerekçelendiren her özgün çalışma kabul edilir.',
    ['Gündelik teknoloji kullanımının belirtilmesi', 'günlük yaşamdan somut bir teknoloji kullanımı seçer'],
    ['Gündeme getirilen felsefi sorunun yazılması (teknoloji)', 'kullanımın anlam, araçlık ya da yabancılaşma gibi felsefi bir soruyu gündeme getirdiğini belirtir'],
    ['Soruya gerekçeli yanıt verilmesi (teknoloji)', 'sorusuna dayanağı olan tutarlı bir yanıt verir']),
  task('create', 'Teknolojiyle ilişkimizi anlamı koruyacak biçimde düzenleyen bir “ne yapmalıyız?” önerisi yazınız ve önerinin dayandığı değeri belirtiniz.',
    'Örnek: Aile yemeklerinde telefon kullanılmamalı; öneri, birlikte olmanın ve yaşantının anlamının korunması değerine dayanır. Günlük yaşama uygun öneri ile onun dayandığı değeri (anlam, bağ, dikkat vb.) doğru bağlayan her özgün çalışma kabul edilir.',
    ['Günlük yaşama uygun önerinin yazılması (teknoloji)', 'somut ve uygulanabilir bir öneri yazar'],
    ['Önerinin dayandığı değerin belirtilmesi (teknoloji)', 'öneriyi bir değere (anlam, bağ, dikkat gibi) bağlar'],
    ['Öneri ile değerin tutarlı bağlanması (teknoloji)', 'değerin öneriyi neden desteklediğini açıklar']),
];

// ---------- FEL.11.2.2 a: felsefi argümanları çözümler ----------
const a2: Task[] = [
  task('understand', 'Emre’nin sözündeki öncülleri ve sonucu ayırarak yazınız.',
    'Birinci öncül: can güvenliği her şeyden önce gelir. İkinci öncül: kişisel bilgiler önlemlerle korunabilir. Sonuç (örtük): kameralar kurulabilir.',
    ['Güvenlik öncülünün belirlenmesi', 'can güvenliğinin her şeyden önce geldiğini öncül olarak ayırır'],
    ['Koruma öncülünün belirlenmesi', 'kişisel bilgilerin önlemlerle korunabileceğini ikinci öncül olarak ayırır'],
    ['Örtük sonucun ayrılması', 'sonucun kameraların kurulabileceği olduğunu, sözde açıkça söylenmediğini belirtir']),
  task('understand', 'Fatma’nın sözündeki olgu iddiasını ve değer iddiasını ayırarak yazınız.',
    'Olgu iddiası: sürekli izlenen insan davranışını değiştirir ve güven yerini kuşkuya bırakır. Değer iddiası: güvenlik uğruna vazgeçilen değerler kaybedilir ve bu kayıp istenmez.',
    ['Olgu iddiasının ayrılması', 'izlenmenin davranışı ve güveni değiştirdiği iddiasını olgu iddiası olarak ayırır'],
    ['Değer iddiasının ayrılması', 'güvenlik uğruna değerlerin kaybedildiği ve bunun istenmediği iddiasını değer iddiası olarak ayırır'],
    ['İki iddianın birbirine karıştırılmaması', 'olguyu değerle, değeri olguyla karıştırmaz']),
  task('apply', 'Gökhan’ın sorusunu, kameranın yanlış bir kişiyi şüpheli işaretlediği bir olaya uygulayınız; bu olayda sorumluluğun kimlere ait olabileceğini ve sorunun neden belirsizleştiğini yazınız.',
    'Yazılımı yapan, işleten kurum, işaretlemeye bakarak karar veren görevli ve kurulumu onaylayan belediye sorumlu olabilir. Gökhan’a göre karar bir makineye bırakıldığında kimin eylediği belirsizleşir ve ahlaki sorumluluk zincire dağılır. Sorun belirsizleşir çünkü yazılım kendisi ahlaki sorumluluk taşıyan bir özne gibi görünmez; sorumluluğun kime yükleneceği ayrıca belirlenmelidir.',
    ['Olaya sorumluların belirtilmesi', 'yazılımı yapan, işleten ya da karar veren gibi olası sorumluları belirtir'],
    ['Gökhan’ın sorusunun uygulanması', 'sorumluluğun karar makineye bırakılınca belirsizleştiğini olayla ilişkilendirir'],
    ['Belirsizliğin nedeninin gösterilmesi', 'yazılımın ahlaki özne olmadığı ve sorumluluğun ayrıca belirlenmesi gerektiği için sorunun belirsizleştiğini belirtir']),
  task('apply', 'Emre’nin ilkesini, kameranın görüntülerinin izinsiz üçüncü kişilere sızdığı yeni bir duruma uygulayınız; Emre’nin nasıl bir sonuca varacağını gerekçesiyle yazınız.',
    'Emre’nin öncülü kişisel bilgilerin önlemlerle korunabileceğidir. Sızıntı bu öncülü zayıflatır; Emre ya önlemlerin güçlendirilmesini ister ya da öncülünü gözden geçirir. Can güvenliğinin önceliğini savunmayı sürdürebilir ama koruma öncülünün artık koşulsuz olmadığını kabul etmelidir. Sonucu ilkeye bağlayan her tutarlı cevap kabul edilir.',
    ['Emre’nin öncülünün duruma uygulanması', 'koruma öncülünün sızıntı durumuyla zayıfladığını gösterir'],
    ['Emre’nin olası sonucunun yazılması', 'Emre’nin önlemleri güçlendirmesi ya da öncülünü gözden geçirmesi gibi tutarlı bir sonuç yazar'],
    ['Sonucun görüşten fazlasını söylememesi (güvenlik)', 'Emre’ye söylemediği bir iddiayı yüklemez']),
  task('analyze', 'Üç görüşün güçlü ve zayıf yanlarını birer cümleyle belirleyerek bir karşılaştırma tablosu biçiminde yazınız.',
    'Emre: güçlü yan, can güvenliğini somut bir önceliğe bağlaması; zayıf yan, kameraların güvenliği gerçekten artırdığını ve önlemlerin yeterli olduğunu göstermemesi. Fatma: güçlü yan, izlenmenin değerlere etkisini görmesi; zayıf yan, izlenmenin davranışı bozduğunu ve bu kaybın güvenlik kazancından ağır olduğunu göstermemesi. Gökhan: güçlü yan, sorumluluk sorununu görünür kılması; zayıf yan, sorumluluğun makineye değil kuran ve işleten insanlara ait olabileceği olasılığını hesaba katmaması.',
    ['Emre’nin güçlü ve zayıf yanlarının belirlenmesi', 'Emre için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir'],
    ['Fatma’nın güçlü ve zayıf yanlarının belirlenmesi', 'Fatma için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir'],
    ['Gökhan’ın güçlü ve zayıf yanlarının belirlenmesi', 'Gökhan için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir']),
  task('analyze', 'Fatma’nın “izlenme davranışı değiştirir” öncülü ile “değerleri kaybederiz” sonucu arasında hangi örtük öncülün gerektiğini çözümleyiniz.',
    'Örtük öncül: izlenmeyle değişen davranış ve güven kaybı bir değer kaybıdır ve bu kayıp güvenlik kazancından ağır basar. Metinde bu öncül söylenmemiştir; öncül ile sonuç arasındaki geçiş buna dayanır. Öncül kanıtlanmamıştır: davranış değişiminin her durumda değer kaybı olduğu ve kameraların sağladığı güvenlikten daha ağır geldiği ayrıca gerekçe ister.',
    ['Öncül ile sonucun ayrılması (izlenme)', 'izlenme öncülünü ve değer kaybı sonucunu ayırır'],
    ['Örtük öncülün belirlenmesi (izlenme)', 'davranış değişiminin değer kaybı olduğu ve güvenlik kazancından ağır geldiği öncülünü gösterir'],
    ['Öncülün kanıtlanmamış olduğunun belirtilmesi (izlenme)', 'bu öncülün ayrıca gerekçe gerektirdiğini belirtir']),
  task('evaluate', 'Gökhan’ın “Karar makineye bırakılırsa sorumluluk kime ait olur?” sorusunun kamera planına karşı güçlü bir itiraz olup olmadığını değerlendiriniz.',
    'Soru kısmen güçlü bir itirazdır: sorumluluk zinciri belirsizse yanlış işaretlemenin zararı kimseye yüklenemez. Ancak soru, kameraların kurulmaması gerektiğini tek başına göstermez; yazılım ahlaki özne olmadığından sorumluluk kuran, işleten ve karar veren insanlarda kalabilir. Bu durumda itiraz, kameraya değil sorumluluğun açıkça belirlenmesi şartına yöneliktir. Gerekçeli karşı değerlendirme de kabul edilir.',
    ['İtirazın güçlü yanının gösterilmesi', 'sorumluluk zinciri belirsizse zararın kimseye yüklenemeyeceğini belirtir'],
    ['İtirazın sınırının gösterilmesi', 'sorunun kameranın kurulmamasını tek başına gerektirmediğini ve sorumluluğun insanlarda kalabileceğini belirtir'],
    ['Gerekçeli değerlendirme yargısı (sorumluluk)', 'itirazı sorumluluğun belirlenmesi şartına bağlayarak gerekçeli yargıya varır']),
  task('evaluate', 'Emre ve Fatma’nın görüşlerinden hangisinin diğerine karşı daha güçlü bir itirazı olduğunu gerekçelendirerek değerlendiriniz.',
    'Fatma’nın Emre’ye itirazı: koruma öncülü kanıtlanmamıştır ve güvenliğin her şeyin önüne konması başka değerleri yok edebilir. Emre’nin Fatma’ya itirazı: izlenmenin davranışı bozduğu gösterilmemiştir ve can güvenliğinin kaybı geri alınamaz. İki itiraz da kısmen güçlüdür; öğrenci hangisini daha güçlü sayarsa saysın, gerekçesini ve diğer itirazın sınırını göstermelidir; gerekçeli her seçim kabul edilir.',
    ['İki itirazın belirlenmesi (güvenlik)', 'Fatma’nın Emre’ye ve Emre’nin Fatma’ya itirazını belirtir'],
    ['İtirazların gücünün karşılaştırılması (güvenlik)', 'itirazlardan birini diğerinden neden daha güçlü saydığını gösterir'],
    ['Karşı itirazın sınırının belirtilmesi (güvenlik)', 'seçmediği itirazın hangi bakımdan geçerli kaldığını belirtir']),
  task('create', 'Üç görüşten birinin zayıf yanını gideren ve o görüşü güçlendiren bir ek öncül yazınız.',
    'Örnek (Emre): kameralar yalnız belirli suçlarda ve denetimli biçimde kullanıldığında güvenliği artırır. Örnek (Fatma): izlenmenin davranışı bozduğu, benzer uygulamalardan elde edilen gözlemlerle gösterilebilir. Örnek (Gökhan): sorumluluk makineye değil, kararı onaylayan insana yüklenir. Seçilen görüşün zayıf yanına yanıt veren tutarlı her ek öncül kabul edilir.',
    ['Görüşün ve zayıf yanının belirtilmesi (güvenlik)', 'seçtiği görüşü ve gidermek istediği zayıf yanı belirtir'],
    ['Zayıf yanı gideren ek öncülün yazılması (güvenlik)', 'zayıf yana gerçekten yanıt veren, görüşü tutarlı biçimde güçlendiren bir öncül yazar'],
    ['Ek öncülün görüşün diğer öncülleriyle tutarlı olması (güvenlik)', 'yeni öncülün görüşün temel iddiasıyla çelişmediğini gösterir']),
  task('create', 'Üç görüşten birden fazlasından bir şey koruyan bir birleştirici öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğinizi belirtiniz.',
    'Örnek öneri: kameralar yalnız ağır suçların olduğu noktalarda kurulur (Emre), görüntüler kısa süre saklanır ve izlenme bildirilir (Fatma), işaretlemeyi bir görevli doğrular ve sorumluluk adıyla belirlenir (Gökhan). Çözülmeyen: güvenlik ile izlenmeme değeri çatıştığında hangisinin ağır basacağı. Öneri herkesin uzlaşacağını varsaymamalı, çatışmanın nerede sürdüğünü göstermelidir.',
    ['Birleştirici önerinin yazılması (güvenlik)', 'en az iki görüşten bir unsuru içeren tutarlı bir öneri yazar'],
    ['Hangi görüşten neyin korunduğunun belirtilmesi (güvenlik)', 'korunan unsurları ilgili görüşlerle eşleştirir'],
    ['Çözülmeyen çatışmanın belirtilmesi (güvenlik)', 'önerinin hangi çatışmayı çözmediğini ve herkesin uzlaşacağını varsaymadığını gösterir']),
];

// ---------- FEL.11.2.2 b: görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini kamera tartışmasından bir örnekle açıklayınız.',
    'Bir görüş, gerekçe(ler) ve bunlardan çıkan sonuçla argümana dönüşür. Örnek: Görüş: kameralar sınırlı kurulmalıdır. Gerekçe: güvenlik önemlidir ama sürekli izlenme davranışı ve güveni bozabilir. Sonuç: kameralar yalnız gerekli noktalarda ve denetimle kurulmalıdır.',
    ['Görüş, gerekçe ve sonucun belirtilmesi (kamera)', 'argümanın görüş, gerekçe ve sonuç öğelerini belirtir'],
    ['Örneğin tartışmadan verilmesi (kamera)', 'kamera tartışmasından tutarlı bir örnek verir'],
    ['Gerekçe ile sonucun bağlanması (kamera)', 'gerekçenin sonucu nasıl desteklediğini gösterir']),
  task('understand', 'Kameralar konusundaki kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: Kameralar kurulmamalıdır. Bu görüş, güvenliğin hangi değerlerin pahasına sağlanabileceği sorusuna ya da kararların ahlaki sorumluluğunun kime ait olduğu sorusuna cevaptır. Kurulmalı ya da koşula bağlı gibi farklı görüşler de bir felsefi soruya doğru bağlanırsa kabul edilir.',
    ['Görüşün açık yazılması (kamera)', 'kameralar konusundaki görüşünü açıkça yazar'],
    ['Görüşün felsefi soruya bağlanması (kamera)', 'görüşü güvenlik ve değerler ya da sorumluluk sorusuna bağlar'],
    ['Görüşün vakayla tutarlı olması (kamera)', 'görüşü vakadaki duruma uygun yazar']),
  task('apply', 'Kameralar konusunda bir görüş seçiniz ve bu görüşü bir değer ilkesi, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: İlke: güvenlik uğruna insanın güveni ve özgürlüğü feda edilmemelidir. Durum: kameralar sürekli izleme ve görüntü saklama getirir. Sonuç: kameralar bu biçimiyle kurulmamalıdır. İlkeyi, durumu ve sonucu doğru ayıran ve sonucu öncüllerden çıkaran her görüş kabul edilir.',
    ['Değer ilkesinin yazılması (kamera)', 'argümanın dayandığı değer ilkesini açıkça yazar'],
    ['Durum bilgisinin yazılması (kamera)', 'vakadan alınan bir durum bilgisini öncül olarak yazar'],
    ['Sonucun öncüllerden çıkarılması (kamera)', 'sonucun ilke ve durumdan çıktığını gösterir']),
  task('apply', '“Can güvenliği her şeyden önce gelir” ilkesinden yola çıkarak kamera planı için bir argüman kurunuz.',
    'Örnek: İlke: can güvenliği her şeyden önce gelir. Durum: yüz tanıyan kameralar ağır suçları azaltır ve görüntü saklaması denetimli yapılabilir. Sonuç: kameralar kurulmalıdır. İlkeden hem kurulmasını hem koşullu kurulmasını ya da kurulmamasını (örneğin kameranın güvenliği gerçekten artırmadığını göstererek) savunan tutarlı argümanlar kurulabilir; aranan tutarlılıktır.',
    ['İlkenin argümana doğru yerleştirilmesi (kamera)', 'verilen ilkeyi argümanın öncülü olarak kullanır'],
    ['Durum bilgisinin ilkeyle ilişkilendirilmesi (kamera)', 'kamera planının güvenliğe etkisini ilkeye göre değerlendirir'],
    ['Sonucun ilkeyle tutarlı çıkarılması (kamera)', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('analyze', 'Kameralar konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümanın dayandığı değer varsayımını ve bu varsayıma yöneltilebilecek güçlü bir itirazı çözümleyiniz; itirazın neden güçlü olduğunu açıklayınız.',
    'Örnek: Öncül: güvenlik uğruna insanın güveni ve özgürlüğü feda edilmemelidir. Öncül: sürekli izleme güveni ve davranıştaki serbestliği azaltır. Sonuç: kameralar sürekli izleme biçiminde kurulmamalıdır. Değer varsayımı: özgürlük ve güven güvenlikten önce gelir. İtiraz: ağır suçların önlenmesi de insanların özgürlüğünü korur; bu varsayım güvenliğin özgürlüğün koşulu olabileceğini hesaba katmaz. İtiraz güçlüdür, çünkü varsayımın değer sıralamasını sorgular. Kendi argümanını öncül ve sonuçla kuran, değer varsayımını belirleyen ve itirazın gücünü gerekçelendiren eşdeğer yanıtlar kabul edilir.',
    ['Argümanın kurulması ve değer varsayımının belirlenmesi (kamera)', 'kameralar konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve dayandığı değer varsayımını gösterir'],
    ['Güçlü bir itirazın belirlenmesi (kamera)', 'varsayıma yöneltilebilecek güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi (kamera)', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Kameralar suçları azaltacak; bu yüzden herkesin her davranışı kaydedilebilir.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: suçları azaltan her uygulama, getirdiği bedel ne olursa olsun haklıdır. Fatma itiraz eder: izlenme davranışı ve güveni bozar, değer kaybı vardır. Gökhan da itiraz edebilir: kayıtlar makine tarafından değerlendirilirse yanlış işaretlemenin sorumluluğu belirsizleşir. Emre ise öncülü bu biçimiyle kabul etmeyebilir: kişisel bilginin korunması için önlem gerektiğini söylemiştir.',
    ['Gizli öncülün belirlenmesi (kamera)', 'suçu azaltan her uygulamanın bedel ne olursa olsun haklı olduğu öncülünü gösterir'],
    ['Fatma ve Gökhan’ın itirazının gösterilmesi', 'değer kaybı ve sorumluluk itirazlarını doğru ilişkilendirir'],
    ['Emre’nin konumunun ayrıca gösterilmesi', 'Emre’nin öncülü koşulsuz kabul etmeyebileceğini belirtir']),
  task('evaluate', 'Kameralar konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümana yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını gösteriniz. İtiraza gerekçeli bir yanıt veriniz ve bu yanıtın itirazı karşılayıp karşılamadığını değerlendiriniz.',
    'Örnek: Öncül: ağır suçları azaltan önlemler kabul edilebilir. Öncül: sınırlı kamera kurulumu ağır suçları azaltır. Sonuç: kameralar sınırlı kurulmalıdır. İtiraz: sınırlı kurulum suçu yeterince azaltmaz. Zayıflayan öncül: sınırlı kurulumun ağır suçları azalttığı. Yanıt: kurulum en riskli noktalarda yoğunlaşırsa etki kapsam genişletilmeden de sağlanabilir. Değerlendirme: yanıt itirazı kısmen karşılar; ancak etkinin gerçekten sağlanacağını göstermek gerekir. Öğrencinin kendi argümanını açıkça kurduğu, itirazı bir öncülle ilişkilendirdiği ve gerekçeli yanıtının yeterliliğini değerlendirdiği eşdeğer çalışmalar kabul edilir.',
    ['Argümanın kurulması ve itirazın belirlenmesi (kamera)', 'kameralar konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve bu argümana yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi (kamera)', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['İtiraza yanıt verilmesi ve yanıtın değerlendirilmesi (kamera)', 'itiraza gerekçeli bir yanıt verir ve bu yanıtın itirazı karşılayıp karşılamadığını gerekçeyle değerlendirir']),
  task('evaluate', '“Saklayacak bir şeyi olmayan kimse izlenmekten korkmaz” gerekçesinin kamera tartışmasında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: izlenmenin değerini, saklanacak bir şeyin olup olmadığına bağlamak mahremiyetin başka değerlerini (özgürlük, güven, davranışta serbestlik) yok sayar. Ayrıca kayıtlar kötüye kullanılabilir ve yanlış işaretleme saklayacak bir şeyi olmayanı da etkiler. Ancak denetimli ve sınırlı izlemenin güvenlik açısından savunulabileceği, gerekçenin geçersizliğinden ayrı bir sorudur.',
    ['Gerekçenin yetersizliğinin gösterilmesi (kamera)', 'mahremiyetin değerinin saklanacak şeye bağlı olmadığını belirtir'],
    ['Eksik kalan gerekçenin belirtilmesi (kamera)', 'kötüye kullanım ya da yanlış işaretleme gibi riskleri gösterir'],
    ['Denetimli izleme ile gerekçenin ayrılması', 'sınırlı ve denetimli izlemenin savunulabilirliğini gerekçenin geçerliliğinden ayrı olarak belirtir']),
  task('create', 'Kamera sorununa metindekilerden farklı, gerekçeli özgün bir görüş ve argüman oluşturunuz.',
    'Örnek: Kameralar kurulabilir; ancak yalnız ağır suçların işlendiği noktalarda, görüntüleri kısa süre saklayan ve işaretlemeyi bir görevlinin onayına bağlayan bir düzenle. Gerekçe: güvenlik ve güven birlikte değerlidir; sorumluluk açıkça bir insanda olmalıdır. Görüşü, gerekçesini ve sonucu tutarlı kuran özgün her argüman kabul edilir.',
    ['Özgün görüşün açıkça yazılması (kamera)', 'metindeki üç görüşün tekrarı olmayan, açık bir görüş yazar'],
    ['Gerekçenin kurulması (kamera)', 'görüşünü en az bir gerekçeyle destekler'],
    ['Argümanın tutarlılığı (kamera)', 'öncüller ile sonucun çelişmediğini gösterir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan kısa bir diyalog yazınız.',
    'Örnek: A: Kameralar sınırlı kurulmalı; çünkü sürekli izlenme güveni bozar. B: Ama güvenlik de değerli. A: Güvenlik değerli; yine de her noktaya kamera koymadan, riskli noktalara odaklanarak güveni koruyabiliriz. Gerekçe, itiraz ve itirazı yanıtlayan karşılık içeren tutarlı her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması (kamera)', 'bir görüşün gerekçesini diyalogda açıkça verir'],
    ['İtirazın yazılması (kamera)', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması (kamera)', 'itirazı yok saymadan gerekçeli bir karşılık verir']),
];

// ---------- FEL.11.2.2 c: felsefi metin yazar ----------
const sampleParagraph = '“Kentte güvenlik kameralarının artırılmasındaki temel problem, güvenliğin hangi değerlerin pahasına sağlanabileceğidir. Güvenliği her şeyin önüne koyan görüş, kamerayı yeterli sayar. Oysa her şeyin önüne konan bir değer, onu anlamlı kılan özgürlük ve güven gibi değerleri yok edebilir; bu nedenle güvenlik uğruna her şey feda edilemez.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: güvenliğin hangi değerlerin pahasına sağlanabileceği. Kavram: değer (ayrıca güvenlik, özgürlük, güven). Gerekçe: her şeyin önüne konan değer, onu anlamlı kılan özgürlük ve güven gibi değerleri yok edebilir.',
    ['Problemin belirlenmesi (güvenlik paragrafı)', 'paragrafın problemini güvenliğin hangi değerlerin pahasına sağlanabileceği olarak belirtir'],
    ['Kavramın belirlenmesi (güvenlik paragrafı)', 'paragraftaki felsefi kavramlardan birini (değer, güvenlik, özgürlük) belirtir'],
    ['Gerekçenin belirlenmesi (güvenlik paragrafı)', 'her şeyin önüne konan değerin diğer değerleri yok edebileceği gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: güvenlik uğruna her şey feda edilemez. Sonucu taşıyan cümle paragrafın son cümlesidir (“bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi (güvenlik paragrafı)', 'görüşü güvenlik uğruna her şeyin feda edilemeyeceği biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi (güvenlik paragrafı)', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması (güvenlik paragrafı)', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “Kentte kamera sayısının artırılmasındaki temel problem, güvenlik ile özgürlük arasındaki dengedir. Fatma’ya göre ……… . Bu nedenle ………” Boş bırakılan yerleri Fatma’nın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: sürekli izlenen insan davranışını değiştirir ve güven yerini kuşkuya bırakır. Boşluk 2: güvenlik uğruna bu değerler feda edilemez ya da karar bu değerler gözetilerek verilmelidir. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Fatma)', 'Fatma’nın görüşünü doğru biçimde (izlenmenin davranışı ve güveni bozması) tamamlar'],
    ['İkinci boşluğun tamamlanması (Fatma)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Fatma)', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Gökhan’ın görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: Kamera planındaki temel problem, kararın bir makineye bırakıldığı durumda ahlaki sorumluluğun kime ait olduğudur. Gökhan’ın görüşünde “sorumluluk” kavramı, yanlış işaretlemenin sonuçlarını üstlenecek öznenin belirlenmesini gösterir. Yazılım ahlaki özne olamayacağından karar makineye bırakıldığında sorumluluk belirsizleşir. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması (Gökhan)', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması (Gökhan)', 'sorumluluk ya da ahlaki eylem kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması (Gökhan)', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “Teknoloji çok tehlikelidir, kimse kameraları sevmiyor. Bu yüzden kameralar kurulmamalı.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (güvenlik ve değerler, sorumluluk) belirsizdir. Kavram: güvenlik, özgürlük, değer gibi kavramlar ele alınmamış, “tehlikeli” kavramı belirsiz bırakılmıştır. Temellendirme: “kimse sevmiyor” gerekçesi, kameraların yanlış olduğunu göstermez; beğeni ya da çoğunluğa başvurmaktır.',
    ['Problemin eksikliğinin gösterilmesi (kamera paragrafı)', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi (kamera paragrafı)', 'güvenlik, özgürlük ve değer gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi (kamera paragrafı)', '“kimse sevmiyor” gerekçesinin sonucu desteklemediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Güvenlik önemlidir. Bu yüzden her kavşağa kamera konmalıdır.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: güvenlik önemlidir. Sonuç: her kavşağa kamera konmalıdır. Sonuç öncülden çıkmaz: güvenliğin önemli olması, kameranın güvenliği artırdığını ve getirdiği bedelin (izlenme, saklama, sorumluluk) kabul edilebilir olduğunu göstermez. Aradaki boşluğu dolduran bir gerekçe gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması (kamera paragrafı)', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi (kamera paragrafı)', 'önemli olmanın kameranın gerekliliğini göstermediğini belirtir'],
    ['Eksik gerekçenin belirtilmesi (kamera paragrafı)', 'kameranın güvenliği artırdığı ve bedelin kabul edilebilir olduğu gerekçesinin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence kameralar iyi. Çünkü güvenlik önemli. Herkes güvende olmalı, yoksa kötü olur.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (güvenliğin hangi değerlerin pahasına sağlanabileceği), kavramlar yerinde (değer, güvenlik, özgürlük), argüman ve gerekçe açık (her şeyin önüne konan değer diğerlerini yok edebilir), bütünlük var. Paragraf 2’de problem tanımlanmamış, “iyi” ve “kötü” belirsiz, gerekçe sonucu tekrar ediyor (güvenlik önemli olduğu için kamera iyi), felsefi terim yok. Paragraf 1’in sınırı: karşı görüşe yanıt vermemesi.',
    ['Problem ve kavram ölçütlerine göre değerlendirme (kamera paragrafları)', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme (kamera paragrafları)', 'iki paragrafın gerekçelerini karşılaştırır ve ikincinin gerekçesinin sonucu tekrar ettiğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme (kamera paragrafları)', 'terminoloji ve metin bütünlüğü bakımından yargıya varır']),
  task('evaluate', 'Paragraf: “Gökhan’ın görüşü doğrudur; çünkü yazılım karar veriyor. Karar veren yazılım olduğuna göre kimse sorumlu tutulamaz.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki öneri yazınız.',
    'Temellendirme zayıftır: “yazılım karar veriyor” kimsenin sorumlu tutulamayacağını göstermez; sonuç (kimse sorumlu değil) gerekçeyle birlikte varsayılmıştır. Yazılım ahlaki özne olmadığı için sorumluluk kuran, işleten ya da onaylayan insanlarda kalabilir; paragraf bunu ele almamıştır. Öneri 1: sorumluluğun kime ait olabileceğini ayırarak göster. Öneri 2: karşı görüşe (sorumluluğun insanlarda kaldığı görüşü) yanıt ver. Terminoloji ve problem tanımı da eklenebilir.',
    ['Temellendirmenin değerlendirilmesi (Gökhan paragrafı)', 'gerekçenin sonucu varsaydığını ya da desteklemediğini gösterir'],
    ['İlk önerinin yazılması (Gökhan paragrafı)', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması (Gökhan paragrafı)', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Kamera planı tartışmasını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (değer, güvenlik, sorumluluk) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (güvenliğin hangi değerlerin pahasına sağlanabileceği ya da kararların sorumluluğunun kime ait olduğu); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: güvenlik her değerin önüne konabilir mi? Görüş: konamaz, çünkü güvenlik özgürlük ve güven gibi değerleri yok edebilir. Karşı görüş (Emre): can güvenliği geri alınamaz. Yanıt: bu, güvenliği önemli kılar ama koşulsuz kılmaz; sınırlı ve denetimli kurulum her iki değeri de gözetir. Üç görüşten herhangi biri ya da özgün bir görüş, ölçütleri karşıladığı sürece kabul edilir; görüşün hangisi olduğu puanı etkilemez. Not: programdaki performans görevi öğrencinin teknoloji ve felsefe ilişkisine yönelik yazdığı felsefi metindir; bu soru onun vakaya bağlı küçültülmüş hâlidir.',
    ...W),
  task('create', 'Yaşlı bakımında robot kullanılması tartışmasını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (değer, sorumluluk, ahlaki eylem) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (bakımın bir makineye bırakılıp bırakılamayacağı, ahlaki sorumluluğun kime ait olduğu); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: bakım bir robota bırakılabilir mi? Görüş: yalnız yardımcı olarak kullanılabilir, çünkü bakımın ahlaki sorumluluğu insana aittir. Karşı görüş: robot yorulmaz ve hata payı azdır. Yanıt: bu bakımın yardımcı bir aracı olarak yararlıdır ama sorumluluğun ve ilişkinin yerini tutmaz. Hangi görüş savunulursa savunulsun, ölçütleri karşılayan metin kabul edilir. Not: bu soru, programdaki performans görevinin vakaya bağlı küçültülmüş hâlidir.',
    ...W),
];

export const grade11Unit2: Record<string, Focus[]> = {
  'FEL.11.2.1': [
    { context: ontological, focus: 'teknoloji ile ilgili felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma teknolojinin amaç için tarafsız bir araç olup olmadığı sorusuna dayanır.', 'Tartışma teknolojinin yaşantının anlamını nasıl etkilediği sorusuna dayanır.'], inference: 'Görüntülü görüşme tartışması teknolojinin ontolojik anlam ve yabancılaşma sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Bir anıyı yaşamak yerine kaydetmek.', tasks: a1 },
    { context: ontological, focus: 'teknoloji ile ilgili felsefi soru ve problemlerin hayatla ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki görüşler günlük teknoloji kararlarında da kullanılır.', 'Günlük teknoloji kararları kolaylık ile anlam arasında bir gerilim içerir.'], inference: 'Teknolojiye ilişkin felsefi sorular günlük yaşamdaki kararlarla ilişkilendirilerek değerlendirilebilir.', limit: 'Günlük örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Arkadaş buluşmasının mesajlaşmayla yapılması.', tasks: b1 },
  ],
  'FEL.11.2.2': [
    { context: axiological, focus: 'teknoloji ve hayat ilişkisiyle ilgili felsefi argümanların çözümlenmesi', evidence: ['Üç görüşün her birinin değer öncülü ve sonucu vardır.', 'Her görüşün güçlü ve zayıf yanı vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Kameranın görüntüleri sızdırması.', tasks: a2 },
    { context: axiological, focus: 'teknoloji ve hayat ilişkisiyle ilgili görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir değer varsayımına dayanır ve itirazlara açıktır.'], inference: 'Öğrenci kamera planı için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Sınırlı ve denetimli kamera kurulumu önerisi.', tasks: b2 },
    { context: axiological, focus: 'teknoloji ve hayat ilişkisiyle ilgili felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'Yaşlı bakımında robot kullanımı tartışması.', tasks: c2 },
  ],
};
