import type { Level } from './philosophy-exam-case.ts';
import type { Focus, Task } from './philosophy-early-units-2026.ts';

// FEL.11.1 — Çevre Sorunları ve Felsefe. Özgün vaka (düşünür adı ve alıntı yok): sulak alanın kurutulması tartışması.
// Üç ses programdaki üç çevre etiği yaklaşımına denk gelir (Deniz: insan merkezci, Elif: canlı merkezci, Cem: çevre merkezci);
// hiçbiri doğru ilan edilmez, her birinin gerekçe yükü vardır. Yaklaşım adları yalnız öğretmen anahtarında geçer.
// Kapsam dışı: tüketim ölçüsü, küresel ısınma, afet bilinci, belirli düşünürler.
// ÖĞRETMEN ONAYI: vaka metni ve 11.1.2 c ürün/ölçüt tasarımı Aytekin tarafından onaylandı.
// 11.1.2 c: programdaki performans görevi (öğrencinin gözlemlediği çevre sorunu, araştırma) yazılıda vakaya bağlı küçültülmüş hâlle sınanır;
// yazım görevinin ölçütü programın 7 ölçütlü, 100 puanlık "Felsefi Metin Yazımı" anahtarının 32/32/36 gruplamasıdır.
const context = 'Bir kasabanın kenarındaki sulak alanı belediye kurutup tarıma ve konuta açmayı düşünüyor. Üç öğrenci bu planı tartışıyor. Deniz: “Doğa, insanın ihtiyaçlarını karşıladığı ölçüde değerlidir; kurutmanın yararı kaybı aşıyorsa kurutulmalıdır.” Elif: “Sulak alandaki her canlının yaşamak gibi kendi başına bir değeri var; insanın çıkarı bu canlıları yok etmeye tek başına yetmez.” Cem: “Asıl değer tek tek canlılarda değil, su döngüsünü ve canlıların birbirine bağlılığını taşıyan bütünde; bu düzen insan olsun olmasın değerlidir.” Öğretmen, tartışmanın doğanın kendi başına bir değeri olup olmadığı ve insanın doğaya karşı sorumluluğu sorularına dayandığını belirtir.';

type Criterion = [label: string, description: string];
export const grade11CriterionDescriptions: Record<string, string> = {};
// Yazım görevi ölçütü: programın 7 ölçütü 32/32/36 olarak gruplanır (problem+kavram, argüman+temellendirme, terminoloji+dil+bütünlük).
export const WRITING_CRITERION_LABELS: [string, string, string] = ['Problemin tanımlanması ve kavramların yansıtılması', 'Argümanın ortaya konması ve temellendirilmesi', 'Felsefi terminoloji, dil ve metin bütünlüğü'];

function task(level: Level, stem: string, key: string, c1: Criterion, c2: Criterion, c3: Criterion): Task {
  for (const [label, description] of [c1, c2, c3]) {
    const known = grade11CriterionDescriptions[label];
    if (known !== undefined && known !== description) throw new Error(`Ölçüt etiketi iki farklı açıklamayla kullanılamaz: ${label}`);
    grade11CriterionDescriptions[label] = description;
  }
  return { level, stem, key, criteria: [c1[0], c2[0], c3[0]] };
}

const W: [Criterion, Criterion, Criterion] = [
  [WRITING_CRITERION_LABELS[0], 'çevre sorununda tartışılan felsefi problemi açıkça tanımlar; değer, doğa ya da çevre etiği gibi kavramları problemi yansıtacak biçimde kullanır (programın problem ve kavram ölçütleri, %32)'],
  [WRITING_CRITERION_LABELS[1], 'görüşünü öncül ve sonuç olarak açıkça kurar, gerekçelerini verir ve karşı görüşe gerekçeli yanıt verir; yalnız “bence”e, çoğunluğa ya da duyguya dayanmaz (programın argüman ve temellendirme ölçütleri, %32)'],
  [WRITING_CRITERION_LABELS[2], 'felsefi terimleri yerinde kullanır, dil kurallarına uyar ve metni problemden sonuca tutarlı bir bütün olarak kurar (programın terminoloji, dil ve bütünlük ölçütleri, %36)'],
];

// ---------- FEL.11.1.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: doğanın insana yararından bağımsız, kendi başına bir değeri var mıdır; bu soru doğaya değer verilmesinin dayanağını sorgular. İkinci soru: insanın doğaya karşı ahlaki sorumluluğu var mıdır, varsa nedir; bu soru insanın doğa karşısındaki yükümlülüğünü sorgular.',
    ['Doğanın kendi başına değeri sorusunun açıklanması', 'doğanın insana yararından bağımsız değerinin olup olmadığını ve bunun doğaya değer verilmesinin dayanağını sorguladığını belirtir'],
    ['İnsanın ahlaki sorumluluğu sorusunun açıklanması', 'insanın doğaya karşı ahlaki sorumluluğunun olup olmadığını ve kapsamını sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Deniz, Elif ve Cem’in sözlerinin her birinin doğanın değeri sorusuna nasıl bir cevap verdiğini belirtiniz.',
    'Deniz doğanın değerini insanın ihtiyaçlarını karşılamasına (yarara) bağlar. Elif sulak alandaki her canlının kendi başına değeri olduğunu söyler. Cem değeri tek tek canlılarda değil, canlıları birbirine bağlayan bütünde görür. Üçü de aynı soruya farklı cevap verir.',
    ['Deniz’in cevabının belirlenmesi', 'Deniz’in değeri insan ihtiyacını karşılama ölçüsüne bağladığını belirtir'],
    ['Elif’in cevabının belirlenmesi', 'Elif’in değeri her canlının kendi yaşamında gördüğünü belirtir'],
    ['Cem’in cevabının belirlenmesi', 'Cem’in değeri bütünde, canlıların birbirine bağlılığında gördüğünü belirtir']),
  task('apply', '“Çevre sorunu” ve “çevre etiği” kavramlarını metindeki duruma uygulayarak her birinin bu durumda neyi gösterdiğini açıklayınız.',
    'Çevre sorunu: sulak alanın kurutulması insan-doğa ilişkisinde bir tahribat ve yok oluş riski doğurur. Çevre etiği: tartışma kurutmanın yararlı olup olmadığını değil, doğru olup olmadığını ve doğaya nasıl bir değer verilmesi gerektiğini sorar; bu nedenle tartışma çevre etiğine girer. İki kavram aynı şey değildir: biri durumu, diğeri o duruma ahlaki bakışı gösterir.',
    ['Çevre sorununun durumda gösterilmesi', 'sulak alanın kurutulmasını insan-doğa ilişkisinde bir tahribat riski olarak belirtir'],
    ['Çevre etiğinin durumda gösterilmesi', 'tartışmanın doğruluk, değer ve sorumluluk sorularına dayandığını belirterek çevre etiğiyle ilişkilendirir'],
    ['İki kavramın ayrılması', 'çevre sorunu ile çevre etiği arasındaki farkı (durum ve ahlaki bakış) korur']),
  task('apply', '“Değer” kavramını metindeki üç görüşten birine uygulayarak o görüşün doğaya hangi bakımdan değer verdiğini açıklayınız.',
    'Örnek (Deniz): doğanın değeri insana yararına bağlıdır; doğa araç olarak değerlidir. Örnek (Elif): her canlının yaşamı kendi başına değerlidir. Örnek (Cem): bütünün, yani su döngüsü ve bağlılıklar düzeninin değeri vardır. Üç görüşten biri doğru uygulanırsa tam puan verilir.',
    ['Görüşün doğru seçilmesi ve belirtilmesi', 'metindeki üç görüşten birini adıyla belirtir ve sözüne uygun yorumlar'],
    ['Değer kavramının görüşe uygulanması', 'seçtiği görüşte değerin nereye (yarara, canlıya, bütüne) bağlandığını gösterir'],
    ['Açıklamanın metinle tutarlı olması', 'açıklamasını görüşün sözünde olmayan bir iddiayla genişletmez']),
  task('analyze', 'Üç öğrencinin sözlerinde doğaya değer verme ölçütünün ne olduğunu ayırarak karşılaştırınız.',
    'Ortak soru: doğaya neden ve hangi ölçüde değer verilmelidir. Deniz’in ölçütü insanın ihtiyacı ve yarardır. Elif’in ölçütü canlı olmaktır; her canlı kendi başına değerlidir. Cem’in ölçütü bütünlüktür; canlıları birbirine bağlayan düzen değerlidir. Üçü aynı soruya farklı değer ölçütüyle cevap verir.',
    ['Üç ölçütün ayrı ayrı belirlenmesi', 'yarar, canlı olma ve bütünlük ölçütlerini üç öğrenciye doğru dağıtır'],
    ['Ortak sorunun belirlenmesi', 'üç sözün de doğaya neden ve hangi ölçüde değer verileceği sorusuna cevap olduğunu belirtir'],
    ['Karşılaştırmanın gerekçelendirilmesi', 'ölçütler arasındaki farkı (insana bağlı olma, canlıya bağlı olma, bütüne bağlı olma) gerekçesiyle gösterir']),
  task('analyze', 'Deniz “kurutmanın yararı kaybı aşıyorsa kurutulmalıdır” der. Bu ölçüt kurutma kararını bir hesap sorusuna indirger; bu indirgemenin hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Yarar-kayıp hesabı bir olgu ve ölçüm sorusudur; ama hesabın dayandığı kabul, doğanın yalnız yararı ölçüsünde değerli olduğudur. Bu kabul doğanın kendi başına değeri olup olmadığı sorusunu önceden cevaplanmış sayar. Hesap yapılınca bu felsefi soru görünmez olur, oysa Elif ve Cem’in itirazı tam bu soruya yöneliktir.',
    ['Hesap sorusu ile felsefi sorunun ayrılması', 'yarar-kayıp hesabının ölçülebilir bir soru olduğunu ve felsefi sorunun hesaptan ayrı olduğunu belirtir'],
    ['Hesabın dayandığı kabulün gösterilmesi', 'hesabın doğanın yalnız yararı ölçüsünde değerli olduğu kabulüne dayandığını belirtir'],
    ['Görünmez kalan sorunun adlandırılması', 'görünmez kalan sorunun doğanın kendi başına değeri olup olmadığı olduğunu belirtir']),
  task('evaluate', '“Bu tartışma yalnızca kasabalıları ilgilendirir, felsefeyle ilgisi yoktur” yargısını metne dayanarak değerlendiriniz.',
    'Yargı kısmen doğrudur: planın sonuçlarını en çok kasabalılar yaşar ve karar yerel koşulları bilmeyi gerektirir. Ancak tartışmanın dayandığı sorular (doğanın kendi başına değeri olup olmadığı, insanın doğaya karşı sorumluluğu) kasabaya özgü değildir, genel felsefi sorulardır; kasabanın durumu bu soruların bir örneğidir. Bu ayrımı gösteren gerekçeli değerlendirmeler kabul edilir.',
    ['Yargının doğru yanının belirlenmesi', 'kararın yerel olduğunu ve sonuçlarının kasabalıları ilgilendirdiğini kabul eder'],
    ['Yargının sınırının gösterilmesi', 'tartışmanın dayandığı soruların kasabaya özgü olmayıp genel felsefi sorular olduğunu gösterir'],
    ['Gerekçeli değerlendirme yargısı', 'yargıyı ayrımına dayanarak gerekçeli biçimde değerlendirir']),
  task('evaluate', 'Öğretmenin belirttiği iki soruyu “Kurutmanın maliyeti ne kadardır?” sorusuyla karşılaştırarak onları felsefi soru yapan özelliği gerekçelendiriniz.',
    'Maliyet sorusu hesap ve kayıtla cevaplanır; olgusal bir sorudur. Doğanın kendi başına değeri olup olmadığı ve insanın doğaya karşı sorumluluğu soruları ise değer ve sorumluluk kavramlarının anlamını ve dayanağını sorgular; kayıt ya da hesapla değil, gerekçelendirme ve tartışmayla ele alınır. Felsefi olmalarının nedeni cevaplarının zor bulunması değil, kavramları ve kabulleri sorgulatmalarıdır.',
    ['Maliyet sorusunun olgusal niteliğinin belirlenmesi', 'maliyet sorusunun hesap ya da kayıtla cevaplandığını belirtir'],
    ['İki sorunun kavramsal niteliğinin gerekçelendirilmesi', 'değer ve sorumluluk kavramlarının anlamını ve dayanağını sorguladıklarını gösterir'],
    ['Zorluğun ölçüt olmadığının belirtilmesi', 'sorunun felsefi olmasını cevabının zor bulunmasına değil kavram ve kabulleri sorgulatmasına bağlar']),
  task('create', 'Metindekilerden farklı, çevreyle ilgili bir felsefi soru yazınız ve bu sorunun neden felsefi olduğunu açıklayınız.',
    'Örnek soru: İnsanın doğal kaynakları tüketmesinin ölçüsü ne olmalıdır? Neden felsefi: ölçünün neye göre belirleneceği, doğaya ve gelecek kuşaklara karşı sorumluluğun ne olduğu gibi değer ve sorumluluk kabullerine dayanır; bir ölçümle ya da kayıtla cevaplanmaz. Çevreye ilişkin, metindekilerden farklı ve kavram ya da kabulü sorgulatan her gerekçeli soru kabul edilir.',
    ['Metindekilerden farklı, çevreyle ilgili bir sorunun yazılması', 'çevreyle ilgili, metindekilerden farklı bir soru yazar; yalnız durum anlatmak bu ölçütü karşılamaz'],
    ['Sorunun kavram ya da kabulü sorgulattığının gösterilmesi', 'sorunun hangi kavramı ya da kabulü (değer, sorumluluk, ölçü gibi) sorgulattığını belirtir'],
    ['Sorunun neden felsefi sayıldığının gerekçelendirilmesi', 'sorunun olgusal ya da hesapla cevaplanan bir soru olmadığını gerekçeyle gösterir']),
  task('create', 'Metindekilerden farklı, çevreyle ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun bulunduğunu belirtiniz.',
    'Örnek durum: Bir nehir üzerine baraj kurulacaktır; baraj çevre köylerin suyunu güvenceye alırken nehirdeki canlı yaşamını bitirecektir. Felsefi sorun: nehrin ve canlıların insana yararından bağımsız bir değeri olup olmadığı ve insanın bu duruma karşı sorumluluğu. İnsan-doğa ilişkisinde değer ya da sorumluluk sorusunu doğru gösteren özgün durumlar kabul edilir.',
    ['Özgün ve çevreyle ilgili bir durumun yazılması', 'metindekilerden farklı, çevre sorununu içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi', 'durumda değer ya da sorumluluk sorusunun nerede ortaya çıktığını belirtir'],
    ['Sorunun durumla tutarlı açıklanması', 'belirttiği felsefi sorunun yazdığı durumdan gerçekten çıktığını gösterir']),
];

// ---------- FEL.11.1.1 b: hayatla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın gündelik yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: mahalledeki bir yeşil alanın yapılaşmaya açılması; yararı ile doğaya verilecek değer arasındaki çatışma burada da vardır. Tartışmayla aynı soruyu (çıkar mı, değer mi) gündeme getiren her örnek kabul edilir.',
    ['Gündelik yaşamdan bir örneğin verilmesi', 'öğrencinin çevresinde karşılaşabileceği somut bir durum belirtir'],
    ['Örneğin tartışmayla ilişkilendirilmesi', 'örnekte doğanın değeri ile insanın çıkarı arasındaki gerilimi gösterir'],
    ['Açıklamanın anlaşılır olması', 'örneği ve bağlantıyı anlaşılır biçimde yazar']),
  task('understand', 'Deniz, Elif ve Cem’in görüşlerinden birinin günlük yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Örnek (Deniz): tüketim ve yapılaşma kararlarında önce insana yararına bakılır. Örnek (Elif): canlılara gereksiz zarar vermekten kaçınılır. Örnek (Cem): bir alanın ekosistemi bütün olarak korunmaya çalışılır. Görüşle tutarlı doğru bir tutum açıklanırsa tam puan verilir.',
    ['Görüşün belirtilmesi', 'üç görüşten birini adıyla belirtir'],
    ['Görüşten çıkan tutumun açıklanması', 'görüşün günlük yaşamda yol açabileceği somut bir tutumu yazar'],
    ['Tutumun görüşle tutarlı olması', 'yazdığı tutumu görüşün dayandığı değer ölçütüyle (yarar, canlı, bütün) ilişkilendirir']),
  task('apply', 'Yaşadığınız çevreden (mahalle, okul, şehir) bir çevre sorunu seçiniz ve metindeki iki görüşün bu soruna nasıl yaklaşacağını yazınız.',
    'Örnek: okul bahçesindeki ağaç kesimi. Deniz yararlarını karşılaştırır; Elif ağaçta yaşayan canlıların değerini hesaba katar; Cem ağacın bahçe ekosistemindeki yerine bakar. Seçilen sorun gerçek bir çevre sorunu olmalı ve seçilen iki görüşün yaklaşımı kendi ölçütleriyle tutarlı yazılmalıdır; iki görüşün aynı sonuca varması zorunlu değildir.',
    ['Çevre sorununun belirtilmesi', 'yaşadığı çevreden somut bir çevre sorunu seçer'],
    ['İki görüşün soruna uygulanması', 'seçtiği iki görüşün soruna nasıl yaklaşacağını kendi ölçütleriyle tutarlı yazar'],
    ['Uygulamanın görüşlerin ayrımını koruması', 'iki görüşü birbirinin yerine koymaz; yaklaşımların farkını gösterir']),
  task('apply', 'Okulunuzun bahçesindeki bir ağacın kesilmesi öneriliyor. Metindeki üç görüşün bu öneriye nasıl yaklaşacağını yazınız.',
    'Deniz: ağacın gölge ve temizlik gibi yararlarını, kesmenin sağlayacağı yararla karşılaştırır. Elif: ağacın ve üzerinde yaşayan canlıların yaşamını göz önüne alır, insan çıkarının tek başına yetmeyeceğini söyler. Cem: ağacı bahçenin ekosistemi içindeki yeri ve diğer canlılarla bağlılığı bakımından değerlendirir.',
    ['Deniz’in yaklaşımının uygulanması', 'ağacın insana yararını kesmenin yararıyla karşılaştırarak değerlendirir'],
    ['Elif’in yaklaşımının uygulanması', 'ağaçta yaşayan canlıların kendi değerini göz önüne alır'],
    ['Cem’in yaklaşımının uygulanması', 'ağacı bahçe ekosistemi ve bağlılıklar bakımından değerlendirir']),
  task('analyze', 'Günlük yaşamınızdan bir çevre davranışı seçiniz (su kullanımı, atık ayırma vb.) ve bu davranışın dayandığı değer varsayımını çözümleyiniz.',
    'Örnek: atıkları ayırmak. Varsayım yarara dayanabilir (kaynak tasarrufu insana yarar), canlıya dayanabilir (hayvanlara zarar vermemek) ya da bütüne dayanabilir (doğa düzeninin korunması). Davranışla ilgili değer varsayımını doğru ve gerekçeli ayıran her çözümleme kabul edilir.',
    ['Çevre davranışının belirtilmesi', 'günlük yaşamdan somut bir çevre davranışı seçer'],
    ['Davranışın dayandığı değer varsayımının belirlenmesi', 'davranışın yarara, canlıya ya da bütüne dayanan hangi değer varsayımını taşıdığını gösterir'],
    ['Varsayımın gerekçelendirilmesi', 'seçtiği varsayımın neden davranışa uygun düştüğünü gerekçelendirir']),
  task('analyze', 'Plastik poşet kullanımının kısıtlanması gibi çevre için kolaylıktan vazgeçmeyi gerektiren bir kararda hangi çıkarların ve hangi değerlerin çatıştığını çözümleyiniz.',
    'Çatışan çıkar: bireyin kısa vadeli kolaylığı ve maliyeti. Çatışan değer: doğanın ve canlıların korunması. Bu çatışma yalnız kişisel çıkar hesabıyla çözülürse doğanın değeri sorusu yanıtsız kalır; bu yüzden karar bir değer ve sorumluluk sorusudur. Çıkar ile değeri ayırarak çatışmayı doğru gösteren çözümlemeler kabul edilir.',
    ['Çıkar tarafının belirlenmesi', 'bireyin kolaylık ve maliyet gibi çıkarlarını belirtir'],
    ['Değer tarafının belirlenmesi', 'doğanın ve canlıların korunması gibi değerleri belirtir'],
    ['Çatışmanın felsefi niteliğinin gösterilmesi', 'çatışmanın yalnız çıkar hesabıyla çözülemeyeceğini, değer ve sorumluluk sorusu içerdiğini gösterir']),
  task('evaluate', '“Çevre sorunları bilim insanlarının işidir; sıradan insanın ahlaki sorumluluğu yoktur” yargısını günlük yaşamla ilişkilendirerek değerlendiriniz.',
    'Yargı kısmen doğrudur: çözümler için bilimsel bilgi gerekir ve tek tek bireyin etkisi sınırlıdır. Ancak çevre sorunları günlük tüketim ve davranışlarla oluşur; kimin neden sorumlu olduğu bilimsel bir bilgi değil ahlaki bir sorudur. Bu nedenle bilgi gerekliliğinden sorumluluğun yalnız uzmanlara ait olduğu sonucu çıkmaz. Bu ayrımı gerekçeleyen değerlendirmeler kabul edilir.',
    ['Yargının doğru yanının belirlenmesi (günlük yaşam)', 'çözüm için bilimsel bilginin gerekli olduğunu ve bireyin etkisinin sınırlı olabileceğini kabul eder'],
    ['Yargının sınırının günlük yaşamla gösterilmesi', 'çevre sorunlarının günlük davranışlarla oluştuğunu ve sorumluluğun ahlaki bir soru olduğunu gösterir'],
    ['Gerekçeli değerlendirme yargısı (günlük yaşam)', 'bilgi gerekliliği ile sorumluluğun kime ait olduğunu ayırarak gerekçeli yargıya varır']),
  task('evaluate', 'Metindeki üç görüşten hangisinin günlük yaşamdaki bir çevre kararında en savunulabilir olduğunu, bir güçlü ve bir zayıf yanıyla gerekçelendirerek değerlendiriniz.',
    'Her görüş gerekçeyle seçilebilir. Deniz: güçlü yan somut yarar karşılaştırmasıdır; zayıf yan ölçülemeyen değerlerin ve yararın tek ölçüt olduğunun gösterilmemesidir. Elif: güçlü yan insan dışı canlıların değerini görmesidir; zayıf yan canlılar arasındaki çıkar çatışmasında ölçüt vermemesidir. Cem: güçlü yan canlıların birbirine bağlılığını görmesidir; zayıf yan bütünün değerinin bireylerinkinden ayrı olduğunun gösterilmemesidir.',
    ['Görüşün ve çevre kararının belirtilmesi', 'bir görüşü ve günlük yaşamdan bir çevre kararını belirtir'],
    ['Güçlü ve zayıf yanın gösterilmesi', 'seçtiği görüşün bir güçlü ve bir zayıf yanını kararla ilişkilendirerek gösterir'],
    ['Savunulabilirlik yargısının gerekçelendirilmesi', 'görüşün neden en savunulabilir olduğunu zayıf yanını da hesaba katarak gerekçelendirir']),
  task('create', 'Günlük yaşamınızdan bir çevre sorunu seçiniz; bu sorunun hangi felsefi soruyu gündeme getirdiğini yazınız ve bu soruya gerekçeli bir yanıt oluşturunuz.',
    'Örnek: kullanılmayan elektronik eşyaların atılması; doğaya zarar vermekten kaçınma ödevi var mıdır sorusunu gündeme getirir. Örnek yanıt: Evet, çünkü doğa insanın yaşamının dayanağıdır ve bu yarara bağlı bir sorumluluk doğurur. Soruyu doğru kuran ve yanıtını gerekçelendiren her özgün çalışma kabul edilir.',
    ['Gündelik çevre sorununun belirtilmesi', 'günlük yaşamdan somut bir çevre sorunu seçer'],
    ['Gündeme getirilen felsefi sorunun yazılması', 'sorunun değer ya da sorumluluk gibi felsefi bir soruyu gündeme getirdiğini belirtir'],
    ['Soruya gerekçeli yanıt verilmesi', 'sorusuna dayanağı olan tutarlı bir yanıt verir']),
  task('create', 'Çevre sorunlarını yaşamla ilişkilendiren bir “ne yapmalıyız?” önerisi yazınız ve önerinin dayandığı değeri belirtiniz.',
    'Örnek: Okulumuzda kâğıt kullanımını azaltmalıyız; öneri, doğanın insanlar kadar gelecek kuşaklar için de yaşanabilir kalması gerektiği değerine dayanır. Günlük yaşama uygun öneri ile onun dayandığı değeri (yarar, canlıların yaşamı, bütünün korunması vb.) doğru bağlayan her özgün çalışma kabul edilir.',
    ['Günlük yaşama uygun önerinin yazılması', 'somut ve uygulanabilir bir çevre önerisi yazar'],
    ['Önerinin dayandığı değerin belirtilmesi', 'öneriyi bir değere (yarar, canlı, bütün gibi) bağlar'],
    ['Öneri ile değerin tutarlı bağlanması', 'değerin öneriyi neden desteklediğini açıklar']),
];

// ---------- FEL.11.1.2 a: felsefi argümanları çözümler ----------
const a2: Task[] = [
  task('understand', 'Deniz’in sözündeki öncülü, koşulu ve sonucu ayırarak yazınız.',
    'Öncül: doğa, insanın ihtiyaçlarını karşıladığı ölçüde değerlidir. Koşul: kurutmanın yararı kaybı aşar. Sonuç: sulak alan kurutulmalıdır.',
    ['Değer öncülünün belirlenmesi', 'doğanın insanın ihtiyaçlarını karşıladığı ölçüde değerli olduğunu öncül olarak ayırır'],
    ['Koşulun belirlenmesi', 'kurutmanın yararının kaybı aşması koşulunu ayırır'],
    ['Sonucun ayrılması', 'kurutulmalıdır yargısını sonuç olarak gösterir']),
  task('understand', 'Cem’in sözünde değerin nerede bulunduğunu ve bu değerin insana nasıl bağlı olmadığını belirtiniz.',
    'Cem’e göre değer tek tek canlılarda değil, su döngüsünü ve canlıların birbirine bağlılığını taşıyan bütündedir. Bu düzen insanın bulunup bulunmamasına bağlı olmaksızın, yani insandan bağımsız olarak değerlidir.',
    ['Değerin bütünde bulunduğunun belirtilmesi', 'değerin tek tek canlılarda değil bütünde (su döngüsü ve bağlılık düzeninde) olduğunu belirtir'],
    ['İnsandan bağımsızlığın belirtilmesi', 'bu düzenin insan olsun olmasın değerli olduğunu belirtir'],
    ['Açıklamanın sözle tutarlı olması', 'Cem’in sözünde olmayan bir iddia eklemez']),
  task('apply', 'Elif’in görüşünü, bir çiftlik gölünün doldurulması örneğine uygulayınız; Elif’in nasıl bir sonuca varacağını gerekçesiyle yazınız.',
    'Elif’in ilkesine göre gölde yaşayan her canlının kendi başına değeri vardır ve insan çıkarı bu canlıları yok etmeye tek başına yetmez. Bu yüzden Elif doldurmaya gerekçe olarak yalnız insan çıkarının gösterilmesine karşı çıkar. Sözünden çıkan sonuç, canlıların değerinin hesaba katılması gerektiğidir; kesin bir yasak sonucu için ek bir öncül gerekir.',
    ['Elif’in ilkesinin göle uygulanması', 'gölde yaşayan canlıların kendi başına değeri olduğu ilkesini duruma uygular'],
    ['Sonucun gerekçelendirilmesi', 'doldurmaya karşı çıkışını insan çıkarının tek başına yetmeyeceği gerekçesine dayandırır'],
    ['Sonucun görüşten fazlasını söylememesi', 'kesin yasağı görüşün sözünden değil ek bir öncülden çıkardığını fark eder ya da sonucu ölçülü yazar']),
  task('apply', 'Deniz’in ilkesini aynı çiftlik gölüne uygulayınız: gölün doldurulması yarar sağlamıyor, zarar getiriyorsa Deniz nasıl bir sonuca varır?',
    'Deniz’in ilkesine göre doğa insanın ihtiyaçlarını karşıladığı ölçüde değerlidir ve yararı kaybı aşmayan bir kurutma yapılmaz. Doldurma yarar sağlamıyor, zarar getiriyorsa Deniz doldurulmamasını savunur. Bu, Deniz’in doğa karşıtı olmadığını, yarara dayalı bir ölçüt kullandığını gösterir.',
    ['Deniz’in ilkesinin doğru kullanılması', 'doğanın yarar ölçüsünde değerli olduğu ilkesini duruma uygular'],
    ['Sonucun ilkeden çıkarılması', 'zarar getiren doldurmanın savunulmayacağı sonucunu ilkeden çıkarır'],
    ['Görüşün yanlış temsil edilmemesi', 'Deniz’i doğa karşıtı göstermez; ölçütünün yarar olduğunu belirtir']),
  task('analyze', 'Üç görüşün güçlü ve zayıf yanlarını birer cümleyle belirleyerek bir karşılaştırma tablosu biçiminde yazınız.',
    'Deniz: güçlü yan, kararı karşılaştırılabilir bir ölçüte (yarar-kayıp) bağlaması; zayıf yan, yararın tek değer ölçütü olduğunu ve ölçülemeyen değerleri nasıl hesaba kattığını göstermemesi. Elif: güçlü yan, insan dışı canlıların kendi değerini görmesi; zayıf yan, canlılar arasında ya da insanla canlı arasında çıkar çatıştığında ölçüt vermemesi. Cem: güçlü yan, canlıların birbirine bağlılığını ve ekosistemi görmesi; zayıf yan, bütünün değerinin bireylerinkinden ayrı olduğunu göstermemesi.',
    ['Deniz’in güçlü ve zayıf yanlarının belirlenmesi', 'Deniz için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir'],
    ['Elif’in güçlü ve zayıf yanlarının belirlenmesi', 'Elif için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir'],
    ['Cem’in güçlü ve zayıf yanlarının belirlenmesi', 'Cem için bir güçlü ve bir zayıf yanı gerekçesiyle gösterir']),
  task('analyze', 'Elif’in “her canlının kendi başına değeri var” öncülü ile “insanın çıkarı yetmez” sonucu arasında hangi örtük öncülün gerektiğini çözümleyiniz.',
    'Örtük öncül: bir varlığın kendi başına değeri varsa, onun yaşamı yalnız insan çıkarı için feda edilemez. Metinde bu öncül söylenmemiştir; öncül ile sonuç arasındaki geçiş buna dayanır. Bu öncül kanıtlanmamıştır: değerli olmak, çıkar çatıştığında her durumda korunmayı gerektirir mi sorusu ayrıca gerekçe ister.',
    ['Öncül ile sonucun ayrılması', 'değer öncülünü ve insan çıkarının yetmeyeceği sonucunu ayırır'],
    ['Örtük öncülün belirlenmesi', 'değerli varlığın yalnız insan çıkarı için feda edilemeyeceği yönündeki eksik öncülü gösterir'],
    ['Öncülün kanıtlanmamış olduğunun belirtilmesi', 'bu öncülün ayrıca gerekçe gerektirdiğini belirtir']),
  task('evaluate', 'Cem’in “bütünün değeri insan olsun olmasın vardır” gerekçesinin yeterli olup olmadığını değerlendiriniz.',
    'Metinde Cem iddiasını canlıların birbirine bağlılığına dayandırır. Bağlılık bütünün canlılar ve insan için işlevli olduğunu gösterebilir; ama bütünün kendi başına, insandan bağımsız değerli olduğunu tek başına göstermez. Bu yüzden gerekçe iddiayı kısmen destekler, ek bir gerekçe ister. Gerekçeli karşı değerlendirme de kabul edilir.',
    ['İddia ile gerekçenin ayrılması', 'bütünün insandan bağımsız değerli olduğu iddiasını ve bağlılık gerekçesini ayırır'],
    ['Gerekçenin iddiayı ne ölçüde desteklediğinin gösterilmesi', 'bağlılığın işlevi gösterebileceğini ama kendi başına değeri tek başına göstermediğini belirtir'],
    ['Gerekçeli değerlendirme yargısı (argüman)', 'yeterli ya da yetersiz yargısını gerekçesiyle verir']),
  task('evaluate', 'Deniz ve Elif’in görüşlerinden hangisinin diğerine karşı daha güçlü bir itirazı olduğunu gerekçelendirerek değerlendiriniz.',
    'Elif’in Deniz’e itirazı: yararın tek değer ölçütü olduğu gösterilmemiştir ve canlıların değeri hesaba katılmaz. Deniz’in Elif’e itirazı: bir varlığın değerli olması, çıkar çatıştığında her durumda korunmasını gerektirmez; Elif ölçüt vermez. İki itiraz da kısmen güçlüdür; öğrenci hangisini daha güçlü sayarsa saysın, gerekçesini ve diğer itirazın sınırını göstermelidir; gerekçeli her seçim kabul edilir.',
    ['İki itirazın belirlenmesi', 'Elif’in Deniz’e ve Deniz’in Elif’e itirazını belirtir'],
    ['İtirazların gücünün karşılaştırılması', 'itirazlardan birini diğerinden neden daha güçlü saydığını gösterir'],
    ['Karşı itirazın sınırının belirtilmesi', 'seçmediği itirazın hangi bakımdan geçerli kaldığını belirtir']),
  task('create', 'Üç görüşten birinin zayıf yanını gideren ve o görüşü güçlendiren bir ek öncül yazınız.',
    'Örnek (Deniz): yarar yalnız bugünkü kazancı değil, gelecek kuşakların ve doğal düzenin sağladığı dolaylı yararları da kapsar. Örnek (Elif): değerler derecelidir; çıkar çatıştığında canlıların değeri ağırlıklarına göre tartılır. Örnek (Cem): bütünün değeri, onu oluşturan canlıların yaşamının ortak koşulu olmasından ayrıca gösterilir. Seçilen görüşün zayıf yanına yanıt veren tutarlı her ek öncül kabul edilir.',
    ['Görüşün ve zayıf yanının belirtilmesi', 'seçtiği görüşü ve gidermek istediği zayıf yanı belirtir'],
    ['Zayıf yanı gideren ek öncülün yazılması', 'zayıf yana gerçekten yanıt veren, görüşü tutarlı biçimde güçlendiren bir öncül yazar'],
    ['Ek öncülün görüşün diğer öncülleriyle tutarlı olması', 'yeni öncülün görüşün temel iddiasıyla çelişmediğini gösterir']),
  task('create', 'Üç görüşten birden fazlasından bir şey koruyan bir birleştirici öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğini belirtiniz.',
    'Örnek öneri: sulak alan kurutulmadan önce insanın gerçek ihtiyaçları (Deniz) ile canlıların zarar görmesinin en aza indirilmesi (Elif) ve bütünün işlevinin korunması (Cem) birlikte değerlendirilir. Çözemediği: üç ilke çatıştığında hangisinin ağır basacağı. Öneri herkesin uzlaşacağını varsaymamalı, çatışmanın nerede sürdüğünü göstermelidir.',
    ['Birleştirici önerinin yazılması', 'en az iki görüşten bir unsuru içeren tutarlı bir öneri yazar'],
    ['Hangi görüşten neyin korunduğunun belirtilmesi', 'korunan unsurları ilgili görüşlerle eşleştirir'],
    ['Çözülmeyen çatışmanın belirtilmesi', 'önerinin hangi çatışmayı çözmediğini ve herkesin uzlaşacağını varsaymadığını gösterir']),
];

// ---------- FEL.11.1.2 b: görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini sulak alan tartışmasından bir örnekle açıklayınız.',
    'Bir görüş, gerekçe(ler) ve bunlardan çıkan sonuçla argümana dönüşür. Örnek: Görüş: sulak alan kurutulmamalıdır. Gerekçe: sulak alandaki canlıların kendi başına değeri vardır ve bu değer insan çıkarıyla yok edilemez. Sonuç: kurutma yalnız insan çıkarıyla temellendirilemez.',
    ['Görüş, gerekçe ve sonucun belirtilmesi', 'argümanın görüş, gerekçe ve sonuç öğelerini belirtir'],
    ['Örneğin tartışmadan verilmesi', 'sulak alan tartışmasından tutarlı bir örnek verir'],
    ['Gerekçe ile sonucun bağlanması', 'gerekçenin sonucu nasıl desteklediğini gösterir']),
  task('understand', 'Sulak alanın kurutulmasına ilişkin kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: Sulak alan kurutulmamalıdır. Bu görüş, doğanın insana yararından bağımsız bir değeri olup olmadığı sorusuna ya da insanın doğaya karşı sorumluluğu sorusuna cevaptır. Kurutulmalı ya da koşula bağlı gibi farklı görüşler de, bir felsefi soruya doğru bağlanırsa kabul edilir.',
    ['Görüşün açık yazılması', 'sulak alan konusundaki görüşünü açıkça yazar'],
    ['Görüşün felsefi soruya bağlanması', 'görüşü doğanın değeri ya da insanın sorumluluğu sorusuna bağlar'],
    ['Görüşün metinle tutarlı olması', 'görüşü vakadaki duruma uygun yazar']),
  task('apply', 'Seçtiğiniz görüşü bir değer ilkesi, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: İlke: canlıların kendi başına değeri vardır. Durum: sulak alan birçok canlıya yaşam alanıdır. Sonuç: sulak alan yalnız insan çıkarı için yok edilmemelidir. İlkeyi, durumu ve sonucu doğru ayıran ve sonucu öncüllerden çıkaran her görüş kabul edilir.',
    ['Değer ilkesinin yazılması', 'argümanın dayandığı değer ilkesini açıkça yazar'],
    ['Durum bilgisinin yazılması', 'vakadan alınan bir durum bilgisini öncül olarak yazar'],
    ['Sonucun öncüllerden çıkarılması', 'sonucun ilke ve durumdan çıktığını gösterir']),
  task('apply', '“Doğa insana yararı ölçüsünde değerlidir” ilkesinden yola çıkarak sulak alan için bir argüman kurunuz.',
    'Örnek: İlke: doğa insana yararı ölçüsünde değerlidir. Durum: sulak alan suyu düzenler ve kasabayı taşkından korur; kurutmanın yararı bunları yitirmekten küçüktür. Sonuç: sulak alan kurutulmamalıdır. İlkeden hem kurutmayı hem korumayı savunan tutarlı argümanlar kurulabilir; aranan tutarlılıktır.',
    ['İlkenin argümana doğru yerleştirilmesi', 'verilen ilkeyi argümanın öncülü olarak kullanır'],
    ['Durum bilgisinin ilkeyle ilişkilendirilmesi', 'sulak alanın yararını ilkeye göre değerlendirir'],
    ['Sonucun ilkeyle tutarlı çıkarılması', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('analyze', 'Kurduğunuz argümanın dayandığı değer varsayımını ve bu varsayıma yöneltilebilecek en güçlü itirazı çözümleyiniz.',
    'Her argüman bir değer varsayımına dayanır (yarar, canlı değeri, bütünün değeri gibi). En güçlü itiraz, bu varsayımın kanıtlanmamış olmasına ya da başka bir görüşün bir yönü açıklayamamasına dayanır. Kendi argümanındaki varsayımı doğru belirleyen ve karşı görüşün itirazını doğru kuran çözümlemeler kabul edilir.',
    ['Değer varsayımının belirlenmesi', 'kendi argümanındaki değer varsayımını doğru gösterir'],
    ['En güçlü itirazın belirlenmesi', 'varsayıma yöneltilebilecek gerçekten güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Sulak alan bize doğrudan gelir sağlamıyor; bu yüzden değersizdir.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: bir şeyin değeri, insana sağladığı doğrudan gelirle ölçülür. Elif ve Cem bu öncüle itiraz eder: canlılar ya da bütün, gelirden bağımsız değerlidir. Deniz de itiraz edebilir: yararı doğrudan gelirle sınırlamak yanlıştır, sulak alanın taşkından koruma gibi dolaylı yararları da vardır. Böylece öncül hem insan merkezci hem diğer görüşler tarafından sınanabilir.',
    ['Gizli öncülün belirlenmesi', 'değerin doğrudan gelirle ölçüldüğü öncülünü gösterir'],
    ['Elif ve Cem’in itirazının gösterilmesi', 'canlıların ya da bütünün gelirden bağımsız değerli olduğu itirazını gösterir'],
    ['Deniz’in itirazının ayrıca gösterilmesi', 'yararın dolaylı biçimlerini hesaba katarak Deniz’in de öncüle itiraz edebileceğini belirtir']),
  task('evaluate', 'Kendi argümanınıza yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını ve argümanınızın buna nasıl yanıt verdiğini değerlendiriniz.',
    'Örnek: Argüman: canlıların değeri insan çıkarıyla yok edilemez. İtiraz: bu ilke canlılar arasında çıkar çatışmasında ölçüt vermez. Zayıflayan öncül: değerli olan her varlığın korunması gerektiği. Yanıt: değerler dereceli olabilir; bu durumda ilke ağırlık ölçütüyle tamamlanır. Seçilen argümana yönelen gerçek bir itirazı ve tutarlı yanıtı gösteren her çalışma kabul edilir.',
    ['İtirazın belirlenmesi', 'kendi argümanına yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['Argümanın yanıtının değerlendirilmesi', 'argümanın itiraza nasıl yanıt verdiğini gerekçeyle değerlendirir']),
  task('evaluate', '“Kasabanın çoğunluğu kurutmayı istiyorsa bu görüş doğrudur” gerekçesinin çevre sorunlarında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: çoğunluğun bir görüşü istemesi, o görüşün doğru ya da değer bakımından savunulabilir olduğunu göstermez (çoğunluğa başvurma). Hangi değere dayandığını ve neden doğru olduğunu göstermez. Ancak çoğunluğun kararı yönetimde meşruiyet bakımından önemli olabilir; bu, görüşün doğruluğundan ayrı bir sorudur.',
    ['Gerekçenin yetersizliğinin gösterilmesi', 'çoğunluğun istemesinin görüşün doğru olduğunu göstermediğini belirtir'],
    ['Eksik kalan gerekçenin belirtilmesi', 'argümanın hangi değere ve gerekçeye dayanması gerektiğini gösterir'],
    ['Meşruiyet ile doğruluğun ayrılması', 'çoğunluk kararının meşruiyet bakımından önemini, doğruluktan ayrı olarak belirtir']),
  task('create', 'Sulak alan sorununa metindekilerden farklı, gerekçeli özgün bir görüş ve argüman oluşturunuz.',
    'Örnek: Sulak alan kısmen kurutulmalı; kasabanın barınma ihtiyacı doğanın değerini yok saymadan, bütünün işlevini koruyan bir alan bırakılarak karşılanmalıdır. Gerekçe: insanın ihtiyacı ile bütünün işlevi birlikte değerlidir. Görüşü, gerekçesini ve sonucu tutarlı kuran özgün her argüman kabul edilir.',
    ['Özgün görüşün açıkça yazılması', 'metindeki üç görüşün tekrarı olmayan, açık bir görüş yazar'],
    ['Gerekçenin kurulması', 'görüşünü en az bir gerekçeyle destekler'],
    ['Argümanın tutarlılığı', 'öncüller ile sonucun çelişmediğini gösterir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan kısa bir diyalog yazınız.',
    'Örnek: A: Sulak alan korunmalı; çünkü canlıların kendi başına değeri var. B: Ama kasabanın barınma ihtiyacı da gerçek. A: İhtiyaç gerçek; yine de başka alanlar da kullanılabilirken canlıları yok etmek ihtiyacı karşılamak için zorunlu değildir. Gerekçe, itiraz ve itirazı yanıtlayan karşılık içeren tutarlı her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması', 'bir görüşün gerekçesini diyalogda açıkça verir'],
    ['İtirazın yazılması', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması', 'itirazı yok saymadan gerekçeli bir karşılık verir']),
];

// ---------- FEL.11.1.2 c: felsefi metin yazar ----------
const sampleParagraph = '“Sulak alanın kurutulmasındaki temel problem, doğaya insana yararından bağımsız bir değer tanınıp tanınmayacağıdır. İnsan merkezci görüş doğaya yalnız yararı ölçüsünde değer verir ve kurutmanın yararını hesaplamakla yetinir. Oysa yarar hesabı, değerin ne olduğu sorusunu önceden cevaplanmış sayar; bu nedenle kurutma kararı yalnız hesapla temellendirilemez.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: doğaya insana yararından bağımsız bir değer tanınıp tanınmayacağı. Kavram: değer (ayrıca insan merkezci görüş ya da çevre etiği). Gerekçe: yarar hesabı değerin ne olduğu sorusunu önceden cevaplanmış sayar.',
    ['Problemin belirlenmesi', 'paragrafın problemini doğaya yarardan bağımsız değer tanınıp tanınmayacağı olarak belirtir'],
    ['Kavramın belirlenmesi', 'paragraftaki felsefi kavramlardan birini (değer, insan merkezci görüş, çevre etiği) belirtir'],
    ['Gerekçenin belirlenmesi', 'yarar hesabının değeri önceden cevaplanmış saydığı gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: kurutma kararı yalnız yarar hesabıyla temellendirilemez. Sonucu taşıyan cümle paragrafın son cümlesidir (“bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi', 'görüşü kurutma kararının yalnız hesapla temellendirilemeyeceği biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “Sulak alanın kurutulmasındaki temel problem, canlıların insan çıkarından bağımsız bir değeri olup olmadığıdır. Elif’e göre ……… . Bu nedenle ………” Boş bırakılan yerleri Elif’in görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: sulak alandaki her canlının yaşamak gibi kendi başına bir değeri vardır. Boşluk 2: insan çıkarı tek başına canlıları yok etmeyi temellendirmez. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması', 'Elif’in görüşünü doğru biçimde (canlıların kendi değeri) tamamlar'],
    ['İkinci boşluğun tamamlanması', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Elif’in görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: Sulak alanın kurutulmasında temel problem, canlıların insan çıkarından bağımsız bir değeri olup olmadığıdır. Elif’in görüşünde “değer” kavramı her canlının yaşamının kendi başına taşıdığı değeri gösterir. Bu görüşe göre canlıların kendi başına değeri olduğundan, insan çıkarı onları yok etmeye tek başına yetmez. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması', 'değer ya da çevre etiği kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “Doğa çok güzeldir, herkes onu sever. Bu yüzden sulak alan kurutulmamalı.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (doğanın değeri, insanın sorumluluğu) belirsizdir. Kavram: değer, doğa gibi kavramlar ele alınmamış, “güzel” kavramı da belirsiz bırakılmıştır. Temellendirme: “herkes sever” gerekçesi, sevilmenin değerli olmayı gösterdiğini ya da kurutmanın yanlış olduğunu göstermez; çoğunluğun ya da beğeninin gerekçe sayıldığı bir geçiştir.',
    ['Problemin eksikliğinin gösterilmesi', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi', 'değer ve doğa gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi', '“herkes sever” gerekçesinin sonucu desteklemediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Canlıların hepsi değerlidir. Bu yüzden sulak alan kurutulmalıdır.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: canlıların hepsi değerlidir. Sonuç: sulak alan kurutulmalıdır. Sonuç öncülden çıkmaz; hatta öncülün tersini önerir, çünkü sulak alandaki canlıların değerli olması kurutmayı değil korumayı destekler. Aradaki boşluğu dolduran bir gerekçe (örneğin başka bir değerin ağır bastığı) gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi', 'sonucun öncülle uyumsuz olduğunu ya da öncülden çıkmadığını belirtir'],
    ['Eksik gerekçenin belirtilmesi', 'aradaki boşluğu dolduracak bir gerekçenin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence doğa korunmalı. Çünkü doğa önemli. Herkes doğayı korumalı, yoksa kötü olur.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (doğaya yarardan bağımsız değer tanınıp tanınmayacağı), kavramlar yerinde (değer, insan merkezci görüş), argüman ve gerekçe açık (yarar hesabı değeri önceden varsayar), bütünlük var. Paragraf 2’de problem tanımlanmamış, “önemli” ve “kötü” belirsiz, gerekçe sonucu tekrar ediyor (önemli olduğu için korunmalı), felsefi terim yok. Paragraf 1’in sınırı: karşı görüşe yanıt vermemesi.',
    ['Problem ve kavram ölçütlerine göre değerlendirme', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme', 'iki paragrafın gerekçelerini karşılaştırır ve ikincinin gerekçesinin sonucu tekrar ettiğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme', 'terminoloji ve metin bütünlüğü bakımından yargıya varır']),
  task('evaluate', 'Paragraf: “Cem’in görüşü doğrudur; çünkü ekosistem bütündür. Bütün değerli olduğuna göre sulak alan kurutulamaz.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki öneri yazınız.',
    'Temellendirme zayıftır: “ekosistem bütündür” bütünün değerli olduğunu göstermez; sonuç (bütün değerli) gerekçe olarak zaten varsayılmıştır. Cem’in bağlılık gerekçesi kullanılmamıştır. Öneri 1: bütünün değerini canlıların birbirine bağlılığıyla destekle. Öneri 2: karşı görüşe (Deniz ya da Elif) kısa bir yanıt ekle. Terminoloji ve problem tanımı da eklenebilir.',
    ['Temellendirmenin değerlendirilmesi', 'gerekçenin sonucu varsaydığını ya da desteklemediğini gösterir'],
    ['İlk önerinin yazılması', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Sulak alan tartışmasını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (değer, doğa, çevre etiği) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (doğanın kendi başına değeri olup olmadığı ya da insanın sorumluluğu); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: doğaya yararından bağımsız değer tanınmalı mı? Görüş: tanınmalıdır, çünkü yarar ölçütü değeri önceden varsayar. Karşı görüş (Deniz): yarar hesabı karar verilebilir kılar. Yanıt: karar verilebilirlik, değerin ne olduğu sorusunu cevaplamaz. Üç görüşten herhangi biri ya da özgün bir görüş, ölçütleri karşıladığı sürece kabul edilir; görüşün hangisi olduğu puanı etkilemez. Not: programdaki performans görevi öğrencinin gözlemlediği bir çevre sorununu araştırarak yazmasıdır; bu soru onun vakaya bağlı küçültülmüş hâlidir.',
    ...W),
  task('create', 'Bir kasabanın ormanının kesilip yol açılması tartışmasını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (değer, doğa, çevre etiği) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (ormanın insana yararından bağımsız değeri olup olmadığı ya da insanın sorumluluğu); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: orman yol yararı için feda edilebilir mi? Görüş: yalnız yarar için feda edilmemelidir, çünkü ormanın canlıları kendi başına değerlidir. Karşı görüş: yol insanların ulaşımını kolaylaştırır. Yanıt: kolaylık, canlıların değerini ortadan kaldırmaz; değer ile çıkarın tartılması gerekir. Hangi görüş savunulursa savunulsun, ölçütleri karşılayan metin kabul edilir. Not: bu soru, programdaki performans görevinin vakaya bağlı küçültülmüş hâlidir.',
    ...W),
];

export const grade11Units: Record<string, Focus[]> = {
  'FEL.11.1.1': [
    { context, focus: 'çevre ile ilgili felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma doğanın kendi başına değeri olup olmadığı sorusuna dayanır.', 'Tartışma insanın doğaya karşı sorumluluğu sorusuna dayanır.'], inference: 'Sulak alan tartışması çevre etiğinin değer ve sorumluluk sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Mahalledeki yeşil alanın yapılaşmaya açılması.', tasks: a1 },
    { context, focus: 'çevre ile ilgili felsefi soru ve problemlerin hayatla ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki değer ölçütleri günlük çevre kararlarında da kullanılır.', 'Günlük çevre kararları çıkar ile değer arasında bir gerilim içerir.'], inference: 'Felsefi çevre soruları günlük yaşamdaki kararlarla ilişkilendirilerek değerlendirilebilir.', limit: 'Günlük örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Okul bahçesindeki ağacın kesilmesi.', tasks: b1 },
  ],
  'FEL.11.1.2': [
    { context, focus: 'çevre sorunlarıyla ilgili felsefi argümanların çözümlenmesi', evidence: ['Üç görüşün her birinin bir değer öncülü ve bir sonucu vardır.', 'Her görüşün güçlü ve zayıf yanı vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Bir çiftlik gölünün doldurulması.', tasks: a2 },
    { context, focus: 'çevre sorunlarıyla ilgili görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir değer varsayımına dayanır ve itirazlara açıktır.'], inference: 'Öğrenci sulak alan sorunu için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Sulak alanın kısmen korunması önerisi.', tasks: b2 },
    { context, focus: 'çevre sorunlarıyla ilgili felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'Kasabanın ormanının kesilmesi tartışması.', tasks: c2 },
  ],
};
