import type { Focus, Task } from './philosophy-early-units-2026.ts';
import { task, W } from './philosophy-grade11-units-2026.ts';

// FEL.11.3 — Akıl ve İnanç. Özgün tek vaka (düşünür adı ve alıntı yok); Aytekin tarafından onaylandı (üçüncü görüşün kolay seçilmemesi için
// Funda’nın konumu tartışmalı bir iddiaya çevrildi; Eren’in örneği güven/sevgiden değer ve umuda kaydırıldı).
// Üç ses: Derya (inanç gerekçeyle sınanmalı; yükü: değer ve umut inançlarının gerekçesi kanıtla verilemez),
// Eren (inanç aklın ulaşamadığı yerde başlar, gönlün işidir; yükü: aklın sınırını ve ölçütü gösterememesi),
// Funda (akıl sınar ama yerini tutamaz, boşluğu bağlanma doldurur; yükü: boşluğu neyin doldurduğu, irade/alışkanlık olasılığı).
// Kapsam dışı: Tanrı’nın varlığı kanıtları, belirli bir dinin öğretileri, mucize, vahiy, ibadet, kutsal, ateizm ve agnostisizm (10.8’de ele alındı),
// düşünür adlı kuramlar, bilim-din çatışmasının tarihi. Metin genel inanç düzeyindedir; dinî değildir.
// 11.3.1 → felsefi soru ve problemler (a açıklar, b hayatla ilişkilendirerek değerlendirir); 11.3.2 → görüş ve argümanlar (a çözümler, b oluşturur, c metin yazar).
// 11.3.2 c: yazım görevinin ölçütü, programın 7 ölçütlü 100 puanlık Felsefi Metin Yazımı anahtarının 32/32/36 gruplamasıdır (bkz. 11.1).
const reasonFaith = 'Bir lisede felsefe kulübü, “İnanç kanıt ister mi?” başlıklı bir söyleşi düzenliyor. Üç öğrenci tartışıyor. Derya: “Bir haberin doğruluğunu sormadan kabul etmeyiz. Bir şeye inanıyorsam bunun gerekçesini söyleyebilmeliyim; aklın sınamadığı inanç, yanlış olsa bile fark edilmez.” Eren: “Bir işin değerli olduğuna ya da yarının daha iyi olacağına inanmayı kanıtlayarak kurmuyoruz. İnanç, aklın ulaşamadığı yerde başlar; bu gönlün işidir ve akılla ölçülmez.” Funda: “Akıl bir inancı sınayabilir, ama onun yerini tutamaz. Bir gerekçeyi doğru bulmakla ona göre yaşamak ayrı şeyler; bu boşluğu akıl değil, bağlanma doldurur.” Öğretmen, tartışmanın inancın gerekçe isteyip istemediğine ve akıl ile inancın birbirinin yerini tutup tutamayacağına dayandığını belirtir.';

// ---------- FEL.11.3.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: inanç, doğruluğunu gerekçeyle göstermek zorunda mıdır; bu soru inanmanın gerekçe isteyip istemediğini sorgular. İkinci soru: akıl ile inanç birbirinin yerini tutabilir mi; bu soru ikisinin aynı işi görüp görmediğini, birinin eksikliğini ötekinin giderip gideremeyeceğini sorgular.',
    ['İnancın gerekçe istemesi sorusunun açıklanması', 'inancın gerekçeyle gösterilmesinin gerekip gerekmediğini sorguladığını belirtir'],
    ['Yerini tutma sorusunun açıklanması', 'akıl ile inancın birbirinin yerini tutup tutamayacağını sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması (akıl-inanç)', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Derya, Eren ve Funda’nın sözlerinin her birinin inancın gerekçe isteyip istemediği sorusuna nasıl bir cevap verdiğini belirtiniz.',
    'Derya inancın gerekçeyle sınanması gerektiğini söyler; sınanmayan inancın yanlış olsa da fark edilmeyeceğini düşünür. Eren inancın aklın ulaşamadığı yerde başladığını ve kanıtla kurulmadığını söyler; bunu gönlün işi sayar. Funda aklın inancı sınayabileceğini ama yerini tutamayacağını söyler; gerekçeyi doğru bulmakla ona göre yaşamak arasındaki boşluğu bağlanmanın doldurduğunu savunur.',
    ['Derya’nın cevabının belirlenmesi (akıl-inanç)', 'Derya’nın inancın gerekçeyle sınanması gerektiğini söylediğini belirtir'],
    ['Eren’in cevabının belirlenmesi (akıl-inanç)', 'Eren’in inancı aklın ulaşamadığı yerde başlayan, gönle ait bir şey saydığını belirtir'],
    ['Funda’nın cevabının belirlenmesi (akıl-inanç)', 'Funda’nın aklın inancı sınadığını ama yerini tutamadığını, boşluğu bağlanmanın doldurduğunu belirtir']),
  task('apply', 'Şu durumda öğretmenin belirttiği iki sorudan hangisinin ortaya çıktığını gerekçesiyle yazınız: Bir öğrenci arkadaşının anlattığı bir söylentiyi kimseye sormadan kabul eder; başka bir arkadaşı bunun nereden çıktığını sorar.',
    'Birinci soru ortaya çıkar: inanç gerekçe ister mi. Söylentiyi sormadan kabul eden kişi inancı gerekçesiz benimsemiştir; arkadaşı ise gerekçe sormaktadır. İkinci soru (akıl ile inancın birbirinin yerini tutup tutmadığı) bu durumda ancak gerekçe bulunduktan sonra, gerekçenin kişiyi inanmaya yetip yetmediği sorulursa gündeme gelir.',
    ['Durumdaki sorunun belirlenmesi (akıl-inanç)', 'durumda inancın gerekçe isteyip istemediği sorusunun ortaya çıktığını belirtir'],
    ['Sorunun durumla ilişkilendirilmesi (akıl-inanç)', 'kimin gerekçesiz kabul ettiğini ve kimin gerekçe sorduğunu ayırır'],
    ['Diğer sorunun ayrıca ele alınması (akıl-inanç)', 'ikinci sorunun bu durumda neden öne çıkmadığını ya da ne zaman çıkacağını belirtir']),
  task('apply', '“Akıl ile inanç birbirinin yerini tutabilir mi?” sorusunu şu duruma uygulayınız: Bir kişi bir köprünün sağlam olduğunu gösteren mühendis raporunu okumuştur, yine de köprüden geçmek için kararsız kalır.',
    'Rapor akıl yoluyla bir gerekçe sunar; kişi gerekçeyi doğru bulur ama geçmeye karar veremez. Bu, gerekçeyi doğru bulmak ile ona güvenip davranmak arasındaki farkı gösterir ve sorunun karşılığıdır: akıl gerekçeyi verir, ama geçmek ayrı bir güven ya da bağlanma gerektiriyor olabilir. Funda bu boşluğa dikkat çeker. Derya ise kararsızlığın gerekçeyle değil, kişinin korkusuyla ilgili olduğunu söyleyebilir.',
    ['Durumdaki gerekçenin belirtilmesi (akıl-inanç)', 'raporun aklın verdiği bir gerekçe olduğunu belirtir'],
    ['Gerekçe ile davranış arasındaki farkın gösterilmesi (akıl-inanç)', 'gerekçeyi doğru bulmakla geçmeye karar vermenin ayrı olduğunu gösterir'],
    ['Sorunun sonuca bağlanması (akıl-inanç)', 'durumun aklın inancın yerini tutup tutamadığı sorusunu nasıl gündeme getirdiğini belirtir']),
  task('analyze', 'Derya “Aklın sınamadığı inanç, yanlış olsa bile fark edilmez” der. Bu sözün hangi varsayıma dayandığını ve hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Söz, bir inancın yanlışlığının ancak akılla (gerekçe sorarak) fark edilebileceğini varsayar. Bu varsayım, inancın doğruluğunu sınamanın yalnız akılla mı yapıldığı ve aklın sınayamadığı alanlarda (değer, umut) inancın nasıl değerlendirileceği sorusunu görünmez kılar. Eren’in itirazı tam bu alana yöneliktir.',
    ['Derya’nın varsayımının gösterilmesi (akıl-inanç)', 'yanlışlığın ancak akılla fark edilebileceği varsayımını gösterir'],
    ['Görünmez kalan sorunun belirlenmesi (akıl-inanç)', 'aklın sınamadığı alanlarda inancın nasıl değerlendirileceği sorusunun görünmez kaldığını belirtir'],
    ['Eren’in itirazıyla ilişkilendirilmesi (akıl-inanç)', 'Eren’in itirazının bu soruya yöneldiğini gösterir']),
  task('analyze', 'Eren “İnanç, aklın ulaşamadığı yerde başlar” der. “Aklın ulaşamadığı yer”in iki farklı anlama gelebileceğini gösteriniz ve cümlenin hangi felsefi sorunu doğurduğunu çözümleyiniz.',
    'Cümle, aklın bir sınırı olduğunu ve inancın bu sınırın ötesinde başladığını varsayar. “Aklın ulaşamadığı yer” henüz ulaşılamamış bir yer olabilir ya da ilkesel olarak ulaşılamaz bir yer olabilir. İkincisini göstermek zordur; birincisi ise inancın zamanla aklın alanına girebileceği anlamına gelir. Sorun: sınırın nerede olduğunu kim ve nasıl belirler.',
    ['İki anlamın ayrılması (akıl-inanç)', 'aklın henüz ulaşamadığı yer ile ilkesel olarak ulaşamayacağı yeri ayırır'],
    ['Sınırın varsayıldığının gösterilmesi (akıl-inanç)', 'cümlenin aklın bir sınırı olduğunu varsaydığını belirtir'],
    ['Doğan sorunun belirtilmesi (akıl-inanç)', 'sınırın nasıl belirleneceği sorununu gösterir']),
  task('evaluate', 'Funda’nın “Bir gerekçeyi doğru bulmakla ona göre yaşamak ayrı şeyler; bu boşluğu akıl değil, bağlanma doldurur” sözünün bir güçlü ve bir zayıf yanını değerlendiriniz.',
    'Güçlü yan: bilmek ile yaşamak arasındaki gündelik farkı (köprüden geçmek gibi) açıklar ve inancı yalnız bilgiye indirgemez. Zayıf yan: bu boşluğu dolduran şeyin neden bağlanma olduğunu söylemez; fark irade zayıflığıyla ya da alışkanlıkla da açıklanabilir, o zaman inancın ayrı bir rolü gerekmez. Güçlü ve zayıf yanı Funda’nın sözüne dayanarak gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (Funda)', 'bilmek ile yaşamak arasındaki farkı açıkladığını ya da inancı bilgiye indirgemediğini gösterir'],
    ['Zayıf yanın belirtilmesi (Funda)', 'boşluğu neyin doldurduğunun gösterilmediğini ya da başka açıklamaların olabileceğini belirtir'],
    ['Değerlendirmenin sözle ilişkilendirilmesi (Funda)', 'güçlü ve zayıf yanı Funda’nın sözüne dayanarak gerekçelendirir']),
  task('evaluate', 'Metindeki sorunun “inanç gerekçe ister mi?” biçiminde sorulmasının neden felsefi bir soru olduğunu, olgusal bir soruyla karşılaştırarak değerlendiriniz.',
    'Soru felsefidir. “Bu kulüpte kaç öğrenci bir şeye inandığını söylüyor?” gibi olgusal bir soru sayarak ya da ölçerek cevaplanır. “İnanç gerekçe ister mi?” sorusu ise ölçmeyle cevaplanmaz; gerekçe, inanç ve doğruluk kavramlarının ne anlama geldiğine ve neyin ölçüt sayılacağına bağlıdır. Her görüş başka bir ölçütten yola çıkar.',
    ['Olgusal sorunun ayrılması (akıl-inanç)', 'olgusal bir soruyu sayarak ya da ölçerek cevaplanan bir soru olarak gösterir'],
    ['Felsefi sorunun niteliğinin gösterilmesi (akıl-inanç)', 'sorunun ölçmeyle değil kavramlar ve ölçütler üzerinden cevaplandığını belirtir'],
    ['Karşılaştırmanın gerekçelendirilmesi (akıl-inanç)', 'iki soru arasındaki farkı gerekçesiyle gösterir']),
  task('create', 'Metindekilerden farklı, akıl ile inanç arasındaki ilişkiyle ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun (gerekçe isteme, birbirinin yerini tutma gibi) bulunduğunu belirtiniz.',
    'Örnek durum: Bir öğrenci sınavın iyi geçeceğine inanır ama çalışmaz; arkadaşı “Neye dayanarak inanıyorsun?” diye sorar. Felsefi sorun: inancın bir dayanak gerektirip gerektirmediği. Durumu ve sorunu tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün ve akıl-inanç ilişkisiyle ilgili bir durumun yazılması', 'metindekilerden farklı, inanç ile akıl ilişkisini içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi (akıl-inanç)', 'durumda gerekçe isteme ya da birbirinin yerini tutma sorusunun nerede ortaya çıktığını belirtir'],
    ['Sorunun durumla tutarlı açıklanması (akıl-inanç)', 'belirttiği felsefi sorunun yazdığı durumdan gerçekten çıktığını gösterir']),
  task('create', 'Tartışmaya katılmayan dördüncü bir öğrenci için inanç ve akıl ilişkisiyle ilgili yeni bir felsefi soru yazınız ve bu sorunun üç öğrenciden hangisinin görüşüyle en çok ilgili olduğunu belirtiniz.',
    'Örnek soru: Kişi bir inancın gerekçesini bulamadığında inancından vazgeçmeli midir? Bu soru Derya’nın gerekçe ölçütüyle doğrudan ilgilidir; Eren ve Funda bu soruya farklı cevap verir. Metindeki soruları tekrar etmeyen, inanç ile akıl ilişkisini sorgulayan ve üç öğrenciden biriyle gerekçeli ilişkilendirilen özgün her soru kabul edilir.',
    ['Yeni sorunun yazılması (akıl-inanç)', 'metindeki iki sorudan farklı, soru biçiminde yeni bir soru yazar'],
    ['Sorunun akıl-inanç ilişkisini sorgulaması', 'sorunun inanç ile akıl arasındaki ilişkiyi sorguladığını gösterir'],
    ['Soruyu bir öğrenciyle ilişkilendirme (akıl-inanç)', 'sorunun üç öğrenciden hangisiyle ilgili olduğunu gerekçesiyle belirtir']),
];

// ---------- FEL.11.3.1 b: hayatla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın gündelik yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: internette okunan bir bilgiye inanmadan önce kaynağına bakmak; bir işin değerli olduğuna kanıt beklemeden inanıp sürdürmek. Tartışmayla aynı soruyu (inanç gerekçe ister mi, akıl inancın yerini tutar mı) gündeme getiren her örnek kabul edilir.',
    ['Gündelik yaşamdan örneğin verilmesi (akıl-inanç)', 'öğrencinin çevresinde karşılaşabileceği somut bir durum belirtir'],
    ['Örneğin tartışmayla ilişkilendirilmesi (akıl-inanç)', 'örnekte inancın gerekçe istemesi ile aklın sınırı arasındaki gerilimi gösterir'],
    ['Açıklamanın anlaşılır olması (akıl-inanç)', 'örneği ve bağlantıyı anlaşılır biçimde yazar']),
  task('understand', 'Derya, Eren ve Funda’nın görüşlerinden birinin günlük yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Örnek (Derya): duyduğu bilgiyi kaynağına bakarak kabul eder, kanıtsız iddiaya mesafeli durur. Örnek (Eren): bir işin değerli olduğuna inandığı için kanıt beklemeden sürdürür, umudunu kanıta bağlamaz. Örnek (Funda): gerekçeleri tartar ama karar anında bir bağlanma yapar. Görüşle tutarlı doğru bir tutum açıklanırsa tam puan verilir.',
    ['Görüşün belirtilmesi (akıl-inanç)', 'üç görüşten birini adıyla belirtir'],
    ['Görüşten çıkan tutumun açıklanması (akıl-inanç)', 'görüşün günlük yaşamda yol açabileceği somut bir tutumu yazar'],
    ['Tutumun görüşle tutarlı olması (akıl-inanç)', 'tutumu görüşün dayandığı iddiayla (gerekçe, aklın sınırı, bağlanma) ilişkilendirir']),
  task('apply', 'Kendi hayatınızdan (okul, aile, arkadaşlık) bir şeye gerekçesini tam bilmeden güvendiğiniz ya da inandığınız bir durum seçiniz ve metindeki iki görüşün bu duruma nasıl yaklaşacağını yazınız.',
    'Örnek: yeni dönemde sınıfın daha uyumlu olacağına inanmak. Derya bu inancın neye dayandığını sorar ve gerekçe yoksa yanlış olsa da fark edilmeyeceğini söyler; Eren bu tür bir inancın kanıtla kurulmadığını, aklın ulaşamadığı yerde başladığını söyler; Funda gerekçeleri tartmanın yetmediğini, inanmanın bir bağlanma gerektirdiğini söyler. Seçilen durum gerçek olmalı ve iki görüşün yaklaşımı kendi ölçütleriyle tutarlı yazılmalıdır; iki görüşün aynı sonuca varması zorunlu değildir.',
    ['Durumun belirtilmesi (akıl-inanç)', 'kendi hayatından gerekçesi tam bilinmeyen bir inanç ya da güven durumu seçer'],
    ['İki görüşün duruma uygulanması (akıl-inanç)', 'seçtiği iki görüşün duruma nasıl yaklaşacağını kendi ölçütleriyle tutarlı yazar'],
    ['Görüşlerin ayrımının korunması (akıl-inanç)', 'iki görüşü birbirinin yerine koymaz; yaklaşımların farkını gösterir']),
  task('apply', 'Yarının daha iyi olacağına inanmak örneğine metindeki üç görüşün nasıl yaklaşacağını yazınız.',
    'Derya: bu inancın neye dayandığı sorulmalıdır; gerekçe yoksa inanç yanlış olsa da fark edilmez. Eren: bu inanç kanıtla kurulmaz, aklın ulaşamadığı yerde başlar ve gönülle beslenir. Funda: akıl bu inancı sınayabilir (yarının neden daha iyi olabileceğini tartabilir) ama umutla yaşamak için gerekçeden başka bir bağlanma gerekir.',
    ['Derya’nın yaklaşımının uygulanması (akıl-inanç)', 'inancın gerekçesinin sorulması gerektiğini belirtir'],
    ['Eren’in yaklaşımının uygulanması (akıl-inanç)', 'inancın kanıtla kurulmadığını ve gönüle ait olduğunu belirtir'],
    ['Funda’nın yaklaşımının uygulanması (akıl-inanç)', 'aklın sınayabileceğini ama yaşamak için ayrıca bir bağlanma gerektiğini belirtir']),
  task('analyze', 'Bir haberi kaynağına bakarak kabul etmek ile bir işin değerli olduğuna inanarak onu sürdürmek arasında, inancın gerekçe istemesi bakımından nasıl bir fark olduğunu çözümleyiniz.',
    'Haberde gerekçe (kaynak, tutarlılık) doğrulanabilir; kabul bu doğrulamaya bağlanır (Derya). Bir işin değerli olduğuna inanmakta ise gerekçe kanıtla tam verilemez; inanç deneyimle ve çabayla zamanla kurulur (Eren). Fark, gerekçenin türü ve verilebilirliğidir. Bu farkın inancın gerekçe istemediğini mi yoksa farklı türde gerekçe istediğini mi gösterdiği felsefi bir sorudur.',
    ['Haberdeki gerekçenin belirtilmesi (akıl-inanç)', 'haberin kaynak ve tutarlılık gibi doğrulanabilir gerekçeye bağlandığını belirtir'],
    ['Değer inancındaki gerekçenin belirtilmesi (akıl-inanç)', 'bir işin değerinin kanıtla tam gösterilemediğini belirtir'],
    ['Farkın felsefi niteliğinin gösterilmesi (akıl-inanç)', 'farkın gerekçe istememe mi, farklı gerekçe isteme mi olduğu sorusunu gösterir']),
  task('analyze', 'Bir sınavdan önce “iyi geçecek” diye inanmak ile çalışarak hazırlanmak arasındaki ilişkiyi, gerekçeyi doğru bulmak ile ona göre yaşamak ayrımı bakımından çözümleyiniz.',
    'İnanç tek başına hazırlığın gerekçesi değildir. Çalışmanın başarıyı artırdığını doğru bulmak ile gerçekten çalışmak ayrı şeylerdir. “İyi geçecek” diye inanıp çalışmayan kişi gerekçe bilgisini davranışa dönüştürmemiştir; çalışan kişi dönüştürmüştür. Ayrım Funda’nın söylediği boşluğa karşılık gelir; ama boşluğu bağlanmanın mı yoksa irade ve alışkanlığın mı doldurduğu açık kalır.',
    ['Gerekçeyi doğru bulmanın belirtilmesi (akıl-inanç)', 'çalışmanın başarıyı artırdığını doğru bulmayı ayrı bir öğe olarak belirtir'],
    ['Ona göre yaşamanın belirtilmesi (akıl-inanç)', 'gerekçeye göre davranmanın (çalışmanın) ayrı bir öğe olduğunu gösterir'],
    ['Ayrımın Funda’nın boşluğuyla ilişkilendirilmesi (akıl-inanç)', 'ayrımı Funda’nın sözündeki boşlukla ilişkilendirir ve açık kalan soruyu belirtir']),
  task('evaluate', 'Derya’nın gerekçe ölçütünün (“bir şeye inanıyorsam gerekçesini söyleyebilmeliyim”) günlük yaşamda her inanca uygulanıp uygulanamayacağını bir güçlü ve bir zayıf yanıyla değerlendiriniz.',
    'Güçlü yan: haber, iddia ve ürün gibi doğruluğu sınanabilen inançlarda yanlışı ayıklar. Zayıf yan: bir işin değerli olduğuna ya da yarının daha iyi olacağına inanmak gibi gerekçesi kanıtla tam verilemeyen inançlarda ölçüt ya bu inançları gereksiz yere dışlar ya da gerekçeyi zorlama bir hâle getirir. Güçlü ve zayıf yanı örnekle gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (Derya ölçütü)', 'ölçütün doğruluğu sınanabilen inançlarda yanlışı ayıkladığını gösterir'],
    ['Zayıf yanın belirtilmesi (Derya ölçütü)', 'gerekçesi tam verilemeyen inançlarda ölçütün sınırını gösterir'],
    ['Değerlendirmenin örnekle gerekçelendirilmesi (Derya ölçütü)', 'güçlü ve zayıf yanı günlük bir örnekle destekler']),
  task('evaluate', 'Eren’in “İnanç, aklın ulaşamadığı yerde başlar” görüşünün günlük yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: zor zamanlarda umudu ve çabayı sürdürmeyi sağlar; her inancı kanıta bağlama zorunluluğunu kaldırır. Sakınca: aklın sınamadığı inanç yanlış olsa da fark edilmez ve hangi inancın savunulabilir olduğuna dair ölçüt vermez; kişi asılsız bir iddiaya da “gönlüm böyle diyor” diyebilir. Yarar ve sakıncayı görüşten çıkaran ve örnekle gösteren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Eren)', 'görüşün günlük yaşamda sağlayabileceği somut bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Eren)', 'görüşün ölçüt vermemesi ya da yanlışın fark edilmemesi gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşten çıkarılması (Eren)', 'yarar ve sakıncayı görüşün kendi iddiasından çıkarır']),
  task('create', 'Üç görüşten biriyle ilgili, bir öğrencinin gündelik yaşamda karşılaşabileceği kısa bir karar durumu yazınız ve o görüşün bu duruma nasıl yaklaşacağını belirtiniz.',
    'Örnek durum: Bir öğrenci, okulda yayılan bir etkinlik iptali haberini arkadaşlarına iletmek üzeredir. Derya’ya göre iletmeden önce haberin kaynağı ve gerekçesi sorulmalıdır; Funda’ya göre kaynağı doğru bulmak yetmez, haberi iletme kararı ayrıca bir güven ister. Durumu ve seçilen görüşün yaklaşımını tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün karar durumunun yazılması (akıl-inanç)', 'metindekilerden farklı, günlük yaşamdan somut bir karar durumu yazar'],
    ['Görüşün seçilmesi (akıl-inanç)', 'üç görüşten birini adıyla belirtir'],
    ['Görüşün duruma uygulanması (akıl-inanç)', 'seçtiği görüşün duruma nasıl yaklaşacağını görüşün kendi ölçütüyle tutarlı yazar']),
  task('create', 'Akıl ile inancın günlük yaşamda birbirini nasıl tamamlayabileceğini ya da engelleyebileceğini gösteren kısa bir diyalog yazınız.',
    'Örnek: A: Yeni bir spor kulübüne katılacağım, iyi bir şey olacağına inanıyorum. B: Neye dayanarak? A: Kulübün çalışma düzenine baktım, bu akıl yoluyla bir gerekçe; ama ilk antrenmana gitmek için yine de bir cesaret gerekiyor. Diyalog, aklın gerekçe verdiğini ve inancın ya da güvenin ayrıca bir adım gerektirdiğini (ya da birbirini engellediğini) iki sesle gösteriyorsa kabul edilir.',
    ['İki sesin diyalogda yer alması (akıl-inanç)', 'diyalogda iki farklı konuşan ve onların sözleri bulunur'],
    ['Akıl ile inanç ilişkisinin gösterilmesi (akıl-inanç)', 'aklın ve inancın birbirini tamamlama ya da engelleme biçimini gösterir'],
    ['Diyaloğun günlük yaşamla tutarlı olması (akıl-inanç)', 'durumu ve sözleri günlük yaşama uygun ve tutarlı kurar']),
];

// ---------- FEL.11.3.2 a: felsefi argümanları çözümler ----------
const a2: Task[] = [
  task('understand', 'Derya’nın sözünde öncülleri ve sonucu ayırarak yazınız.',
    'Öncül 1: aklın sınamadığı inanç yanlış olsa bile fark edilmez. Öncül 2: bir haberin doğruluğunu sormadan kabul etmeyiz. Sonuç: bir şeye inanıyorsam bunun gerekçesini söyleyebilmeliyim.',
    ['Öncüllerin belirlenmesi (Derya)', 'sınanmayan inancın yanlış olsa da fark edilmeyeceği öncülünü ve haber örneğini öncül olarak yazar'],
    ['Sonucun belirlenmesi (Derya)', 'inancın gerekçeyle söylenebilmesi gerektiği sonucunu belirtir'],
    ['Öncül ile sonucun ayrılması (Derya)', 'öncülleri sonuçtan ayırır, birini ötekinin yerine yazmaz']),
  task('understand', 'Funda’nın sözünde ileri sürdüğü iddiayı ve onu destekleyen gerekçeyi ayırarak yazınız.',
    'İddia: boşluğu akıl değil, bağlanma doldurur. Gerekçe: akıl bir inancı sınayabilir ama onun yerini tutamaz; bir gerekçeyi doğru bulmakla ona göre yaşamak ayrı şeylerdir.',
    ['İddianın belirlenmesi (Funda)', 'boşluğu bağlanmanın doldurduğu iddiasını belirtir'],
    ['Gerekçenin belirlenmesi (Funda)', 'aklın inancın yerini tutamadığı ve doğru bulmakla yaşamanın ayrı olduğu gerekçesini belirtir'],
    ['İddia ile gerekçenin karıştırılmaması (Funda)', 'iddiayı gerekçe, gerekçeyi iddia olarak yazmaz']),
  task('apply', 'Paragraf: “Bir arkadaşımız bize bir iddiayı kanıtsız anlattı. Derya’ya göre ……… . Bu nedenle ………” Boş bırakılan yerleri Derya’nın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: gerekçesi sorulmayan ve sınanmayan inanç yanlış olsa da fark edilmez. Boşluk 2: iddia kabul edilmeden önce gerekçesi sorulmalıdır. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Derya)', 'Derya’nın görüşünü doğru biçimde (sınanmayanın yanlışının fark edilmemesi) tamamlar'],
    ['İkinci boşluğun tamamlanması (Derya)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın akışa uyması (Derya)', 'tamamlanan cümleler verilen durumla tutarlı bir bütün oluşturur']),
  task('apply', 'Eren’in görüşünü “iddia – gerekçe – sonuç” sırasıyla üç cümlelik bir akıl yürütme hâline getiriniz.',
    'Örnek: İddia: bir işin değerli olduğuna inanmak kanıtla kurulmaz. Gerekçe: böyle inançlar aklın ulaşamadığı yerde başlar. Sonuç: bu inançlar gönlün işidir ve akılla ölçülmez. Üç öğeyi sırayla ve doğru kuran her akıl yürütme kabul edilir.',
    ['İddianın yazılması (Eren)', 'değer ya da umut inancının kanıtla kurulmadığı iddiasını yazar'],
    ['Gerekçenin yazılması (Eren)', 'inancın aklın ulaşamadığı yerde başladığı gerekçesini yazar'],
    ['Sonucun yazılması (Eren)', 'gerekçeden çıkan sonucu (gönlün işi, akılla ölçülmez) yazar']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Derya haklıdır; çünkü herkes gerekçesiz inancın yanlış olduğunu söylüyor.” Bu argümandaki temellendirme sorununu belirtiniz.',
    'Gerekçe, çoğunluğun söylediğine başvurur: herkesin söylemesi gerekçesiz inancın yanlış olduğunu göstermez. Derya’nın görüşü ayrı bir gerekçeyle (sınanmayan inancın yanlışının fark edilmemesi) savunulabilir; bu argüman o gerekçeyi kullanmaz. Argüman bu yüzden temellendirilmemiştir.',
    ['Gerekçenin türünün belirlenmesi (çoğunluk argümanı)', 'gerekçenin çoğunluğa başvurduğunu belirtir'],
    ['Sonucun gerekçeden çıkmadığının gösterilmesi (çoğunluk argümanı)', 'herkesin söylemesinin doğruluğu göstermediğini belirtir'],
    ['Savunulabilir gerekçenin ayrılması (çoğunluk argümanı)', 'Derya’nın görüşünün başka bir gerekçeyle savunulabileceğini belirtir']),
  task('analyze', 'Eren’in argümanındaki örtük bir öncülü belirleyiniz ve bu öncüle yöneltilebilecek bir itirazı yazınız.',
    'Örtük öncül: aklın ulaşamadığı yer ilkesel bir sınırdır ve orada akıl hiçbir ölçüt veremez. Bu gösterilmemiştir. İtiraz: aklın ulaşamadığı yer henüz ulaşılamamış bir yer olabilir; ya da gönlün ölçüsü yoksa hangi inancın savunulacağı belirsiz kalır (Derya). Örtük öncülü doğru belirleyen ve ona gerçek bir itiraz kuran çözümlemeler kabul edilir.',
    ['Örtük öncülün belirlenmesi (Eren)', 'aklın ulaşamadığı yerin ilkesel bir sınır olduğu varsayımını gösterir'],
    ['İtirazın yazılması (Eren)', 'örtük öncüle yöneltilebilecek gerçek bir itiraz kurar'],
    ['İtirazın örtük öncülle ilişkilendirilmesi (Eren)', 'itirazın örtük öncülün hangi yönünü zayıflattığını gösterir']),
  task('evaluate', 'Derya, Eren ve Funda’nın argümanlarından hangisinin gerekçe yükünün en ağır olduğunu değerlendiriniz; seçiminizi gerekçelendiriniz.',
    'Üçünün de gerekçe yükü vardır. Derya, her inancın gerekçe vermesi gerektiğini değer ve umut inançlarında da göstermelidir. Eren, aklın sınırının nerede olduğunu ve gönlün neye göre ölçüleceğini göstermelidir. Funda, boşluğu neden bağlanmanın doldurduğunu ve irade ya da alışkanlığın neden doldurmadığını göstermelidir. Her seçim, seçilen görüşün yükünü örnekle ortaya koyduğu ölçüde kabul edilir.',
    ['Seçimin yapılması (akıl-inanç)', 'üç argümandan birini adıyla seçer'],
    ['Gerekçe yükünün gösterilmesi (akıl-inanç)', 'seçtiği argümanın göstermesi gereken şeyi belirtir'],
    ['Seçimin gerekçelendirilmesi (akıl-inanç)', 'seçimini diğer iki argümanla karşılaştırarak ya da örnekle gerekçelendirir']),
  task('evaluate', 'Funda’nın “Bu boşluğu akıl değil, bağlanma doldurur” sonucunun öncüllerinden çıkıp çıkmadığını değerlendiriniz.',
    'Öncüller: akıl bir inancı sınayabilir ama yerini tutamaz; doğru bulmakla ona göre yaşamak ayrı şeylerdir. Sonuç: boşluğu bağlanma doldurur. Sonuç tam çıkmaz: öncüller boşluğun varlığını gösterir ama onu neyin doldurduğunu göstermez; irade, alışkanlık ya da korku da doldurabilir. Sonucun çıkması için bağlanmanın neden bu işi gördüğünü gösteren ek bir öncül gerekir.',
    ['Öncül ve sonucun belirlenmesi (Funda)', 'öncülleri ve sonucu doğru ayırır'],
    ['Sonucun öncüllerden çıkmadığının gösterilmesi (Funda)', 'öncüllerin boşluğun varlığını gösterdiğini ama doldurucuyu göstermediğini belirtir'],
    ['Eksik öncülün belirtilmesi (Funda)', 'bağlanmanın neden bu işi gördüğünü gösteren ek bir öncüle ihtiyaç olduğunu belirtir']),
  task('create', 'Derya’nın argümanını güçlendirecek bir ek öncül yazınız ve bu öncülün hangi itiraza karşı işe yaradığını belirtiniz.',
    'Örnek ek öncül: gerekçe yalnız kanıt değildir; tutarlılık ve yaşantıyla sınanma da gerekçe sayılır. Bu öncül, değer ve umut inançlarının gerekçesinin kanıtla verilemeyeceği itirazına karşı işe yarar: Derya bu inançların da başka türden gerekçeyle sınanabileceğini söyleyebilir. Ek öncülü ve karşılık verdiği itirazı tutarlı kuran özgün her çalışma kabul edilir.',
    ['Ek öncülün yazılması (Derya)', 'Derya’nın sonucunu destekleyen yeni bir öncül yazar'],
    ['Karşılık verilen itirazın belirtilmesi (Derya)', 'öncülün hangi itiraza karşı yazıldığını belirtir'],
    ['Öncülün argümanla tutarlı olması (Derya)', 'yeni öncülün Derya’nın görüşüyle çelişmediğini gösterir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan, akıl ile inanç konulu kısa bir diyalog yazınız.',
    'Örnek: A: İnanç gerekçe istemeli; çünkü sınanmayan inanç yanlış olsa da fark edilmez. B: Ama bir işin değerli olduğuna dair inancın kanıtı yok. A: Kanıt olmayabilir; yine de tutarlılığı ve yaşantıyla sınanıp sınanmadığı sorulabilir. Gerekçe, itiraz ve itirazı yanıtlayan karşılık içeren tutarlı her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması (akıl-inanç)', 'bir görüşün gerekçesini diyalogda açıkça verir'],
    ['İtirazın yazılması (akıl-inanç)', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması (akıl-inanç)', 'itirazı yok saymadan gerekçeli bir karşılık verir']),
];

// ---------- FEL.11.3.2 b: görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini inanç tartışmasından bir örnekle açıklayınız.',
    'Bir görüş, gerekçe(ler) ve bunlardan çıkan sonuçla argümana dönüşür. Örnek: Görüş: inanç gerekçe istemelidir. Gerekçe: gerekçesiz inanç yanlış olsa da fark edilmez. Sonuç: inanç gerekçeyle sınanmalıdır.',
    ['Görüş, gerekçe ve sonucun belirtilmesi (akıl-inanç)', 'argümanın görüş, gerekçe ve sonuç öğelerini belirtir'],
    ['Örneğin tartışmadan verilmesi (akıl-inanç)', 'inanç tartışmasından tutarlı bir örnek verir'],
    ['Gerekçe ile sonucun bağlanması (akıl-inanç)', 'gerekçenin sonucu nasıl desteklediğini gösterir']),
  task('understand', 'İnanç ile akıl ilişkisi konusunda kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: İnanç gerekçeyle birlikte olmalıdır. Bu görüş, inancın gerekçe isteyip istemediği sorusuna cevaptır. İnanç gerekçe istemez ya da gerekçe ister ama yeterli değildir gibi farklı görüşler de bir felsefi soruya doğru bağlanırsa kabul edilir.',
    ['Görüşün açık yazılması (akıl-inanç)', 'inanç ile akıl ilişkisi konusundaki görüşünü açıkça yazar'],
    ['Görüşün felsefi soruya bağlanması (akıl-inanç)', 'görüşü gerekçe isteme ya da birbirinin yerini tutma sorusuna bağlar'],
    ['Görüşün vakayla tutarlı olması (akıl-inanç)', 'görüşü tartışmadaki duruma uygun yazar']),
  task('apply', 'İnanç ile akıl ilişkisi konusunda bir görüş seçiniz ve bu görüşü bir ilke, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: İlke: sınanmayan inanç yanlış olsa da fark edilmez ve yanlış inanç zarar verebilir. Durum: bir iddia kanıtsız yayılıyor. Sonuç: iddia kabul edilmeden önce gerekçesi sorulmalıdır. İlkeyi, durumu ve sonucu doğru ayıran ve sonucu öncüllerden çıkaran her görüş kabul edilir.',
    ['İlkenin yazılması (akıl-inanç)', 'argümanın dayandığı ilkeyi açıkça yazar'],
    ['Durum bilgisinin yazılması (akıl-inanç)', 'tartışmadan ya da günlük yaşamdan bir durum bilgisini öncül olarak yazar'],
    ['Sonucun öncüllerden çıkarılması (akıl-inanç)', 'sonucun ilke ve durumdan çıktığını gösterir']),
  task('apply', '“Aklın ulaşamadığı yerde inanç başlar” ilkesinden yola çıkarak bir inanç durumu için argüman kurunuz.',
    'Örnek: İlke: aklın ulaşamadığı yerde inanç başlar. Durum: bir işin değerli olduğuna inanmak kanıtla kurulamaz. Sonuç: bu inanç kanıtın yokluğuyla çürütülemez. İlkeden hem bu sonucu hem de aklın sınırının yeniden çizilebileceğini ya da gönlün ölçütsüz kalacağını savunan tutarlı argümanlar kurulabilir; aranan tutarlılıktır.',
    ['İlkenin argümana doğru yerleştirilmesi (akıl-inanç)', 'verilen ilkeyi argümanın öncülü olarak kullanır'],
    ['Durum bilgisinin ilkeyle ilişkilendirilmesi (akıl-inanç)', 'seçtiği inanç durumunu ilkeye göre değerlendirir'],
    ['Sonucun ilkeyle tutarlı çıkarılması (akıl-inanç)', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('analyze', 'İnanç ile akıl ilişkisi konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümanın dayandığı varsayımı ve bu varsayıma yöneltilebilecek güçlü bir itirazı çözümleyiniz; itirazın neden güçlü olduğunu açıklayınız.',
    'Örnek: Öncül: sınanmayan inanç yanlış olsa da fark edilmez. Öncül: yanlış inanç zarar verebilir. Sonuç: inanç gerekçeyle sınanmalıdır. Varsayım: inancın doğruluğu yalnız gerekçeyle sınanabilir. İtiraz: değer ve umut inançlarının gerekçesi kanıtla verilemez; bu varsayım onları ya dışlar ya da gerekçeyi zorlama bir hâle getirir. İtiraz güçlüdür, çünkü varsayımın kapsamını sorgular. Kendi argümanını öncül ve sonuçla kuran, varsayımını belirleyen ve itirazın gücünü gerekçelendiren eşdeğer yanıtlar kabul edilir.',
    ['Argümanın kurulması ve varsayımın belirlenmesi (akıl-inanç)', 'inanç ile akıl ilişkisi konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve dayandığı varsayımı gösterir'],
    ['Güçlü bir itirazın belirlenmesi (akıl-inanç)', 'varsayıma yöneltilebilecek güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi (akıl-inanç)', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “İnanç gönlün işidir; bu yüzden hiçbir inanç yanlış olamaz.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: akıl ile ölçülemeyen bir inanç doğru ya da yanlış olamaz. Derya itiraz eder: sınanmayan inanç yanlış olabilir, yalnız yanlışı fark edilmez. Funda da itiraz edebilir: akıl inancı sınayabilir, yani inanç aklın ölçüsünden tümüyle bağımsız değildir. Eren ise öncülü bu biçimiyle kabul etmeyebilir: inancın akılla ölçülememesi, yanlış olamayacağı anlamına gelmez.',
    ['Gizli öncülün belirlenmesi (akıl-inanç)', 'akılla ölçülemeyen inancın doğru ya da yanlış olamayacağı öncülünü gösterir'],
    ['Derya ve Funda’nın itirazının gösterilmesi', 'yanlışın fark edilmemesi ve aklın inancı sınayabilmesi itirazlarını doğru ilişkilendirir'],
    ['Eren’in konumunun ayrıca gösterilmesi', 'Eren’in öncülü bu biçimiyle kabul etmeyebileceğini belirtir']),
  task('evaluate', 'İnanç ile akıl ilişkisi konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümana yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını gösteriniz. İtiraza gerekçeli bir yanıt veriniz ve bu yanıtın itirazı karşılayıp karşılamadığını değerlendiriniz.',
    'Örnek: Öncül: gerekçeyi doğru bulmak ile ona göre yaşamak ayrı şeylerdir. Öncül: bu ayrım her önemli yaşam kararında vardır. Sonuç: aklın verdiği gerekçe tek başına yaşamı yönlendirmeye yetmez. İtiraz: ayrım irade ya da alışkanlıkla da açıklanabilir. Zayıflayan öncül: bu ayrımın inancın ayrı bir rolüne işaret ettiği. Yanıt: irade ve alışkanlık da bir şeye bağlanmayı gerektirir. Değerlendirme: yanıt itirazı kısmen karşılar; ancak bağlanmanın irade ve alışkanlıktan nasıl ayrıldığını göstermek gerekir. Öğrencinin kendi argümanını açıkça kurduğu, itirazı bir öncülle ilişkilendirdiği ve gerekçeli yanıtının yeterliliğini değerlendirdiği eşdeğer çalışmalar kabul edilir.',
    ['Argümanın kurulması ve itirazın belirlenmesi (akıl-inanç)', 'inanç ile akıl ilişkisi konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve bu argümana yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi (akıl-inanç)', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['İtiraza yanıt verilmesi ve yanıtın değerlendirilmesi (akıl-inanç)', 'itiraza gerekçeli bir yanıt verir ve bu yanıtın itirazı karşılayıp karşılamadığını gerekçeyle değerlendirir']),
  task('evaluate', '“Gerekçesi olmayan inanca güvenilmez” gerekçesinin inanç tartışmasında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: güvenilirliğin ölçütünü gerekçenin varlığına bağlar ve bunu önceden kabul eder; oysa tartışılan soru tam olarak inancın gerekçe isteyip istemediğidir, yani sonuç öncülde varsayılmıştır. Ayrıca hangi tür gerekçenin (kanıt, yaşantı, tutarlılık) kastedildiği belirsizdir. Ancak gerekçesiz inancın yanlış olsa da fark edilmeyeceği (Derya) ayrı ve savunulabilir bir gerekçedir; gerekçenin yetersizliği görüşün yanlışlığını göstermez.',
    ['Gerekçenin yetersizliğinin gösterilmesi (akıl-inanç)', 'gerekçenin tartışılan soruyu önceden kabul ettiğini belirtir'],
    ['Belirsizliğin gösterilmesi (akıl-inanç)', 'hangi tür gerekçenin kastedildiğinin belirsiz olduğunu belirtir'],
    ['Görüşten ayrılması (akıl-inanç)', 'gerekçenin yetersizliğinin görüşün yanlışlığını göstermediğini belirtir']),
  task('create', 'Üç görüşten farklı dördüncü bir görüş ortaya koyunuz ve bu görüşü bir gerekçeyle destekleyiniz.',
    'Örnek görüş: inanç gerekçe ister, ama gerekçenin türü inancın alanına göre değişir. Gerekçe: haberde kanıt, değer inancında tutarlılık ve yaşantıyla sınanma gerekçe sayılır. Bu görüşe karşı çıkış: gerekçe türünü kimin belirleyeceği sorusu çözülmemiştir. Üç görüşü tekrar etmeyen, gerekçeyle desteklenen ve tutarlı her görüş kabul edilir.',
    ['Yeni görüşün yazılması (akıl-inanç)', 'Derya, Eren ve Funda’dan farklı, açık bir görüş yazar'],
    ['Görüşün gerekçeyle desteklenmesi (akıl-inanç)', 'görüşü en az bir gerekçeyle destekler'],
    ['Görüşün tutarlılığı (akıl-inanç)', 'görüş ile gerekçenin birbiriyle çelişmediğini gösterir']),
  task('create', 'Derya, Eren ve Funda’nın görüşlerinden birden fazlasından bir şey koruyan birleştirici bir öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğinizi belirtiniz.',
    'Örnek öneri: doğruluğu sınanabilen inançlar gerekçe ister (Derya); değer ve umut inançları kanıtla kurulmaz ama yaşantıyla sınanır (Eren); gerekçeyi doğru bulmak ile ona göre yaşamak arasında ayrıca bir bağlanma gerekebilir (Funda). Çözülmeyen: bağlanmanın hangi durumda gerekçeden ayrı bir şey sayılacağı. Öneri herkesin uzlaşacağını varsaymamalı, çatışmanın nerede sürdüğünü göstermelidir.',
    ['Birleştirici önerinin yazılması (akıl-inanç)', 'en az iki görüşten bir unsuru içeren tutarlı bir öneri yazar'],
    ['Hangi görüşten neyin korunduğunun belirtilmesi (akıl-inanç)', 'korunan unsurları ilgili görüşlerle eşleştirir'],
    ['Çözülmeyen çatışmanın belirtilmesi (akıl-inanç)', 'önerinin hangi çatışmayı çözmediğini ve herkesin uzlaşacağını varsaymadığını gösterir']),
];

// ---------- FEL.11.3.2 c: felsefi metin yazar ----------
const sampleParagraph = '“İnanç tartışmasındaki temel problem, inancın gerekçe isteyip istemediğidir. Her inancın gerekçeyle sınanmasını isteyen görüş, sınanmayan inancın yanlış olsa da fark edilmeyeceğini söyler. Oysa bir işin değerli olduğuna inanmak gibi bazı inançlar kanıtla verilemez; bu nedenle gerekçe istemek her inanç için aynı biçimde işlemez.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: inancın gerekçe isteyip istemediği. Kavram: inanç (ayrıca gerekçe, kanıt). Gerekçe: bir işin değerli olduğuna inanmak gibi bazı inançlar kanıtla verilemez.',
    ['Problemin belirlenmesi (inanç paragrafı)', 'paragrafın problemini inancın gerekçe isteyip istemediği olarak belirtir'],
    ['Kavramın belirlenmesi (inanç paragrafı)', 'paragraftaki felsefi kavramlardan birini (inanç, gerekçe, kanıt) belirtir'],
    ['Gerekçenin belirlenmesi (inanç paragrafı)', 'bazı inançların kanıtla verilemediği gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: gerekçe istemek her inanç için aynı biçimde işlemez. Sonucu taşıyan cümle paragrafın son cümlesidir (“bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi (inanç paragrafı)', 'görüşü gerekçe istemenin her inanç için aynı biçimde işlemediği biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi (inanç paragrafı)', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması (inanç paragrafı)', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “İnanç tartışmasındaki temel problem, akıl ile inancın birbirinin yerini tutup tutamayacağıdır. Funda’ya göre ……… . Bu nedenle ………” Boş bırakılan yerleri Funda’nın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: akıl bir inancı sınayabilir ama yerini tutamaz; gerekçeyi doğru bulmakla ona göre yaşamak ayrı şeylerdir. Boşluk 2: aklın verdiği gerekçe tek başına yaşamı yönlendirmeye yetmez; boşluğu bir bağlanmanın doldurduğu düşünülmelidir. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Funda)', 'Funda’nın görüşünü doğru biçimde (aklın yerini tutamaması, ayrı şeyler) tamamlar'],
    ['İkinci boşluğun tamamlanması (Funda)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Funda)', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Eren’in görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: İnanç tartışmasındaki temel problem, inancın akılla ölçülüp ölçülemeyeceğidir. Eren’in görüşünde “inanç”, aklın ulaşamadığı yerde başlayan ve kanıtla kurulmayan bir tutum olarak yer alır. Bir işin değerli olduğuna inanmak kanıtla kurulamadığından, bu tür inançlar akılla ölçülemez. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması (Eren)', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması (Eren)', 'inanç ya da akıl kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması (Eren)', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “İnanç çok önemlidir, herkes bir şeye inanıyor. Bu yüzden inanç için gerekçe aramaya gerek yok.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (inancın gerekçe isteyip istemediği) belirsizdir. Kavram: inanç, gerekçe, akıl gibi kavramlar ele alınmamış, “önemli” kavramı belirsiz bırakılmıştır. Temellendirme: “herkes bir şeye inanıyor” gerekçesi, gerekçe aramaya gerek olmadığını göstermez; çoğunluğa ya da yaygınlığa başvurmaktır.',
    ['Problemin eksikliğinin gösterilmesi (inanç paragrafı)', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi (inanç paragrafı)', 'inanç, gerekçe ve akıl gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi (inanç paragrafı)', '“herkes inanıyor” gerekçesinin sonucu desteklemediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Akıl önemlidir. Bu yüzden inancı bırakmalıyız.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: akıl önemlidir. Sonuç: inancı bırakmalıyız. Sonuç öncülden çıkmaz: aklın önemli olması, inancın akılla çatıştığını ya da akıl varken inanca yer olmadığını göstermez. Aradaki boşluğu dolduran bir gerekçe (inancın aklın alanını işgal ettiği ya da gerekçesiz kaldığı) gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması (akıl paragrafı)', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi (akıl paragrafı)', 'aklın önemli olmasının inancın bırakılmasını gerektirmediğini belirtir'],
    ['Eksik gerekçenin belirtilmesi (akıl paragrafı)', 'inancın akılla çatıştığı ya da gerekçesiz kaldığı gerekçesinin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence inanç güzel bir şey. Çünkü insan inanınca mutlu oluyor. Herkes inanmalı.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (inancın gerekçe isteyip istemediği), kavramlar yerinde (inanç, gerekçe, kanıt), argüman ve gerekçe açık (bazı inançlar kanıtla verilemez), bütünlük var. Paragraf 2’de problem tanımlanmamış, “güzel” belirsiz, gerekçe (mutlu etmesi) sonucu (herkes inanmalı) desteklemiyor, felsefi terim yok. Paragraf 1’in sınırı: gerekçenin hangi türünün kabul edileceğini söylememesi.',
    ['Problem ve kavram ölçütlerine göre değerlendirme (inanç paragrafları)', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme (inanç paragrafları)', 'iki paragrafın gerekçelerini karşılaştırır ve ikincinin gerekçesinin sonucu desteklemediğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme (inanç paragrafları)', 'iki paragrafı felsefi terim ve metin bütünlüğü bakımından karşılaştırır']),
  task('evaluate', 'Paragraf: “İnanç tartışmasındaki problem, aklın inancın yerini tutup tutamayacağıdır. Funda’ya göre akıl inancın yerini tutamaz. Bu yüzden akıl gereksizdir.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki farklı öneri yazınız.',
    'Temellendirme zayıftır: aklın inancın yerini tutamaması, aklın gereksiz olduğunu göstermez; Funda da aklın inancı sınadığını söyler. Sonuç öncülden çıkmaz. Öneri 1: sonucu “akıl tek başına yeterli değildir” biçiminde değiştirmek. Öneri 2: Funda’nın gerekçesini (doğru bulmak ile yaşamak ayrı şeylerdir) açıkça yazıp sonucu ona bağlamak. Metni gerçekten geliştiren iki farklı öneri kabul edilir.',
    ['Temellendirmenin değerlendirilmesi (Funda paragrafı)', 'gerekçenin sonucu desteklemediğini gösterir'],
    ['İlk önerinin yazılması (Funda paragrafı)', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması (Funda paragrafı)', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Akıl ve inanç ilişkisi tartışmasını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (inanç, akıl, gerekçe) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (inancın gerekçe isteyip istemediği ya da akıl ile inancın birbirinin yerini tutup tutamayacağı); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: inanç gerekçe ister mi? Görüş: ister, çünkü sınanmayan inanç yanlış olsa da fark edilmez. Karşı görüş (Eren): değer ve umut inançları kanıtla kurulmaz. Yanıt: kanıt olmasa da tutarlılık ve yaşantıyla sınanma bir gerekçe sayılabilir. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
  task('create', 'Gerekçeyi doğru bulmakla ona göre yaşamak arasındaki farkı konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (gerekçe, inanç, bağlanma) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (bir gerekçeyi doğru bulmanın ona göre yaşamaya yetip yetmediği); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: gerekçeyi doğru bulmak ona göre yaşamaya yeter mi? Görüş: yetmez, çünkü köprünün sağlam olduğunu bilen kişi yine de geçmekten çekinebilir. Karşı görüş: bu fark irade zayıflığıdır, inançla ilgisi yoktur. Yanıt: irade de bir şeye bağlanmayı gerektirir; fark inancın ayrı bir rolüne işaret edebilir, ama bunu göstermek gerekir. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
];

export const grade11Unit3: Record<string, Focus[]> = {
  'FEL.11.3.1': [
    { context: reasonFaith, focus: 'akıl-inanç ilişkisiyle ilgili felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma inancın gerekçe isteyip istemediği sorusuna dayanır.', 'Tartışma akıl ile inancın birbirinin yerini tutup tutamayacağı sorusuna dayanır.'], inference: 'Kulüp söyleşisi akıl-inanç ilişkisinin gerekçe isteme ve birbirinin yerini tutma sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Bir söylentiyi sormadan kabul etmek.', tasks: a1 },
    { context: reasonFaith, focus: 'akıl-inanç ilişkisiyle ilgili felsefi soru ve problemlerin hayatla ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki görüşler günlük kararlarda da kullanılır.', 'Günlük inanç kararları gerekçe ile bağlanma arasında bir gerilim içerir.'], inference: 'Akıl-inanç ilişkisine dair felsefi sorular günlük yaşamdaki kararlarla ilişkilendirilerek değerlendirilebilir.', limit: 'Günlük örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Bir haberin kaynağına bakmak ile bir işin değerli olduğuna inanmak.', tasks: b1 },
  ],
  'FEL.11.3.2': [
    { context: reasonFaith, focus: 'akıl-inanç ilişkisiyle ilgili felsefi argümanların çözümlenmesi', evidence: ['Üç görüşün her birinin öncülü ve sonucu vardır.', 'Her görüşün gerekçe yükü vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Gerekçesiz inancın yanlışının fark edilmemesi.', tasks: a2 },
    { context: reasonFaith, focus: 'akıl-inanç ilişkisiyle ilgili görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir varsayıma dayanır ve itirazlara açıktır.'], inference: 'Öğrenci inanç ile akıl ilişkisi için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Gerekçeyi doğru bulmak ile ona göre yaşamak arasındaki fark.', tasks: b2 },
    { context: reasonFaith, focus: 'akıl-inanç ilişkisiyle ilgili felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'İnancın gerekçe isteyip istemediği tartışması.', tasks: c2 },
  ],
};
