import type { Level } from './philosophy-exam-case.ts';

// Özgün öğretmen örnekleri. Bileşen sırası 2026 programının 14 ve 19. sayfalarıyla eşlenir.
// Her bileşenin kendi metni ve yanıt kanıtları vardır; ünite anahtar kelimelerinden anahtar üretilmez.
type Focus = { context: string; focus: string; evidence: [string, string]; inference: string; limit: string; example: string };
export const earlyUnits: Record<string, Focus[]> = {
  'FEL.10.1.1': [
    { context: 'Bir öğrenci felsefeyi “bilgeliği arama”, arkadaşı ise “kabullerimizi gerekçeleriyle sorgulama” olarak tanımlar. İlk öğrenci, insanın nasıl yaşaması gerektiğini anlamaya çalışmanın önemini vurgular. İkinci öğrenci, doğru kabul edilen görüşlerin hangi gerekçelere dayandığını sorgulamanın önemini vurgular. İki öğrenci bu etkinliklerin birbiriyle ilişkili olabileceğini kabul eder; ancak felsefeyi tanımlarken farklı yönlere ağırlık verir.', focus: 'felsefenin anlamı ve ortak tanımın imkânı', evidence: ['Birinci tanım, nasıl yaşamak gerektiğini anlamaya yönelik bilgelik arayışına ağırlık verir.', 'İkinci tanım, kabullerin gerekçelerini sorgulamaya ağırlık verir. Bu yönler birbirini dışlamaz.'], inference: 'Farklı kişilerin felsefenin farklı yönlerini öncelikli görmesi, herkesin kabul edeceği ortak bir tanım üzerinde uzlaşmayı güçleştirebilir.', limit: 'Vurgu farklılığı ortak tanımın imkânsız olduğunu kanıtlamaz; iki yönü birleştiren bir öneri de tek başına herkesin uzlaşacağını göstermez.', example: 'Felsefe, insanın kendisi ve dünya hakkındaki kabullerini gerekçeleriyle sorguladığı bir bilgelik arayışıdır.' },
    { context: 'Bir çalışma kâğıdında Hint ve Çin geleneklerinde yaşam ve düzen, Antik Yunan geleneğinde doğa ve varlık, Türk-İslam geleneğinde akıl ve bilgi üzerine tartışmalar bulunduğu yazılıdır. Aynı kâğıtta bu tartışmaların ticaret yolları üzerindeki şehirlerde ve farklı görüşlerin bir arada dinlendiği ortamlarda sürdüğü, bazı dönemlerde ise aynı şehirlerde yeni bir düşünce üretilmediği belirtilir. Bir öğrenci “Felsefe ticaret yapılan yerlerde doğar” der.', focus: 'felsefi düşüncenin özellikleri ve tarihsel gelişimi', evidence: ['Farklı gelenekler farklı soruları öne çıkarır; felsefe tek bir kültüre indirgenemez.', 'Ticaret yollarındaki şehirler ve tartışma ortamları düşüncenin gelişmesini kolaylaştırmış olabilir; ancak aynı şehirlerde yeni düşüncenin üretilmediği dönemler de vardır.'], inference: 'Tarihsel gelişimi tek koşulla değil, birden fazla koşulun birlikte etkisiyle ele almak gerekir.', limit: 'Ticaret ve tartışma ortamının felsefenin tek nedeni olduğu iddiası, metindeki dönemsel istisnalarla desteklenmez.', example: 'Ticaret yoluyla farklı görüşlerle karşılaşan kişiler, kendi kabullerini yeniden sorgulayabilir; bu örnek coğrafya kadar kültürel etkileşimin de önemini gösterir.' },
    { context: 'Öğrenciler üç soruyu karşılaştırır: “Kütüphane kaçta kapanıyor?”, “Bilgi sahibi olmak insanı bilge yapar mı?” ve “Bu hafta en çok ödünç alınan kitap hangisi?” Bir öğrenci, üçüncü sorunun cevabını bulmak zor olduğu için onun felsefi olduğunu söyler. Kütüphaneci, üçüncü sorunun ödünç kayıtlarına bakılarak cevaplanabileceğini belirtir.', focus: 'felsefi sorunun özellikleri ve felsefi soru sorma', evidence: ['Kapanış saati ve ödünç alınan kitap soruları kayıtlara bakılarak, olgusal bilgiyle cevaplanır.', 'Bilgi-bilgelik sorusu kayıtlarla cevaplanmaz; bilgi ve bilgelik kavramlarının anlamını ve ilişkisini sorgulamayı gerektirir.'], inference: 'Felsefi sorular olgusal kayıtla değil, temel kavram ve kabullerin sorgulanmasıyla cevaplanır.', limit: 'Bir sorunun cevabının bulunmasının zor olması, onu tek başına felsefi yapmaz.', example: 'Bir bilgiyi doğru kabul etmemizi sağlayan nedir? Bu soru bilginin dayanağını sorgular; yalnız bir bilgi istemez.' },
    { context: 'Bir bilim insanı suyun hangi koşullarda kaynadığını deneyle araştırır. Bir sanatçı suyu bir resimde yalnızlığın simgesi olarak işler. Bir inanan suyu dinî bir arınma pratiğiyle ilişkilendirir. Bir öğrenci “Bilim ve sanat zaten her şeyi açıklıyor, felsefeye gerek yok” der.', focus: 'felsefenin bilim, din ve sanatla ilişkisi', evidence: ['Bilim deney ve gözlemle olguları, sanat yorum ve ifadeyle anlamı, din inanç ve pratikle bağlılığı öne çıkarır.', 'Bu etkinlikler kendi dayanaklarını sorgulamaz: kanıtın ne sayılacağı, anlamın nasıl oluştuğu ve inancın nasıl temellendirildiği felsefi sorulardır.'], inference: 'Felsefe bu alanların yerini almaz; onların dayanak, yöntem ve anlam iddialarını eleştirel olarak sorgular.', limit: 'Bu örneklerden bilim, sanat veya dinin değersiz olduğu ya da felsefenin onların yerini aldığı sonucu çıkarılamaz.', example: 'Bir eserin güzel sayılmasının dayanaklarını sormak sanatla ilişkili felsefi bir sorudur; resmi yapmakla aynı etkinlik değildir.' },
    { context: 'Bir öğrenci sosyal medyada yaygın bir iddiayı hemen paylaşmak yerine kaynağını ve gerekçelerini sorgular. Sınıfta farklı görüşleri dinleyen öğrenciler ortak karar almadan önce gerekçeleri karşılaştırır; tartışma bir ders saatini aşar ve sınıf yine de tek bir öneride birleşemez. Bir öğrenci bu tartışmanın zaman kaybı olduğunu söyler.', focus: 'felsefenin bireysel ve toplumsal işlevleri', evidence: ['Kaynağı ve gerekçeyi sorgulamak kişinin kendi yargısını gözden geçirmesini sağlar.', 'Gerekçeleri karşılaştırmak ortak kararın dayanaklarını görünür kılar, ancak uzlaşmayı garanti etmez.'], inference: 'Felsefi sorgulama bireysel yargıyı ve toplumsal diyaloğu geliştirebilir; yararı hızlı uzlaşmayla ölçülmemelidir.', limit: 'Sorgulama her zaman hızlı uzlaşma veya kesin doğru karar garantisi vermez.', example: 'Sınıf kurallarının adil olup olmadığını gerekçeleriyle tartışmak hem bireysel yargıyı hem ortak yaşam kararını geliştirebilir.' },
  ],
  'FEL.10.2.1': [
    { context: 'Bir öğrenci önceden yalnız “üzgünüm” derken hayal kırıklığı ve kaygı sözcüklerini öğrendikten sonra duygularını daha ayrıntılı ayırır. Buna karşılık bir bisikletçi, her hareketini sözcüklere dökmeden dengeyi ayarlar. Bir arkadaşları “Sözcüğü olmayan şeyi düşünemeyiz” der.', focus: 'düşünme ve dil arasındaki nedensel ilişkiler', evidence: ['Yeni sözcükler duyguların ayrılmasını ve ifade edilmesini kolaylaştırabilir.', 'Bisiklet örneği bazı işlemlerin sözel anlatım olmadan yürütülebildiğini gösterir.'], inference: 'Dil düşüncenin ayrıntılandırılmasına katkı sağlayabilir; her düşünme işleminin sözcüklere bağlı olduğu sonucu bu örneklerden çıkarılamaz.', limit: 'Bir öğrenci örneği ve bir bisiklet örneği, bütün düşünmenin sözcüklere bağlı olduğunu ya da olmadığını kanıtlamaz.', example: 'Adil ile eşit sözcüklerinin ayrımını öğrenen bir öğrenci, herkese aynı davranmanın her durumda adil olmayabileceğini daha açık ifade edebilir.' },
    { context: 'Bir grup “eşit” ve “adil” sözcüklerini ayırınca okul kaynaklarının dağıtımı hakkındaki görüşlerini daha açık yazar. Bir öğrenci çizdiği şemayı cümlelere dönüştürürken şemada eksik bir ayrıntıyı fark eder ve şemasını değiştirir. Bir arkadaşı “Düşünce önce gelir, dil yalnız onu taşır” der.', focus: 'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma', evidence: ['Kavram ayrımı yargıların daha açık kurulmasına yardımcı olur.', 'Cümleye dönüştürme çalışması şemanın değişmesine yol açmıştır: ifade etme çabası düşünceyi de etkilemiştir.'], inference: 'Düşünme ve dil karşılıklı ilişkilidir: dil düşünceyi düzenleyip paylaşırken ifade etme çabası düşünceyi de değiştirebilir.', limit: 'Karşılıklı ilişkiyi göstermek, dilin ya da düşüncenin tek belirleyici olduğunu kanıtlamaz.', example: 'Bir öğrenci problemi önce çizimle tasarlar, sonra sözcüklerle açıklar ve arkadaşının sorusuyla çizimini düzeltir; ilişki tek yönlü değildir.' },
  ],
  'FEL.10.2.2': [
    { context: 'Bir gün “Bütün okul kitapları kayıtlıdır” ve “Bu atlas bir okul kitabıdır” denir; bunlardan “Bu atlas kayıtlıdır” sonucuna ulaşılır. Başka bir kişi aynı atlas için “Bu atlas hem kayıtlıdır hem kayıtlı değildir” der. Bir öğrenci ise “Bu atlas kayıtlıdır, çünkü sınıfta herkes öyle düşünüyor” der.', focus: 'mantık ve argümantasyonun temel kavramları', evidence: ['İlk iki ifade öncül, atlasın kayıtlı olduğu yargısı sonuçtur; çıkarım tümdengelimdir.', 'Aynı atlasın hem kayıtlı hem kayıtsız olduğunu söylemek çelişkidir; çok kişinin kabul etmesi bir yargıyı doğru kılmaz.'], inference: 'Argümanın değerlendirilmesinde öncül, sonuç, çıkarım ilişkisi ve tutarlılık ayrı ayrı incelenmelidir.', limit: 'Geçerli çıkarım öncüllerin gerçekte doğru olduğunu tek başına kanıtlamaz.', example: 'Bütün memeliler omurgalıdır; yunus memelidir; öyleyse yunus omurgalıdır. İlk iki yargı öncül, son yargı sonuçtur.' },
    { context: 'Sınıf temsilcisi şöyle der: “Bu hafta kütüphaneye yalnız kulüp üyeleri girebilir. Deniz kulüp üyesi değildir. Bu nedenle Deniz bu hafta kütüphaneye giremez.” Deniz’in bir arkadaşı bunu duyunca “Demek ki Deniz hiçbir zaman kütüphaneye giremez” der.', focus: 'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma', evidence: ['Öncül 1: Bu hafta kütüphaneye girebilen herkes kulüp üyesidir.', 'Öncül 2: Deniz kulüp üyesi değildir. Sonuç: Deniz bu hafta kütüphaneye giremez.'], inference: 'Sonuç iki öncülden çıkar; zaman sınırlaması öncül ve sonuçta korunmalıdır.', limit: 'Deniz hiçbir zaman kütüphaneye giremez sonucu metni aşar; kulüp üyesi olmak tek başına giriş garantisi olarak da verilmemiştir.', example: 'P1: Bu hafta giriş için üyelik gereklidir. P2: Deniz üye değildir. C: Deniz bu hafta giremez.' },
    { context: 'Bir duyuruda “Yağış olursa cuma günkü açık hava etkinliği salona alınacak; yağış olmazsa bahçede yapılacak” yazılıdır. Bir öğrenci duyuruyu “Etkinlikler salonda yapılacak” diye özetler.', focus: 'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme', evidence: ['Yağış koşulunda cuma günkü etkinliğin yeri salondur.', 'Yağış olmaması koşulunda aynı etkinliğin yeri bahçedir.'], inference: 'Yeniden ifade, koşulu, zamanı ve kapsamı korumalı; yorum veya yeni iddia eklememelidir.', limit: 'Etkinlik iptal edilir veya bütün etkinlikler salondadır ifadeleri özgün anlamı değiştirir.', example: 'Cuma günkü etkinlik, yağışlı havada salonda, yağışsız havada bahçede gerçekleştirilecektir.' },
  ],
};

type Task = { level: Level; stem: string; key: string; criteria: [string, string, string] };
export function earlyUnitTasks(f: Focus): Task[] {
  const [a, b] = f.evidence;
  const tasks: Task[] = [
    { level: 'understand', stem: `Metinde ${f.focus} hakkında verilen iki temel bilgiyi kendi cümlelerinizle açıklayınız.`, key: `${a} ${b}`, criteria: ['Birinci bilginin doğru açıklanması', 'İkinci bilginin doğru açıklanması', 'Anlamın ve bağlamın korunması'] },
    { level: 'understand', stem: `Metindeki ${f.focus} konusunu bir cümlede özetleyiniz; özeti destekleyen bir ifadeyi belirtiniz.`, key: `${f.inference} Dayanak örneği: ${a}`, criteria: ['Konunun doğru özetlenmesi', 'Uygun metin dayanağının belirtilmesi', 'Özet ve dayanağın ilişkilendirilmesi'] },
    { level: 'apply', stem: `${f.focus} konusunu şu örneğe uygulayarak metinle bağlantısını açıklayınız: ${f.example}`, key: `Örnek bağlantısı: ${f.example} Metindeki ilişki: ${f.inference}`, criteria: ['Örnekte ilgili ilişkinin belirlenmesi', 'Metindeki bilgiyle doğru bağlantı kurulması', 'Bağlantının açıklanması'] },
    { level: 'apply', stem: `Metindeki ${f.focus} konusunu açıklayan farklı bir günlük yaşam örneği veriniz ve bağlantıyı belirtiniz.`, key: `Örnek: ${f.example} Kabul: aynı ilişkiyi doğru gösteren farklı örnekler de kabul edilir. ${f.inference}`, criteria: ['Konuya uygun örnek', 'Örnekte ilişkinin doğru gösterilmesi', 'Metinle bağlantının açıklanması'] },
    { level: 'analyze', stem: `Metinde ${f.focus} için verilen iki bilgiyi ayırınız ve aralarındaki ilişkiyi çözümleyiniz.`, key: `Bilgi 1: ${a} Bilgi 2: ${b} İlişki: ${f.inference}`, criteria: ['Birinci bilginin doğru ayrılması', 'İkinci bilginin doğru ayrılması', 'İlişkinin gerekçeli çözümlenmesi'] },
    { level: 'analyze', stem: `Metinde ${f.focus} bakımından hangi sonuca ulaşılabilir? Bu sonucun dayanaklarını ve metinden çıkarılamayacak bir yargıyı ayırınız.`, key: `Sonuç: ${f.inference} Dayanaklar: ${a} ${b} Sınır: ${f.limit}`, criteria: ['Metinle uyumlu sonuç', 'Sonucun dayanaklarının gösterilmesi', 'Çıkarım sınırının doğru ayrılması'] },
    { level: 'evaluate', stem: `“${f.inference}” yargısını metindeki dayanakları ve sınırları açısından değerlendiriniz.`, key: `Dayanaklar: ${a} ${b} Sınır: ${f.limit} Bu sınırı koruyan gerekçeli değerlendirmeler kabul edilir.`, criteria: ['Destekleyici kanıtın doğru kullanımı', 'Sınırın doğru değerlendirilmesi', 'Gerekçeli değerlendirme yargısı'] },
    { level: 'evaluate', stem: `${f.focus} hakkında metnin izin verdiği sonuçla aşırı genellemeyi ayırarak gerekçeli bir değerlendirme yapınız.`, key: `Desteklenen yargı: ${f.inference} Aşırı genellemenin sınırı: ${f.limit}`, criteria: ['Desteklenen yargının belirlenmesi', 'Aşırı genellemenin ayırt edilmesi', 'Ayrımın gerekçelendirilmesi'] },
    { level: 'create', stem: `${f.focus} konusunda yeni bir soru ve bu soruya gerekçeli bir yanıt oluşturunuz.`, key: `Örnek soru: ${f.focus} hangi dayanaklarla açıklanabilir? Örnek yanıt: ${f.inference} Çünkü ${a} ${b} Konuya uygun farklı sorular ve gerekçeli yanıtlar kabul edilir.`, criteria: ['Konuya uygun yeni soru', 'Soruya cevap veren tutarlı yanıt', 'Yanıtın gerekçelendirilmesi'] },
    { level: 'create', stem: `${f.focus} konusunu gösteren yeni bir kısa durum yazınız; durumun hangi ilişkiyi gösterdiğini açıklayınız.`, key: `Örnek durum: ${f.example} Gösterdiği ilişki: ${f.inference} Aynı ilişkiyi doğru kuran özgün durumlar kabul edilir.`, criteria: ['İlişkiye uygun özgün durum', 'Durumda ilişkiyi gösteren öğeler', 'İlişkinin doğru açıklanması'] },
  ];

  const analysis: Record<string, [string, string]> = {
    'felsefenin anlamı ve ortak tanımın imkânı': ['İki tanımın farklı yönlere verdiği ağırlığı karşılaştırınız; bu vurgu farklılığını ortak tanım üzerinde uzlaşma güçlüğüyle ilişkilendirerek çözümleyiniz.', 'İki örnekten hareketle felsefe için ortak bir çerçeve önerilebilir mi? Önerinizin dayandığı yargıyı ve metinden çıkarılamayacak sonucu ayırınız.'],
    'felsefi düşüncenin özellikleri ve tarihsel gelişimi': ['Metindeki geleneklerin soru çeşitliliği ile şehir ve tartışma ortamı bilgisini felsefenin gelişimi bakımından ilişkilendirerek çözümleyiniz.', '“Felsefe ticaret yapılan yerlerde doğar” iddiasının metindeki hangi bilgilerle sınırlandığını ve neden tek neden iddiası olarak kabul edilemeyeceğini çözümleyiniz.'],
    'felsefi sorunun özellikleri ve felsefi soru sorma': ['Metindeki üç sorunun cevaplanma biçimlerini karşılaştırarak hangisinin felsefi olduğunu gerekçelendirerek çözümleyiniz.', 'Öğrencinin “cevabı zor olduğu için felsefidir” yargısını metindeki üç soru üzerinden değerlendirerek sınırını belirleyiniz.'],
    'felsefenin bilim, din ve sanatla ilişkisi': ['Bilim, sanat ve din örneklerinin dayandığı yöntemleri ayırarak felsefi sorgulamanın bu alanlara hangi bakımdan yöneldiğini çözümleyiniz.', '“Bilim ve sanat her şeyi açıklıyor, felsefeye gerek yok” yargısının metindeki örneklerle hangi bakımdan sınırlandığını çözümleyiniz.'],
    'felsefenin bireysel ve toplumsal işlevleri': ['Kaynak sorgulama ile ortak karar tartışmasını felsefenin bireysel ve toplumsal işlevleri bakımından ayırarak çözümleyiniz.', '“Tartışma uzlaşmayla bitmedi, bu yüzden sorgulama yararsızdır” yargısındaki çıkarımı metne dayanarak çözümleyiniz; sorgulamanın yine de sağladığı katkıyı belirtiniz.'],
    'düşünme ve dil arasındaki nedensel ilişkiler': ['Duygu sözcüklerini öğrenme ve bisiklet örneklerinin “Sözcüğü olmayan şeyi düşünemeyiz” iddiasını hangi bakımdan desteklediğini ya da sınırladığını çözümleyiniz.', 'Dilin düşünceyi ayrıntılandırdığı yargısıyla bütün düşünmenin dile bağlı olduğu yargısını metindeki örneklere dayanarak ayırınız.'],
    'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma': ['Kavramları ayırma ve şemayı cümleye dönüştürme örneklerini birbiriyle ilişkilendirerek düşünme-dil ilişkisi hakkında uyumlu bir yargı oluşturunuz.', '“Düşünce önce gelir, dil yalnız onu taşır” yargısını metindeki örneklere dayanarak değerlendiriniz; tek yönlü ilişkinin neyi açıklayamadığını belirtiniz.'],
    'mantık ve argümantasyonun temel kavramları': ['Atlas örneğindeki öncülleri ve sonucu ayırınız; çıkarım türünü ve çelişkili ifadeyi belirleyiniz. Çıkarımın geçerliliği ile “sınıfta herkes öyle düşünüyor” gerekçesini karşılaştırarak aradaki farkı açıklayınız.', 'Atlas argümanının geçerliliği ile “sınıfta herkes öyle düşünüyor” gerekçesinin dayanağını karşılaştırarak aradaki farkı çözümleyiniz.'],
    'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma': ['Temsilcinin sözünü iki öncül ve bir sonuç olarak yeniden düzenleyiniz.', 'Arkadaşın “hiçbir zaman giremez” sonucunun temsilcinin sözünü hangi bakımdan aştığını öncül-sonuç ilişkisi üzerinden açıklayınız.'],
    'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme': ['Duyurudaki iki koşullu ilişkiyi ayırınız ve kendi cümlelerinizle yeniden yazınız.', 'Öğrencinin “Etkinlikler salonda yapılacak” özetini özgün duyuruyla karşılaştırınız; kaybolan koşulu ve değişen kapsamı belirtiniz.'],
  };
  const analysisCriteria: Record<string, [string, string, string]> = {
    'felsefenin anlamı ve ortak tanımın imkânı': ['Birinci tanımın bilgelik yöneliminin belirlenmesi', 'İkinci tanımın gerekçeli sorgulama yöneliminin belirlenmesi', 'Vurgu farklılığının uzlaşma güçlüğüyle ilişkilendirilmesi'],
    'felsefi düşüncenin özellikleri ve tarihsel gelişimi': ['Gelenekler arası soru çeşitliliğinin açıklanması', 'Şehir ve tartışma ortamının etkisi ile dönemsel istisnanın ilişkilendirilmesi', 'Gelişimin tek nedene indirgenemeyeceğinin gösterilmesi'],
    'felsefi sorunun özellikleri ve felsefi soru sorma': ['Saat ve ödünç sorularının olgusal niteliğinin ayrılması', 'Bilgi-bilgelik sorusunun kavramsal niteliğinin gerekçelendirilmesi', 'Cevap güçlüğünün tek ölçüt olamayacağının gösterilmesi'],
    'felsefenin bilim, din ve sanatla ilişkisi': ['Üç alanın yöntem ve dayanaklarının ayrılması', 'Felsefi sorgulamanın bu dayanaklara yönelişinin açıklanması', 'Felsefenin yerine geçme değil eleştirel yaklaşma ilişkisinin kurulması'],
    'felsefenin bireysel ve toplumsal işlevleri': ['Kaynak sorgulamanın bireysel işlevinin açıklanması', 'Gerekçe karşılaştırmanın toplumsal işlevinin açıklanması', 'Uzlaşma ile yarar arasındaki ayrımın gerekçelendirilmesi'],
    'düşünme ve dil arasındaki nedensel ilişkiler': ['Sözcüklerin düşünceyi ayrıntılandırma etkisinin açıklanması', 'Bisiklet örneğinin sözel olmayan yönünün ayrılması', 'Bütün düşünmeyi dile indirgemeden ilişki kurulması'],
    'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma': ['Kavram ayrımının düşünceyi düzenleme etkisinin açıklanması', 'Şemanın değişmesinin ifade etmenin düşünceyi etkilediğini gösterdiğinin belirtilmesi', 'Tek yönlü iddianın sınırının gösterilerek karşılıklı ilişkinin kurulması'],
    'mantık ve argümantasyonun temel kavramları': ['Atlas argümanındaki öncül ve sonucun ayrılması', 'Tümdengelim ve çelişki örneğinin doğru belirlenmesi', 'Geçerlilik ile çoğunluk kabulünün gerekçe olarak ayrılması'],
    'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma': ['Giriş için üyelik gerektiren birinci öncülün doğru yazılması', 'Denizin üye olmadığı ikinci öncülün doğru yazılması', 'Bu hafta giremeyeceği sonucunun bağlamı korunarak yazılması'],
  };
  if (analysisCriteria[f.focus]) tasks[4].criteria = analysisCriteria[f.focus];
  const stems = analysis[f.focus];
  if (stems) {
    tasks[4].stem = stems[0]; tasks[5].stem = stems[1];
    if (f.focus === 'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma') {
      tasks[4].key = `Örnek düzenleme: ${f.example} Ayrıntı: ${a} ${b}`;
    }
    if (f.focus === 'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme') {
      tasks[4].key = `Örnek yeniden ifade: ${f.example} Korunan koşullar: ${a} ${b}`;
      tasks[4].criteria = ['Yağış koşulunun ve salon bilgisinin korunması', 'Yağış olmaması koşulunun ve bahçe bilgisinin korunması', 'Cuma gününün ve tek etkinlik kapsamının korunması'];
    }
  }
  // Onaylanan dört soruluk paket: iki A/B görevi aynı düzeyde farklı yönergeler taşır.
  if (f.focus === 'felsefenin anlamı ve ortak tanımın imkânı') {
    tasks[0] = { level: 'understand', stem: 'Metindeki iki felsefe tanımının hangi yönlere ağırlık verdiğini kendi cümlelerinizle açıklayınız. Bu vurgu farklılığının herkesin kabul edeceği ortak bir tanıma ulaşmayı neden güçleştirebileceğini belirtiniz.', key: `${a} ${b} ${f.inference} ${f.limit}`, criteria: ['Birinci tanımın vurgusunun açıklanması', 'İkinci tanımın vurgusunun açıklanması', 'Ortak tanımın güçlüğünün açıklanması'] };
    tasks[1] = { ...tasks[0], stem: 'İki öğrencinin felsefeye ilişkin tanımlarını özetleyiniz; hangi yönleri öncelikli gördüklerini ve bu farklılığın ortak tanım üzerinde uzlaşmayı nasıl güçleştirebileceğini açıklayınız.', key: `Vurgu karşılaştırması: ${a} ${b} Ortak tanım: ${f.inference} ${f.limit}` };
  }
  if (f.focus === 'felsefi düşüncenin özellikleri ve tarihsel gelişimi') {
    const criteria: [string, string, string] = ['Metindeki ilgili bilginin belirlenmesi', 'Bilginin yeni duruma uygulanması', 'Tarihsel gelişimin çok koşullu ele alınması'];
    tasks[2] = { level: 'apply', stem: 'Metindeki bilgileri aşağıdaki yeni duruma uygulayınız: Yüzyıllar boyunca ticaretin yoğun yapıldığı bir liman kentinde yönetim, farklı görüşlerin açıkça dile getirilmesine izin vermemektedir. Bu kentte felsefi düşüncenin gelişmesini bekleyip beklemediğinizi, metindeki hangi bilgiye dayandığınızı göstererek açıklayınız.', key: 'Kentte ticaret vardır, fakat farklı görüşlerin açıkça dile getirilmesine izin verilmemektedir. Metindeki tartışma ortamları ve aynı ticaret şehirlerinde yeni düşünce üretilmeyen dönemler ticaretin tek başına yetmediğini gösterir. Gelişimin sınırlı kalması beklenebilir; kesin yargı verilemeyeceğini gerekçelendiren yanıtlar da kabul edilir.', criteria };
    tasks[3] = { level: 'apply', stem: 'Metindeki bilgileri aşağıdaki yeni duruma uygulayınız: Farklı bölgelerden gelen tüccarların her hafta buluştuğu bir kasabada insanlar yalnızca kendi görüşlerini söylemekte, başkalarının görüşlerini dinlememektedir. Bu kasabada felsefi düşüncenin gelişmesi için hangi koşulun eksik olduğunu, metindeki hangi bilgiye dayandığınızı göstererek açıklayınız.', key: 'Kasabada ticaret ve buluşma vardır; eksik koşul karşılıklı dinleme ve tartışmadır. Metindeki farklı görüşlerin bir arada dinlendiği ortamlar bu bağlantının dayanağıdır; ticaret şehirlerinde düşünce üretilmeyen dönemler ticaretin tek başına yetmediğini gösterir.', criteria };
  }
  if (f.focus === 'mantık ve argümantasyonun temel kavramları') {
    const key = 'İlk iki ifade öncül, atlasın kayıtlı olduğu yargısı sonuçtur; genel kayıt kuralı atlasın okul kitabı olmasıyla birlikte bu sonucu verir (tümdengelim). Aynı atlas hakkında aynı zamanda ve aynı bakımdan kayıtlı olma ile kayıtlı olmama birlikte doğru olamaz (çelişki). “Herkes öyle düşünüyor” çoğunluğa başvurmadır; kabul edenlerin sayısı atlasın gerçekten kayıtlı olduğuna kanıt oluşturmaz. Kavram adlandırması ve işlev açıklaması bağımsız puanlanır; eşdeğer adlar kabul edilir.';
    const criteria: [string, string, string] = ['Çıkarım yapısının tanınması ve açıklanması', 'Çelişkinin tanınması ve açıklanması', 'Çoğunluğa başvurmanın tanınması ve açıklanması'];
    tasks[0] = { level: 'understand', stem: 'Metindeki üç duruma (atlasın kayıtlı olduğu sonucuna ulaşılması; aynı atlas için “hem kayıtlıdır hem kayıtlı değildir” denmesi; “sınıfta herkes öyle düşünüyor” denmesi) karşılık gelen mantık ve argümantasyon kavramlarını belirtip her birini kendi cümlelerinizle açıklayınız.', key, criteria };
    tasks[1] = { level: 'understand', stem: 'Metinde atlasın kayıtlı olduğu sonucuna götüren ifadeleri ve sonucu mantık terimleriyle adlandırarak çıkarımı açıklayınız; ardından ikinci ve üçüncü kişinin söylediklerinin neden bir argümanı güçlendirmediğini, ilgili kavramları adlandırarak kendi cümlelerinizle açıklayınız.', key: `Üç durumun açıklaması: ${key}`, criteria };
  }
  if (f.focus === 'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma') {
    const criteria: [string, string, string] = ['Kural öncülünün bağlamla yazılması', 'Durum öncülü ile sonucun ayrılması', 'Genişletilmiş sonucun değerlendirilmesi'];
    tasks[2] = { level: 'apply', stem: 'Sınıf temsilcisinin sözlerini bağlamı (zaman, kural, kişi) koruyarak öncül(ler) ve sonuç biçiminde ayırıp yazınız. Ardından Deniz’in arkadaşının “Deniz hiçbir zaman kütüphaneye giremez” sonucunun bu öncüllerden neden çıkmadığını belirtiniz.', key: `${f.example} Kural yalnız bu hafta için geçerlidir; “hiçbir zaman” zaman kapsamını genişlettiği için öncüllerden çıkmaz.`, criteria };
    tasks[3] = { level: 'apply', stem: 'Aşağıdaki durumu bağlamı koruyarak öncül(ler) ve sonuç biçiminde ayırınız: “Bu ay spor salonuna yalnız kayıtlı üyeler girebilir. Selin kayıtlı üye değildir. Bu yüzden Selin bu ay salona giremez.” Ardından “Selin hiçbir zaman salona giremez” denirse bu sonucun neden çıkmayacağını açıklayınız.', key: 'Kural öncülü: Bu ay spor salonuna yalnız kayıtlı üyeler girebilir. Durum öncülü: Selin kayıtlı üye değildir. Sonuç: Selin bu ay salona giremez. “Hiçbir zaman” kuralın bu ay ile sınırlı zaman kapsamını aşar.', criteria };
  }
  // Kalan şablon artıkları: bileşen cümlesi taşıyan ve yargıyı kökte veren sorular, aynı düzeyde ve aynı ölçütlerle paralel A/B çiftlerine çevrilir.
  if (f.focus === 'düşünme ve dil arasındaki nedensel ilişkiler') {
    const criteria: [string, string, string] = ['Duygu sözcükleri örneğinin yargıya katkısının belirlenmesi', 'Bisiklet örneğinin yargıyı sınırlamasının belirlenmesi', 'Gerekçeli değerlendirme yargısının kurulması'];
    const key = 'Duygu sözcüklerini öğrenen öğrenci duygularını daha ayrıntılı ayırır; bu örnek dilin düşünceyi ayrıntılandırmaya katkı sağlayabildiğini gösterir. Bisikletçi hareketlerini sözcüğe dökmeden dengeyi ayarlar; bu örnek bazı işlemlerin sözcüksüz yürütülebildiğini gösterir. “Sözcüğü olmayan şeyi düşünemeyiz” genellemesi bu iki örnekle desteklenmez; “dil düşünceye katkı sağlayabilir” biçiminde daraltılmış yargı metinle uyumludur. Bisiklet dengesinin “düşünme” sayılıp sayılmayacağına ilişkin gerekçeli itiraz kabul edilir.';
    tasks[6] = { level: 'evaluate', stem: 'Arkadaşın “Sözcüğü olmayan şeyi düşünemeyiz” yargısını metindeki iki örneğe dayanarak değerlendiriniz; yargıya katılıp katılmadığınızı gerekçelendiriniz.', key, criteria };
    tasks[7] = { level: 'evaluate', stem: '“Sözcüğü olmayan şeyi düşünemeyiz” yargısının metindeki örneklerle desteklenen ve desteklenmeyen kısmını ayırınız; yargıyı metne uygun biçimde yeniden yazınız.', key: `${key} Yeniden yazım örneği: Sözcükler düşünceyi ayrıntılandırmaya katkı sağlayabilir; ancak bu örneklerden her düşünmenin sözcüğe bağlı olduğu sonucu çıkmaz.`, criteria: [criteria[0], criteria[1], 'Yargının metne uygun biçimde yeniden yazılması'] };
  }
  if (f.focus === 'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma') {
    const questionCriteria: [string, string, string] = ['Metindekilerden farklı, ilişkiye uygun yeni bir sorunun yazılması', 'Yanıtın soruyla tutarlı ve ilişkiyi gösterecek biçimde kurulması', 'Yanıtın metindeki örneğe dayandırılması'];
    const situationCriteria: [string, string, string] = ['Metindekilerden farklı, ilişkiye uygun yeni bir durumun yazılması', 'Durumun ilişkiyi tutarlı biçimde göstermesi', 'Durumun metindeki hangi örnekle eşleştiğinin açıklanması'];
    tasks[8] = { level: 'create', stem: 'Metindeki bilgileri dikkate alarak düşünme ile dil arasındaki ilişki hakkında yeni bir soru yazınız ve metne dayanan gerekçeli bir yanıt veriniz.', key: 'Örnek soru: İfade etme çabası düşünceyi de değiştirebilir mi? Örnek yanıt: Şemayı cümleye dönüştüren öğrenci eksik ayrıntıyı fark edip şemasını değiştirmiştir; “eşit” ve “adil” ayrımı da görüşlerin daha açık yazılmasını sağlamıştır. Bu örnekler dil ile düşüncenin birbirini etkileyebildiğini gösterir; dilin ya da düşüncenin tek belirleyici olduğu bu örneklerden çıkmaz. Metne dayanan farklı sorular ve gerekçeli yanıtlar (tek yönlü ilişkiyi savunanlar dahil) kabul edilir; metnin tek yönlü bir ilişkiyi kanıtladığı iddiası kabul edilmez.', criteria: questionCriteria };
    tasks[9] = { level: 'create', stem: 'Metindekilerden farklı, düşünme ile dil arasındaki ilişkiyi gösteren kısa bir durum yazınız; durumun metindeki hangi örnekle aynı ilişkiyi gösterdiğini açıklayınız.', key: `Örnek durum: ${f.example} Eşleşen örnek: şemayı cümleye dönüştürürken şemanın değişmesi (ifade etme çabasının düşünceyi etkilemesi); kavram ayrımı örneği (dilin düşünceyi düzenlemesi) ya da ikisi birlikte de kabul edilir. İlişki: ${f.inference} Özgün durumlar ve metindeki örnekle doğru eşleştirmeler kabul edilir.`, criteria: situationCriteria };
  }
  if (f.focus === 'felsefi sorunun özellikleri ve felsefi soru sorma') {
    const criteria: [string, string, string] = ['Saat ve ödünç sorularının olgusal niteliğinin ayrılması', 'Bilgi-bilgelik sorusunun kavramsal niteliğinin gerekçelendirilmesi', 'Cevap güçlüğünün tek ölçüt olamayacağının gösterilmesi'];
    const key = 'Kapanış saati ve ödünç alınan kitap soruları kayıtlara bakılarak, olgusal bilgiyle cevaplanır. Bilgi-bilgelik sorusu kayıtlarla cevaplanmaz; bilgi ve bilgelik kavramlarının anlamını ve ilişkisini sorgulamayı gerektirir, felsefi olan odur. Üçüncü sorunun cevabını bulmanın zor olması onu felsefi yapmaz; ölçüt cevabın güçlüğü değil, cevabın nasıl bulunduğudur.';
    tasks[4] = { level: 'analyze', stem: 'Üç sorunun cevaplanma biçimlerini karşılaştırarak hangisinin felsefi olduğunu belirleyiniz; öğrencinin “cevabı zor olduğu için felsefidir” yargısının bu belirlemeyi neden desteklemediğini gerekçelendiriniz.', key, criteria };
    tasks[5] = { level: 'analyze', stem: 'Öğrencinin “cevabı zor olduğu için felsefidir” yargısını üç sorunun cevaplanma biçimleri üzerinden çözümleyiniz; bu yargının sınırını ve metindeki hangi sorunun felsefi sayılması gerektiğini gösteriniz.', key, criteria };
  }
  if (f.focus === 'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme') {
    const criteria: [string, string, string] = ['Yağış koşulunun ve salon bilgisinin korunması', 'Yağış olmaması koşulunun ve bahçe bilgisinin korunması', 'Cuma gününün ve tek etkinlik kapsamının korunması; özetteki kaybın belirtilmesi'];
    const key = `Örnek yeniden ifade: ${f.example} Korunan koşullar: ${a} ${b} Özetteki kayıp: yağış olmaması durumunda etkinliğin bahçede yapılacağı koşulu düşmüş, “cuma günkü açık hava etkinliği” kapsamı “etkinlikler” diye genişlemiştir.`;
    tasks[4] = { level: 'analyze', stem: 'Duyurudaki iki koşullu ilişkiyi ayırarak anlamı değiştirmeden kendi cümlelerinizle yeniden yazınız; öğrencinin özetinin bu yazımdan hangi bakımdan ayrıldığını belirtiniz.', key, criteria };
    tasks[5] = { level: 'analyze', stem: 'Öğrencinin “Etkinlikler salonda yapılacak” özetini özgün duyuruyla karşılaştırınız; kaybolan koşulu ve değişen kapsamı belirtiniz. Ardından duyuruyu anlamı değiştirmeden kendi cümlelerinizle yeniden yazınız.', key, criteria };
  }
  // Genel şablon kökleri bileşen ifadesiyle başlayabilir; soru kökü her zaman büyük harfle başlar.
  return tasks.map(task => ({ ...task, stem: task.stem.charAt(0).toLocaleUpperCase('tr') + task.stem.slice(1) }));
}

export function earlyUnitCriterion(points: number, labels: [string, string, string]) {
  const definition = labels[0] === 'Birinci tanımın vurgusunun açıklanması';
  const logic = labels[0] === 'Çıkarım yapısının tanınması ve açıklanması';
  const shares = definition || logic ? [Math.floor(points / 3), Math.floor(points / 3), 0] : [Math.floor(points * .4), Math.floor(points * .4), 0];
  shares[2] = points - shares[0] - shares[1];
  const descriptions: Record<string, string> = {
    'Birinci tanımın vurgusunun açıklanması': 'bilgelik arayışını nasıl yaşamak gerektiğini anlamaya çalışmayla ilişkilendirir',
    'İkinci tanımın vurgusunun açıklanması': 'kabulleri sorgulamayı görüşlerin gerekçelerini araştırmayla ilişkilendirir',
    'Ortak tanımın güçlüğünün açıklanması': 'farklı önceliklerin uzlaşmayı güçleştirebileceğini açıklar; tanımların birbirini dışladığını veya ortak tanımın imkânsızlığını varsaymaz',
    'Metindeki ilgili bilginin belirlenmesi': 'tartışma ortamını ve ticaret şehirlerinde düşünce üretilmeyen dönemleri dayanak gösterir',
    'Bilginin yeni duruma uygulanması': 'yeni durumda bulunan ticaret koşulu ile eksik tartışma veya dinleme koşulunu ayırıp sonuca bağlar',
    'Tarihsel gelişimin çok koşullu ele alınması': 'gelişimi tek koşula indirgemez; kesin gelişmeme hükmü çıkarmaz',
    'Kural öncülünün bağlamla yazılması': 'üyeliğin gerekli koşul olduğunu ve belirtilen zaman sınırını korur',
    'Durum öncülü ile sonucun ayrılması': 'kişinin üye olmadığını öncül, yalnız belirtilen dönemde giremeyeceğini sonuç olarak ayırır',
    'Genişletilmiş sonucun değerlendirilmesi': 'hiçbir zaman sonucunun kuralın zaman kapsamını aştığını açıklar',
    'Duygu sözcükleri örneğinin yargıya katkısının belirlenmesi': 'yeni sözcüklerin duyguları daha ayrıntılı ayırmayı kolaylaştırdığını dilin düşünceye katkısı olarak yorumlar',
    'Bisiklet örneğinin yargıyı sınırlamasının belirlenmesi': 'sözcüğe dökülmeden yürütülen işlemin “her düşünme sözcüğe bağlıdır” genellemesini sınırladığını belirtir; bisikletin düşünme sayılıp sayılmayacağına gerekçeli itirazı da kabul edilir',
    'Gerekçeli değerlendirme yargısının kurulması': 'yargıya katılma, katılmama ya da daraltılmış yeni yargıyı metindeki dayanaklarla gerekçelendirir',
    'Metindekilerden farklı, ilişkiye uygun yeni bir sorunun yazılması': 'düşünme ile dil ilişkisine yönelik, metindekilerden farklı bir soru yazar; yalnız durum yazmak bu ölçütü karşılamaz',
    'Yanıtın soruyla tutarlı ve ilişkiyi gösterecek biçimde kurulması': 'yazdığı soruya doğrudan cevap verir ve yanıtta düşünme-dil ilişkisini gösterir; dilin ya da düşüncenin tek belirleyici olduğunu metinden kanıtlanmış saymaz',
    'Yanıtın metindeki örneğe dayandırılması': 'yanıtını metindeki kavram ayrımı ya da şemanın değişmesi örneğine dayandırır',
    'Metindekilerden farklı, ilişkiye uygun yeni bir durumun yazılması': 'düşünme ile dil ilişkisini gösteren, metindekilerden farklı kısa bir durum yazar; yalnız soru ve yanıt yazmak bu ölçütü karşılamaz',
    'Durumun ilişkiyi tutarlı biçimde göstermesi': 'durumda dil ile düşüncenin ilişkisini tutarlı biçimde gösterir; dilin ya da düşüncenin tek belirleyici olduğunu metinden kanıtlanmış saymaz',
    'Durumun metindeki hangi örnekle eşleştiğinin açıklanması': 'durumun metindeki kavram ayrımı ya da şemanın değişmesi örneklerinden hangisiyle aynı ilişkiyi gösterdiğini açıklar',
    'Yargının metne uygun biçimde yeniden yazılması': 'yargıyı desteklenen kısmı koruyup aşırı genellemeyi çıkararak metne uygun biçimde yeniden yazar; yalnız katılma ya da katılmama bu ölçütü karşılamaz',
    'Saat ve ödünç sorularının olgusal niteliğinin ayrılması': 'kapanış saati ve ödünç sorularının kayıtlarla cevaplanan olgusal sorular olduğunu belirtir',
    'Bilgi-bilgelik sorusunun kavramsal niteliğinin gerekçelendirilmesi': 'bilgi-bilgelik sorusunun kayıtla değil kavramların anlamı ve ilişkisi üzerine sorgulamayla cevaplanacağını gerekçelendirir',
    'Cevap güçlüğünün tek ölçüt olamayacağının gösterilmesi': 'cevabı bulmanın zor olmasının bir soruyu tek başına felsefi yapmadığını, ölçütün cevabın nasıl bulunduğu olduğunu gösterir',
    'Cuma gününün ve tek etkinlik kapsamının korunması; özetteki kaybın belirtilmesi': 'cuma gününü ve tek etkinlik kapsamını korur; özetin yağışsız durumu ve kapsamı nasıl kaybettiğini belirtir',
  };
  const names = ['öncül ve sonuç', 'çelişki veya çelişmezlik ilkesinin ihlali', 'çoğunluğa başvurma veya eşdeğer ad'];
  const explanations = ['genel kayıt kuralı ve atlasın okul kitabı olması arasındaki bağı açıklayarak atlasın kayıtlı olduğu sonucuna ulaşır; tümdengelim terimi ayrıca şart değildir', 'aynı atlas hakkında aynı zamanda ve aynı bakımdan kayıtlı olma ile olmamanın birlikte doğru olamayacağını açıklar', 'kabul edenlerin sayısının atlasın gerçekten kayıtlı olduğuna kanıt oluşturmadığını açıklar'];
  return labels.map((label, i) => {
    if (logic) {
      const naming = shares[i] > 0 ? Math.max(1, Math.floor(shares[i] / 4)) : 0, explanation = shares[i] - naming;
      return `${label}: ${shares[i]} puan. Tam: adlandırma ve açıklama doğru ve eksiksizdir. Adlandırma: ${names[i]} (${naming} puan); yok/yanlış: 0 puan. Açıklama: ${explanations[i]} (${explanation} puan); kısmi: doğru fakat eksik açıklama (${Math.floor(explanation / 2)} puan); yok/yanlış: 0 puan. İki bileşen bağımsız puanlanır.`;
    }
    return `${label}: ${shares[i]} puan. Tam: ${descriptions[label] ?? 'doğru ve eksiksiz'}; kısmi: doğru fakat eksik (${Math.floor(shares[i] / 2)} puan); yok/yanlış: 0 puan.`;
  }).join('\n') + '\nEşdeğer gerekçeli yanıtlar kabul edilir. Sunum biçimi ayrıca puan kaybettirmez.';
}
