import type { Focus, Task } from './philosophy-early-units-2026.ts';
import { task, W } from './philosophy-grade11-units-2026.ts';

// FEL.11.4 — Edebiyat ve Felsefe. Özgün tek vaka (düşünür adı, eser adı ve alıntı yok).
// ÖĞRETMEN ONAYI: vaka metni Aytekin’in onayına sunuldu; onay gelene kadar bu satır “bekliyor” kalır.
// Üç ses: Gamze (edebî eser felsefe yapabilir, çünkü soruyu okura yaşatır; yükü: soruyu görünür kılmak ile gerekçeli cevap vermek arasındaki fark),
// Hakan (gerekçe açıkça gösterilmeyen yazı felsefe sayılmaz; yükü: “açık seçik gösterme” ölçütünün kendisi ve felsefi metinlerdeki benzetme/örnek kullanımı),
// İlkay (yazının felsefi olup olmadığını yazarın niyeti belirler; yükü: niyetin bilinememesi ve niyetin yeterli mi gerekli mi olduğu).
// İlkay’ın konumu bilerek tartışmalıdır: üçüncü görüş “ortası” olduğu için kolay seçilmesin (11.3 dersi).
// Programın iki problemi: edebî unsurlarla felsefe yapmanın imkânı (soru 1) ve edebî unsurlara felsefi bakışın imkânı (soru 2: mecaz, kurgu gibi unsurların felsefi metne katkısı).
// Kapsam dışı: belirli düşünürlerin görüşleri, belirli eser/yazar adları, edebî akım ve tür tarihi, sanatın tanımı ve güzellik tartışması (10.6’da ele alındı).
// 11.4.1 → felsefi soru ve problemler (a açıklar, b hayatla ilişkilendirerek değerlendirir); 11.4.2 → görüş ve argümanlar (a çözümler, b oluşturur, c metin yazar).
// 11.4.2 c: yazım görevinin ölçütü, programın 7 ölçütlü 100 puanlık Felsefi Metin Yazımı anahtarının 32/32/36 gruplamasıdır (bkz. 11.1).
const litPhil = 'Bir lisede edebiyat ve felsefe kulüpleri “Bir hikâye felsefe yapabilir mi?” başlıklı ortak bir söyleşi düzenliyor. Üç öğrenci tartışıyor. Gamze: “Bir hikâyede okur, kahramanla birlikte zor bir karar vermek zorunda kalır ve soruyu içeriden yaşar. Hikâye bir soruyu yalnız söylemez, gösterir; bu yüzden edebî eser felsefe yapabilir.” Hakan: “Felsefede her iddia gerekçesiyle açıkça gösterilmelidir. Hikâyede mecaz, kurgu ve duygu araya girer; okurun hangi sonuca vardığı yoruma kalır. Gerekçesi açık seçik gösterilemeyen bir yazı felsefe sayılmaz.” İlkay: “Bir yazının felsefi olup olmadığını, yazarın onu bir soruyu sorgulamak için yazıp yazmadığı belirler. Niyeti felsefi olan hikâye de felsefedir; niyeti bulunmayan yazı ise ne kadar derin görünürse görünsün felsefe sayılmaz.” Öğretmen, tartışmanın bir edebî eserin felsefe yapıp yapamayacağına ve mecaz, kurgu gibi edebî unsurların felsefi bir metne katkı sağlayıp sağlamadığına dayandığını belirtir.';

// ---------- FEL.11.4.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: bir edebî eser felsefe yapabilir mi; bu soru, hikâye gibi edebî bir türün yalnız bir soruyu görünür kılmakla mı kaldığını, yoksa felsefi bir düşünce ortaya koyup koyamadığını sorgular. İkinci soru: mecaz, kurgu gibi edebî unsurlar felsefi bir metne katkı sağlar mı; bu soru edebî unsurların felsefi bir metni zenginleştirip zenginleştirmediğini, yoksa gerekçeyi bulandırıp bulandırmadığını sorgular.',
    ['Eserin felsefe yapıp yapamayacağı sorusunun açıklanması (edebiyat-felsefe)', 'edebî bir eserin felsefe yapıp yapamayacağını sorguladığını belirtir'],
    ['Edebî unsurların katkısı sorusunun açıklanması (edebiyat-felsefe)', 'mecaz ve kurgu gibi unsurların felsefi metne katkı sağlayıp sağlamadığını sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması (edebiyat-felsefe)', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Gamze, Hakan ve İlkay’ın sözlerinin her birinin bir edebî eserin felsefe yapıp yapamayacağı sorusuna nasıl bir cevap verdiğini belirtiniz.',
    'Gamze yapabileceğini söyler; hikâyenin soruyu okura yaşattığını ve gösterdiğini düşünür. Hakan, felsefede gerekçenin açıkça gösterilmesi gerektiğini, hikâyede mecaz, kurgu ve duygunun sonucu yoruma bıraktığını söyler; gerekçesi açık gösterilemeyen yazıyı felsefe saymaz. İlkay ölçütü yazarın niyetine bağlar: soruyu sorgulamak için yazılmışsa hikâye de felsefedir, niyet yoksa yazı derin görünse bile felsefe değildir.',
    ['Gamze’nin cevabının belirlenmesi (edebiyat-felsefe)', 'Gamze’nin hikâyenin soruyu okura yaşatarak felsefe yapabileceğini söylediğini belirtir'],
    ['Hakan’ın cevabının belirlenmesi (edebiyat-felsefe)', 'Hakan’ın gerekçesi açık gösterilemeyen yazıyı felsefe saymadığını belirtir'],
    ['İlkay’ın cevabının belirlenmesi (edebiyat-felsefe)', 'İlkay’ın ölçütü yazarın niyetine bağladığını belirtir']),
  task('apply', 'Şu durumda öğretmenin belirttiği iki sorudan hangisinin ortaya çıktığını gerekçesiyle yazınız: Bir öğrenci, okuduğu öyküdeki kahramanın yaşadığı ikilemin ona “doğru olanla yararlı olan arasında nasıl seçim yapılır” sorusunu düşündürdüğünü söyler; arkadaşı “Bu öykü felsefe değil, yalnız bir hikâye” der.',
    'Birinci soru ortaya çıkar: edebî eser felsefe yapabilir mi. Öğrenci öykünün bir felsefi soruyu düşündürdüğünü, arkadaşı ise bunun felsefe sayılmayacağını söyler; ikisi eserin felsefe yapıp yapamayacağında ayrılır. İkinci soru (mecaz, kurgu gibi unsurların katkısı) bu durumda ancak öykünün anlatım biçiminin düşünceyi açıklayıp açıklamadığı sorulursa gündeme gelir.',
    ['Durumdaki sorunun belirlenmesi (edebiyat-felsefe)', 'durumda edebî eserin felsefe yapıp yapamayacağı sorusunun ortaya çıktığını belirtir'],
    ['Sorunun durumla ilişkilendirilmesi (edebiyat-felsefe)', 'öğrencinin öykünün soru düşündürdüğünü, arkadaşının ise öyküyü felsefe saymadığını ayırır'],
    ['Diğer sorunun ayrıca ele alınması (edebiyat-felsefe)', 'ikinci sorunun bu durumda neden öne çıkmadığını ya da ne zaman çıkacağını belirtir']),
  task('apply', '“Mecaz, kurgu gibi edebî unsurlar felsefi bir metne katkı sağlar mı?” sorusunu şu duruma uygulayınız: Bir öğrenci bir felsefi görüşü anlatmak için sınıfta kısa bir hikâye anlatır; arkadaşları görüşü hikâyeyle daha kolay anladıklarını söyler, ancak biri “Hikâyeyi dinledim ama görüşün gerekçesini hatırlamıyorum” der.',
    'Hikâye görüşü somutlaştırarak anlaşılmasını kolaylaştırır; bu, edebî unsurun katkı sağlayabileceğini gösterir. Gerekçeyi hatırlamayan arkadaşın sözü ise hikâyenin gerekçeyi görünür kılmayabileceğini, katkının yanında bir bulanıklık riski de olduğunu gösterir. Soru bu durumda şudur: edebî unsur gerekçeyi de aydınlatıyor mu, yoksa yalnız anlatıyı mı kolaylaştırıyor? Hakan bu noktaya dikkat çeker; Gamze ise hikâyenin soruyu yaşatmasına bakar.',
    ['Durumdaki katkının belirtilmesi (edebiyat-felsefe)', 'hikâyenin görüşün anlaşılmasını kolaylaştırdığını belirtir'],
    ['Durumdaki bulanıklık riskinin gösterilmesi (edebiyat-felsefe)', 'gerekçenin hatırlanmamasının hikâyenin gerekçeyi görünür kılmayabileceğini gösterdiğini belirtir'],
    ['Sorunun sonuca bağlanması (edebiyat-felsefe)', 'durumun edebî unsurların katkısı sorusunu nasıl gündeme getirdiğini belirtir']),
  task('analyze', 'Hakan “Gerekçesi açık seçik gösterilemeyen bir yazı felsefe sayılmaz” der. Bu sözün hangi varsayıma dayandığını ve hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Söz, felsefenin ölçütünün gerekçenin açık seçik gösterilmesi olduğunu varsayar. Bu varsayım, açık seçik gösterilmeyen ama okuru bir soruyu düşünmeye iten bir metnin felsefi bir iş görüp görmediği sorusunu ve gerekçenin yalnız açık gösterim yoluyla mı verilebileceği sorusunu görünmez kılar. Gamze’nin itirazı tam bu alana yöneliktir.',
    ['Hakan’ın varsayımının gösterilmesi (edebiyat-felsefe)', 'felsefenin ölçütünün gerekçenin açık seçik gösterilmesi olduğu varsayımını gösterir'],
    ['Görünmez kalan sorunun belirlenmesi (edebiyat-felsefe)', 'açık gösterilmeyen ama soru düşündüren metnin felsefi bir iş görüp görmediği sorusunun görünmez kaldığını belirtir'],
    ['Gamze’nin itirazıyla ilişkilendirilmesi (edebiyat-felsefe)', 'Gamze’nin itirazının bu soruya yöneldiğini gösterir']),
  task('analyze', 'Gamze “Hikâye bir soruyu yalnız söylemez, gösterir” der. “Göstermek”in iki farklı anlama gelebileceğini gösteriniz ve sözün hangi felsefi sorunu doğurduğunu çözümleyiniz.',
    '“Göstermek”, bir durumu okura yaşatıp soruyu görünür kılmak olabilir; ya da bir görüşü gerekçesiyle ortaya koymak olabilir. Birincisi için hikâye yeterli olabilir; ikincisi için hikâyenin gerekçeyi de taşıdığını göstermek gerekir. Doğan sorun: soruyu görünür kılmak ile soruya gerekçeli bir cevap vermek aynı şey midir.',
    ['İki anlamın ayrılması (edebiyat-felsefe)', 'soruyu yaşatmak ile görüşü gerekçesiyle ortaya koymayı ayırır'],
    ['Her anlam için hikâyenin yeterliliğinin ele alınması (edebiyat-felsefe)', 'her anlam için hikâyenin yeterli olup olmadığını ayrı ayrı belirtir'],
    ['Doğan sorunun belirtilmesi (edebiyat-felsefe)', 'soruyu görünür kılmak ile gerekçeli cevap vermenin aynı olup olmadığı sorununu gösterir']),
  task('evaluate', 'İlkay’ın “Bir yazının felsefi olup olmadığını, yazarın niyeti belirler” sözünün bir güçlü ve bir zayıf yanını değerlendiriniz.',
    'Güçlü yan: bir soruyu sorgulamak için yazmak ile yalnız eğlendirmek için yazmak arasındaki farkı gösterir ve felsefeyi yalnız biçime indirgemez. Zayıf yan: yazarın niyeti çoğu zaman bilinemez; niyet felsefi olsa bile gerekçesiz bir metnin felsefe sayılıp sayılmayacağı açıkta kalır; niyeti bilinmeyen bir metni okurun felsefi okuması da bu ölçütle açıklanamaz. Güçlü ve zayıf yanı İlkay’ın sözüne dayanarak gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (İlkay)', 'niyet ile eğlendirme arasındaki farkı gösterdiğini ya da felsefeyi biçime indirgemediğini belirtir'],
    ['Zayıf yanın belirtilmesi (İlkay)', 'niyetin bilinememesini ya da niyetin tek başına yeterli olmayabileceğini belirtir'],
    ['Değerlendirmenin sözle ilişkilendirilmesi (İlkay)', 'güçlü ve zayıf yanı İlkay’ın sözüne dayanarak gerekçelendirir']),
  task('evaluate', 'Metindeki sorunun “Bir hikâye felsefe yapabilir mi?” biçiminde sorulmasının neden felsefi bir soru olduğunu, olgusal bir soruyla karşılaştırarak değerlendiriniz.',
    'Soru felsefidir. “Bu kulüpte kaç öğrenci bir felsefi roman okudu?” gibi olgusal bir soru sayarak cevaplanır. “Bir hikâye felsefe yapabilir mi?” sorusu ise sayımla cevaplanmaz; “felsefe yapmak” ve “hikâye” kavramlarının ne anlama geldiğine ve neyin ölçüt sayılacağına bağlıdır. Her görüş başka bir ölçütten yola çıkar: açık gerekçe, soruyu yaşatma, yazarın niyeti.',
    ['Olgusal sorunun ayrılması (edebiyat-felsefe)', 'olgusal bir soruyu sayarak cevaplanan bir soru olarak gösterir'],
    ['Felsefi sorunun niteliğinin gösterilmesi (edebiyat-felsefe)', 'sorunun sayımla değil kavramlar ve ölçütler üzerinden cevaplandığını belirtir'],
    ['Karşılaştırmanın gerekçelendirilmesi (edebiyat-felsefe)', 'iki soru arasındaki farkı gerekçesiyle gösterir']),
  task('create', 'Metindekilerden farklı, edebiyat ile felsefe arasındaki ilişkiyle ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun (bir eserin felsefe yapıp yapamaması, edebî unsurların katkısı gibi) bulunduğunu belirtiniz.',
    'Örnek durum: Bir öğrenci felsefi bir fikri anlatmak için bir şiir yazar; öğretmeni “Şiirdeki mecaz fikri gizliyor” der. Felsefi sorun: edebî unsurun felsefi düşünceye katkı mı yoksa engel mi olduğu. Durumu ve sorunu tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün ve edebiyat-felsefe ilişkisiyle ilgili bir durumun yazılması (edebiyat-felsefe)', 'metindekilerden farklı, edebiyat ile felsefe ilişkisini içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi (edebiyat-felsefe)', 'durumda eserin felsefe yapıp yapamaması ya da edebî unsurların katkısı sorusunun nerede ortaya çıktığını belirtir'],
    ['Durum ile sorunun tutarlılığı (edebiyat-felsefe)', 'yazılan durum ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('create', 'Tartışmaya katılmayan dördüncü bir öğrenci için edebiyat ile felsefe ilişkisiyle ilgili yeni bir felsefi soru yazınız ve bu sorunun üç öğrenciden hangisinin görüşüyle en çok ilgili olduğunu belirtiniz.',
    'Örnek soru: Bir şiir, bir kavramı tanımlamadan o kavramı felsefi olarak düşündürebilir mi? Bu soru en çok Gamze’nin görüşüyle ilgilidir; çünkü şiirin soruyu gösterme biçimini sorgular. Yeni ve felsefi nitelikte olan, öğrenciyle ilişkisini gerekçelendiren her çalışma kabul edilir.',
    ['Yeni bir felsefi sorunun yazılması (edebiyat-felsefe)', 'metindeki iki sorudan farklı, edebiyat-felsefe ilişkisiyle ilgili bir felsefi soru yazar'],
    ['Sorunun bir öğrenciyle ilişkilendirilmesi (edebiyat-felsefe)', 'sorunun Gamze, Hakan ya da İlkay’dan birinin görüşüyle ilgisini belirtir'],
    ['İlişkinin gerekçelendirilmesi (edebiyat-felsefe)', 'seçtiği öğrenciyle ilişkiyi gerekçeyle gösterir']),
];

// ---------- FEL.11.4.1 b: hayatla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın gündelik yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: bir filmi izledikten sonra arkadaşların “Kahraman haklı mıydı?” diye tartışması. Bu, bir hikâyenin gündelik hayatta felsefi bir soruyu gündeme getirmesidir. Gündelik bir örnek verip tartışmayla ilişkisini gösteren her çalışma kabul edilir.',
    ['Gündelik örneğin verilmesi (edebiyat-felsefe)', 'gündelik yaşamdan bir örnek verir'],
    ['Örneğin tartışmaya bağlanması (edebiyat-felsefe)', 'örneğin eserin felsefe yapıp yapamayacağı ya da edebî unsurların katkısı tartışmasıyla ilişkisini belirtir'],
    ['Örneğin açık yazılması (edebiyat-felsefe)', 'örneği başkasının anlayabileceği açıklıkta yazar']),
  task('understand', 'Gamze, Hakan ve İlkay’ın görüşlerinden birinin günlük yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Gamze: okuduğu ya da izlediği hikâyelerden kendi kararları için soru çıkarmak, kahramanın yerine kendini koymak. Hakan: bir sözün gerekçesini her zaman sormak, süslü anlatımla kolay ikna olmamak. İlkay: bir yazıyı değerlendirirken söyleyenin ne amaçla söylediğini sormak. Seçilen görüşün tutumunu doğru bağlayan yanıt kabul edilir.',
    ['Bir görüşün seçilmesi ve belirtilmesi (edebiyat-felsefe)', 'üç görüşten birini doğru biçimde belirtir'],
    ['Günlük tutumun gösterilmesi (edebiyat-felsefe)', 'seçilen görüşün günlük yaşamdaki bir tutuma nasıl yol açabileceğini gösterir'],
    ['Tutumun görüşle ilişkilendirilmesi (edebiyat-felsefe)', 'tutum ile görüş arasındaki bağı açıklar']),
  task('apply', 'Kendi hayatınızdan (okul, aile, arkadaşlık) bir öykü, şarkı sözü, atasözü ya da film seçiniz ve metindeki iki görüşün bu esere nasıl yaklaşacağını yazınız.',
    'Örnek: bir atasözü. Gamze atasözünü, kısa bir hikâyenin bir yaşam sorusunu görünür kılması olarak okur. Hakan, atasözünün gerekçe göstermeden yalnız sonucu söylediğini belirtir. Seçilen eseri tanıtan ve iki görüşün yaklaşımını tutarlı gösteren her çalışma kabul edilir.',
    ['Eserin seçilmesi ve tanıtılması (edebiyat-felsefe)', 'kendi hayatından bir eser ya da durum seçer ve tanıtır'],
    ['Birinci görüşün yaklaşımının yazılması (edebiyat-felsefe)', 'metindeki bir görüşün eserle ilişkisini doğru yazar'],
    ['İkinci görüşün yaklaşımının yazılması (edebiyat-felsefe)', 'metindeki ikinci bir görüşün eserle ilişkisini doğru ve birinciden ayırarak yazar']),
  task('apply', '“Çocukken dinlediğimiz masallardan bir ders çıkarırız” örneğine metindeki üç görüşün nasıl yaklaşacağını yazınız.',
    'Gamze: masal bir soruyu yaşatır; ders, okura bırakılan bir sorudur ve masal bu yolla felsefe yapabilir. Hakan: masalın dersi gerekçeyle gösterilmediği için ders çıkarmak öğüt almaktır, felsefe değildir. İlkay: masalı anlatanın niyetine bağlıdır; yalnız öğüt vermek istiyorsa felsefe değildir, bir soruyu sorgulatmak istiyorsa felsefedir.',
    ['Gamze’nin yaklaşımının yazılması (edebiyat-felsefe)', 'Gamze’nin masalı soruyu yaşatan bir anlatı olarak ele alacağını belirtir'],
    ['Hakan’ın yaklaşımının yazılması (edebiyat-felsefe)', 'Hakan’ın masalın dersinin gerekçeyle gösterilmediğini vurgulayacağını belirtir'],
    ['İlkay’ın yaklaşımının yazılması (edebiyat-felsefe)', 'İlkay’ın masalı anlatanın niyetine bağlı değerlendireceğini belirtir']),
  task('analyze', 'Bir kitabı okuyup “Bu kitap beni düşündürdü” demek ile bir felsefe metnini okuyup “Bunu anladım” demek arasında, edebî eserin felsefeyle ilişkisi bakımından nasıl bir fark olduğunu çözümleyiniz.',
    'Bir kitabın düşündürmesi, bir soruyu görünür kılmasıdır. Bir felsefe metnini anladım demek ise iddiaları ve gerekçeleri izleyebilmektir. Fark şudur: birincisi soruyu başlatır, ikincisi gerekçelendirmeyi izler. İkisi birbirini dışlamaz; kitabın düşündürdüğü soru felsefi bir incelemeyi başlatabilir.',
    ['Düşündürmenin niteliğinin gösterilmesi (edebiyat-felsefe)', 'kitabın düşündürmesini bir soruyu görünür kılmak olarak gösterir'],
    ['Anlamanın niteliğinin gösterilmesi (edebiyat-felsefe)', 'felsefe metnini anlamayı iddia ve gerekçeleri izleyebilmek olarak gösterir'],
    ['İki durum arasındaki ilişkinin çözümlenmesi (edebiyat-felsefe)', 'ikisinin birbirini dışlamadığını ve soru ile gerekçelendirme arasındaki ilişkiyi gösterir']),
  task('analyze', 'Bir görüşü bir arkadaşınıza önce bir hikâyeyle, sonra gerekçeli bir paragrafla anlatmanız arasındaki ilişkiyi, edebî unsurların felsefi bir metne katkısı bakımından çözümleyiniz.',
    'Hikâye görüşü somutlaştırır, ilgi çeker ve akılda kalır; paragraf gerekçeleri açıkça sıralar. Hikâye gerekçeyi yoruma bırakabilir; paragraf somutluğu kaybedebilir. İkisi birbirini tamamlayabilir: hikâyeyle somutlaştırılan görüş paragrafla gerekçelendirilir.',
    ['Hikâyenin katkısının gösterilmesi (edebiyat-felsefe)', 'hikâyenin somutlaştırma ve akılda kalma gibi bir katkısını gösterir'],
    ['Paragrafın katkısının gösterilmesi (edebiyat-felsefe)', 'paragrafın gerekçeyi açıkça sıralamasını gösterir'],
    ['İkisi arasındaki ilişkinin çözümlenmesi (edebiyat-felsefe)', 'ikisinin sınırını ve birbirini nasıl tamamlayabileceğini gösterir']),
  task('evaluate', 'Hakan’ın gerekçe ölçütünün (“Gerekçesi açık seçik gösterilemeyen bir yazı felsefe sayılmaz”) günlük yaşamda okuduğumuz her yazıya uygulanıp uygulanamayacağını bir güçlü ve bir zayıf yanıyla değerlendiriniz.',
    'Güçlü yan: süslü ya da yanıltıcı anlatımla ikna olmayı önler; gerekçe sormayı alışkanlık hâline getirir. Zayıf yan: bir öykünün ya da şiirin düşündürdüğü soruyu dışarıda bırakır; ayrıca “açık seçik”in ne demek olduğunu söylemediği için ölçütün sınırı belirsizdir. Güçlü ve zayıf yanı gerekçelendiren her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (Hakan)', 'ölçütün ikna olmayı önlemesi ya da gerekçe sormayı alışkanlık yapması gibi bir yarar belirtir'],
    ['Zayıf yanın belirtilmesi (Hakan)', 'ölçütün soru düşündüren metni dışarıda bıraktığını ya da sınırının belirsizliğini belirtir'],
    ['Değerlendirmenin günlük yaşamla ilişkilendirilmesi (Hakan)', 'güçlü ve zayıf yanı günlük okuma örneğine dayandırarak gerekçelendirir']),
  task('evaluate', 'Gamze’nin “Hikâye soruyu yalnız söylemez, gösterir” görüşünün günlük yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: kahramanın yerine kendini koyarak başkalarının durumunu anlamaya ve kendi kararları üzerine düşünmeye yardım eder. Sakınca: hikâyenin yaşattığı duygu görüşün gerekçesinin yerine geçerse kişi gerekçeyi sormadan hikâyenin gösterdiği sonuca inanabilir. Yarar ve sakıncayı görüşe dayanarak gerekçelendiren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Gamze)', 'görüşün günlük yaşamda sağlayabileceği bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Gamze)', 'duygunun gerekçenin yerine geçme riski gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşle ilişkilendirilmesi (Gamze)', 'yarar ve sakıncayı Gamze’nin görüşüne dayanarak gerekçelendirir']),
  task('create', 'Üç görüşten biriyle ilgili, bir öğrencinin gündelik yaşamda karşılaşabileceği kısa bir karar durumu yazınız ve o görüşün bu duruma nasıl yaklaşacağını belirtiniz.',
    'Örnek durum: Bir öğrenci felsefe ödevini hikâye biçiminde yazmak ister; öğretmeni gerekçelerin açıkça yazılmasını bekler. Hakan’ın görüşü bu durumda ödevin gerekçeleri açıkça göstermesini gerektirir. Durumu ve yaklaşımı tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün bir karar durumunun yazılması (edebiyat-felsefe)', 'bir öğrencinin gündelik yaşamda karşılaşabileceği kısa bir karar durumu yazar'],
    ['Görüşün seçilmesi ve belirtilmesi (edebiyat-felsefe)', 'durumla ilgili bir görüşü belirtir'],
    ['Görüşün duruma uygulanması (edebiyat-felsefe)', 'seçilen görüşün duruma nasıl yaklaşacağını tutarlı biçimde yazar']),
  task('create', 'Edebiyat ile felsefenin günlük yaşamda birbirini nasıl tamamlayabileceğini ya da engelleyebileceğini gösteren kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Bu romanı okuyunca ne yapacağımı daha iyi düşündüm.” İkinci kişi: “Peki neden öyle düşündün, gerekçen ne?” Diyalog, romanın soruyu görünür kıldığını, gerekçelendirmenin ayrı bir iş olduğunu gösterir. Edebiyat ile felsefe arasındaki bir ilişkiyi tutarlı gösteren özgün her diyalog kabul edilir.',
    ['Diyalogun konuya uygunluğu (edebiyat-felsefe)', 'diyalogun edebiyat ile felsefe arasındaki ilişkiyi konu aldığı görülür'],
    ['Tamamlama ya da engellemenin gösterilmesi (edebiyat-felsefe)', 'birbirini tamamlama ya da engelleme ilişkisini diyalogda gösterir'],
    ['Diyalogun tutarlı kurulması (edebiyat-felsefe)', 'konuşmacıların sözlerini birbirine bağlı ve tutarlı kurar']),
];

// ---------- FEL.11.4.2 a: felsefi argümanları çözümler ----------
const a2: Task[] = [
  task('understand', 'Gamze’nin sözünde öncülleri ve sonucu ayırarak yazınız.',
    'Öncül: hikâyede okur, kahramanla birlikte zor bir karar vermek zorunda kalır ve soruyu içeriden yaşar. Öncül: hikâye bir soruyu yalnız söylemez, gösterir. Sonuç: edebî eser felsefe yapabilir.',
    ['Birinci öncülün belirlenmesi (Gamze)', 'okurun soruyu içeriden yaşadığı öncülünü belirtir'],
    ['İkinci öncülün belirlenmesi (Gamze)', 'hikâyenin soruyu gösterdiği öncülünü belirtir'],
    ['Sonucun belirlenmesi (Gamze)', 'sonucu edebî eserin felsefe yapabileceği olarak belirtir']),
  task('understand', 'İlkay’ın sözünde ileri sürdüğü iddiayı ve onu destekleyen gerekçeyi ayırarak yazınız.',
    'İddia: bir yazının felsefi olup olmadığını yazarın niyeti belirler. Gerekçe: niyeti bir soruyu sorgulamak olan hikâye de felsefedir; niyeti bulunmayan yazı ise ne kadar derin görünürse görünsün felsefe sayılmaz.',
    ['İddianın belirlenmesi (İlkay)', 'yazının felsefi olup olmadığını yazarın niyetinin belirlediğini belirtir'],
    ['Gerekçenin belirlenmesi (İlkay)', 'niyeti felsefi olan hikâyenin felsefe, niyeti olmayan yazının felsefe olmadığı gerekçesini belirtir'],
    ['İddia ile gerekçenin ayrılması (İlkay)', 'iddia ile gerekçeyi karıştırmadan ayrı ayrı yazar']),
  task('apply', 'Paragraf: “Bir hikâyenin felsefe yapıp yapmadığı sorusu tartışmalıdır. Hakan’a göre ……… . Bu nedenle ………” Boş bırakılan yerleri Hakan’ın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: felsefede her iddia gerekçesiyle açıkça gösterilmelidir; hikâyede mecaz, kurgu ve duygu sonucu yoruma bırakır. Boşluk 2: gerekçesi açık seçik gösterilemeyen hikâye felsefe sayılmaz. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Hakan)', 'Hakan’ın görüşünü doğru biçimde (gerekçenin açık gösterilmesi, sonucun yoruma kalması) tamamlar'],
    ['İkinci boşluğun tamamlanması (Hakan)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Hakan)', 'tamamlanan cümleler ilk cümleyle tutarlı bir bütün oluşturur']),
  task('apply', 'Gamze’nin görüşünü “iddia – gerekçe – sonuç” sırasıyla üç cümlelik bir akıl yürütme hâline getiriniz.',
    'Örnek: İddia: edebî bir eser felsefi bir soruyu okura yaşatabilir. Gerekçe: okur kahramanla birlikte zor bir karar verirken soruyu içeriden yaşar. Sonuç: bu nedenle edebî eser felsefe yapabilir. Üç öğeyi sırayla ve doğru kuran her akıl yürütme kabul edilir.',
    ['İddianın yazılması (Gamze)', 'görüşün iddiasını açıkça yazar'],
    ['Gerekçenin yazılması (Gamze)', 'iddiayı destekleyen gerekçeyi yazar'],
    ['Sonucun gerekçeden çıkarılması (Gamze)', 'sonucu iddia ve gerekçeyle tutarlı biçimde yazar']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Gamze haklıdır; çünkü herkes iyi bir romanın insanı düşündürdüğünü söylüyor.” Bu argümandaki temellendirme sorununu belirtiniz.',
    'Gerekçe çoğunluğa (herkes söylüyor) dayanır; çoğunluğun söylemesi bir görüşü doğru yapmaz. Ayrıca bir romanın düşündürmesi ile felsefe yapması aynı şey değildir: düşündürmek ile bir iddiayı gerekçelendirmek arasında boşluk vardır. Gamze’nin kendi gerekçesi (soruyu yaşatma) ise bu argümanla desteklenmemektedir.',
    ['Çoğunluğa başvurunun gösterilmesi (edebiyat-felsefe)', 'gerekçenin çoğunluğa dayandığını ve bunun görüşü doğru yapmadığını belirtir'],
    ['Düşündürme ile felsefe yapma arasındaki boşluğun gösterilmesi (edebiyat-felsefe)', 'romanın düşündürmesinin felsefe yapmasıyla aynı olmadığını belirtir'],
    ['Gamze’nin gerekçesinin ayrıca gösterilmesi (edebiyat-felsefe)', 'Gamze’nin asıl gerekçesinin bu argümanda yer almadığını belirtir']),
  task('analyze', 'Hakan’ın argümanındaki örtük bir öncülü belirleyiniz ve bu öncüle yöneltilebilecek bir itirazı yazınız.',
    'Örtük öncül: mecaz, kurgu ve duygu gerekçeyi her zaman yoruma bırakır; ya da felsefi gerekçe mecaz ve kurgudan arındırılarak verilebilir. İtiraz: felsefi metinlerde de benzetme ve örnek kullanılır ve bunlar gerekçeyi anlaşılır kılabilir; edebî unsur gerekçeyi her zaman bulandırmaz. Öncülü doğru belirleyen ve gerçek bir itiraz yazan eşdeğer yanıtlar kabul edilir.',
    ['Örtük öncülün belirlenmesi (Hakan)', 'edebî unsurların gerekçeyi her zaman yoruma bıraktığı ya da gerekçenin bunlardan arındırılabileceği öncülünü belirtir'],
    ['İtirazın yazılması (Hakan)', 'öncüle yönelen gerçek bir itiraz yazar'],
    ['İtirazın öncülle ilişkilendirilmesi (Hakan)', 'itirazın hangi öncülü zayıflattığını gösterir']),
  task('evaluate', 'Gamze, Hakan ve İlkay’ın argümanlarından hangisinin gerekçe yükünün en ağır olduğunu değerlendiriniz; seçiminizi gerekçelendiriniz.',
    'Tek doğru seçim yoktur; her görüşün bir yükü vardır. Gamze: soruyu görünür kılmak ile gerekçeli cevap vermek arasındaki farkı kapatmak zorundadır. Hakan: “açık seçik gösterme” ölçütünü kendisi gerekçelendirmeli ve felsefi metinlerdeki benzetme ve örnek kullanımını açıklamalıdır. İlkay: niyetin nasıl bilineceğini ve niyetin tek başına yeterli olup olmadığını göstermelidir. Seçimini bu yüklerden biriyle gerekçelendiren her yanıt kabul edilir.',
    ['Seçilen görüşün belirtilmesi (edebiyat-felsefe)', 'üç görüşten birini gerekçe yükü en ağır olan olarak seçer'],
    ['Gerekçe yükünün gösterilmesi (edebiyat-felsefe)', 'seçilen görüşün neyi göstermek zorunda olduğunu belirtir'],
    ['Seçimin diğer görüşlerle karşılaştırılması (edebiyat-felsefe)', 'diğer iki görüşün yüküyle karşılaştırarak seçimini gerekçelendirir']),
  task('evaluate', 'İlkay’ın “Niyeti bulunmayan yazı ne kadar derin görünürse görünsün felsefe sayılmaz” sonucunun öncüllerinden çıkıp çıkmadığını değerlendiriniz.',
    'Sonuç öncüllerden tam çıkmaz. Öncül, felsefi niyetin yazıyı felsefi yaptığını söyler (niyet yeterlidir); sonuç ise niyet yoksa yazının felsefe olamayacağını söyler (niyet gereklidir). Yeterli koşuldan gerekli koşula geçiş ayrıca gerekçelendirilmemiştir. Ayrıca yazarının niyetini bilmediğimiz bir metin bu ölçütle değerlendirilemez. Sonuç gerekçelendirilmeden kurulmuştur; bu, görüşün yanlış olduğunu göstermez.',
    ['Öncül ve sonucun ayrılması (İlkay)', 'niyetin yeterli koşul olarak öncülde, gerekli koşul olarak sonuçta geçtiğini gösterir'],
    ['Geçişin gerekçelendirilmediğinin gösterilmesi (İlkay)', 'yeterli koşuldan gerekli koşula geçişin gerekçelendirilmediğini belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (İlkay)', 'sonucun çıkmamasının görüşün yanlışlığını göstermediğini belirtir']),
  task('create', 'Gamze’nin argümanını güçlendirecek bir ek öncül yazınız ve bu öncülün hangi itiraza karşı işe yaradığını belirtiniz.',
    'Örnek ek öncül: soruyu içeriden yaşayan okur, soruyla ilgili seçenekleri ve gerekçeleri ayırt etmeye başlar. Bu öncül, Hakan’ın “hikâyede okurun varacağı sonuç yoruma kalır” itirazına karşı işe yarar; çünkü yaşantının gerekçeleri ayırt etmeyi sağladığını söyler. Gamze’nin argümanını gerçekten güçlendiren ve itirazla ilişkilendirilen eşdeğer öncüller kabul edilir.',
    ['Ek öncülün yazılması (Gamze)', 'Gamze’nin argümanına eklenebilecek bir öncül yazar'],
    ['Öncülün argümanı güçlendirmesi (Gamze)', 'öncülün argümanı nasıl güçlendirdiğini gösterir'],
    ['Karşı çıkılan itirazın belirtilmesi (Gamze)', 'öncülün hangi itiraza karşı işe yaradığını belirtir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan, edebiyat ile felsefe konulu kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Bu roman bir felsefi soruyu gösteriyor, çünkü kahraman zor bir seçim yapıyor.” İkinci kişi: “Soruyu göstermek, ona cevap vermek değil.” Birinci kişi: “Doğru, ama gösterilen soru bir cevap aramaya zorluyor; gerekçeli cevap bunun ardından gelir.” Gerekçeyi, itirazı ve yanıtı tutarlı kuran özgün her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması (edebiyat-felsefe)', 'diyalogda edebiyat ile felsefe ilişkisiyle ilgili bir gerekçe verir'],
    ['İtirazın diyalogda yer alması (edebiyat-felsefe)', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması (edebiyat-felsefe)', 'itiraza gerekçeli bir yanıt verir']),
];

// ---------- FEL.11.4.2 b: görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini edebiyat ile felsefe tartışmasından bir örnekle açıklayınız.',
    'Bir görüşün argümana dönüşmesi için öncüllerin (gerekçelerin) ve onlardan çıkan bir sonucun açıkça yazılması gerekir. Örnek: görüş “hikâye felsefe yapabilir”; öncül: hikâye soruyu okura yaşatır; sonuç: hikâye felsefe yapabilir. Öncül ve sonuç ilişkisini örnekle gösteren her açıklama kabul edilir.',
    ['Gerekenlerin belirtilmesi (edebiyat-felsefe)', 'görüşü argümana dönüştürmek için öncül ve sonuç gerektiğini belirtir'],
    ['Örneğin verilmesi (edebiyat-felsefe)', 'edebiyat-felsefe tartışmasından bir örnek verir'],
    ['Örnekle açıklamanın ilişkilendirilmesi (edebiyat-felsefe)', 'örnekte öncül ve sonuç ilişkisini gösterir']),
  task('understand', 'Edebiyat ile felsefe ilişkisi konusunda kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: “Edebî eser, soruyu görünür kılarak felsefenin başlangıcını oluşturabilir.” Bu görüş, edebî eserin felsefe yapıp yapamayacağı sorusuna cevaptır. Görüşü açık yazan ve soruyla doğru ilişkilendiren her çalışma kabul edilir.',
    ['Görüşün yazılması (edebiyat-felsefe)', 'edebiyat ile felsefe ilişkisiyle ilgili bir görüşü bir cümleyle yazar'],
    ['Felsefi sorunun belirtilmesi (edebiyat-felsefe)', 'görüşün hangi felsefi soruya cevap olduğunu belirtir'],
    ['Görüş ile sorunun uyumu (edebiyat-felsefe)', 'yazılan görüş ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('apply', 'Edebiyat ile felsefe ilişkisi konusunda bir görüş seçiniz ve bu görüşü bir ilke, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: Görüş: edebî unsurlar felsefi bir metne katkı sağlar. İlke: bir düşünceyi somutlaştıran unsur, düşüncenin anlaşılmasına katkı sağlar. Durum: felsefi bir görüşü anlatan kısa bir hikâye, görüşü sınıfta kolay anlaşılır kılmıştır. Sonuç: hikâye edebî bir unsur olarak felsefi görüşe katkı sağlamıştır. İlke, durum ve sonucu tutarlı kuran her argüman kabul edilir.',
    ['İlkenin yazılması (edebiyat-felsefe)', 'seçtiği görüşe uygun bir ilke yazar'],
    ['Durum bilgisinin yazılması (edebiyat-felsefe)', 'ilkenin uygulandığı somut bir durum bilgisi yazar'],
    ['Sonucun ilkeyle tutarlı çıkarılması (edebiyat-felsefe)', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('apply', '“Edebî unsurlar gerekçeyi bulandırır” ilkesinden yola çıkarak, bir öğrencinin felsefe ödevini hikâye biçiminde yazması durumu için bir argüman kurunuz.',
    'Örnek: İlke: edebî unsurlar gerekçeyi bulandırır. Durum: öğrenci ödevini hikâye biçiminde yazmıştır ve gerekçeler olayların arasında dağılmıştır. Sonuç: ödevde gerekçeler açıkça görülemeyeceği için ödevin felsefi gerekçelendirme bakımından zayıf kalma riski vardır. İlkeyi duruma uygulayan ve sonucu tutarlı çıkaran her argüman kabul edilir.',
    ['İlkenin duruma uygulanması (edebiyat-felsefe)', 'verilen ilkeyi öğrencinin ödev durumuna uygular'],
    ['Durum bilgisinin kullanılması (edebiyat-felsefe)', 'durumdan somut bir bilgi kullanır'],
    ['Sonucun tutarlı çıkarılması (edebiyat-felsefe)', 'sonucu ilkeden ve durumdan tutarlı biçimde çıkarır']),
  task('analyze', 'Edebiyat ile felsefe ilişkisi konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümanın dayandığı varsayımı ve bu varsayıma yöneltilebilecek güçlü bir itirazı çözümleyiniz; itirazın neden güçlü olduğunu açıklayınız.',
    'Örnek: Öncül: hikâye okura soruyu içeriden yaşatır. Öncül: soruyu içeriden yaşamak, soru üzerine düşünmeyi başlatır. Sonuç: edebî eser felsefi düşünmeyi başlatabilir. Varsayım: düşünmeyi başlatmak felsefe yapmanın bir parçasıdır. İtiraz: düşünmeyi başlatan her şey felsefe yapmış sayılırsa ölçüt çok geniş olur; örneğin bir kaza da düşündürebilir. İtiraz güçlüdür, çünkü varsayımın kapsamını sorgular. Kendi argümanını öncül ve sonuçla kuran, varsayımını belirleyen ve itirazın gücünü gerekçelendiren eşdeğer yanıtlar kabul edilir.',
    ['Argümanın kurulması ve varsayımın belirlenmesi (edebiyat-felsefe)', 'edebiyat ile felsefe ilişkisi konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve dayandığı varsayımı gösterir'],
    ['Güçlü bir itirazın belirlenmesi (edebiyat-felsefe)', 'varsayıma yöneltilebilecek güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi (edebiyat-felsefe)', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Şiir duygudur; bu yüzden şiir felsefi bir düşünce taşıyamaz.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: duygu anlatan bir yazı düşünce ya da gerekçe taşıyamaz. Gamze itiraz eder: şiir ya da hikâye, duyguyla birlikte bir soruyu görünür kılabilir. İlkay da itiraz edebilir: niyeti felsefi olan bir yazıda duygunun bulunması bunu engellemez. Hakan ise öncülü bu biçimiyle kabul etmeyebilir: ona göre sorun duygunun varlığı değil, gerekçenin açık gösterilememesidir.',
    ['Gizli öncülün belirlenmesi (edebiyat-felsefe)', 'duygu anlatan yazının düşünce taşıyamayacağı öncülünü gösterir'],
    ['Gamze ve İlkay’ın itirazının gösterilmesi (edebiyat-felsefe)', 'soruyu görünür kılma ve niyet itirazlarını doğru ilişkilendirir'],
    ['Hakan’ın konumunun ayrıca gösterilmesi (edebiyat-felsefe)', 'Hakan’ın öncülü bu biçimiyle kabul etmeyebileceğini ve ölçütünün gerekçenin açık gösterilmesi olduğunu belirtir']),
  task('evaluate', 'Edebiyat ile felsefe ilişkisi konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümana yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını gösteriniz. İtiraza gerekçeli bir yanıt veriniz ve bu yanıtın itirazı karşılayıp karşılamadığını değerlendiriniz.',
    'Örnek: Öncül: edebî unsurlar bir düşünceyi somutlaştırır. Öncül: somutlaştırılan düşünce daha kolay anlaşılır. Sonuç: edebî unsurlar felsefi bir metne katkı sağlar. İtiraz: anlaşılırlık, düşüncenin doğru ya da gerekçeli olduğunu göstermez; katkı yalnız anlaşılırlıkla sınırlı kalabilir. Zayıflayan öncül: kolay anlaşılmanın felsefi katkı sayılabileceği. Yanıt: anlaşılırlık gerekçelerin izlenebilmesinin ön koşuludur. Değerlendirme: yanıt itirazı kısmen karşılar; ancak anlaşılırlığın gerekçelendirmeye nasıl dönüştüğünü göstermek gerekir. Öğrencinin kendi argümanını açıkça kurduğu, itirazı bir öncülle ilişkilendirdiği ve gerekçeli yanıtının yeterliliğini değerlendirdiği eşdeğer çalışmalar kabul edilir.',
    ['Argümanın kurulması ve itirazın belirlenmesi (edebiyat-felsefe)', 'edebiyat ile felsefe ilişkisi konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve bu argümana yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi (edebiyat-felsefe)', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['İtiraza yanıt verilmesi ve yanıtın değerlendirilmesi (edebiyat-felsefe)', 'itiraza gerekçeli bir yanıt verir ve bu yanıtın itirazı karşılayıp karşılamadığını gerekçeyle değerlendirir']),
  task('evaluate', '“Hikâyeler yalnız eğlendirmek içindir” gerekçesinin edebiyat ile felsefe tartışmasında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: hikâyelerin tek amacının eğlendirmek olduğunu önceden kabul eder; oysa tartışılan soru tam olarak hikâyenin başka bir iş görüp göremeyeceğidir, yani sonuç öncülde varsayılmıştır. Ayrıca bazı yazarların eğlendirmenin dışında amaçlarla yazdığı da bilinir. Ancak hikâyelerin çoğunun eğlendirmek için yazılmış olması doğru olabilir; bu, hiçbirinin felsefe yapamayacağını göstermez. Gerekçenin yetersizliği görüşün yanlışlığını göstermez.',
    ['Gerekçenin yetersizliğinin gösterilmesi (edebiyat-felsefe)', 'gerekçenin sonucu öncülde varsaydığını ya da yetersiz kaldığını gösterir'],
    ['Karşı bilginin belirtilmesi (edebiyat-felsefe)', 'bazı eserlerin eğlendirmenin dışında amaçlarla yazılabildiğini belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (edebiyat-felsefe)', 'gerekçenin yetersizliğinin görüşün yanlış olduğunu göstermediğini belirtir']),
  task('create', 'Üç görüşten farklı dördüncü bir görüş ortaya koyunuz ve bu görüşü bir gerekçeyle destekleyiniz.',
    'Örnek: Edebî eser felsefe yapmaz, ama felsefi bir incelemenin malzemesini sağlar; çünkü eser soruyu görünür kılar, gerekçelendirme ise okurun ya da yorumcunun işidir. Üç görüşten farklı olan, tutarlı ve gerekçeli her görüş kabul edilir.',
    ['Dördüncü görüşün ortaya konması (edebiyat-felsefe)', 'metindeki üç görüşten farklı bir görüş ortaya koyar'],
    ['Görüşün gerekçelendirilmesi (edebiyat-felsefe)', 'görüşü bir gerekçeyle destekler'],
    ['Görüş ile gerekçenin tutarlılığı (edebiyat-felsefe)', 'görüş ile gerekçenin birbirine uyduğunu gösterir']),
  task('create', 'Gamze, Hakan ve İlkay’ın görüşlerinden birden fazlasından bir şey koruyan birleştirici bir öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğinizi belirtiniz.',
    'Örnek: Edebî eser soruyu yaşatarak felsefenin başlangıcını sağlar (Gamze); ancak bir yazının felsefe sayılması için gerekçelerin açıkça gösterilmesi gerekir (Hakan). Çözülmeyen: gerekçenin hikâyenin içinde verilip verilemeyeceği, yani hikâyenin hem soruyu yaşatıp hem gerekçeyi taşıyıp taşıyamayacağı. Hangi görüşten neyi koruduğunu ve neyi çözemediğini belirten tutarlı her öneri kabul edilir.',
    ['Birleştirici önerinin oluşturulması (edebiyat-felsefe)', 'en az iki görüşten bir şey koruyan tutarlı bir öneri yazar'],
    ['Korunan öğelerin belirtilmesi (edebiyat-felsefe)', 'hangi görüşten neyi koruduğunu belirtir'],
    ['Çözülemeyenin belirtilmesi (edebiyat-felsefe)', 'önerinin çözemediği bir noktayı açıkça belirtir']),
];

// ---------- FEL.11.4.2 c: felsefi metin yazar ----------
const sampleParagraph = '“Edebiyat ile felsefe ilişkisindeki temel problem, bir edebî eserin felsefe yapıp yapamayacağıdır. Eseri yalnız bir hikâye sayan görüş, felsefenin gerekçeyi açıkça göstermesi gerektiğini söyler. Oysa bir hikâye, okuru kahramanla birlikte zor bir karar vermeye zorlayarak bir soruyu yaşanır kılar. Bu nedenle felsefenin tek biçimi açık gerekçe göstermek değildir; edebî eser de felsefe yapabilir.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: bir edebî eserin felsefe yapıp yapamayacağı. Kavram: edebî eser (ayrıca felsefe, gerekçe). Gerekçe: hikâye, okuru kahramanla birlikte zor bir karar vermeye zorlayarak soruyu yaşanır kılar.',
    ['Problemin belirlenmesi (edebiyat paragrafı)', 'paragrafın problemini edebî eserin felsefe yapıp yapamayacağı olarak belirtir'],
    ['Kavramın belirlenmesi (edebiyat paragrafı)', 'paragraftaki felsefi kavramlardan birini (edebî eser, felsefe, gerekçe) belirtir'],
    ['Gerekçenin belirlenmesi (edebiyat paragrafı)', 'hikâyenin soruyu yaşanır kıldığı gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: felsefenin tek biçimi açık gerekçe göstermek değildir; edebî eser de felsefe yapabilir. Sonucu taşıyan cümle paragrafın son cümlesidir (“Bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi (edebiyat paragrafı)', 'görüşü edebî eserin de felsefe yapabileceği biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi (edebiyat paragrafı)', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması (edebiyat paragrafı)', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “Edebiyat ile felsefe ilişkisindeki temel problem, bir yazının neye göre felsefi sayılacağıdır. İlkay’a göre ……… . Bu nedenle ………” Boş bırakılan yerleri İlkay’ın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: bir yazının felsefi olup olmadığını yazarın onu bir soruyu sorgulamak için yazıp yazmadığı, yani niyeti belirler. Boşluk 2: niyeti felsefi olan hikâye de felsefedir; niyeti bulunmayan yazı derin görünse bile felsefe sayılmaz. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (İlkay)', 'İlkay’ın görüşünü doğru biçimde (yazarın niyeti ölçüttür) tamamlar'],
    ['İkinci boşluğun tamamlanması (İlkay)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (İlkay)', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Hakan’ın görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: Edebiyat ile felsefe ilişkisindeki temel problem, edebî unsurların felsefi bir metne katkı sağlayıp sağlamadığıdır. Hakan’ın görüşünde “gerekçe”, felsefede açıkça gösterilmesi gereken öğedir. Mecaz ve kurgu gerekçeyi yoruma bıraktığından, gerekçesi açık gösterilemeyen yazı felsefe sayılmaz. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması (Hakan)', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması (Hakan)', 'gerekçe ya da edebî unsur kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması (Hakan)', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “Hikâyeler çok güzeldir, herkes hikâye okumayı sever. Bu yüzden hikâyeler felsefe yapar.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (edebî eserin felsefe yapıp yapamayacağı) belirsizdir. Kavram: felsefe, felsefe yapmak ve gerekçe gibi kavramlar ele alınmamış, “güzel” kavramı belirsiz bırakılmıştır. Temellendirme: “herkes hikâye okumayı sever” gerekçesi, hikâyelerin felsefe yaptığını göstermez; beğeniye ve çoğunluğa başvurmaktır.',
    ['Problemin eksikliğinin gösterilmesi (edebiyat paragrafı)', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi (edebiyat paragrafı)', 'felsefe, felsefe yapmak ve gerekçe gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi (edebiyat paragrafı)', '“herkes sever” gerekçesinin sonucu desteklemediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Felsefe gerekçe ister. Bu yüzden edebiyat felsefeyle ilgisiz kalmalıdır.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: felsefe gerekçe ister. Sonuç: edebiyat felsefeyle ilgisiz kalmalıdır. Sonuç öncülden çıkmaz: felsefenin gerekçe istemesi, edebiyatın gerekçe taşıyamayacağını ya da felsefeyle ilişki kuramayacağını göstermez. Aradaki boşluğu dolduran bir gerekçe (edebiyatın gerekçe sunmaktan temelde yoksun olduğu) gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması (edebiyat paragrafı)', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi (edebiyat paragrafı)', 'felsefenin gerekçe istemesinin edebiyatın felsefeyle ilgisiz kalmasını gerektirmediğini belirtir'],
    ['Eksik gerekçenin belirtilmesi (edebiyat paragrafı)', 'edebiyatın gerekçe sunamayacağı gerekçesinin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence şiirler çok anlamlı. Çünkü insanı duygulandırıyor. Herkes şiir okumalı.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (edebî eserin felsefe yapıp yapamayacağı), kavramlar yerinde (edebî eser, felsefe, gerekçe), argüman ve gerekçe açık (hikâye soruyu yaşanır kılar), bütünlük var. Paragraf 2’de problem tanımlanmamış, “anlamlı” belirsiz, gerekçe (duygulandırması) sonucu (herkes şiir okumalı) desteklemiyor, felsefi terim yok. Paragraf 1’in sınırı: soruyu yaşanır kılmanın gerekçelendirme yerine geçip geçemeyeceğini göstermemesi.',
    ['Problem ve kavram ölçütlerine göre değerlendirme (edebiyat paragrafları)', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme (edebiyat paragrafları)', 'iki paragrafın gerekçelerini karşılaştırır ve ikincisinin gerekçesinin sonucu desteklemediğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme (edebiyat paragrafları)', 'iki paragrafı felsefi terim ve metin bütünlüğü bakımından karşılaştırır']),
  task('evaluate', 'Paragraf: “Edebiyat ile felsefe ilişkisindeki problem, edebî unsurların felsefeye katkı sağlayıp sağlamadığıdır. Hakan’a göre mecaz gerekçeyi bulandırır. Bu yüzden felsefede mecaz kullanılmamalıdır.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki farklı öneri yazınız.',
    'Temellendirme zayıftır: mecazın gerekçeyi bulandırabilmesi, her mecazın bulandırdığını ya da hiç kullanılmaması gerektiğini göstermez; sonuç öncülden çıkmaz. Hakan da ölçütünü mecazın varlığına değil, gerekçenin açık gösterilmesine bağlar. Öneri 1: sonucu “mecaz gerekçeyi bulandırmayacak biçimde kullanılmalıdır” olarak değiştirmek. Öneri 2: Hakan’ın gerekçesini (okurun vardığı sonuç yoruma kalır) açıkça yazıp sonucu ona bağlamak. Metni gerçekten geliştiren iki farklı öneri kabul edilir.',
    ['Temellendirmenin değerlendirilmesi (Hakan paragrafı)', 'gerekçenin sonucu desteklemediğini gösterir'],
    ['İlk önerinin yazılması (Hakan paragrafı)', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması (Hakan paragrafı)', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Bir edebî eserin felsefe yapıp yapamayacağını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (edebî eser, felsefe, gerekçe) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (bir edebî eserin felsefe yapıp yapamayacağı); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: edebî eser felsefe yapabilir mi? Görüş: yapabilir, çünkü okuru soruyu içeriden yaşamaya zorlar. Karşı görüş (Hakan): gerekçe açıkça gösterilmedikçe felsefe değildir. Yanıt: gösterilen soru gerekçe aramaya zorlar; gerekçeli cevap eserin ardından gelen felsefi incelemede verilir, ama eser bu incelemeyi başlatır. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
  task('create', 'Mecaz, kurgu gibi edebî unsurların felsefi bir metne katkı sağlayıp sağlamadığını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (edebî unsur, gerekçe, mecaz) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (edebî unsurların felsefi metne katkı sağlayıp sağlamadığı); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: mecaz felsefi bir metne katkı sağlar mı? Görüş: sağlar, çünkü soyut bir düşünceyi somutlaştırarak anlaşılır kılar. Karşı görüş: mecaz gerekçeyi bulandırır. Yanıt: bulandırma mecazın kendisinden değil, gerekçenin ayrıca verilmemesinden doğar; mecaz gerekçeyle birlikte kullanıldığında anlaşılırlığı artırır. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
];

export const grade11Unit4: Record<string, Focus[]> = {
  'FEL.11.4.1': [
    { context: litPhil, focus: 'edebiyat felsefe ilişkisiyle ilgili felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma bir edebî eserin felsefe yapıp yapamayacağı sorusuna dayanır.', 'Tartışma edebî unsurların felsefi bir metne katkı sağlayıp sağlamadığı sorusuna dayanır.'], inference: 'Kulüp söyleşisi edebiyat-felsefe ilişkisinin eserin felsefe yapması ve edebî unsurların katkısı sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Bir öyküdeki ikilemin felsefi bir soru düşündürmesi.', tasks: a1 },
    { context: litPhil, focus: 'edebiyat felsefe ilişkisiyle ilgili felsefi soru ve problemlerin hayatla ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki görüşler günlük okuma ve izleme alışkanlıklarında da kullanılır.', 'Günlük örnekler soruyu yaşatma ile gerekçeyi açıkça gösterme arasında bir gerilim içerir.'], inference: 'Edebiyat-felsefe ilişkisine dair felsefi sorular günlük yaşamdaki okuma ve değerlendirme alışkanlıklarıyla ilişkilendirilerek değerlendirilebilir.', limit: 'Günlük örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Bir filmi izledikten sonra kahramanın haklı olup olmadığını tartışmak.', tasks: b1 },
  ],
  'FEL.11.4.2': [
    { context: litPhil, focus: 'edebiyat felsefe ilişkisiyle ilgili felsefi argümanların çözümlenmesi', evidence: ['Üç görüşün her birinin öncülü ve sonucu vardır.', 'Her görüşün gerekçe yükü vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Romanın düşündürmesinden felsefe yaptığı sonucuna geçiş.', tasks: a2 },
    { context: litPhil, focus: 'edebiyat felsefe ilişkisiyle ilgili görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir varsayıma dayanır ve itirazlara açıktır.'], inference: 'Öğrenci edebiyat ile felsefe ilişkisi için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Edebî unsurların felsefi metne katkısı üzerine bir argüman.', tasks: b2 },
    { context: litPhil, focus: 'edebiyat felsefe ilişkisiyle ilgili felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'Bir hikâyenin felsefe yapıp yapamayacağı tartışması.', tasks: c2 },
  ],
};
