import type { Focus, Task } from './philosophy-early-units-2026.ts';
import { task, W } from './philosophy-grade11-units-2026.ts';

// FEL.11.6 — Hukuk ve Felsefe. Özgün tek vaka (düşünür adı, gerçek yasa maddesi, gerçek dava ve alıntı yok).
// ÖĞRETMEN ONAYI: vaka metni Aytekin tarafından onaylandı.
// Vaka okul kuralı düzeyindedir (derste telefon kuralı); ağır suç, şiddet ve güncel siyasi dava senaryosu içermez.
// Programın iki problemi: hukukun kaynağı (soru 1: yazılı kural mı, insanın doğuştan hakları mı) ve ahlak-hukuk ilişkisi (soru 2: hakkaniyet ve vicdan kuralın önüne geçebilir mi).
// Hukukun gereği ve önemi problemi, toplumsal hayat görevlerinde (b1) “kuralsız düzen” ve “kural özgürlüğü sınırlar mı güvenceye mi alır” soruları olarak işlenir.
// Üç ses: Nehir (hukuk, yetkili merciin koyup duyurduğu kurallardır; adil olup olmadığı ayrı sorudur; yükü: adaletsiz kuralın da hukuk sayılması ve uyulma yükümlülüğünün temeli),
// Oğuz (insanın doğuştan hakları vardır, aykırı kural geçerli sayılmamalı; yükü: bu hakların neler olduğunu kimin belirleyeceği ve geçerlilik ile hakkın varlığı ayrımı),
// Pelin (kural herkese aynı uygulanmalı ama hakkaniyet gözetilmeli, açık haksızlıkta vicdan kuralın önüne geçebilir; yükü: vicdanların farklılığı, uygulayıcı keyfîliği, hukuk güvenliği).
// Pelin’in konumu bilerek tartışmalıdır: üçüncü görüş “orta yol” olarak kolay seçilmesin (11.3, 11.4, 11.5 dersi).
// HUKUKİ DANIŞMANLIK DEĞİL: görevler “hukuken ne yapılmalı” değil “felsefi olarak nasıl gerekçelendirilir” sorar; yasa maddesi, dava, kurum adı ve hukuki tavsiye yoktur. Test bunu kilitler.
// Kapsam dışı: belirli düşünürlerin görüşleri (cehalet örtüsü düşünce deneyi dâhil), pozitif hukuk dalları, güncel dava ve kurum tartışmaları, suç türleri ve ceza türleri.
// 11.6.1 → felsefi soru ve problemler (a açıklar, b toplumsal hayatla ilişkilendirerek değerlendirir); 11.6.2 → görüş ve argümanlar (a çözümler, b oluşturur, c metin yazar).
// 11.6.2 c: yazım görevinin ölçütü, programın 7 ölçütlü 100 puanlık Felsefi Metin Yazımı anahtarının 32/32/36 gruplamasıdır (bkz. 11.1).
const lawPhil = 'Bir lisede öğrenci meclisi, “Derste telefon kullanan öğrencinin telefonu bir hafta alınır” kuralını tartışıyor. Bir öğrenci, ailesinden gelebilecek önemli bir aramayı beklediği için telefona baktığını söylüyor; telefonu yine de alınmış. Üç meclis üyesi konuşuyor. Nehir: “Kural, yetkili kurul tarafından yazıldığı ve herkese duyurulduğu için geçerlidir. Kuralın adil olup olmadığı ayrı bir sorudur; hukuk, konulmuş ve herkese uygulanan kurallar demektir.” Oğuz: “İnsanın doğuştan bazı hakları vardır; hiçbir yazılı kural bunları ortadan kaldıramaz. Bir kural bu haklara aykırıysa geçerli sayılmamalıdır.” Pelin: “Kural herkese aynı uygulanmalı, ama uygulanırken hakkaniyet gözetilmelidir. Kural bir durumda açık bir haksızlık doğuruyorsa vicdan kuralın önüne geçebilir.” Öğretmen, tartışmanın hukukun kaynağının yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğuna ve hukuk ile vicdan arasındaki ilişkiye dayandığını belirtir.';

// ---------- FEL.11.6.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: hukukun kaynağı yazılı kurallar mıdır, yoksa insanın doğuştan hakları mı; bu soru bir kuralı hukuk yapan şeyin, onun yetkili merci tarafından konulmuş olması mı yoksa insanın doğuştan haklarına uygun olması mı olduğunu sorgular. İkinci soru: hukuk ile vicdan arasında nasıl bir ilişki vardır, hakkaniyet ve vicdan kuralın önüne geçebilir mi; bu soru kuralın uygulanmasında hakkaniyetin ya da vicdanın ölçüt olup olamayacağını sorgular.',
    ['Hukukun kaynağı sorusunun açıklanması (hukuk ve felsefe)', 'hukukun kaynağının yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğunu sorguladığını belirtir'],
    ['Hukuk ile vicdan ilişkisi sorusunun açıklanması (hukuk ve felsefe)', 'hakkaniyet ya da vicdanın kuralın önüne geçip geçemeyeceğini sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması (hukuk ve felsefe)', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Nehir, Oğuz ve Pelin’in sözlerinin her birinin bir kuralı geçerli kılan şeyin ne olduğu konusunda nasıl bir cevap verdiğini belirtiniz.',
    'Nehir, kuralı geçerli kılan şeyin yetkili kurul tarafından yazılması ve herkese duyurulması olduğunu söyler; adaleti ayrı bir soru sayar. Oğuz, kuralın insanın doğuştan haklarına aykırı olmaması gerektiğini söyler; aykırı kuralı geçerli saymaz. Pelin, kuralın herkese aynı uygulanmasını kabul eder ama uygulanırken hakkaniyetin gözetilmesini ister; açık haksızlıkta vicdanı kuralın önüne koyar.',
    ['Nehir’in cevabının belirlenmesi (hukuk ve felsefe)', 'Nehir’in kuralı yetkili kurulca konulup duyurulmasının geçerli kıldığını belirtir'],
    ['Oğuz’un cevabının belirlenmesi (hukuk ve felsefe)', 'Oğuz’un kuralın doğuştan haklara aykırı olmaması gerektiğini söylediğini belirtir'],
    ['Pelin’in cevabının belirlenmesi (hukuk ve felsefe)', 'Pelin’in kuralın uygulanırken hakkaniyetin gözetilmesini istediğini belirtir']),
  task('apply', 'Şu durumda öğretmenin belirttiği iki sorudan hangisinin ortaya çıktığını gerekçesiyle yazınız: Bir sınıfta yıllardır uygulanan ama hiçbir yerde yazılı olmayan bir “ilk teneffüste sıradan ayrılınmaz” kuralı vardır; yeni gelen bir öğrenci “Bu kural yazılı değil, neden uymak zorundayım?” der.',
    'Birinci soru ortaya çıkar: hukukun kaynağı yazılı kurallar mı yoksa başka bir şey mi. Öğrenci, kuralın yazılı olmamasını geçerliliğinin sorgulanması için gerekçe yapar; bu, kuralı geçerli kılan şeyin yazılı olmak mı yoksa uygulanagelmek ya da kabul görmek mi olduğu sorusunu doğurur. İkinci soru (hakkaniyet ve vicdanın kuralın önüne geçmesi) bu durumda ancak kural bir kişiye açık bir haksızlık doğurursa gündeme gelir.',
    ['Durumdaki sorunun belirlenmesi (hukuk ve felsefe)', 'durumda hukukun kaynağı sorusunun ortaya çıktığını belirtir'],
    ['Sorunun durumla ilişkilendirilmesi (hukuk ve felsefe)', 'kuralın yazılı olmamasının geçerlilik sorusunu nasıl doğurduğunu belirtir'],
    ['Diğer sorunun ayrıca ele alınması (hukuk ve felsefe)', 'ikinci sorunun bu durumda neden öne çıkmadığını ya da ne zaman çıkacağını belirtir']),
  task('apply', '“Hakkaniyet ve vicdan kuralın önüne geçebilir mi?” sorusunu şu duruma uygulayınız: Kural, derste telefona bakan her öğrencinin telefonunun bir hafta alınmasını söyler; bir öğrenci ailesinden gelebilecek önemli bir aramayı beklediği için telefona bakmıştır.',
    'Kural herkese aynı uygulanırsa öğrencinin telefonu alınır; ancak öğrencinin gerekçesi bu uygulamayı haksız gösterebilir. Soru: kuralı aynen uygulamak mı, yoksa durumun özelliğini gözeterek hakkaniyetle yumuşatmak mı gerekir? Pelin yumuşatmayı savunur; Nehir kuralın herkese aynı uygulanmasına önem verir. Kuralı yumuşatmak herkese eşit uygulama ilkesini zayıflatabilir.',
    ['Kuralın aynen uygulanmasının belirtilmesi (hukuk ve felsefe)', 'kuralın herkese aynı uygulanması durumunda öğrencinin telefonunun alınacağını belirtir'],
    ['Hakkaniyetin gözetilmesinin belirtilmesi (hukuk ve felsefe)', 'öğrencinin gerekçesinin uygulamayı haksız gösterebileceğini belirtir'],
    ['Sorunun duruma bağlanması (hukuk ve felsefe)', 'durumun hakkaniyet ile kuralın eşit uygulanması arasındaki gerilimi nasıl gündeme getirdiğini belirtir']),
  task('analyze', 'Nehir “Kuralın adil olup olmadığı ayrı bir sorudur” der. Bu sözün hangi varsayıma dayandığını ve hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Söz, bir kuralın geçerli olmasının onun adil olmasından ayrı bir mesele olduğunu varsayar. Bu varsayım, adil olmayan bir kuralın hâlâ hukuk sayılıp sayılmayacağı ve ona uymanın bir yükümlülük doğurup doğurmadığı sorusunu görünmez kılar. Oğuz’un itirazı tam bu alana yöneliktir.',
    ['Nehir’in varsayımının gösterilmesi (hukuk ve felsefe)', 'geçerlilik ile adaletin ayrı olduğu varsayımını gösterir'],
    ['Görünmez kalan sorunun belirlenmesi (hukuk ve felsefe)', 'adil olmayan kuralın hukuk sayılıp sayılmayacağı ya da ona uymanın yükümlülük doğurup doğurmadığı sorusunun görünmez kaldığını belirtir'],
    ['Oğuz’un itirazıyla ilişkilendirilmesi (hukuk ve felsefe)', 'Oğuz’un itirazının bu soruya yöneldiğini gösterir']),
  task('analyze', 'Oğuz “İnsanın doğuştan bazı hakları vardır” der. Bu sözün iki farklı iddia olarak okunabileceğini gösteriniz ve sözün hangi felsefi sorunu doğurduğunu çözümleyiniz.',
    'Söz, bu hakların yazılı kuraldan önce var olduğu iddiası olarak okunabilir; ya da yazılı kuralların bu haklara göre ölçülmesi gerektiği iddiası olarak. Birincisi hakların varlığına, ikincisi onların kurallar için ölçüt olmasına ilişkindir. Doğan sorun: bu hakların neler olduğunu kimin ve nasıl belirleyeceği.',
    ['İki iddianın ayrılması (hukuk ve felsefe)', 'hakların kuraldan önce varlığı ile hakların kurallara ölçüt olması iddialarını ayırır'],
    ['Her iddianın ayrı ele alınması (hukuk ve felsefe)', 'iki iddiayı birbirinden bağımsız olarak açıklar'],
    ['Doğan sorunun belirtilmesi (hukuk ve felsefe)', 'hakların neler olduğunu kimin belirleyeceği sorununu gösterir']),
  task('evaluate', 'Pelin’in “Kural bir durumda açık bir haksızlık doğuruyorsa vicdan kuralın önüne geçebilir” sözünün bir güçlü ve bir zayıf yanını değerlendiriniz.',
    'Güçlü yan: kuralın her durumda körü körüne uygulanmasının doğurabileceği açık haksızlığı görür ve kuralı amacından koparmaz. Zayıf yan: vicdanlar kişiden kişiye farklıdır; kuralın önüne geçecek vicdanı kimin belirleyeceği belirsizdir; uygulayıcı keyfî davranabilir ve hukukun öngörülebilirliği zayıflar. Güçlü ve zayıf yanı Pelin’in sözüne dayanarak gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (Pelin)', 'kuralın körü körüne uygulanmasının doğurabileceği haksızlığı görmesi gibi bir güçlü yanı belirtir'],
    ['Zayıf yanın belirtilmesi (Pelin)', 'vicdanların farklılığı, uygulayıcı keyfîliği ya da öngörülebilirliğin zayıflaması gibi bir zayıf yanı belirtir'],
    ['Değerlendirmenin sözle ilişkilendirilmesi (Pelin)', 'güçlü ve zayıf yanı Pelin’in sözüne dayanarak gerekçelendirir']),
  task('evaluate', 'Metindeki sorunun “Hukukun kaynağı yazılı kurallar mıdır, yoksa insanın doğuştan hakları mı?” biçiminde sorulmasının neden felsefi bir soru olduğunu, olgusal bir soruyla karşılaştırarak değerlendiriniz.',
    'Soru felsefidir. “Bu okulda kaç öğrencinin telefonu alındı?” gibi olgusal bir soru kayıtlara bakarak cevaplanır. “Hukukun kaynağı nedir?” sorusu ise kayıtlarla cevaplanmaz; “hukuk”, “geçerlilik” ve “hak” kavramlarının ne anlama geldiğine ve neyin ölçüt sayılacağına bağlıdır. Her görüş başka bir ölçütten yola çıkar: yetkili merciin koyması, doğuştan haklar, hakkaniyet.',
    ['Olgusal sorunun ayrılması (hukuk ve felsefe)', 'olgusal bir soruyu kayıtlara bakarak cevaplanan bir soru olarak gösterir'],
    ['Felsefi sorunun niteliğinin gösterilmesi (hukuk ve felsefe)', 'sorunun kayıtla değil kavramlar ve ölçütler üzerinden cevaplandığını belirtir'],
    ['Karşılaştırmanın gerekçelendirilmesi (hukuk ve felsefe)', 'iki soru arasındaki farkı gerekçesiyle gösterir']),
  task('create', 'Metindekilerden farklı, bir kural ile adalet ya da hak arasındaki ilişkiyle ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun (hukukun kaynağı, hakkaniyetin kuralın önüne geçmesi gibi) bulunduğunu belirtiniz.',
    'Örnek durum: Bir okul kütüphanesinde geç getirilen her kitap için aynı süre kitap alma yasağı uygulanır; bir öğrenci kitabı yağmur nedeniyle okula ulaşamadığı için geç getirmiştir. Felsefi sorun: kuralın herkese aynı uygulanması mı yoksa durumun özelliğine göre hakkaniyetle yumuşatılması mı gerektiği. Durumu ve sorunu tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün ve konuyla ilgili bir durumun yazılması (hukuk ve felsefe)', 'metindekilerden farklı, bir kural ile adalet ya da hak ilişkisini içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi (hukuk ve felsefe)', 'durumda hukukun kaynağı ya da hakkaniyet sorusunun nerede ortaya çıktığını belirtir'],
    ['Durum ile sorunun tutarlılığı (hukuk ve felsefe)', 'yazılan durum ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('create', 'Tartışmaya katılmayan dördüncü bir öğrenci için hukuk ile ilgili yeni bir felsefi soru yazınız ve bu sorunun üç öğrenciden hangisinin görüşüyle en çok ilgili olduğunu belirtiniz.',
    'Örnek soru: Bir kuralın herkes tarafından kabul edilmesi, onu adil yapar mı? Bu soru en çok Nehir’in görüşüyle ilgilidir; çünkü kuralı geçerli kılan şeyin konulmuş ve duyurulmuş olması mı yoksa kabul görmesi mi olduğunu sorgular. Yeni ve felsefi nitelikte olan, öğrenciyle ilişkisini gerekçelendiren her çalışma kabul edilir.',
    ['Yeni bir felsefi sorunun yazılması (hukuk ve felsefe)', 'metindeki iki sorudan farklı, hukukla ilgili bir felsefi soru yazar'],
    ['Sorunun bir öğrenciyle ilişkilendirilmesi (hukuk ve felsefe)', 'sorunun Nehir, Oğuz ya da Pelin’den birinin görüşüyle ilgisini belirtir'],
    ['İlişkinin gerekçelendirilmesi (hukuk ve felsefe)', 'seçtiği öğrenciyle ilişkiyi gerekçeyle gösterir']),
];

// ---------- FEL.11.6.1 b: toplumsal hayatla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın toplumsal yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: bir trafik kuralının herkese aynı uygulanması ve istisnai bir durumda bu uygulamanın haksız görünmesi. Bu, tartışmadaki kuralın geçerliliği ve hakkaniyet sorularının toplumsal bir karşılığıdır. Toplumsal bir örnek verip tartışmayla ilişkisini gösteren her çalışma kabul edilir.',
    ['Toplumsal örneğin verilmesi (hukuk ve felsefe)', 'toplumsal yaşamdan bir örnek verir'],
    ['Örneğin tartışmaya bağlanması (hukuk ve felsefe)', 'örneğin hukukun kaynağı ya da hakkaniyet tartışmasıyla ilişkisini belirtir'],
    ['Örneğin açık yazılması (hukuk ve felsefe)', 'örneği başkasının anlayabileceği açıklıkta yazar']),
  task('understand', 'Nehir, Oğuz ve Pelin’in görüşlerinden birinin toplumsal yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Nehir: kurallara uymayı ve itirazı kuralı değiştirme yoluyla yapmayı önemser; herkese eşit uygulamaya değer verir. Oğuz: bir kural insanın temel haklarına aykırı göründüğünde itiraz etmeyi haklı görür. Pelin: kuralın uygulanmasında durumun özelliğine bakılmasını ister. Seçilen görüşün tutumunu doğru bağlayan yanıt kabul edilir.',
    ['Bir görüşün seçilmesi ve belirtilmesi (hukuk ve felsefe)', 'üç görüşten birini doğru biçimde belirtir'],
    ['Toplumsal tutumun gösterilmesi (hukuk ve felsefe)', 'seçilen görüşün toplumsal yaşamdaki bir tutuma nasıl yol açabileceğini gösterir'],
    ['Tutumun görüşle ilişkilendirilmesi (hukuk ve felsefe)', 'tutum ile görüş arasındaki bağı açıklar']),
  task('apply', 'Kendi yaşamınızdan (okul, aile, mahalle) yazılı ya da yazılı olmayan bir kural seçiniz ve metindeki iki görüşün bu kurala nasıl yaklaşacağını yazınız.',
    'Örnek: okuldaki yemekhane sırası kuralı. Nehir, kuralın herkese aynı uygulanmasına ve konulmuş olmasına bakar. Pelin, sırayı bozmak zorunda kalan birinin özel durumuna hakkaniyetle bakılmasını ister. Seçilen kuralı tanıtan ve iki görüşün yaklaşımını tutarlı gösteren her çalışma kabul edilir.',
    ['Kuralın seçilmesi ve tanıtılması (hukuk ve felsefe)', 'kendi yaşamından gündelik bir kural seçer ve tanıtır'],
    ['Birinci görüşün yaklaşımının yazılması (hukuk ve felsefe)', 'metindeki bir görüşün kurala yaklaşımını doğru yazar'],
    ['İkinci görüşün yaklaşımının yazılması (hukuk ve felsefe)', 'metindeki ikinci bir görüşün kurala yaklaşımını doğru ve birinciden ayırarak yazar']),
  task('apply', 'Şu örneğe metindeki üç görüşün nasıl yaklaşacağını yazınız: Bir okul kütüphanesinde kitabı geç getirene bir hafta kitap alma yasağı uygulanıyor; bir öğrenci kitabı yağmur nedeniyle okula ulaşamadığı için geç getirmiş.',
    'Nehir: kural yetkili merci tarafından konulmuş ve duyurulmuştur; herkese aynı uygulanır, yasak sürer. Oğuz: kural, insanın doğuştan haklarına açıkça aykırı değilse geçerlidir; bu örnekte temel bir hakka aykırılık görünmediği için kuralı geçersiz saymaz. Pelin: durumun özelliği (yağmur) gözetilerek yasak yumuşatılabilir; ancak bu herkese eşit uygulamayı zayıflatabilir.',
    ['Nehir’in yaklaşımının yazılması (hukuk ve felsefe)', 'Nehir’in kuralı herkese aynı uygulayacağını belirtir'],
    ['Oğuz’un yaklaşımının yazılması (hukuk ve felsefe)', 'Oğuz’un kuralın doğuştan haklara aykırı olup olmadığına bakacağını belirtir'],
    ['Pelin’in yaklaşımının yazılması (hukuk ve felsefe)', 'Pelin’in durumun özelliğine göre yumuşatmayı savunacağını belirtir']),
  task('analyze', 'Okulda hiç yazılı kural bulunmasaydı toplumsal düzenin nasıl etkileneceğini, hukukun gereği ve önemi bakımından çözümleyiniz.',
    'Kural yoksa kişiler birbirlerinin davranışlarını önceden bilemez; anlaşmazlıklar çözümsüz kalabilir; güçlü olan kendi isteğini kabul ettirebilir. Kural düzen, öngörülebilirlik ve eşit muamele sağlar. Ancak kural özgürlüğü sınırlar da; bu yüzden hukuk hem özgürlüğü sınırlayan hem de güvence altına alan bir yapıdır.',
    ['Kuralsızlığın sonuçlarının gösterilmesi (hukuk ve felsefe)', 'kural yokluğunda öngörülemezlik ya da anlaşmazlığın çözümsüz kalması gibi sonuçları gösterir'],
    ['Hukukun gereğinin gösterilmesi (hukuk ve felsefe)', 'kuralın düzen, öngörülebilirlik ya da eşit muamele sağladığını gösterir'],
    ['Sınırlama ve güvence ilişkisinin çözümlenmesi (hukuk ve felsefe)', 'hukukun özgürlüğü hem sınırlayabildiğini hem güvence altına alabildiğini gösterir']),
  task('analyze', 'Bir kurala yalnız “yazılı olduğu için” uymak ile kuralın “adil olduğunu düşündüğünüz için” uymak arasındaki ilişkiyi, hukukun kaynağı sorusu bakımından çözümleyiniz.',
    'Yazılı olduğu için uymak, kuralın geçerliliğini konulmuş ve duyurulmuş olmasına bağlar (Nehir’in yaklaşımı). Adil olduğunu düşündüğü için uymak, geçerliliği kuralın adalet ya da haklarla uyumuna bağlar (Oğuz’un yaklaşımı). İkisi aynı sonuca götürebilir; ayrıştıkları nokta, kuralın adil bulunmadığı durumda ortaya çıkar: uyulur mu, uyulmaz mı.',
    ['Yazılı olduğu için uymanın gösterilmesi (hukuk ve felsefe)', 'geçerliliği kuralın konulmuş olmasına bağlayan yaklaşımı gösterir'],
    ['Adil bulduğu için uymanın gösterilmesi (hukuk ve felsefe)', 'geçerliliği adalet ya da haklarla uyuma bağlayan yaklaşımı gösterir'],
    ['İki yaklaşımın ayrıştığı noktanın çözümlenmesi (hukuk ve felsefe)', 'kuralın adil bulunmadığı durumda iki yaklaşımın ayrıştığını gösterir']),
  task('evaluate', 'Nehir’in “Hukuk, konulmuş ve herkese uygulanan kurallar demektir” görüşünün toplumsal yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: kuralların önceden bilinmesini ve herkese eşit uygulanmasını sağlar; keyfîliği azaltır. Sakınca: adil olmayan bir kuralın da hukuk sayılması gerekir ve kuralı koyanın yetkisi sorgulanmadan kalabilir. Yarar ve sakıncayı görüşe dayanarak gerekçelendiren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Nehir)', 'görüşün toplumsal yaşamda sağlayabileceği bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Nehir)', 'adil olmayan kuralın da hukuk sayılması ya da yetkinin sorgulanmaması gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşle ilişkilendirilmesi (Nehir)', 'yarar ve sakıncayı Nehir’in görüşüne dayanarak gerekçelendirir']),
  task('evaluate', 'Oğuz’un “İnsanın doğuştan bazı hakları vardır; aykırı kural geçerli sayılmamalıdır” görüşünün toplumsal yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: kuralların temel haklara aykırı olmasına karşı bir ölçüt sunar ve kural koyucuyu sınırlar. Sakınca: bu hakların neler olduğu konusunda insanlar anlaşamayabilir; herkes kendi saydığı haklar gerekçesiyle kurala uymamayı haklı görebilir ve toplumsal düzen zayıflayabilir. Yarar ve sakıncayı görüşe dayanarak gerekçelendiren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Oğuz)', 'görüşün toplumsal yaşamda sağlayabileceği bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Oğuz)', 'hakların belirlenmesinde anlaşmazlık ya da herkesin kurala uymamayı haklı görmesi gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşle ilişkilendirilmesi (Oğuz)', 'yarar ve sakıncayı Oğuz’un görüşüne dayanarak gerekçelendirir']),
  task('create', 'Üç görüşten biriyle ilgili, bir öğrencinin okul ya da mahalle yaşamında karşılaşabileceği kısa bir durum yazınız ve o görüşün bu duruma nasıl yaklaşacağını belirtiniz.',
    'Örnek durum: Bir öğrenci, okulun yazılı olmayan “koridorda koşulmaz” kuralına bir gün acil bir durum nedeniyle uymaz. Pelin’in görüşü bu durumda öğrencinin özel durumuna bakılmasını gerektirir. Durumu ve yaklaşımı tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün bir durumun yazılması (hukuk ve felsefe)', 'bir öğrencinin okul ya da mahalle yaşamında karşılaşabileceği kısa bir durum yazar'],
    ['Görüşün seçilmesi ve belirtilmesi (hukuk ve felsefe)', 'durumla ilgili bir görüşü belirtir'],
    ['Görüşün duruma uygulanması (hukuk ve felsefe)', 'seçilen görüşün duruma nasıl yaklaşacağını tutarlı biçimde yazar']),
  task('create', 'Kural ile hakkaniyetin toplumsal yaşamda birbirini nasıl tamamlayabileceğini ya da çatışabileceğini gösteren kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Kural herkese aynı uygulanmalı, yoksa kimse neyin geçerli olduğunu bilemez.” İkinci kişi: “Ama bu durumda kural açık bir haksızlık yapıyor.” Diyalog, eşit uygulama ile hakkaniyet arasındaki gerilimi gösterir. Kural ile hakkaniyet arasındaki ilişkiyi tutarlı gösteren özgün her diyalog kabul edilir.',
    ['Diyalogun konuya uygunluğu (hukuk ve felsefe)', 'diyalogun kural ile hakkaniyet arasındaki ilişkiyi konu aldığı görülür'],
    ['Tamamlama ya da çatışmanın gösterilmesi (hukuk ve felsefe)', 'kural ile hakkaniyetin tamamlama ya da çatışma ilişkisini diyalogda gösterir'],
    ['Diyalogun tutarlı kurulması (hukuk ve felsefe)', 'konuşmacıların sözlerini birbirine bağlı ve tutarlı kurar']),
];

// ---------- FEL.11.6.2 a: hak ve özgürlüklerin hukuksal temellerini çözümler ----------
const a2: Task[] = [
  task('understand', 'Oğuz’un sözünde öncülleri ve sonucu ayırarak yazınız.',
    'Öncül: insanın doğuştan bazı hakları vardır. Öncül: hiçbir yazılı kural bu hakları ortadan kaldıramaz. Sonuç: bu haklara aykırı bir kural geçerli sayılmamalıdır.',
    ['Birinci öncülün belirlenmesi (Oğuz)', 'insanın doğuştan bazı haklarının olduğu öncülünü belirtir'],
    ['İkinci öncülün belirlenmesi (Oğuz)', 'yazılı kuralın bu hakları ortadan kaldıramayacağı öncülünü belirtir'],
    ['Sonucun belirlenmesi (Oğuz)', 'sonucu haklara aykırı kuralın geçerli sayılmaması olarak belirtir']),
  task('understand', 'Pelin’in sözünde ileri sürdüğü iddiayı ve onu destekleyen gerekçeyi ayırarak yazınız.',
    'İddia: kural uygulanırken hakkaniyet gözetilmelidir; açık haksızlıkta vicdan kuralın önüne geçebilir. Gerekçe: kural bir durumda açık bir haksızlık doğuruyorsa onu aynen uygulamak kuralın amacına aykırı bir sonuç verir.',
    ['İddianın belirlenmesi (Pelin)', 'kural uygulanırken hakkaniyetin gözetilmesi ve vicdanın önüne geçebilmesi iddiasını belirtir'],
    ['Gerekçenin belirlenmesi (Pelin)', 'kuralın bir durumda açık haksızlık doğurabileceği gerekçesini belirtir'],
    ['İddia ile gerekçenin ayrılması (Pelin)', 'iddia ile gerekçeyi karıştırmadan ayrı ayrı yazar']),
  task('apply', 'Paragraf: “Hukukun kaynağı tartışmasında temel soru, kuralı geçerli kılan şeyin ne olduğudur. Nehir’e göre ……… . Bu nedenle ………” Boş bırakılan yerleri Nehir’in görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: kural, yetkili kurul tarafından yazıldığı ve herkese duyurulduğu için geçerlidir; kuralın adil olup olmadığı ayrı bir sorudur. Boşluk 2: konulmuş ve herkese uygulanan kurallar hukuktur; adaletsiz bulunsa da konulmuş kural hukuk sayılır. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Nehir)', 'Nehir’in görüşünü doğru biçimde (yetkili merci tarafından konulma ve duyurulma) tamamlar'],
    ['İkinci boşluğun tamamlanması (Nehir)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Nehir)', 'tamamlanan cümleler ilk cümleyle tutarlı bir bütün oluşturur']),
  task('apply', 'Oğuz’un görüşünü “iddia – gerekçe – sonuç” sırasıyla üç cümlelik bir akıl yürütme hâline getiriniz.',
    'Örnek: İddia: bir kuralın geçerliliği insanın doğuştan haklarına uygunluğa bağlıdır. Gerekçe: insanın doğuştan bazı hakları vardır ve yazılı bir kural bunları ortadan kaldıramaz. Sonuç: bu nedenle bu haklara aykırı bir kural geçerli sayılmamalıdır. Üç öğeyi sırayla ve doğru kuran her akıl yürütme kabul edilir.',
    ['İddianın yazılması (Oğuz)', 'görüşün iddiasını açıkça yazar'],
    ['Gerekçenin yazılması (Oğuz)', 'iddiayı destekleyen gerekçeyi yazar'],
    ['Sonucun gerekçeden çıkarılması (Oğuz)', 'sonucu iddia ve gerekçeyle tutarlı biçimde yazar']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Nehir haklıdır; çünkü kurallar herkese aynı uygulanır.” Bu argümandaki temellendirme sorununu belirtiniz.',
    'Gerekçe, kuralların herkese aynı uygulanmasına dayanır. Eşit uygulama, bir kuralın geçerli ya da adil olduğunu göstermez; adil olmayan bir kural da herkese aynı uygulanabilir. Ayrıca Nehir’in kendi gerekçesi (kuralın yetkili merci tarafından konulması ve duyurulması) bu argümanla desteklenmemektedir.',
    ['Eşit uygulamaya başvurunun gösterilmesi (hukuk ve felsefe)', 'gerekçenin kuralların herkese aynı uygulanmasına dayandığını belirtir'],
    ['Eşit uygulama ile geçerlilik arasındaki boşluğun gösterilmesi (hukuk ve felsefe)', 'eşit uygulamanın kuralın geçerli ya da adil olduğunu göstermediğini belirtir'],
    ['Nehir’in gerekçesinin ayrıca gösterilmesi (hukuk ve felsefe)', 'Nehir’in asıl gerekçesinin bu argümanda yer almadığını belirtir']),
  task('analyze', 'Pelin’in argümanındaki örtük bir öncülü belirleyiniz ve bu öncüle yöneltilebilecek bir itirazı yazınız.',
    'Örtük öncül: uygulayıcı, açık haksızlığı doğru ayırt edebilir ve bu ayırt etmeye güvenilebilir. İtiraz: vicdanlar kişiden kişiye farklıdır; uygulayıcı kendi vicdanına göre kuralı yumuşatırsa keyfî davranabilir ve hukukun öngörülebilirliği zayıflar. Öncülü doğru belirleyen ve gerçek bir itiraz yazan eşdeğer yanıtlar kabul edilir.',
    ['Örtük öncülün belirlenmesi (Pelin)', 'uygulayıcının açık haksızlığı doğru ayırt edebileceği öncülünü belirtir'],
    ['İtirazın yazılması (Pelin)', 'öncüle yönelen gerçek bir itiraz yazar'],
    ['İtirazın öncülle ilişkilendirilmesi (Pelin)', 'itirazın hangi öncülü zayıflattığını gösterir']),
  task('evaluate', 'Nehir, Oğuz ve Pelin’in argümanlarından hangisinin gerekçe yükünün en ağır olduğunu değerlendiriniz; seçiminizi gerekçelendiriniz.',
    'Tek doğru seçim yoktur; her görüşün bir yükü vardır. Nehir: adil olmayan bir kuralın da hukuk sayılmasının ve ona uyma yükümlülüğünün temelini göstermelidir. Oğuz: doğuştan hakların neler olduğunu ve bunları kimin belirleyeceğini göstermelidir. Pelin: vicdanların farklı olmasına ve uygulayıcının keyfîliğine rağmen vicdanın kuralın önüne nasıl geçebileceğini göstermelidir. Seçimini bu yüklerden biriyle gerekçelendiren her yanıt kabul edilir.',
    ['Seçilen görüşün belirtilmesi (hukuk ve felsefe)', 'üç görüşten birini gerekçe yükü en ağır olan olarak seçer'],
    ['Gerekçe yükünün gösterilmesi (hukuk ve felsefe)', 'seçilen görüşün neyi göstermek zorunda olduğunu belirtir'],
    ['Seçimin diğer görüşlerle karşılaştırılması (hukuk ve felsefe)', 'diğer iki görüşün yüküyle karşılaştırarak seçimini gerekçelendirir']),
  task('evaluate', 'Oğuz’un “Bu haklara aykırı kural geçerli sayılmamalıdır” sonucunun öncüllerinden çıkıp çıkmadığını değerlendiriniz.',
    'Sonuç öncüllerden tam çıkmaz. Öncüller, hakların kuraldan önce var olduğunu ve yazılı kuralın onları ortadan kaldıramayacağını söyler; sonuç ise aykırı kuralın geçerli sayılmaması gerektiğini söyler. Bir kural bir hakkı ortadan kaldıramasa da yürürlükte kalabilir; hakkın varlığından kuralın geçersizliğine geçiş ayrıca gerekçelendirilmemiştir. Ayrıca hakların neler olduğu belirsizdir. Sonuç gerekçelendirilmeden kurulmuştur; bu, görüşün yanlış olduğunu göstermez.',
    ['Öncül ve sonucun ayrılması (Oğuz)', 'hakkın varlığı öncülü ile kuralın geçersizliği sonucunu ayırır'],
    ['Geçişin gerekçelendirilmediğinin gösterilmesi (Oğuz)', 'hakkı ortadan kaldıramayan bir kuralın yürürlükte kalabileceğini ve sonucun öncülden çıkmadığını belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (Oğuz)', 'sonucun çıkmamasının görüşün yanlışlığını göstermediğini belirtir']),
  task('create', 'Pelin’in argümanını güçlendirecek bir ek öncül yazınız ve bu öncülün hangi itiraza karşı işe yaradığını belirtiniz.',
    'Örnek ek öncül: kuralın amacı, uygulandığı durumda gerçekleşmiyorsa kuralı amacına uygun biçimde yumuşatmak kuralı korur. Bu öncül, “uygulayıcı keyfî davranır” itirazına karşı işe yarar; çünkü yumuşatmanın ölçütünü keyfî vicdan değil, kuralın amacı olarak koyar. Pelin’in argümanını gerçekten güçlendiren ve itirazla ilişkilendirilen eşdeğer öncüller kabul edilir.',
    ['Ek öncülün yazılması (Pelin)', 'Pelin’in argümanına eklenebilecek bir öncül yazar'],
    ['Öncülün argümanı güçlendirmesi (Pelin)', 'öncülün argümanı nasıl güçlendirdiğini gösterir'],
    ['Karşı çıkılan itirazın belirtilmesi (Pelin)', 'öncülün hangi itiraza karşı işe yaradığını belirtir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan, kural ve hak konulu kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Kural, konulmuş olduğu için herkese uygulanmalı.” İkinci kişi: “Ama kural birinin temel bir hakkını çiğniyorsa yine de uyulmalı mı?” Birinci kişi: “Önce o hakkın ne olduğunu ve kimin belirlediğini göstermelisin.” Gerekçeyi, itirazı ve yanıtı tutarlı kuran özgün her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması (hukuk ve felsefe)', 'diyalogda kural ve hakla ilgili bir gerekçe verir'],
    ['İtirazın diyalogda yer alması (hukuk ve felsefe)', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması (hukuk ve felsefe)', 'itiraza gerekçeli bir yanıt verir']),
];

// ---------- FEL.11.6.2 b: temel hukuk sorunlarına yönelik görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini hukuk ve kural tartışmasından bir örnekle açıklayınız.',
    'Bir görüşün argümana dönüşmesi için öncüllerin (gerekçelerin) ve onlardan çıkan bir sonucun açıkça yazılması gerekir. Örnek: görüş “kural herkese aynı uygulanmalı”; öncül: eşit uygulama keyfîliği azaltır; sonuç: kural herkese aynı uygulanmalıdır. Öncül ve sonuç ilişkisini örnekle gösteren her açıklama kabul edilir.',
    ['Gerekenlerin belirtilmesi (hukuk ve felsefe)', 'görüşü argümana dönüştürmek için öncül ve sonuç gerektiğini belirtir'],
    ['Örneğin verilmesi (hukuk ve felsefe)', 'hukuk ve kural tartışmasından bir örnek verir'],
    ['Örnekle açıklamanın ilişkilendirilmesi (hukuk ve felsefe)', 'örnekte öncül ve sonuç ilişkisini gösterir']),
  task('understand', 'Hukukun doğası konusunda kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: “Bir kural hem yetkili merci tarafından konulmuş hem de temel haklara uygun olduğunda tam anlamıyla geçerlidir.” Bu görüş, hukukun kaynağının yazılı kurallar mı yoksa doğuştan haklar mı olduğu sorusuna cevaptır. Görüşü açık yazan ve soruyla doğru ilişkilendiren her çalışma kabul edilir.',
    ['Görüşün yazılması (hukuk ve felsefe)', 'hukukun doğası konusunda bir görüşü bir cümleyle yazar'],
    ['Felsefi sorunun belirtilmesi (hukuk ve felsefe)', 'görüşün hangi felsefi soruya cevap olduğunu belirtir'],
    ['Görüş ile sorunun uyumu (hukuk ve felsefe)', 'yazılan görüş ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('apply', 'Hukukun doğası konusunda bir görüş seçiniz ve bu görüşü bir ilke, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: Görüş: kural herkese aynı uygulanmalıdır. İlke: eşit uygulama keyfîliği azaltır ve kuralı öngörülebilir kılar. Durum: okul kütüphanesinde geç getirilen her kitap için aynı süre yasak uygulanmaktadır. Sonuç: bu uygulama kuralın öngörülebilir ve keyfîlikten uzak olmasını sağlar. İlke, durum ve sonucu tutarlı kuran her argüman kabul edilir.',
    ['İlkenin yazılması (hukuk ve felsefe)', 'seçtiği görüşe uygun bir ilke yazar'],
    ['Durum bilgisinin yazılması (hukuk ve felsefe)', 'ilkenin uygulandığı somut bir durum bilgisi yazar'],
    ['Sonucun ilkeyle tutarlı çıkarılması (hukuk ve felsefe)', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('apply', '“Kural uygulanırken hakkaniyet gözetilmelidir” ilkesinden yola çıkarak, bir okul kuralının uygulanmasında öğrencinin özel durumunun gözetilip gözetilmeyeceği durumu için bir argüman kurunuz.',
    'Örnek: İlke: kural uygulanırken hakkaniyet gözetilmelidir. Durum: bir öğrenci kuralı, kendi kontrolü dışındaki bir nedenle (yağmur nedeniyle okula ulaşamama) ihlal etmiştir. Sonuç: öğrencinin özel durumu gözetilmelidir. İlkeyi duruma uygulayan ve sonucu tutarlı çıkaran her argüman kabul edilir.',
    ['İlkenin duruma uygulanması (hukuk ve felsefe)', 'verilen ilkeyi öğrencinin durumuna uygular'],
    ['Durum bilgisinin kullanılması (hukuk ve felsefe)', 'durumdan somut bir bilgi kullanır'],
    ['Sonucun tutarlı çıkarılması (hukuk ve felsefe)', 'sonucu ilkeden ve durumdan tutarlı biçimde çıkarır']),
  task('analyze', 'Hukukun doğası konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümanın dayandığı varsayımı ve bu varsayıma yöneltilebilecek güçlü bir itirazı çözümleyiniz; itirazın neden güçlü olduğunu açıklayınız.',
    'Örnek: Öncül: kuralların önceden bilinmesi insanların davranışlarını planlamasını sağlar. Öncül: yetkili merciin koyup duyurduğu kurallar önceden bilinebilir. Sonuç: hukuk, konulmuş ve duyurulmuş kurallara dayanmalıdır. Varsayım: önceden bilinebilirlik, kuralın adil olmasından daha önemlidir. İtiraz: adil olmayan ama önceden bilinen bir kural da insanlara zarar verebilir; bilinebilirlik tek başına yeterli değildir. İtiraz güçlüdür, çünkü varsayımın bilinebilirliğe verdiği önceliği sorgular. Kendi argümanını öncül ve sonuçla kuran, varsayımını belirleyen ve itirazın gücünü gerekçelendiren eşdeğer yanıtlar kabul edilir.',
    ['Argümanın kurulması ve varsayımın belirlenmesi (hukuk ve felsefe)', 'hukukun doğası konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve dayandığı varsayımı gösterir'],
    ['Güçlü bir itirazın belirlenmesi (hukuk ve felsefe)', 'varsayıma yöneltilebilecek güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi (hukuk ve felsefe)', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Kural yazılıysa adildir.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: yazılı kuralı koyanlar her zaman adil davranır ya da yazılı olmak adaleti kendiliğinden sağlar. Oğuz itiraz eder: yazılı kural doğuştan haklara aykırı olabilir. Pelin de itiraz edebilir: yazılı kural bir durumda açık haksızlık doğurabilir. Nehir ise öncülü bu biçimiyle kabul etmeyebilir: ona göre kuralın geçerliliği yazılı ve duyurulmuş olmasındandır, adil olup olmadığı ayrı bir sorudur.',
    ['Gizli öncülün belirlenmesi (hukuk ve felsefe)', 'yazılı olmanın adaleti kendiliğinden sağladığı öncülünü gösterir'],
    ['Oğuz ve Pelin’in itirazının gösterilmesi (hukuk ve felsefe)', 'doğuştan haklara aykırılık ve açık haksızlık itirazlarını doğru ilişkilendirir'],
    ['Nehir’in konumunun ayrıca gösterilmesi (hukuk ve felsefe)', 'Nehir’in öncülü bu biçimiyle kabul etmeyebileceğini ve adaleti ayrı bir soru saydığını belirtir']),
  task('evaluate', 'Hukukun doğası konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümana yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını gösteriniz. İtiraza gerekçeli bir yanıt veriniz ve bu yanıtın itirazı karşılayıp karşılamadığını değerlendiriniz.',
    'Örnek: Öncül: kuralın amacı, uygulandığı durumda gerçekleşmelidir. Öncül: aynen uygulandığında amacına aykırı sonuç veren kural amacını gerçekleştirmez. Sonuç: böyle durumlarda kural hakkaniyetle yumuşatılmalıdır. İtiraz: yumuşatma kararını verenin kendi vicdanı ölçüt olursa keyfîlik doğar. Zayıflayan öncül: kuralın amacının uygulayıcı tarafından doğru belirlenebileceği. Yanıt: amaç kuralı koyan tarafından duyurulmuşsa ölçüt keyfî vicdan değil, bu amaçtır. Değerlendirme: yanıt itirazı kısmen karşılar; ancak amacın açıkça duyurulmadığı durumlarda sorun sürer. Öğrencinin kendi argümanını açıkça kurduğu, itirazı bir öncülle ilişkilendirdiği ve gerekçeli yanıtının yeterliliğini değerlendirdiği eşdeğer çalışmalar kabul edilir.',
    ['Argümanın kurulması ve itirazın belirlenmesi (hukuk ve felsefe)', 'hukukun doğası konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve bu argümana yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi (hukuk ve felsefe)', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['İtiraza yanıt verilmesi ve yanıtın değerlendirilmesi (hukuk ve felsefe)', 'itiraza gerekçeli bir yanıt verir ve bu yanıtın itirazı karşılayıp karşılamadığını gerekçeyle değerlendirir']),
  task('evaluate', '“Kural kuraldır; kimse onu sorgulamamalıdır” gerekçesinin hukuk tartışmasında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: “kural kuraldır” ifadesi kuralın neden uyulmayı hak ettiğini göstermez, yalnız onun kural olduğunu yineler; sorgulamanın neden yanlış olduğu da gösterilmemiştir. Sorgulama, kuralın değiştirilmesi ya da iyileştirilmesi imkânını da sağlar. Ancak düzenin korunması için kurallara genel olarak uyulması gerektiği görüşü ayrıca gerekçelendirilebilir. Gerekçenin yetersizliği görüşün yanlışlığını göstermez.',
    ['Gerekçenin yetersizliğinin gösterilmesi (hukuk ve felsefe)', 'ifadenin kuralın neden uyulmayı hak ettiğini göstermediğini belirtir'],
    ['Karşı bilginin belirtilmesi (hukuk ve felsefe)', 'sorgulamanın kuralı iyileştirme imkânı sağladığını ya da düzen için uymanın ayrıca gerekçelendirilebileceğini belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (hukuk ve felsefe)', 'gerekçenin yetersizliğinin görüşün yanlış olduğunu göstermediğini belirtir']),
  task('create', 'Üç görüşten farklı dördüncü bir görüş ortaya koyunuz ve bu görüşü bir gerekçeyle destekleyiniz.',
    'Örnek: Bir kuralın geçerliliği, onu etkilenen kişilerin makul gerekçelerle kabul edebilmesine bağlıdır; çünkü kural yalnız konulduğu için ya da yalnız haklara uyduğu için değil, kendisine uyacak kişilere gerekçelendirilebildiği için uyulmayı hak eder. Üç görüşten farklı olan, tutarlı ve gerekçeli her görüş kabul edilir.',
    ['Dördüncü görüşün ortaya konması (hukuk ve felsefe)', 'metindeki üç görüşten farklı bir görüş ortaya koyar'],
    ['Görüşün gerekçelendirilmesi (hukuk ve felsefe)', 'görüşü bir gerekçeyle destekler'],
    ['Görüş ile gerekçenin tutarlılığı (hukuk ve felsefe)', 'görüş ile gerekçenin birbirine uyduğunu gösterir']),
  task('create', 'Nehir, Oğuz ve Pelin’in görüşlerinden birden fazlasından bir şey koruyan birleştirici bir öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğinizi belirtiniz.',
    'Örnek: Kural yetkili merci tarafından konulup duyurulmalıdır (Nehir); ancak temel haklara açıkça aykırı kurallar değiştirilmelidir (Oğuz). Çözülmeyen: hangi hakların “temel” sayılacağı ve kuralı değiştirmeye kimin karar vereceği. Hangi görüşten neyi koruduğunu ve neyi çözemediğini belirten tutarlı her öneri kabul edilir.',
    ['Birleştirici önerinin oluşturulması (hukuk ve felsefe)', 'en az iki görüşten bir şey koruyan tutarlı bir öneri yazar'],
    ['Korunan öğelerin belirtilmesi (hukuk ve felsefe)', 'hangi görüşten neyi koruduğunu belirtir'],
    ['Çözülemeyenin belirtilmesi (hukuk ve felsefe)', 'önerinin çözemediği bir noktayı açıkça belirtir']),
];

// ---------- FEL.11.6.2 c: hukuk sorunlarına ilişkin felsefi metin yazar ----------
const sampleParagraph = '“Hukukun kaynağı tartışmasındaki temel problem, hukuku geçerli kılan şeyin yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğudur. Hukuku yazılı kurallara indirgeyen görüş, kuralın yetkili merci tarafından konulmasını ve duyurulmasını yeterli sayar. Oysa yazılı bir kural insanın temel haklarını açıkça çiğniyorsa, yalnız yazılı olması ona uyulması gerektiğini göstermez. Bu nedenle hukukun geçerliliği yalnız yazılı olmaya bağlanamaz.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: hukuku geçerli kılan şeyin yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğu. Kavram: hukuk (ayrıca kural, hak). Gerekçe: yazılı bir kural insanın temel haklarını açıkça çiğniyorsa, yalnız yazılı olması ona uyulması gerektiğini göstermez.',
    ['Problemin belirlenmesi (hukuk paragrafı)', 'paragrafın problemini hukukun kaynağının yazılı kural mı yoksa doğuştan haklar mı olduğu olarak belirtir'],
    ['Kavramın belirlenmesi (hukuk paragrafı)', 'paragraftaki felsefi kavramlardan birini (hukuk, kural, hak) belirtir'],
    ['Gerekçenin belirlenmesi (hukuk paragrafı)', 'yazılı olmanın temel hakları çiğneyen kuralı geçerli kılmadığı gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: hukukun geçerliliği yalnız yazılı olmaya bağlanamaz. Sonucu taşıyan cümle paragrafın son cümlesidir (“Bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi (hukuk paragrafı)', 'görüşü hukukun geçerliliğinin yalnız yazılı olmaya bağlanamayacağı biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi (hukuk paragrafı)', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması (hukuk paragrafı)', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “Hukuk ve vicdan ilişkisindeki temel problem, hakkaniyetin kuralın önüne geçip geçemeyeceğidir. Pelin’e göre ……… . Bu nedenle ………” Boş bırakılan yerleri Pelin’in görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: kural herkese aynı uygulanmalıdır, ama uygulanırken hakkaniyet gözetilmelidir; kural bir durumda açık haksızlık doğuruyorsa vicdan kuralın önüne geçebilir. Boşluk 2: kuralın açık haksızlık doğurduğu durumda kural yumuşatılmalı ya da durumun özelliği gözetilmelidir. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Pelin)', 'Pelin’in görüşünü doğru biçimde (hakkaniyet ve açık haksızlıkta vicdan) tamamlar'],
    ['İkinci boşluğun tamamlanması (Pelin)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Pelin)', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Nehir’in görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: Hukukun kaynağı tartışmasındaki temel problem, bir kuralı geçerli kılan şeyin ne olduğudur. Nehir’in görüşünde “hukuk”, yetkili merci tarafından konulmuş ve herkese duyurulmuş kurallar bütünüdür. Kural bu biçimde konulduğu için geçerlidir; adil olup olmadığı ayrı bir sorudur. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması (Nehir)', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması (Nehir)', 'hukuk ya da kural kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması (Nehir)', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “Kurallar çok önemlidir, herkes kurala uyar. Bu yüzden kurallar hep adildir.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (hukukun kaynağı ya da hakkaniyet) belirsizdir. Kavram: hukuk, kural, adalet ve hakkaniyet gibi kavramlar ele alınmamış, “önemli” kavramı belirsiz bırakılmıştır. Temellendirme: “herkes kurala uyar” gerekçesi, kuralların adil olduğunu göstermez; uyulmak ile adil olmak aynı şey değildir.',
    ['Problemin eksikliğinin gösterilmesi (hukuk paragrafı)', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi (hukuk paragrafı)', 'hukuk, kural, adalet ve hakkaniyet gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi (hukuk paragrafı)', '“herkes uyar” gerekçesinin kuralın adil olduğunu göstermediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Hukuk önemlidir. Bu yüzden vicdana hiç yer verilmemelidir.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: hukuk önemlidir. Sonuç: vicdana hiç yer verilmemelidir. Sonuç öncülden çıkmaz: hukukun önemli olması, vicdanın hukuk uygulamasında hiçbir rol oynamaması gerektiğini göstermez; hukuk bazen vicdanla örtüşebilir ya da onu tamamlayabilir. Aradaki boşluğu dolduran bir gerekçe (vicdanın hukuka zarar verdiği) gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması (hukuk paragrafı)', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi (hukuk paragrafı)', 'hukukun önemli olmasının vicdanı dışlamayı gerektirmediğini belirtir'],
    ['Eksik gerekçenin belirtilmesi (hukuk paragrafı)', 'vicdanın hukuka zarar verdiği gerekçesinin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence kurallar iyi. Çünkü düzen olmasını sağlıyor. Herkes uymalı.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (hukukun kaynağı), kavramlar yerinde (hukuk, kural, hak), argüman ve gerekçe açık (yazılı olmak temel hakları çiğneyen kuralı geçerli kılmaz), bütünlük var. Paragraf 2’de problem tanımlanmamış, “iyi” belirsiz, gerekçe (düzen sağlaması) sonucu (herkes uymalı) tek başına desteklemiyor, felsefi terim yok. Paragraf 1’in sınırı: “temel hak” kavramının neleri kapsadığını belirtmemesi.',
    ['Problem ve kavram ölçütlerine göre değerlendirme (hukuk paragrafları)', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme (hukuk paragrafları)', 'iki paragrafın gerekçelerini karşılaştırır ve ikincisinin gerekçesinin sonucu tek başına desteklemediğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme (hukuk paragrafları)', 'iki paragrafı felsefi terim ve metin bütünlüğü bakımından karşılaştırır']),
  task('evaluate', 'Paragraf: “Hukuk ve vicdan ilişkisindeki problem, hakkaniyetin kuralın önüne geçip geçemeyeceğidir. Pelin’e göre vicdan kuralın önüne geçebilir. Bu yüzden herkes kuralı kendi vicdanına göre uygulamalıdır.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki farklı öneri yazınız.',
    'Temellendirme zayıftır: vicdanın açık bir haksızlıkta kuralın önüne geçebilmesi, herkesin kuralı her durumda kendi vicdanına göre uygulaması gerektiğini göstermez; sonuç öncülden çıkmaz. Pelin de vicdanı yalnız açık haksızlık durumuna bağlar ve kuralın herkese aynı uygulanmasını kabul eder. Öneri 1: sonucu “vicdan yalnız açık haksızlık durumunda kuralın uygulanışını etkilemelidir” biçiminde değiştirmek. Öneri 2: Pelin’in koşulunu (açık haksızlık) açıkça yazıp sonucu ona bağlamak. Metni gerçekten geliştiren iki farklı öneri kabul edilir.',
    ['Temellendirmenin değerlendirilmesi (Pelin paragrafı)', 'gerekçenin sonucu desteklemediğini gösterir'],
    ['İlk önerinin yazılması (Pelin paragrafı)', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması (Pelin paragrafı)', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Hukukun kaynağının yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğunu konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (hukuk, kural, hak) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (hukukun kaynağının yazılı kurallar mı yoksa doğuştan haklar mı olduğu); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: hukuku geçerli kılan şey nedir? Görüş: yalnız yazılı olmak yetmez, çünkü temel hakları çiğneyen bir kural yazılı olsa da uyulmayı hak etmeyebilir. Karşı görüş (Nehir): geçerlilik adaletten ayrıdır. Yanıt: geçerlilik ile uyulmayı hak etmek ayrılabilir; bu durumda sorun, geçerli bir kurala uyma yükümlülüğünün temelinin ne olduğudur. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
  task('create', 'Hukuk ile vicdan arasındaki ilişkiyi, yani hakkaniyetin kuralın önüne geçip geçemeyeceğini konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (hukuk, hakkaniyet, vicdan) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (hakkaniyetin ya da vicdanın kuralın önüne geçip geçemeyeceği); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: hakkaniyet kuralın önüne geçebilir mi? Görüş: yalnız açık haksızlık durumunda, kuralın amacı gerçekleşmiyorsa geçebilir. Karşı görüş: vicdanlar farklıdır, uygulayıcı keyfî davranabilir. Yanıt: ölçüt kişisel vicdan değil kuralın duyurulmuş amacı olursa keyfîlik azalır; ancak amacın belirsiz olduğu durumlarda sorun sürer. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
];

export const grade11Unit6: Record<string, Focus[]> = {
  'FEL.11.6.1': [
    { context: lawPhil, focus: 'hukukun doğasına yönelik felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma hukukun kaynağının yazılı kurallar mı yoksa insanın doğuştan hakları mı olduğu sorusuna dayanır.', 'Tartışma hakkaniyet ve vicdanın kuralın önüne geçip geçemeyeceği sorusuna dayanır.'], inference: 'Öğrenci meclisi tartışması hukukun kaynağı ve hukuk ile vicdan ilişkisi sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Yazılı olmayan bir sınıf kuralına uymak zorunda olup olmadığı.', tasks: a1 },
    { context: lawPhil, focus: 'hukukun doğasına yönelik felsefi soru ve problemlerin toplumsal hayat ile ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki görüşler okul ve toplum yaşamındaki kuralların uygulanmasında da kullanılır.', 'Kuralın herkese aynı uygulanması ile durumun özelliğinin gözetilmesi arasında bir gerilim vardır.'], inference: 'Hukukun doğasına ilişkin felsefi sorular toplumsal yaşamdaki kural uygulamalarıyla ilişkilendirilerek değerlendirilebilir.', limit: 'Toplumsal örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Kütüphanede geç getirilen kitap için uygulanan aynı yasak.', tasks: b1 },
  ],
  'FEL.11.6.2': [
    { context: lawPhil, focus: 'hak ve özgürlüklerin hukuksal temellerinin çözümlenmesi', evidence: ['Üç görüşün her birinin öncülü ve sonucu vardır.', 'Her görüşün gerekçe yükü vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Kuralın herkese aynı uygulanmasından geçerli olduğu sonucuna geçiş.', tasks: a2 },
    { context: lawPhil, focus: 'temel hukuk sorunlarına yönelik görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir varsayıma dayanır ve itirazlara açıktır.'], inference: 'Öğrenci hukukun doğası için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Kural uygulanırken hakkaniyetin gözetilmesi üzerine bir argüman.', tasks: b2 },
    { context: lawPhil, focus: 'hukuk sorunlarına ilişkin felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'Hukukun kaynağının yazılı kurallar mı yoksa doğuştan haklar mı olduğu tartışması.', tasks: c2 },
  ],
};
