import type { Focus, Task } from './philosophy-early-units-2026.ts';
import { task, W } from './philosophy-grade11-units-2026.ts';

// FEL.11.5 — Hayatın Anlamı. Özgün tek vaka (düşünür adı, eser adı ve alıntı yok).
// ÖĞRETMEN ONAYI: vaka metni Aytekin tarafından onaylandı.
// Programın iki problemi tek vakada toplanır: mutluluk ve hayat ilişkisi (soru 1) ile varoluş ve kendi olma (soru 2).
// Üç ses: Kerem (mutluluk hayatın amacıdır; yükü: “mutlu ama boş” hayat ayrımını ve geçici haz ile mutluluk farkını açıklamak),
// Leyla (mutluluk yetmez, anlam kendimizden büyük bir işe emek vermekten gelir; yükü: o işin değerini neyin belirlediği, zararlı işe emeğin anlam sayılıp sayılmayacağı),
// Melih (anlam hazır verilmez, kendi seçimlerimle kurarım; yükü: her seçimin anlam kurup kurmadığı, çizilmiş yolu bilinçle benimsemenin de kendi seçimi olabileceği).
// Melih’in konumu bilerek tartışmalıdır: üçüncü görüş “ortası” olarak kolay seçilmesin (11.3 ve 11.4 dersi).
// HASSASİYET: yaş grubu ve konu gereği vaka ve görevler gündelik, düşük riskli seçimler üzerine kurulur (bölüm seçimi, gönüllülük, boş zaman).
// Ölüm, intihar, kendine zarar, depresyon ve umutsuzluk durumları örnek ya da senaryo olarak yer almaz; “ölüm” ve “umutsuzluk” anahtar kavramları bu yazılıda sınanmaz.
// Test (unit5-content) bu kapsamı kilitler. Öğrenciden “kendi hayatından” örnek isteyen görevler yalnız okul, aile, arkadaşlık gibi gündelik alanları açar.
// Kapsam dışı: belirli düşünürlerin görüşleri ve varoluşçuluğun tarihi, dinî ve ahiret temelli anlam yorumları, klinik kaygı ve ruh sağlığı tartışmaları.
// 11.5.1 → felsefi soru ve problemler (a açıklar, b hayatıyla ilişkilendirerek değerlendirir); 11.5.2 → görüş ve argümanlar (a çözümler, b oluşturur, c metin yazar).
// 11.5.2 c: yazım görevinin ölçütü, programın 7 ölçütlü 100 puanlık Felsefi Metin Yazımı anahtarının 32/32/36 gruplamasıdır (bkz. 11.1).
const meaningLife = 'Bir lisede mezuniyet öncesi “İyi bir hayat nedir?” başlıklı bir panel düzenleniyor. Üç öğrenci konuşuyor. Kerem: “İnsan mutlu olduğu ölçüde iyi yaşar. Mutlu olmayan bir hayatın başka neyle anlamlı olacağını anlamıyorum; mutluluk hayatın amacıdır.” Leyla: “Mutlu olmak yetmez. Gününü yalnız eğlenerek geçiren ve hiçbir şeye emek vermeyen biri mutlu olabilir, ama hayatını anlamlı bulmayabilir. Anlam, kendimizden büyük bir işe emek vermekten gelir; bu yorucu olsa bile.” Melih: “Anlam bize hazır verilmez; aile, okul ya da çevre bize bir hayat çizer. Hayatım ancak bu çizilmiş yolu bırakıp kendi seçimlerimle kurduğumda benim olur ve anlamlı olur.” Öğretmen, tartışmanın mutlu olmanın iyi bir hayat için yeterli olup olmadığına ve hayatın anlamının hazır bulunmasıyla mı yoksa kişinin kendi seçimleriyle mi kurulduğuna dayandığını belirtir.';

// ---------- FEL.11.5.1 a: felsefi soru ve problemleri açıklar ----------
const a1: Task[] = [
  task('understand', 'Öğretmenin belirttiği iki felsefi soruyu kendi cümlelerinizle yazınız ve her birinin neyi sorguladığını açıklayınız.',
    'Birinci soru: mutlu olmak iyi bir hayat için yeterli mi; bu soru mutluluğun tek başına iyi bir hayatı oluşturup oluşturmadığını, ayrıca başka bir şeye (anlama) ihtiyaç olup olmadığını sorgular. İkinci soru: hayatın anlamı hazır bulunur mu, yoksa kişinin kendi seçimleriyle mi kurulur; bu soru anlamın kaynağını, yani anlamın bize verilip verilmediğini ya da bizim tarafımızdan kurulup kurulmadığını sorgular.',
    ['Mutluluğun yeterliliği sorusunun açıklanması (hayatın anlamı)', 'mutlu olmanın iyi bir hayat için yeterli olup olmadığını sorguladığını belirtir'],
    ['Anlamın kaynağı sorusunun açıklanması (hayatın anlamı)', 'anlamın hazır bulunup bulunmadığını ya da kişinin seçimleriyle kurulup kurulmadığını sorguladığını belirtir'],
    ['Soruların anlam korunarak kendi cümlelerle yazılması (hayatın anlamı)', 'soruları metni kopyalamadan, anlamını bozmadan kendi cümleleriyle yazar']),
  task('understand', 'Kerem, Leyla ve Melih’in sözlerinin her birinin iyi bir hayatı anlamlı kılan şeyin ne olduğu konusunda nasıl bir cevap verdiğini belirtiniz.',
    'Kerem anlamlı ve iyi bir hayatı mutlulukla özdeşleştirir; mutluluğu hayatın amacı sayar. Leyla mutluluğun yetmediğini, anlamın kendimizden büyük bir işe emek vermekten geldiğini söyler. Melih anlamı kişinin kendi seçimleriyle kurduğu hayata bağlar; çizilmiş bir yolu izlemeyi anlam kaynağı saymaz.',
    ['Kerem’in cevabının belirlenmesi (hayatın anlamı)', 'Kerem’in anlamlı hayatı mutlulukla özdeşleştirdiğini belirtir'],
    ['Leyla’nın cevabının belirlenmesi (hayatın anlamı)', 'Leyla’nın anlamı kendimizden büyük bir işe emekle ilişkilendirdiğini belirtir'],
    ['Melih’in cevabının belirlenmesi (hayatın anlamı)', 'Melih’in anlamı kişinin kendi seçimleriyle kurduğu hayata bağladığını belirtir']),
  task('apply', 'Şu durumda öğretmenin belirttiği iki sorudan hangisinin ortaya çıktığını gerekçesiyle yazınız: Bir öğrenci hafta sonlarını yalnız hoşuna giden şeylerle geçirir ve kendini mutlu hisseder; arkadaşı “Peki bunların hayatına bir anlam kattığını düşünüyor musun?” diye sorar.',
    'Birinci soru ortaya çıkar: mutlu olmak iyi bir hayat için yeterli mi. Öğrenci mutludur; arkadaşı ise mutluluk ile anlamı birbirinden ayırarak mutluluğun yetip yetmediğini sorar. İkinci soru (anlamın hazır bulunup bulunmadığı ya da kişinin seçimleriyle kurulup kurulmadığı) bu durumda ancak öğrencinin bu hoşuna giden şeyleri kendi seçimiyle mi yaptığı ya da anlamı nereden aldığı sorulursa gündeme gelir.',
    ['Durumdaki sorunun belirlenmesi (hayatın anlamı)', 'durumda mutlu olmanın iyi bir hayat için yeterli olup olmadığı sorusunun ortaya çıktığını belirtir'],
    ['Sorunun durumla ilişkilendirilmesi (hayatın anlamı)', 'öğrencinin mutluluğunu ve arkadaşının anlam sorusunu ayırır'],
    ['Diğer sorunun ayrıca ele alınması (hayatın anlamı)', 'ikinci sorunun bu durumda neden öne çıkmadığını ya da ne zaman çıkacağını belirtir']),
  task('apply', '“Hayatın anlamı hazır bulunur mu, yoksa kişinin kendi seçimleriyle mi kurulur?” sorusunu şu duruma uygulayınız: Bir öğrenci ailesinin istediği bölümü seçmek üzeredir; kendi ilgisi ise başka bir alandadır.',
    'Ailenin istediği bölüm, çevrenin çizdiği hazır bir yoldur; öğrencinin kendi ilgisi ise kendi seçimiyle kuracağı yola işaret eder. Soru, öğrencinin hayatına anlamı çizilmiş yoldan mı alacağı yoksa kendi seçimiyle mi kuracağıdır. Melih çizilmiş yolu bırakıp kendi seçimini öne çıkarır; ancak ailenin önerisini öğrencinin kendisinin de isteyebileceği unutulmamalıdır.',
    ['Çizilmiş yolun belirtilmesi (hayatın anlamı)', 'ailenin istediği bölümü çevrenin çizdiği hazır yol olarak belirtir'],
    ['Kendi seçiminin belirtilmesi (hayatın anlamı)', 'öğrencinin kendi ilgisini kendi seçimiyle kuracağı yol olarak belirtir'],
    ['Sorunun duruma bağlanması (hayatın anlamı)', 'durumun anlamın hazır bulunup bulunmadığı sorusunu nasıl gündeme getirdiğini belirtir']),
  task('analyze', 'Kerem “Mutlu olmayan bir hayatın başka neyle anlamlı olacağını anlamıyorum” der. Bu sözün hangi varsayıma dayandığını ve hangi felsefi soruyu görünmez kıldığını çözümleyiniz.',
    'Söz, bir hayatı anlamlı kılabilecek tek şeyin mutluluk olduğunu varsayar. Bu varsayım, mutlu olmayan ama anlamlı bir hayatın ya da mutlu olan ama anlamsız bir hayatın mümkün olup olmadığı sorusunu görünmez kılar. Leyla’nın itirazı tam bu alana yöneliktir.',
    ['Kerem’in varsayımının gösterilmesi (hayatın anlamı)', 'anlamı kılabilecek tek şeyin mutluluk olduğu varsayımını gösterir'],
    ['Görünmez kalan sorunun belirlenmesi (hayatın anlamı)', 'mutluluk ile anlamın ayrılıp ayrılmayacağı sorusunun görünmez kaldığını belirtir'],
    ['Leyla’nın itirazıyla ilişkilendirilmesi (hayatın anlamı)', 'Leyla’nın itirazının bu soruya yöneldiğini gösterir']),
  task('analyze', 'Melih “Anlam bize hazır verilmez” der. “Hazır verilmez”in iki farklı anlama gelebileceğini gösteriniz ve sözün hangi felsefi sorunu doğurduğunu çözümleyiniz.',
    '“Hazır verilmez”, başkalarının bize hazır bir anlam sunamayacağı anlamına gelebilir; ya da sunulan anlamı benimsesek bile onun bizim sayılmayacağı anlamına gelebilir. Birincisinde, sunulan anlamı bilinçle benimsemek mümkündür; ikincisinde mümkün değildir. Doğan sorun: kendimize ait olanla çevreden gelen anlamı nasıl ayıracağımız.',
    ['İki anlamın ayrılması (hayatın anlamı)', 'başkasının anlam sunamaması ile sunulanın benimsense bile bizim sayılmaması anlamlarını ayırır'],
    ['Her anlamın sonucunun ele alınması (hayatın anlamı)', 'her anlam için sunulan anlamın benimsenip benimsenemeyeceğini ayrı ayrı belirtir'],
    ['Doğan sorunun belirtilmesi (hayatın anlamı)', 'kendimize ait olanla çevreden gelenin nasıl ayrılacağı sorununu gösterir']),
  task('evaluate', 'Leyla’nın “Anlam, kendimizden büyük bir işe emek vermekten gelir” sözünün bir güçlü ve bir zayıf yanını değerlendiriniz.',
    'Güçlü yan: mutlu ama boş hissedilen bir hayat ile emek verilen bir hayat arasındaki farkı gösterir ve anlamı yalnız hoşa giden şeylere indirgemez. Zayıf yan: kendimizden büyük işin değerli olduğunu neyin belirlediğini söylemez; zararlı bir işe emek vermek de anlam sayılacak mıdır sorusu açıkta kalır. Güçlü ve zayıf yanı Leyla’nın sözüne dayanarak gerekçeleyen her değerlendirme kabul edilir.',
    ['Güçlü yanın belirtilmesi (Leyla)', 'mutluluk ile emek arasındaki farkı gösterdiğini ya da anlamı hoşa gitmeye indirgemediğini belirtir'],
    ['Zayıf yanın belirtilmesi (Leyla)', 'işin değerini neyin belirlediğinin söylenmediğini ya da zararlı işe emeğin sorun olduğunu belirtir'],
    ['Değerlendirmenin sözle ilişkilendirilmesi (Leyla)', 'güçlü ve zayıf yanı Leyla’nın sözüne dayanarak gerekçelendirir']),
  task('evaluate', 'Metindeki sorunun “Mutlu olmak iyi bir hayat için yeterli mi?” biçiminde sorulmasının neden felsefi bir soru olduğunu, olgusal bir soruyla karşılaştırarak değerlendiriniz.',
    'Soru felsefidir. “Bu okulda kaç öğrenci kendini mutlu hissediyor?” gibi olgusal bir soru anket yaparak sayılabilir. “Mutlu olmak iyi bir hayat için yeterli mi?” sorusu ise sayımla cevaplanmaz; “mutluluk”, “iyi hayat” ve “anlam” kavramlarının ne anlama geldiğine ve neyin ölçüt sayılacağına bağlıdır. Her görüş başka bir ölçütten yola çıkar: mutluluk, emek, kendi seçim.',
    ['Olgusal sorunun ayrılması (hayatın anlamı)', 'olgusal bir soruyu sayarak ya da ölçerek cevaplanan bir soru olarak gösterir'],
    ['Felsefi sorunun niteliğinin gösterilmesi (hayatın anlamı)', 'sorunun sayımla değil kavramlar ve ölçütler üzerinden cevaplandığını belirtir'],
    ['Karşılaştırmanın gerekçelendirilmesi (hayatın anlamı)', 'iki soru arasındaki farkı gerekçesiyle gösterir']),
  task('create', 'Metindekilerden farklı, mutluluk ya da anlamla ilgili kısa bir durum yazınız ve bu durumda hangi felsefi sorunun (mutluluğun yeterliliği, anlamın kaynağı gibi) bulunduğunu belirtiniz.',
    'Örnek durum: Bir öğrenci kolay ve eğlenceli bulduğu kulübe girmek yerine, zor ama okul için yararlı bir etkinliğe emek vermeyi seçer. Felsefi sorun: iyi bir hayat için hoşa gitmenin mi yoksa anlamlı bir işe emeğin mi ölçüt olduğu. Durumu ve sorunu tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün ve konuyla ilgili bir durumun yazılması (hayatın anlamı)', 'metindekilerden farklı, mutluluk ya da anlam konusunu içeren kısa bir durum yazar; yalnız soru yazmak bu ölçütü karşılamaz'],
    ['Durumdaki felsefi sorunun belirtilmesi (hayatın anlamı)', 'durumda mutluluğun yeterliliği ya da anlamın kaynağı sorusunun nerede ortaya çıktığını belirtir'],
    ['Durum ile sorunun tutarlılığı (hayatın anlamı)', 'yazılan durum ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('create', 'Tartışmaya katılmayan dördüncü bir öğrenci için hayatın anlamıyla ilgili yeni bir felsefi soru yazınız ve bu sorunun üç öğrenciden hangisinin görüşüyle en çok ilgili olduğunu belirtiniz.',
    'Örnek soru: Başkalarına yararlı olmak, kişinin kendi anlamını kurmasının bir yolu mudur? Bu soru en çok Leyla’nın görüşüyle ilgilidir; çünkü anlamı kendimizden büyük bir işe bağlar. Yeni ve felsefi nitelikte olan, öğrenciyle ilişkisini gerekçelendiren her çalışma kabul edilir.',
    ['Yeni bir felsefi sorunun yazılması (hayatın anlamı)', 'metindeki iki sorudan farklı, hayatın anlamıyla ilgili bir felsefi soru yazar'],
    ['Sorunun bir öğrenciyle ilişkilendirilmesi (hayatın anlamı)', 'sorunun Kerem, Leyla ya da Melih’ten birinin görüşüyle ilgisini belirtir'],
    ['İlişkinin gerekçelendirilmesi (hayatın anlamı)', 'seçtiği öğrenciyle ilişkiyi gerekçeyle gösterir']),
];

// ---------- FEL.11.5.1 b: hayatıyla ilişkilendirerek değerlendirir ----------
const b1: Task[] = [
  task('understand', 'Metindeki tartışmanın gündelik yaşamdaki bir karşılığını bir örnekle belirtiniz.',
    'Örnek: bir öğrencinin hangi bölümü seçeceğini düşünürken “Beni mutlu eder mi, yoksa bana bir anlam mı katar?” diye sorması. Bu, tartışmadaki mutluluk ve anlam sorularının gündelik bir karşılığıdır. Gündelik bir örnek verip tartışmayla ilişkisini gösteren her çalışma kabul edilir.',
    ['Gündelik örneğin verilmesi (hayatın anlamı)', 'gündelik yaşamdan bir örnek verir'],
    ['Örneğin tartışmaya bağlanması (hayatın anlamı)', 'örneğin mutluluğun yeterliliği ya da anlamın kaynağı tartışmasıyla ilişkisini belirtir'],
    ['Örneğin açık yazılması (hayatın anlamı)', 'örneği başkasının anlayabileceği açıklıkta yazar']),
  task('understand', 'Kerem, Leyla ve Melih’in görüşlerinden birinin günlük yaşamda hangi tutumlara yol açabileceğini açıklayınız.',
    'Kerem: kararlarında “Bu beni mutlu eder mi?” sorusunu öne çıkarmak. Leyla: yorucu ama kendinden büyük bir işe, örneğin bir gönüllülük etkinliğine emek vermeye istekli olmak. Melih: “Bunu ben mi istiyorum, yoksa bana mı öğretildi?” diye sormak. Seçilen görüşün tutumunu doğru bağlayan yanıt kabul edilir.',
    ['Bir görüşün seçilmesi ve belirtilmesi (hayatın anlamı)', 'üç görüşten birini doğru biçimde belirtir'],
    ['Günlük tutumun gösterilmesi (hayatın anlamı)', 'seçilen görüşün günlük yaşamdaki bir tutuma nasıl yol açabileceğini gösterir'],
    ['Tutumun görüşle ilişkilendirilmesi (hayatın anlamı)', 'tutum ile görüş arasındaki bağı açıklar']),
  task('apply', 'Kendi hayatınızdan (okul, aile, arkadaşlık) bir seçim ya da etkinlik (bir kulüp, bir ders seçimi, bir boş zaman uğraşı gibi) seçiniz ve metindeki iki görüşün bu duruma nasıl yaklaşacağını yazınız.',
    'Örnek: bir kulübe katılma kararı. Kerem, kulübün kişiyi mutlu edip etmediğine bakar. Leyla, kulübün kendinden büyük bir amaca (okula ya da başkalarına yararlı bir işe) hizmet edip etmediğine bakar. Seçilen durumu tanıtan ve iki görüşün yaklaşımını tutarlı gösteren her çalışma kabul edilir.',
    ['Durumun seçilmesi ve tanıtılması (hayatın anlamı)', 'kendi hayatından gündelik bir seçim ya da etkinlik seçer ve tanıtır'],
    ['Birinci görüşün yaklaşımının yazılması (hayatın anlamı)', 'metindeki bir görüşün duruma yaklaşımını doğru yazar'],
    ['İkinci görüşün yaklaşımının yazılması (hayatın anlamı)', 'metindeki ikinci bir görüşün duruma yaklaşımını doğru ve birinciden ayırarak yazar']),
  task('apply', 'Şu örneğe metindeki üç görüşün nasıl yaklaşacağını yazınız: Bir öğrenci haftada üç gün hayvan barınağında gönüllü çalışıyor; yorgun dönüyor ama “İyi ki yapıyorum” diyor.',
    'Kerem: öğrenci yorgun olsa da bundan mutluluk duyduğu için bu hayatı iyi bulur. Leyla: kendinden büyük bir işe emek verdiği için öğrencinin hayatı anlam taşır; yorgunluk bunu azaltmaz. Melih: önemli olan, öğrencinin bu işi kendi seçimiyle yapıp yapmadığıdır; ailesi ya da çevresi yönlendirdiği için yapıyorsa anlam kendi kurduğu bir anlam olmayabilir.',
    ['Kerem’in yaklaşımının yazılması (hayatın anlamı)', 'Kerem’in öğrencinin mutluluğuna bakacağını belirtir'],
    ['Leyla’nın yaklaşımının yazılması (hayatın anlamı)', 'Leyla’nın emek verilen işe bakacağını belirtir'],
    ['Melih’in yaklaşımının yazılması (hayatın anlamı)', 'Melih’in işin öğrencinin kendi seçimi olup olmadığına bakacağını belirtir']),
  task('analyze', 'Bir hafta sonunu yalnız eğlenerek geçirmek ile aynı hafta sonunu bir okul projesi için çalışarak geçirmek arasındaki ilişkiyi, mutluluk ve anlam ayrımı bakımından çözümleyiniz.',
    'Eğlenerek geçirilen hafta sonu hoşa gider ve mutluluk verebilir; proje için çalışmak yorucu olabilir ama kendinden büyük bir iş için emek verme duygusu taşır. Fark, mutluluğun kısa süreli hoşlanmayla, anlamın ise emek ve amaçla ilişkilendirilmesidir. İkisi birbirini dışlamaz; proje çalışması da mutluluk verebilir.',
    ['Eğlencenin niteliğinin gösterilmesi (hayatın anlamı)', 'eğlenmenin hoşa gitme ve mutluluk bakımından değerini gösterir'],
    ['Emeğin niteliğinin gösterilmesi (hayatın anlamı)', 'proje için çalışmanın emek ve amaç bakımından değerini gösterir'],
    ['İkisi arasındaki ilişkinin çözümlenmesi (hayatın anlamı)', 'ikisinin birbirini dışlamadığını ve mutluluk ile anlam ayrımını gösterir']),
  task('analyze', 'Bir mesleğe ailenin isteğiyle girmek ile kendi isteğiyle girmek arasındaki ilişkiyi, anlamın hazır bulunması ya da kişinin kendi seçimiyle kurulması bakımından çözümleyiniz.',
    'Ailenin isteğiyle girilen meslek, çevrenin çizdiği hazır bir yol gibi görünür; kendi isteğiyle girilen meslek ise kişinin seçimiyle kurulmuş bir yol gibi. Ancak ayrım kesin değildir: kişi ailesinin önerdiği mesleği bilinçle benimseyebilir, o zaman bu da onun seçimi olur. Çözülmesi gereken sorun, bir seçimin gerçekten kişiye ait olup olmadığının nasıl anlaşılacağıdır.',
    ['Hazır yolun gösterilmesi (hayatın anlamı)', 'ailenin isteğiyle girilen mesleği çevrenin çizdiği yol olarak gösterir'],
    ['Kendi seçiminin gösterilmesi (hayatın anlamı)', 'kendi isteğiyle girilen mesleği kişinin kurduğu yol olarak gösterir'],
    ['Ayrımın sınırının çözümlenmesi (hayatın anlamı)', 'çizilmiş yolun bilinçle benimsenebileceğini ve ayrımın kesin olmadığını gösterir']),
  task('evaluate', 'Kerem’in “Mutluluk hayatın amacıdır” görüşünün günlük yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: kişinin kendi iyiliğine ve hoşlandığı şeylere önem vermesini sağlar; kendini ihmal etmesini önler. Sakınca: kısa süreli hoşa gidenin peşine düşen kişi, uzun vadede önem verdiği işlerden vazgeçebilir; ayrıca mutluluğun ne olduğu belirsiz kaldığında görüş yol gösteremez. Yarar ve sakıncayı görüşe dayanarak gerekçelendiren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Kerem)', 'görüşün günlük yaşamda sağlayabileceği bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Kerem)', 'kısa süreli hoşa gidene yönelme ya da mutluluk kavramının belirsizliği gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşle ilişkilendirilmesi (Kerem)', 'yarar ve sakıncayı Kerem’in görüşüne dayanarak gerekçelendirir']),
  task('evaluate', 'Melih’in “Anlam bize hazır verilmez” görüşünün günlük yaşamda yol açabileceği bir yarar ve bir sakınca belirterek görüşü değerlendiriniz.',
    'Yarar: kişiyi kendi isteklerini ve değerlerini sorgulamaya, hazır kalıpları düşünmeden benimsememeye yöneltir. Sakınca: çevreden gelen her öneriyi kendi olmaya engel sayarsa, başkalarının deneyiminden yararlanmayı ve onlarla bağları gereksiz yere reddedebilir; ayrıca kendi seçimin çevreden bağımsız olup olmadığı belirsizdir. Yarar ve sakıncayı görüşe dayanarak gerekçelendiren her değerlendirme kabul edilir.',
    ['Yararın belirtilmesi (Melih)', 'görüşün günlük yaşamda sağlayabileceği bir yararı belirtir'],
    ['Sakıncanın belirtilmesi (Melih)', 'çevreden gelen önerileri gereksiz reddetme ya da seçimin bağımsızlığının belirsizliği gibi bir sakıncayı belirtir'],
    ['Değerlendirmenin görüşle ilişkilendirilmesi (Melih)', 'yarar ve sakıncayı Melih’in görüşüne dayanarak gerekçelendirir']),
  task('create', 'Üç görüşten biriyle ilgili, bir öğrencinin gündelik yaşamda karşılaşabileceği kısa bir karar durumu yazınız ve o görüşün bu duruma nasıl yaklaşacağını belirtiniz.',
    'Örnek durum: Bir öğrenci, arkadaşlarının çoğunun seçtiği dersi mi yoksa kendi ilgisini çeken dersi mi seçeceğine karar vermeye çalışır. Melih’in görüşü bu durumda öğrencinin çevresinin çizdiği yolu değil, kendi seçimini öne çıkarmasını gerektirir. Durumu ve yaklaşımı tutarlı kuran özgün her çalışma kabul edilir.',
    ['Özgün bir karar durumunun yazılması (hayatın anlamı)', 'bir öğrencinin gündelik yaşamda karşılaşabileceği kısa bir karar durumu yazar'],
    ['Görüşün seçilmesi ve belirtilmesi (hayatın anlamı)', 'durumla ilgili bir görüşü belirtir'],
    ['Görüşün duruma uygulanması (hayatın anlamı)', 'seçilen görüşün duruma nasıl yaklaşacağını tutarlı biçimde yazar']),
  task('create', 'Mutluluk ile anlamın günlük yaşamda birbirini nasıl tamamlayabileceğini ya da birbirinden ayrılabileceğini gösteren kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Bütün gün istediğim gibi vakit geçirdim, çok mutluydum.” İkinci kişi: “Peki akşam bir şey yaptığın hissi var mı?” Diyalog, mutluluk ile anlamın aynı şey olmayabileceğini, ama birbirini dışlamadığını gösterir. Mutluluk ile anlam arasındaki ilişkiyi tutarlı gösteren özgün her diyalog kabul edilir.',
    ['Diyalogun konuya uygunluğu (hayatın anlamı)', 'diyalogun mutluluk ile anlam arasındaki ilişkiyi konu aldığı görülür'],
    ['Tamamlama ya da ayrılmanın gösterilmesi (hayatın anlamı)', 'mutluluk ile anlamın birbirini tamamlama ya da ayrılma ilişkisini diyalogda gösterir'],
    ['Diyalogun tutarlı kurulması (hayatın anlamı)', 'konuşmacıların sözlerini birbirine bağlı ve tutarlı kurar']),
];

// ---------- FEL.11.5.2 a: felsefi argümanları çözümler ----------
const a2: Task[] = [
  task('understand', 'Kerem’in sözünde öncülleri ve sonucu ayırarak yazınız.',
    'Öncül: insan mutlu olduğu ölçüde iyi yaşar. Öncül: mutlu olmayan bir hayat başka bir şeyle anlamlı olamaz. Sonuç: mutluluk hayatın amacıdır.',
    ['Birinci öncülün belirlenmesi (Kerem)', 'insanın mutlu olduğu ölçüde iyi yaşadığı öncülünü belirtir'],
    ['İkinci öncülün belirlenmesi (Kerem)', 'mutlu olmayan hayatın başka şeyle anlamlı olamayacağı öncülünü belirtir'],
    ['Sonucun belirlenmesi (Kerem)', 'sonucu mutluluğun hayatın amacı olduğu olarak belirtir']),
  task('understand', 'Leyla’nın sözünde ileri sürdüğü iddiayı ve onu destekleyen gerekçeyi ayırarak yazınız.',
    'İddia: mutlu olmak yetmez; anlam kendimizden büyük bir işe emek vermekten gelir. Gerekçe: gününü yalnız eğlenerek geçiren ve hiçbir şeye emek vermeyen biri mutlu olabilir, ama hayatını anlamlı bulmayabilir.',
    ['İddianın belirlenmesi (Leyla)', 'mutluluğun yetmediğini ve anlamın emekten geldiğini belirtir'],
    ['Gerekçenin belirlenmesi (Leyla)', 'eğlenerek geçen ve emek verilmeyen hayatın mutlu ama anlamsız bulunabileceği gerekçesini belirtir'],
    ['İddia ile gerekçenin ayrılması (Leyla)', 'iddia ile gerekçeyi karıştırmadan ayrı ayrı yazar']),
  task('apply', 'Paragraf: “Hayatın anlamı tartışmasında temel soru, anlamın hazır bulunup bulunmadığıdır. Melih’e göre ……… . Bu nedenle ………” Boş bırakılan yerleri Melih’in görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: anlam bize hazır verilmez; aile, okul ya da çevre bize bir hayat çizer, ama bu çizilmiş yol kendiliğinden bizim olmaz. Boşluk 2: hayat ancak çizilmiş yol bırakılıp kişinin kendi seçimleriyle kurulduğunda kişiye ait ve anlamlı olur. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Melih)', 'Melih’in görüşünü doğru biçimde (anlamın hazır verilmemesi, çizilmiş yol) tamamlar'],
    ['İkinci boşluğun tamamlanması (Melih)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Melih)', 'tamamlanan cümleler ilk cümleyle tutarlı bir bütün oluşturur']),
  task('apply', 'Leyla’nın görüşünü “iddia – gerekçe – sonuç” sırasıyla üç cümlelik bir akıl yürütme hâline getiriniz.',
    'Örnek: İddia: mutlu olmak iyi bir hayat için yeterli değildir. Gerekçe: yalnız eğlenerek geçen ve emek verilmeyen bir hayat mutlu olsa da anlamlı bulunmayabilir. Sonuç: bu nedenle anlam, kendimizden büyük bir işe emek vermekle ilişkilidir. Üç öğeyi sırayla ve doğru kuran her akıl yürütme kabul edilir.',
    ['İddianın yazılması (Leyla)', 'görüşün iddiasını açıkça yazar'],
    ['Gerekçenin yazılması (Leyla)', 'iddiayı destekleyen gerekçeyi yazar'],
    ['Sonucun gerekçeden çıkarılması (Leyla)', 'sonucu iddia ve gerekçeyle tutarlı biçimde yazar']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Kerem haklıdır; çünkü herkes mutlu olmak ister.” Bu argümandaki temellendirme sorununu belirtiniz.',
    'Gerekçe, herkesin mutlu olmak istemesine (isteğin yaygınlığına) dayanır. Bir şeyi herkesin istemesi, onun hayatın amacı ya da anlamı olduğunu göstermez; isteme ile değer arasında boşluk vardır. Ayrıca Kerem’in kendi gerekçesi (mutlu olmayan hayat başka şeyle anlamlı olamaz) bu argümanla desteklenmemektedir.',
    ['İsteğin yaygınlığına başvurunun gösterilmesi (hayatın anlamı)', 'gerekçenin herkesin istemesine dayandığını belirtir'],
    ['İsteme ile değer arasındaki boşluğun gösterilmesi (hayatın anlamı)', 'bir şeyin istenmesinin onun amaç ya da anlam olduğunu göstermediğini belirtir'],
    ['Kerem’in gerekçesinin ayrıca gösterilmesi (hayatın anlamı)', 'Kerem’in asıl gerekçesinin bu argümanda yer almadığını belirtir']),
  task('analyze', 'Leyla’nın argümanındaki örtük bir öncülü belirleyiniz ve bu öncüle yöneltilebilecek bir itirazı yazınız.',
    'Örtük öncül: eğlenerek geçen bir hayat anlam taşıyamaz ya da kendimizden büyük bir işe emek vermek her durumda anlam kazandırır. İtiraz: bir arkadaşlık ya da sevilen biriyle geçirilen eğlenceli zaman da anlam taşıyabilir; ayrıca kendimizden büyük görünen bir işe emek vermek, iş zararlıysa anlam kazandırmayabilir. Öncülü doğru belirleyen ve gerçek bir itiraz yazan eşdeğer yanıtlar kabul edilir.',
    ['Örtük öncülün belirlenmesi (Leyla)', 'eğlencenin anlam taşıyamayacağı ya da emeğin her durumda anlam kazandıracağı öncülünü belirtir'],
    ['İtirazın yazılması (Leyla)', 'öncüle yönelen gerçek bir itiraz yazar'],
    ['İtirazın öncülle ilişkilendirilmesi (Leyla)', 'itirazın hangi öncülü zayıflattığını gösterir']),
  task('evaluate', 'Kerem, Leyla ve Melih’in argümanlarından hangisinin gerekçe yükünün en ağır olduğunu değerlendiriniz; seçiminizi gerekçelendiriniz.',
    'Tek doğru seçim yoktur; her görüşün bir yükü vardır. Kerem: “mutlu ama boş” hayat ayrımını açıklamak ve geçici hoşlanma ile mutluluğu ayırmak zorundadır. Leyla: kendimizden büyük işin değerini neyin belirlediğini ve zararlı bir işe emeğin anlam sayılıp sayılmayacağını göstermelidir. Melih: her seçimin anlam kurup kurmadığını ve çizilmiş yolu bilinçle benimsemenin de kendi seçimi olup olmadığını göstermelidir. Seçimini bu yüklerden biriyle gerekçelendiren her yanıt kabul edilir.',
    ['Seçilen görüşün belirtilmesi (hayatın anlamı)', 'üç görüşten birini gerekçe yükü en ağır olan olarak seçer'],
    ['Gerekçe yükünün gösterilmesi (hayatın anlamı)', 'seçilen görüşün neyi göstermek zorunda olduğunu belirtir'],
    ['Seçimin diğer görüşlerle karşılaştırılması (hayatın anlamı)', 'diğer iki görüşün yüküyle karşılaştırarak seçimini gerekçelendirir']),
  task('evaluate', 'Melih’in “Hayatım ancak çizilmiş yolu bırakıp kendi seçimlerimle kurduğumda benim olur” sonucunun öncüllerinden çıkıp çıkmadığını değerlendiriniz.',
    'Sonuç öncüllerden tam çıkmaz. Öncül, anlamın bize hazır verilmediğini söyler; sonuç ise hayatın ancak çizilmiş yol bırakılırsa kişiye ait olacağını söyler. Hazır verilmemesi, çizilmiş yolun bırakılmasını gerektirmez: kişi çevrenin çizdiği yolu bilinçle benimseyebilir ve bu da onun seçimi olabilir. Sonuç gerekçelendirilmeden kurulmuştur; bu, görüşün yanlış olduğunu göstermez.',
    ['Öncül ve sonucun ayrılması (Melih)', 'hazır verilmemesi öncülü ile çizilmiş yolun bırakılması sonucunu ayırır'],
    ['Geçişin gerekçelendirilmediğinin gösterilmesi (Melih)', 'çizilmiş yolun bilinçle benimsenebileceğini ve sonucun öncülden çıkmadığını belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (Melih)', 'sonucun çıkmamasının görüşün yanlışlığını göstermediğini belirtir']),
  task('create', 'Leyla’nın argümanını güçlendirecek bir ek öncül yazınız ve bu öncülün hangi itiraza karşı işe yaradığını belirtiniz.',
    'Örnek ek öncül: kendimizden büyük bir işe emek vermek, kişinin çabasının kendi dışındaki bir amaca bağlanmasını sağlar ve bu bağ hayatı değerli kılar. Bu öncül, “eğlenceli zaman da anlam taşıyabilir” itirazına karşı işe yarar; çünkü anlamı yalnız zevke değil, çabanın bir amaca bağlanmasına dayandırır. Leyla’nın argümanını gerçekten güçlendiren ve itirazla ilişkilendirilen eşdeğer öncüller kabul edilir.',
    ['Ek öncülün yazılması (Leyla)', 'Leyla’nın argümanına eklenebilecek bir öncül yazar'],
    ['Öncülün argümanı güçlendirmesi (Leyla)', 'öncülün argümanı nasıl güçlendirdiğini gösterir'],
    ['Karşı çıkılan itirazın belirtilmesi (Leyla)', 'öncülün hangi itiraza karşı işe yaradığını belirtir']),
  task('create', 'Bir gerekçe ve bu gerekçeye yönelen olası bir itirazı yanıtlayan, mutluluk ve anlam konulu kısa bir diyalog yazınız.',
    'Örnek: Birinci kişi: “Mutlu olduğum sürece hayatım iyidir.” İkinci kişi: “Mutlu olmak yetmeyebilir; bir iş için emek verince hayatın daha anlamlı geliyor.” Birinci kişi: “Emek vermek de beni mutlu ediyorsa ikisi aynı şey olmuyor mu?” Gerekçeyi, itirazı ve yanıtı tutarlı kuran özgün her diyalog kabul edilir.',
    ['Gerekçenin diyalogda yer alması (hayatın anlamı)', 'diyalogda mutluluk ve anlamla ilgili bir gerekçe verir'],
    ['İtirazın diyalogda yer alması (hayatın anlamı)', 'gerekçeye yönelen gerçek bir itiraz yazar'],
    ['İtirazın yanıtlanması (hayatın anlamı)', 'itiraza gerekçeli bir yanıt verir']),
];

// ---------- FEL.11.5.2 b: görüş ve argüman oluşturur ----------
const b2: Task[] = [
  task('understand', 'Bir görüşü argümana dönüştürmek için nelerin gerektiğini mutluluk ve anlam tartışmasından bir örnekle açıklayınız.',
    'Bir görüşün argümana dönüşmesi için öncüllerin (gerekçelerin) ve onlardan çıkan bir sonucun açıkça yazılması gerekir. Örnek: görüş “mutluluk yetmez”; öncül: emek vermeyen ama mutlu olan kişi hayatını anlamlı bulmayabilir; sonuç: mutluluk iyi bir hayat için tek başına yeterli değildir. Öncül ve sonuç ilişkisini örnekle gösteren her açıklama kabul edilir.',
    ['Gerekenlerin belirtilmesi (hayatın anlamı)', 'görüşü argümana dönüştürmek için öncül ve sonuç gerektiğini belirtir'],
    ['Örneğin verilmesi (hayatın anlamı)', 'mutluluk ve anlam tartışmasından bir örnek verir'],
    ['Örnekle açıklamanın ilişkilendirilmesi (hayatın anlamı)', 'örnekte öncül ve sonuç ilişkisini gösterir']),
  task('understand', 'Hayatın anlamı konusunda kendi görüşünüzü bir cümleyle yazınız ve görüşünüzün hangi felsefi soruya cevap olduğunu belirtiniz.',
    'Örnek: “Anlam, hem kendi seçimimizden hem de başkalarıyla kurduğumuz bağlardan oluşur.” Bu görüş, anlamın hazır bulunup bulunmadığı ya da kişinin kendi seçimleriyle kurulup kurulmadığı sorusuna cevaptır. Görüşü açık yazan ve soruyla doğru ilişkilendiren her çalışma kabul edilir.',
    ['Görüşün yazılması (hayatın anlamı)', 'hayatın anlamı konusunda bir görüşü bir cümleyle yazar'],
    ['Felsefi sorunun belirtilmesi (hayatın anlamı)', 'görüşün hangi felsefi soruya cevap olduğunu belirtir'],
    ['Görüş ile sorunun uyumu (hayatın anlamı)', 'yazılan görüş ile belirtilen sorunun birbirine uyduğunu gösterir']),
  task('apply', 'Hayatın anlamı konusunda bir görüş seçiniz ve bu görüşü bir ilke, bir durum bilgisi ve sonuçtan oluşan argüman biçiminde yazınız.',
    'Örnek: Görüş: anlam, kendimizden büyük bir işe emek vermekten gelir. İlke: kişinin çabasını kendi dışındaki bir amaca bağlaması hayatı değerli kılar. Durum: bir öğrenci okul gazetesini çıkarmak için bir yıl emek vermiştir. Sonuç: bu emek öğrencinin hayatına anlam katmıştır. İlke, durum ve sonucu tutarlı kuran her argüman kabul edilir.',
    ['İlkenin yazılması (hayatın anlamı)', 'seçtiği görüşe uygun bir ilke yazar'],
    ['Durum bilgisinin yazılması (hayatın anlamı)', 'ilkenin uygulandığı somut bir durum bilgisi yazar'],
    ['Sonucun ilkeyle tutarlı çıkarılması (hayatın anlamı)', 'sonucun ilkeden ve durumdan tutarlı biçimde çıktığını gösterir']),
  task('apply', '“Hayat ancak kişinin kendi seçimleriyle kurulduğunda ona ait olur” ilkesinden yola çıkarak, bir öğrencinin kulüp seçerken arkadaşlarının tercihini mi yoksa kendi ilgisini mi izleyeceği durumu için bir argüman kurunuz.',
    'Örnek: İlke: hayat ancak kişinin kendi seçimleriyle kurulduğunda ona ait olur. Durum: öğrenci arkadaşlarının tercih ettiği kulüp yerine kendi ilgisini çeken kulübü seçebilir. Sonuç: öğrencinin hayatına ait bir anlam kurması için kendi ilgisini izlemesi gerekir. İlkeyi duruma uygulayan ve sonucu tutarlı çıkaran her argüman kabul edilir.',
    ['İlkenin duruma uygulanması (hayatın anlamı)', 'verilen ilkeyi öğrencinin kulüp seçimi durumuna uygular'],
    ['Durum bilgisinin kullanılması (hayatın anlamı)', 'durumdan somut bir bilgi kullanır'],
    ['Sonucun tutarlı çıkarılması (hayatın anlamı)', 'sonucu ilkeden ve durumdan tutarlı biçimde çıkarır']),
  task('analyze', 'Hayatın anlamı konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümanın dayandığı varsayımı ve bu varsayıma yöneltilebilecek güçlü bir itirazı çözümleyiniz; itirazın neden güçlü olduğunu açıklayınız.',
    'Örnek: Öncül: mutluluk kısa süreli hoşlanmayı da kapsar. Öncül: kısa süreli hoşlanma hayata anlam kazandırmaz. Sonuç: mutluluk, anlamlı bir hayat için tek başına yeterli değildir. Varsayım: mutluluk ile hoşlanma aynı şeydir. İtiraz: mutluluk derin ve kalıcı bir hâl olarak da anlaşılabilir; o zaman anlamı da kapsayabilir. İtiraz güçlüdür, çünkü varsayımın mutluluk kavramına yüklediği anlamı sorgular. Kendi argümanını öncül ve sonuçla kuran, varsayımını belirleyen ve itirazın gücünü gerekçelendiren eşdeğer yanıtlar kabul edilir.',
    ['Argümanın kurulması ve varsayımın belirlenmesi (hayatın anlamı)', 'hayatın anlamı konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve dayandığı varsayımı gösterir'],
    ['Güçlü bir itirazın belirlenmesi (hayatın anlamı)', 'varsayıma yöneltilebilecek güçlü bir itiraz kurar'],
    ['İtirazın gücünün gerekçelendirilmesi (hayatın anlamı)', 'itirazın neden güçlü olduğunu gerekçesiyle gösterir']),
  task('analyze', 'Şu argümanı çözümleyiniz: “Herkes farklıdır; bu yüzden hayatın anlamı hakkında konuşmanın bir anlamı yoktur.” Gizli öncülü belirtiniz ve metindeki hangi görüşlerin bu öncüle itiraz edeceğini açıklayınız.',
    'Gizli öncül: kişiden kişiye değişen bir şey hakkında ortak ve gerekçeli bir konuşma yapılamaz. Kerem itiraz eder: mutluluk gibi herkesin paylaşabileceği bir ölçüt üzerinden konuşulabilir. Leyla da itiraz edebilir: emek ve amaç ölçütü ortak tartışılabilir. Melih ise öncülü bu biçimiyle kabul etmeyebilir: anlamın kişiye özgü olması, onu konuşmanın anlamsız olduğunu göstermez; kişiler kendi seçimlerini gerekçeleriyle paylaşabilir.',
    ['Gizli öncülün belirlenmesi (hayatın anlamı)', 'kişiden kişiye değişen şey hakkında ortak konuşma yapılamayacağı öncülünü gösterir'],
    ['Kerem ve Leyla’nın itirazının gösterilmesi (hayatın anlamı)', 'ortak ölçüt (mutluluk, emek ve amaç) itirazlarını doğru ilişkilendirir'],
    ['Melih’in konumunun ayrıca gösterilmesi (hayatın anlamı)', 'Melih’in öncülü bu biçimiyle kabul etmeyebileceğini ve kişiye özgülüğün konuşmayı anlamsız yapmadığını belirtir']),
  task('evaluate', 'Hayatın anlamı konusunda bir görüşü en az bir öncül ve bir sonuçla argüman olarak kurunuz. Bu argümana yöneltilebilecek bir itirazı belirtiniz; itirazın hangi öncülü zayıflattığını gösteriniz. İtiraza gerekçeli bir yanıt veriniz ve bu yanıtın itirazı karşılayıp karşılamadığını değerlendiriniz.',
    'Örnek: Öncül: kişinin kendi seçimiyle kurduğu hayat ona aittir. Öncül: kişiye ait hayat daha anlamlı bulunur. Sonuç: anlam kişinin kendi seçimleriyle kurulur. İtiraz: kişi çevreden aldığı değerleri de bilinçle benimseyerek yaşayabilir; seçimle benimsenen ile çevreden gelen ayrılamaz. Zayıflayan öncül: kişinin seçiminin çevreden bağımsız olduğu. Yanıt: bilinçle benimsemek de bir seçimdir, ama seçimin bilinçli olması gerekir. Değerlendirme: yanıt itirazı kısmen karşılar; ancak bilinçli seçimin çevreden gelen etkiden nasıl ayrıldığını göstermek gerekir. Öğrencinin kendi argümanını açıkça kurduğu, itirazı bir öncülle ilişkilendirdiği ve gerekçeli yanıtının yeterliliğini değerlendirdiği eşdeğer çalışmalar kabul edilir.',
    ['Argümanın kurulması ve itirazın belirlenmesi (hayatın anlamı)', 'hayatın anlamı konusunda en az bir öncül ve bir sonuç içeren tutarlı bir argüman kurar ve bu argümana yönelen gerçek bir itiraz yazar'],
    ['Zayıflayan öncülün gösterilmesi (hayatın anlamı)', 'itirazın hangi öncülü zayıflattığını belirtir'],
    ['İtiraza yanıt verilmesi ve yanıtın değerlendirilmesi (hayatın anlamı)', 'itiraza gerekçeli bir yanıt verir ve bu yanıtın itirazı karşılayıp karşılamadığını gerekçeyle değerlendirir']),
  task('evaluate', '“Kimse hayatın anlamını kesin olarak bilemez; bu yüzden hayatın anlamını sormak boşunadır” gerekçesinin hayatın anlamı tartışmasında argüman olarak yeterli olup olmadığını değerlendiriniz.',
    'Gerekçe yetersizdir: kesin bilginin bulunmaması, sormanın boşuna olduğunu göstermez; kesin cevabı olmayan sorular üzerinde düşünmek gerekçeleri ve ölçütleri netleştirir. Ayrıca “sormak boşunadır” sonucu, tartışılan sorunun değerinin ayrıca gösterilmesini gerektirir ve burada gösterilmemiştir. Ancak kesin cevabın bulunamaması doğru olabilir; bu, sorunun sorulmasının değerini ayrıca gerekçelendirme yükünü ortadan kaldırmaz. Gerekçenin yetersizliği görüşün yanlışlığını göstermez.',
    ['Gerekçenin yetersizliğinin gösterilmesi (hayatın anlamı)', 'kesin bilginin olmamasının sormanın boşuna olduğunu göstermediğini belirtir'],
    ['Karşı bilginin belirtilmesi (hayatın anlamı)', 'kesin cevabı olmayan soruların da gerekçeleri ve ölçütleri netleştirdiğini belirtir'],
    ['Değerlendirmenin sınırının belirtilmesi (hayatın anlamı)', 'gerekçenin yetersizliğinin görüşün yanlış olduğunu göstermediğini belirtir']),
  task('create', 'Üç görüşten farklı dördüncü bir görüş ortaya koyunuz ve bu görüşü bir gerekçeyle destekleyiniz.',
    'Örnek: Anlam, kişinin başkalarıyla kurduğu karşılıklı bağlardan doğar; çünkü hem mutluluk hem emek hem de kendi seçim, çoğu zaman başkalarıyla ilişki içinde anlam kazanır. Üç görüşten farklı olan, tutarlı ve gerekçeli her görüş kabul edilir.',
    ['Dördüncü görüşün ortaya konması (hayatın anlamı)', 'metindeki üç görüşten farklı bir görüş ortaya koyar'],
    ['Görüşün gerekçelendirilmesi (hayatın anlamı)', 'görüşü bir gerekçeyle destekler'],
    ['Görüş ile gerekçenin tutarlılığı (hayatın anlamı)', 'görüş ile gerekçenin birbirine uyduğunu gösterir']),
  task('create', 'Kerem, Leyla ve Melih’in görüşlerinden birden fazlasından bir şey koruyan birleştirici bir öneri oluşturunuz; hangi görüşten neyi koruduğunuzu ve neyi çözemediğinizi belirtiniz.',
    'Örnek: Anlam, kişinin kendi seçimiyle emek verdiği bir işte kurulur (Melih ve Leyla); bu sürecin mutluluk vermesi de önemlidir (Kerem). Çözülmeyen: seçimin gerçekten kişiye ait olup olmadığı ve mutluluk ile emek çatışırsa hangisinin öne geçeceği. Hangi görüşten neyi koruduğunu ve neyi çözemediğini belirten tutarlı her öneri kabul edilir.',
    ['Birleştirici önerinin oluşturulması (hayatın anlamı)', 'en az iki görüşten bir şey koruyan tutarlı bir öneri yazar'],
    ['Korunan öğelerin belirtilmesi (hayatın anlamı)', 'hangi görüşten neyi koruduğunu belirtir'],
    ['Çözülemeyenin belirtilmesi (hayatın anlamı)', 'önerinin çözemediği bir noktayı açıkça belirtir']),
];

// ---------- FEL.11.5.2 c: felsefi metin yazar ----------
const sampleParagraph = '“Hayatın anlamı tartışmasındaki temel problem, mutlu olmanın iyi bir hayat için yeterli olup olmadığıdır. Mutluluğu yeterli gören görüş, insanın en çok mutlu olduğunda iyi yaşadığını söyler. Oysa gününü yalnız eğlenerek geçiren ve hiçbir şeye emek vermeyen biri mutlu olsa da hayatını anlamlı bulmayabilir. Bu nedenle mutluluk, iyi bir hayatın tek ölçütü olamaz.”';
const c2: Task[] = [
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafta problemi, bir felsefi kavramı ve ileri sürülen gerekçeyi belirtiniz.`,
    'Problem: mutlu olmanın iyi bir hayat için yeterli olup olmadığı. Kavram: mutluluk (ayrıca anlam, iyi hayat). Gerekçe: gününü yalnız eğlenerek geçiren ve emek vermeyen biri mutlu olsa da hayatını anlamlı bulmayabilir.',
    ['Problemin belirlenmesi (anlam paragrafı)', 'paragrafın problemini mutlu olmanın iyi bir hayat için yeterli olup olmadığı olarak belirtir'],
    ['Kavramın belirlenmesi (anlam paragrafı)', 'paragraftaki felsefi kavramlardan birini (mutluluk, anlam, iyi hayat) belirtir'],
    ['Gerekçenin belirlenmesi (anlam paragrafı)', 'eğlenen ve emek vermeyen kişinin hayatı anlamlı bulmayabileceği gerekçesini belirtir']),
  task('understand', `Paragraf: ${sampleParagraph} Bu paragrafın savunduğu görüşü bir cümleyle özetleyiniz ve sonucu taşıyan cümleyi belirtiniz.`,
    'Görüş: mutluluk, iyi bir hayatın tek ölçütü değildir. Sonucu taşıyan cümle paragrafın son cümlesidir (“Bu nedenle…” ile başlayan cümle).',
    ['Görüşün özetlenmesi (anlam paragrafı)', 'görüşü mutluluğun iyi bir hayatın tek ölçütü olmadığı biçiminde özetler'],
    ['Sonuç cümlesinin belirlenmesi (anlam paragrafı)', 'sonucu taşıyan cümlenin son cümle olduğunu belirtir'],
    ['Özetin paragrafla tutarlı olması (anlam paragrafı)', 'özeti paragrafın söylemediği bir iddiayla genişletmez']),
  task('apply', 'Paragraf: “Hayatın anlamı tartışmasındaki temel problem, anlamın nereden geldiğidir. Leyla’ya göre ……… . Bu nedenle ………” Boş bırakılan yerleri Leyla’nın görüşüne uygun olarak tamamlayınız.',
    'Boşluk 1: anlam, kendimizden büyük bir işe emek vermekten gelir; yalnız eğlenerek geçen ve emek verilmeyen bir hayat mutlu olsa da anlamlı bulunmayabilir. Boşluk 2: mutluluk, anlamlı bir hayatın tek ölçütü olamaz; emek ve amaç da hesaba katılmalıdır. Eşdeğer ve tutarlı tamamlamalar kabul edilir.',
    ['Birinci boşluğun tamamlanması (Leyla)', 'Leyla’nın görüşünü doğru biçimde (anlamın emekten gelmesi) tamamlar'],
    ['İkinci boşluğun tamamlanması (Leyla)', 'sonucu öncülden çıkaran bir cümle yazar'],
    ['Tamamlamanın paragrafın akışına uyması (Leyla)', 'tamamlanan cümleler problem cümlesiyle tutarlı bir bütün oluşturur']),
  task('apply', 'Melih’in görüşünü “problem – kavram – argüman” sırasıyla üç cümlelik bir paragraf hâline getiriniz.',
    'Örnek: Hayatın anlamı tartışmasındaki temel problem, anlamın hazır bulunup bulunmadığıdır. Melih’in görüşünde “seçim”, kişinin çizilmiş yolu bırakıp kendi hayatını kurma biçimidir. Anlam bize hazır verilmediğinden, hayat ancak kişinin kendi seçimleriyle kurulduğunda ona ait olur. Üç öğeyi sırayla ve doğru kuran her paragraf kabul edilir.',
    ['Problem cümlesinin yazılması (Melih)', 'felsefi problemi açıkça belirten bir cümle yazar'],
    ['Kavramın kullanılması (Melih)', 'seçim ya da anlam kavramını görüşü yansıtacak biçimde kullanır'],
    ['Argümanın kurulması (Melih)', 'öncül ve sonuç ilişkisini içeren bir argüman cümlesi yazar']),
  task('analyze', 'Aşağıdaki öğrenci paragrafını çözümleyiniz: “Hayat çok önemlidir, herkes bir amaç için yaşıyor. Bu yüzden anlam aramaya gerek yok.” Paragrafta problem, kavram ve temellendirme bakımından nelerin eksik olduğunu belirtiniz.',
    'Problem tanımlanmamıştır: hangi felsefi soruya cevap verildiği (anlamın nereden geldiği ya da mutluluğun yeterli olup olmadığı) belirsizdir. Kavram: anlam, amaç ve mutluluk gibi kavramlar ele alınmamış, “önemli” kavramı belirsiz bırakılmıştır. Temellendirme: “herkes bir amaç için yaşıyor” gerekçesi, anlam aramaya gerek olmadığını göstermez; yaygınlığa başvurmaktır.',
    ['Problemin eksikliğinin gösterilmesi (anlam paragrafı)', 'paragrafta felsefi problemin tanımlanmadığını belirtir'],
    ['Kavramların eksikliğinin gösterilmesi (anlam paragrafı)', 'anlam, amaç ve mutluluk gibi kavramların ele alınmadığını belirtir'],
    ['Temellendirme eksikliğinin gösterilmesi (anlam paragrafı)', '“herkes bir amaç için yaşıyor” gerekçesinin sonucu desteklemediğini belirtir']),
  task('analyze', 'Aşağıdaki paragrafı çözümleyiniz: “Mutluluk önemlidir. Bu yüzden hiç emek vermemeliyiz.” Öncül ve sonuç arasındaki temellendirme boşluğunu gösteriniz.',
    'Öncül: mutluluk önemlidir. Sonuç: hiç emek vermemeliyiz. Sonuç öncülden çıkmaz: mutluluğun önemli olması, emeğin mutluluğa engel olduğunu ya da emeğin hiç gerekmediğini göstermez; emek bazen mutluluğun koşuludur. Aradaki boşluğu dolduran bir gerekçe (emeğin mutluluğu azalttığı) gösterilmemiştir; metin temellendirilmemiştir.',
    ['Öncül ve sonucun ayrılması (anlam paragrafı)', 'öncülü ve sonucu doğru ayırır'],
    ['Sonucun öncülden çıkmadığının gösterilmesi (anlam paragrafı)', 'mutluluğun önemli olmasının emek vermemeyi gerektirmediğini belirtir'],
    ['Eksik gerekçenin belirtilmesi (anlam paragrafı)', 'emeğin mutluluğu azalttığı gerekçesinin gösterilmediğini belirtir']),
  task('evaluate', `Paragraf 1: ${sampleParagraph} Paragraf 2: “Bence hayat güzel. Çünkü insan yaşayınca mutlu oluyor. Herkes mutlu olmalı.” Bu iki paragraftan hangisinin daha iyi bir felsefi metin olduğunu problem, kavram, temellendirme ve bütünlük ölçütleriyle değerlendiriniz.`,
    'Paragraf 1 daha iyi bir felsefi metindir: problem açık (mutluluğun iyi bir hayat için yeterli olup olmadığı), kavramlar yerinde (mutluluk, anlam, iyi hayat), argüman ve gerekçe açık (emek vermeyen ama mutlu kişi hayatını anlamlı bulmayabilir), bütünlük var. Paragraf 2’de problem tanımlanmamış, “güzel” belirsiz, gerekçe (yaşayınca mutlu olunması) sonucu (herkes mutlu olmalı) desteklemiyor, felsefi terim yok. Paragraf 1’in sınırı: anlamlı bulmanın hayatın gerçekten anlamlı olduğunu gösterip göstermediğini tartışmaması.',
    ['Problem ve kavram ölçütlerine göre değerlendirme (anlam paragrafları)', 'iki paragrafı problem ve kavram bakımından karşılaştırır'],
    ['Temellendirme ölçütüne göre değerlendirme (anlam paragrafları)', 'iki paragrafın gerekçelerini karşılaştırır ve ikincisinin gerekçesinin sonucu desteklemediğini gösterir'],
    ['Bütünlük ve terminoloji ölçütüne göre değerlendirme (anlam paragrafları)', 'iki paragrafı felsefi terim ve metin bütünlüğü bakımından karşılaştırır']),
  task('evaluate', 'Paragraf: “Hayatın anlamı tartışmasındaki problem, anlamın hazır bulunup bulunmadığıdır. Melih’e göre anlam hazır verilmez. Bu yüzden ailemizin önerileri hiç dinlenmemelidir.” Bu paragrafın temellendirmesini değerlendiriniz ve metni geliştirecek iki farklı öneri yazınız.',
    'Temellendirme zayıftır: anlamın bize hazır verilmemesi, ailenin önerilerinin hiç dinlenmemesi gerektiğini göstermez; öneriyi dinleyip bilinçle benimsemek de mümkündür. Melih de çizilmiş yolu kendi seçimleriyle kurmaktan söz eder, öneriyi dinlememekten değil. Öneri 1: sonucu “ailemizin önerileri kendi seçimimizin yerine geçmemelidir” biçiminde değiştirmek. Öneri 2: Melih’in gerekçesini (çizilmiş yol kendiliğinden bizim olmaz) açıkça yazıp sonucu ona bağlamak. Metni gerçekten geliştiren iki farklı öneri kabul edilir.',
    ['Temellendirmenin değerlendirilmesi (Melih paragrafı)', 'gerekçenin sonucu desteklemediğini gösterir'],
    ['İlk önerinin yazılması (Melih paragrafı)', 'metni gerçekten geliştirecek somut bir öneri yazar'],
    ['İkinci önerinin yazılması (Melih paragrafı)', 'metni geliştirecek ikinci ve farklı bir öneri yazar']),
  task('create', 'Mutlu olmanın iyi bir hayat için yeterli olup olmadığını konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (mutluluk, anlam, iyi hayat) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (mutlu olmanın iyi bir hayat için yeterli olup olmadığı); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: mutlu olmak iyi bir hayat için yeterli mi? Görüş: yeterli değildir, çünkü emek vermeyen ama mutlu bir kişi hayatını anlamlı bulmayabilir. Karşı görüş (Kerem): mutlu olmayan hayat başka şeyle anlamlı olamaz. Yanıt: mutluluk anlamın bir parçası olabilir, ama anlamlı bulma duygusu mutluluktan ayrılabilir; bu ayrımı göstermek gerekir. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
  task('create', 'Hayatın anlamının hazır bulunup bulunmadığını, yoksa kişinin kendi seçimleriyle mi kurulduğunu konu alan, en az 8 cümlelik kısa bir felsefi metin yazınız. Metinde problemi tanımlayınız, en az iki kavramı (anlam, seçim, kendi olma) kullanınız, bir görüşü gerekçeleriyle savununuz ve karşı görüşe yanıt veriniz.',
    'Tek bir doğru metin yoktur; kabul edilebilir metin şu öğeleri taşır: (1) felsefi problemin açık tanımı (hayatın anlamının hazır bulunup bulunmadığı ya da kişinin seçimleriyle kurulup kurulmadığı); (2) en az iki kavramın yerinde kullanımı; (3) bir görüşün öncül ve sonuçla kurulması; (4) gerekçelerin verilmesi; (5) karşı görüşe gerekçeli yanıt; (6) felsefi terimler, dil ve metin bütünlüğü. İskelet örnek: Problem: anlam hazır bulunur mu, kurulur mu? Görüş: kurulur, çünkü çevrenin çizdiği yol kişi onu seçmedikçe ona ait olmaz. Karşı görüş: kişi çevreden aldığı değerleri bilinçle benimseyebilir. Yanıt: bilinçle benimsemek de bir seçimdir; ancak seçimin bilinçli olduğunu göstermek gerekir. Hangi görüş savunulursa savunulsun, tutarlı ve temellendirilmiş metin kabul edilir; metin programdaki performans görevinin küçültülmüş hâlidir.',
    ...W, 'extended'),
];

export const grade11Unit5: Record<string, Focus[]> = {
  'FEL.11.5.1': [
    { context: meaningLife, focus: 'hayatın anlamına ilişkin felsefi soru ve problemlerin açıklanması', evidence: ['Tartışma mutlu olmanın iyi bir hayat için yeterli olup olmadığı sorusuna dayanır.', 'Tartışma hayatın anlamının hazır bulunup bulunmadığı ya da kişinin seçimleriyle kurulup kurulmadığı sorusuna dayanır.'], inference: 'Panel tartışması hayatın anlamının mutluluğun yeterliliği ve anlamın kaynağı sorularını gündeme getirir.', limit: 'Metin hangi görüşün doğru olduğunu göstermez.', example: 'Hafta sonunu yalnız hoşa giden şeylerle geçirmek.', tasks: a1 },
    { context: meaningLife, focus: 'hayatın anlamına ilişkin felsefi soru ve problemlerin hayatıyla ilişkilendirilerek değerlendirilmesi', evidence: ['Tartışmadaki görüşler günlük seçimlerde de kullanılır.', 'Günlük seçimler hoşa gitme, emek ve kendi isteği arasında bir gerilim içerir.'], inference: 'Hayatın anlamına ilişkin felsefi sorular günlük yaşamdaki seçimlerle ilişkilendirilerek değerlendirilebilir.', limit: 'Günlük örnek, görüşlerden birinin doğru olduğunu tek başına göstermez.', example: 'Bir bölüm ya da kulüp seçerken neye göre karar verileceği.', tasks: b1 },
  ],
  'FEL.11.5.2': [
    { context: meaningLife, focus: 'hayatın anlamına ilişkin felsefi argümanların çözümlenmesi', evidence: ['Üç görüşün her birinin öncülü ve sonucu vardır.', 'Her görüşün gerekçe yükü vardır.'], inference: 'Argümanlar öncül, sonuç ve örtük öncüller bakımından çözümlenebilir.', limit: 'Çözümleme görüşlerden birinin doğru olduğunu kanıtlamaz.', example: 'Herkesin mutlu olmak istemesinden mutluluğun amaç olduğu sonucuna geçiş.', tasks: a2 },
    { context: meaningLife, focus: 'hayatın anlamına ilişkin felsefi görüş ve argüman oluşturulması', evidence: ['Bir görüş gerekçe ve sonuçla argümana dönüşür.', 'Her argüman bir varsayıma dayanır ve itirazlara açıktır.'], inference: 'Öğrenci hayatın anlamı için gerekçeli bir görüş ve argüman kurabilir.', limit: 'Argümanın tutarlı olması doğru olduğunu tek başına göstermez.', example: 'Kendi seçimiyle kurulan hayatın kişiye ait olması üzerine bir argüman.', tasks: b2 },
    { context: meaningLife, focus: 'hayatın anlamına ilişkin felsefi metin yazılması', evidence: ['Felsefi metin problemi tanımlar ve kavramları yansıtır.', 'Felsefi metin argümanı ortaya koyar ve temellendirir.'], inference: 'Felsefi metin problem, kavram, argüman ve temellendirmeyi tutarlı bir bütün olarak kurar.', limit: 'Yazılıdaki metin programdaki performans görevinin küçültülmüş hâlidir.', example: 'Mutluluğun iyi bir hayat için yeterli olup olmadığı tartışması.', tasks: c2 },
  ],
};
