import type { Level } from './philosophy-exam-case.ts';

// Özgün öğretmen örnekleri. Bileşen sırası 2026 programının 14 ve 19. sayfalarıyla eşlenir.
// Her bileşenin kendi metni ve yanıt kanıtları vardır; ünite anahtar kelimelerinden anahtar üretilmez.
type Focus = { context: string; focus: string; evidence: [string, string]; inference: string; limit: string; example: string };
export const earlyUnits: Record<string, Focus[]> = {
  'FEL.10.1.1': [
    { context: 'Bir öğrenci felsefeyi “bilgeliği arama”, arkadaşı “kabullerimizi gerekçeleriyle sorgulama” olarak tanımlar. Öğretmen, felsefede cevapların da yeniden sorgulanabildiğini belirtir. Öğrenciler bu iki tanımın aynı etkinliğin farklı yönlerini vurguladığını tartışır.', focus: 'felsefenin anlamı ve ortak tanımın imkânı', evidence: ['Bilgeliği arama, felsefenin anlama ve iyi yaşama yönelişini vurgular.', 'Kabulleri gerekçeleriyle sorgulama, eleştirel ve gerekçeli düşünmeyi vurgular.'], inference: 'Tanımlar farklı yönleri öne çıkarır; sorgulama ve gerekçelendirme ortak bir çerçeve sağlayabilir.', limit: 'Tek tanımın felsefenin bütün tarihsel biçimlerini kapsadığı bu iki örnekle kanıtlanamaz.', example: 'Felsefe, insanın kendisi ve dünya hakkındaki kabullerini gerekçeleriyle sorguladığı bir bilgelik arayışıdır.' },
    { context: 'Bir çalışma kâğıdında Hint ve Çin geleneklerinde yaşam ve düzen, Antik Yunan geleneğinde doğa ve varlık, Türk-İslam geleneğinde akıl ve bilgi üzerine tartışmalar bulunduğu belirtilir. Ticaret ve kültürler arası karşılaşmaların, tartışma ortamlarının ve bilgi birikiminin düşünceyi besleyebildiği açıklanır. “Felsefenin gelişimini yalnız coğrafya açıklar” iddiasına, aynı coğrafyada farklı dönemlerde farklı düşünceler geliştiği itirazı yöneltilir.', focus: 'felsefi düşüncenin özellikleri ve tarihsel gelişimi', evidence: ['Farklı gelenekler farklı soruları öne çıkarır; felsefe tek bir kültüre indirgenemez.', 'Kültürel karşılaşmalar, tartışma ortamları ve bilgi birikimi düşüncenin gelişmesini besleyebilir.'], inference: 'Tarihsel gelişimi birden fazla koşulu birlikte ele alarak açıklamak gerekir.', limit: 'Bir koşulun etkili olması tek başına yeterli veya zorunlu neden olduğunu göstermez.', example: 'Ticaret yoluyla farklı görüşlerle karşılaşan kişiler, kendi kabullerini yeniden sorgulayabilir; bu örnek coğrafya kadar kültürel etkileşimin de önemini gösterir.' },
    { context: 'Öğrenciler “Kütüphane kaçta kapanıyor?” ile “Bilgi sahibi olmak insanı bilge yapar mı?” sorularını karşılaştırır. İlk soru belirli bir saat bilgisiyle cevaplanabilir. İkinci soru bilgi ve bilgelik kavramlarını sorgulamayı, gerekçeleri tartışmayı ve farklı cevapları değerlendirmeyi gerektirir.', focus: 'felsefi sorunun özellikleri ve felsefi soru sorma', evidence: ['Kapanış saati belirli bir olgusal bilgiyle cevaplanır.', 'Bilgi ile bilgelik ilişkisi kavramsal, açık uçlu ve gerekçeli tartışma gerektirir.'], inference: 'Her soru felsefi değildir; felsefi sorular temel kavram ve kabulleri sorgular.', limit: 'Bir sorunun uzun veya cevabının zor olması tek başına felsefi olmasını sağlamaz.', example: 'Bir bilgiyi doğru kabul etmemizi sağlayan nedir? Bu soru bilginin dayanağını sorgular; yalnız bir bilgi istemez.' },
    { context: 'Bir bilim insanı suyun hangi koşullarda kaynadığını deneyle araştırır. Bir sanatçı suyu bir resimde yalnızlığın simgesi olarak işler. Bir inanan suyu dinî bir arınma pratiğiyle ilişkilendirir. Felsefe öğrencisi ise “Kanıt nedir, bir simgenin anlamı nasıl oluşur, inanç nasıl temellendirilir?” sorularını tartışır.', focus: 'felsefenin bilim, din ve sanatla ilişkisi', evidence: ['Bilim örneği deney ve gözleme, sanat örneği yorum ve ifadeye dayanır.', 'Felsefi sorular bu alanların anlamını, yöntemini ve dayanaklarını sorgular; din örneği inanç ve pratik bağını gösterir.'], inference: 'Alanlar aynı konuya farklı yöntem ve amaçlarla yaklaşabilir; felsefe bu ilişkileri eleştirel biçimde inceler.', limit: 'Bu örneklerden bilim, din veya sanatın değersiz olduğu ya da birbirinin yerini aldığı sonucu çıkarılamaz.', example: 'Bir eserin güzel sayılmasının dayanaklarını sormak sanatla ilişkili felsefi bir sorudur; resmi yapmakla aynı etkinlik değildir.' },
    { context: 'Bir öğrenci sosyal medyada yaygın bir iddiayı hemen paylaşmak yerine kaynağını ve gerekçelerini sorgular. Sınıfta farklı görüşleri dinleyen öğrenciler ortak karar almadan önce gerekçeleri karşılaştırır. Bir öğrenci bu tartışmanın zaman kaybı olduğunu söyler; arkadaşı sorgulamanın yanlış kararları azaltabileceğini belirtir.', focus: 'felsefenin bireysel ve toplumsal işlevleri', evidence: ['Kaynağı sorgulamak kişinin kendi yargısını gözden geçirmesine yardımcı olur.', 'Farklı gerekçeleri dinlemek ortak kararın tartışılarak alınmasına katkı sağlar.'], inference: 'Felsefi sorgulama bireysel eleştirel düşünmeyi ve toplumsal diyalogu destekleyebilir.', limit: 'Sorgulama her zaman hızlı uzlaşma veya kesin doğru karar garantisi vermez.', example: 'Sınıf kurallarının adil olup olmadığını gerekçeleriyle tartışmak hem bireysel yargıyı hem ortak yaşam kararını geliştirebilir.' },
  ],
  'FEL.10.2.1': [
    { context: 'Bir öğrenci önceden yalnız “üzgünüm” derken hayal kırıklığı ve kaygı sözcüklerini öğrendikten sonra duygularını daha ayrıntılı ayırır. Buna karşılık bir bisikletçi, her hareketini sözcüklere dökmeden dengeyi ayarlar. Öğrenciler dilin düşünceyi düzenleyebildiğini, fakat bu örneklerin bütün düşünmenin sözcüklerle gerçekleştiğini kanıtlamadığını tartışır.', focus: 'düşünme ve dil arasındaki nedensel ilişkiler', evidence: ['Yeni sözcükler duyguların ayrılmasını ve ifade edilmesini kolaylaştırabilir.', 'Bisiklet örneği bazı işlemlerin sözel anlatım olmadan yürütülebildiğini gösterir.'], inference: 'Dil düşüncenin ayrıntılandırılmasına katkı sağlayabilir; her düşünme işleminin sözcüklere bağlı olduğu sonucu zorunlu değildir.', limit: 'Tek öğrenci örneği bütün insanlarda aynı nedensel etkiyi kanıtlamaz.', example: 'Adil ile eşit sözcüklerinin ayrımını öğrenen bir öğrenci, herkese aynı davranmanın her durumda adil olmayabileceğini daha açık ifade edebilir.' },
    { context: 'Bir grup “eşit” ve “adil” sözcüklerini ayırınca okul kaynaklarının dağıtımı hakkındaki görüşlerini daha açık yazar. Bir öğrenci çizdiği şemayı sonradan cümlelere dönüştürerek arkadaşlarına anlatır. Grup, dilin düşünceleri düzenleme ve paylaşmada etkili olduğu, düşünmenin ise sözcüklerle sınırlı olmayan görsel biçimler de içerebildiği yargısına ulaşır.', focus: 'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma', evidence: ['Kavram ayrımı yargıların daha açık kurulmasına yardımcı olur.', 'Şema sözel olmayan düşünceyi, cümleler bu düşüncenin paylaşılmasını gösterir.'], inference: 'Düşünme ve dil karşılıklı ilişkilidir: dil düşünceyi düzenleyip paylaşırken düşünce yeni ifadelerin kurulmasını sağlar.', limit: 'Dili tek neden veya düşünmenin tek biçimi kabul etmek metindeki şema örneğini açıklamaz.', example: 'Bir öğrenci problemi önce çizimle tasarlar, sonra sözcüklerle açıklar ve arkadaşının sorusuyla çizimini düzeltir; ilişki tek yönlü değildir.' },
  ],
  'FEL.10.2.2': [
    { context: '“Bütün okul kitapları kayıtlıdır” ve “Bu atlas bir okul kitabıdır” ifadelerinden “Bu atlas kayıtlıdır” sonucuna ulaşılır. Önermeler doğru veya yanlış olabilen yargılardır; argümanda sonucu destekleyen yargılar öncüldür. Aynı atlasın aynı anda ve aynı anlamda hem kayıtlı hem kayıtsız olduğunu söylemek çelişkidir. Bir iddianın çok kişi tarafından kabul edilmesi ise onun doğru olduğuna yeterli kanıt değildir.', focus: 'mantık ve argümantasyonun temel kavramları', evidence: ['İlk iki önerme öncül, atlasın kayıtlı olduğu yargısı sonuçtur; akıl yürütme tümdengelimdir.', 'Aynı koşulda kayıtlı ve kayıtsız demek çelişkilidir; popülerlik tek başına doğruluk kanıtı değildir.'], inference: 'Argümanın değerlendirilmesinde öncül, sonuç, çıkarım ilişkisi ve tutarlılık ayrı ayrı incelenmelidir.', limit: 'Geçerli çıkarım öncüllerin gerçekte doğru olduğunu tek başına kanıtlamaz.', example: 'Bütün memeliler omurgalıdır; yunus memelidir; öyleyse yunus omurgalıdır. İlk iki yargı öncül, son yargı sonuçtur.' },
    { context: 'Sınıf temsilcisi şöyle der: “Bu hafta kütüphaneye yalnız kulüp üyeleri girebilir. Deniz kulüp üyesi değildir. Bu nedenle Deniz bu hafta kütüphaneye giremez.” Kural yalnız bu haftaya ilişkindir; başka haftalar hakkında bilgi verilmemiştir.', focus: 'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma', evidence: ['Öncül 1: Bu hafta kütüphaneye girebilen herkes kulüp üyesidir.', 'Öncül 2: Deniz kulüp üyesi değildir. Sonuç: Deniz bu hafta kütüphaneye giremez.'], inference: 'Sonuç iki öncülden çıkar; zaman sınırlaması öncül ve sonuçta korunmalıdır.', limit: 'Deniz hiçbir zaman kütüphaneye giremez sonucu metni aşar; kulüp üyesi olmak tek başına giriş garantisi olarak da verilmemiştir.', example: 'P1: Bu hafta giriş için üyelik gereklidir. P2: Deniz üye değildir. C: Deniz bu hafta giremez.' },
    { context: 'Bir duyuruda “Yağış olursa cuma günkü açık hava etkinliği salona alınacak; yağış olmazsa bahçede yapılacak” yazılıdır. Duyuru etkinliğin iptal edileceğini veya bütün etkinliklerin salonda yapılacağını söylemez.', focus: 'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme', evidence: ['Yağış koşulunda cuma günkü etkinliğin yeri salondur.', 'Yağış olmaması koşulunda aynı etkinliğin yeri bahçedir.'], inference: 'Yeniden ifade, koşulu, zamanı ve kapsamı korumalı; yorum veya yeni iddia eklememelidir.', limit: 'Etkinlik iptal edilir veya bütün etkinlikler salondadır ifadeleri özgün anlamı değiştirir.', example: 'Cuma günkü etkinlik, yağışlı havada salonda, yağışsız havada bahçede gerçekleştirilecektir.' },
  ],
};

type Task = { level: Level; stem: string; key: string; criteria: [string, string, string] };
export function earlyUnitTasks(f: Focus): Task[] {
  const [a, b] = f.evidence;
  const tasks: Task[] = [
    { level: 'understand', stem: `Metinde ${f.focus} hakkında verilen iki temel bilgiyi kendi cümlelerinizle açıklayınız.`, key: `${a} ${b}`, criteria: ['Birinci bilginin doğru açıklanması', 'İkinci bilginin doğru açıklanması', 'Anlamın ve bağlamın korunması'] },
    { level: 'understand', stem: `Metindeki ${f.focus} konusunu bir cümlede özetleyiniz; özeti destekleyen bir ifadeyi belirtiniz.`, key: `${f.inference} Dayanak örneği: ${a}`, criteria: ['Konunun doğru özetlenmesi', 'Uygun metin dayanağının belirtilmesi', 'Özet ve dayanağın ilişkilendirilmesi'] },
    { level: 'apply', stem: `${f.focus} konusunu şu örneğe uygulayarak metinle bağlantısını açıklayınız: ${f.example}`, key: `Örnek bağlantısı: ${f.example} Metindeki ilişki: ${f.inference}`, criteria: ['Örnekte ilgili ilişkinin belirlenmesi', 'Metindeki bilgiyle doğru bağlantı kurulması', 'Bağlantının açıklanması'] },
    { level: 'apply', stem: `Metindeki ${f.focus} konusunu açıklayan farklı bir günlük yaşam örneği veriniz ve bağlantıyı belirtiniz.`, key: `Örnek: ${f.example} Kabul: aynı ilişkiyi doğru gösteren farklı örnekler de kabul edilir. ${f.inference}`, criteria: ['Konuya uygun örnek', 'Örnekte ilişkinin doğru gösterilmesi', 'Metinle bağlantının açıklanması'] },
    { level: 'analyze', stem: `Metinde ${f.focus} için verilen iki bilgiyi ayırınız ve aralarındaki ilişkiyi çözümleyiniz.`, key: `Bilgi 1: ${a} Bilgi 2: ${b} İlişki: ${f.inference}`, criteria: ['Birinci bilginin doğru ayrılması', 'İkinci bilginin doğru ayrılması', 'İlişkinin gerekçeli çözümlenmesi'] },
    { level: 'analyze', stem: `Metinde ${f.focus} bakımından hangi sonuca ulaşılabilir? Bu sonucun dayanaklarını ve metinden çıkarılamayacak bir yargıyı ayırınız.`, key: `Sonuç: ${f.inference} Dayanaklar: ${a} ${b} Sınır: ${f.limit}`, criteria: ['Metinle uyumlu sonuç', 'Sonucun dayanaklarının gösterilmesi', 'Çıkarım sınırının doğru ayrılması'] },
    { level: 'evaluate', stem: `“${f.inference}” yargısını metindeki dayanakları ve sınırları açısından değerlendiriniz.`, key: `Dayanaklar: ${a} ${b} Sınır: ${f.limit} Bu sınırı koruyan gerekçeli değerlendirmeler kabul edilir.`, criteria: ['Destekleyici kanıtın doğru kullanımı', 'Sınırın doğru değerlendirilmesi', 'Gerekçeli değerlendirme yargısı'] },
    { level: 'evaluate', stem: `${f.focus} hakkında metnin izin verdiği sonuçla aşırı genellemeyi ayırarak gerekçeli bir değerlendirme yapınız.`, key: `Desteklenen yargı: ${f.inference} Aşırı genellemenin sınırı: ${f.limit}`, criteria: ['Desteklenen yargının belirlenmesi', 'Aşırı genellemenin ayırt edilmesi', 'Ayrımın gerekçelendirilmesi'] },
    { level: 'create', stem: `${f.focus} konusunda yeni bir soru ve bu soruya gerekçeli bir yanıt oluşturunuz.`, key: `Örnek soru: ${f.focus} hangi dayanaklarla açıklanabilir? Örnek yanıt: ${f.inference} Çünkü ${a} ${b} Konuya uygun farklı sorular ve gerekçeli yanıtlar kabul edilir.`, criteria: ['Konuya uygun yeni soru', 'Soruya cevap veren tutarlı yanıt', 'Yanıtın gerekçelendirilmesi'] },
    { level: 'create', stem: `${f.focus} konusunu gösteren yeni bir kısa durum yazınız; durumun hangi ilişkiyi gösterdiğini açıklayınız.`, key: `Örnek durum: ${f.example} Gösterdiği ilişki: ${f.inference} Aynı ilişkiyi doğru kuran özgün durumlar kabul edilir.`, criteria: ['İlişkiye uygun özgün durum', 'Durumda ilişkiyi gösteren öğeler', 'İlişkinin doğru açıklanması'] },
  ];

  const analysis: Record<string, [string, string]> = {
    'felsefenin anlamı ve ortak tanımın imkânı': ['Metindeki iki felsefe tanımının ortak ve farklı yönlerini çözümleyiniz.', 'İki tanımdan hareketle felsefe için ortak bir çerçeve çıkarılabilir mi? Metnin izin verdiği sonuçla kanıtlamadığı sonucu ayırınız.'],
    'felsefi düşüncenin özellikleri ve tarihsel gelişimi': ['Metindeki kültürel etkileşim, tartışma ortamı ve bilgi birikiminin felsefi düşüncenin gelişimiyle ilişkisini çözümleyiniz.', '“Felsefenin gelişimini yalnız coğrafya açıklar” iddiasının metindeki itirazla hangi bakımdan sınırlandığını çözümleyiniz.'],
    'felsefi sorunun özellikleri ve felsefi soru sorma': ['Metindeki kapanış saati sorusu ile bilgi-bilgelik sorusunu cevaplanma biçimleri bakımından karşılaştırınız.', 'Bilgi-bilgelik sorusunu felsefi yapan özellikleri metindeki dayanaklarla belirleyiniz; cevap güçlüğünün tek başına yeterli olup olmadığını ayırınız.'],
    'felsefenin bilim, din ve sanatla ilişkisi': ['Metindeki bilim, sanat ve din örnekleriyle felsefi soruların yöntem ve amaç bakımından ilişkisini çözümleyiniz.', 'Felsefi sorgulamanın bilim, sanat ve dinin yerini aldığı sonucu bu metinden çıkar mı? Alanların farklı işlevlerini ayırarak açıklayınız.'],
    'felsefenin bireysel ve toplumsal işlevleri': ['Metindeki kaynak sorgulama ve ortak karar tartışmasını felsefenin bireysel ve toplumsal işlevleri bakımından ayırınız.', 'Tartışmanın zaman aldığı gözlemiyle “sorgulama yararsızdır” yargısı arasındaki çıkarımı çözümleyiniz; metindeki karşı gerekçeyi belirtiniz.'],
    'düşünme ve dil arasındaki nedensel ilişkiler': ['Yeni duygu sözcükleri öğrenme ve bisiklet kullanma örneklerinin düşünme-dil ilişkisi bakımından farklı sonuçlarını çözümleyiniz.', 'Dilin düşünceyi ayrıntılandırdığı yargısıyla bütün düşünmenin sözcüklere bağlı olduğu yargısını ayırınız; metnin hangisini desteklediğini gerekçelendiriniz.'],
    'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma': ['Kavramları ayırma ve şemayı cümlelere dönüştürme örneklerini düşünme-dil ilişkisi bakımından birbiriyle ilişkilendiriniz.', 'Metindeki örneklerden düşünme-dil ilişkisine yönelik uyumlu bir yargı çıkarınız; tek yönlü ilişki iddiasının eksik bıraktığı yönü açıklayınız.'],
    'mantık ve argümantasyonun temel kavramları': ['Atlas örneğindeki öncül ve sonucu, çıkarım türünü ve çelişki örneğini birbirinden ayırınız.', 'Atlas örneğinde çıkarımın geçerliliği ile öncüllerin gerçek doğruluğu arasındaki farkı çözümleyiniz.'],
    'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma': ['Temsilcinin sözünü iki öncül ve bir sonuç olarak yeniden düzenleyiniz; zaman ve üyelik koşulunu koruyunuz.', '“Deniz hiçbir zaman kütüphaneye giremez” sonucunun temsilcinin sözünü hangi bakımdan aştığını öncül-sonuç ilişkisi üzerinden açıklayınız.'],
    'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme': ['Duyurudaki iki koşullu ilişkiyi ayırınız ve kendi cümlelerinizle yeniden yazınız; zamanı ve etkinliğin kapsamını koruyunuz.', '“Bütün etkinlikler salonda yapılacak” yorumuyla özgün duyuruyu karşılaştırınız; kaybolan koşulu ve değişen kapsamı belirtiniz.'],
  };
  const analysisCriteria: Record<string, [string, string, string]> = {
    'felsefenin anlamı ve ortak tanımın imkânı': ['Bilgelik arayışı yönünün açıklanması', 'Gerekçeli sorgulama yönünün açıklanması', 'Tanımların ortak ve farklı yönlerinin ilişkilendirilmesi'],
    'felsefi düşüncenin özellikleri ve tarihsel gelişimi': ['Kültürel etkileşim ve gelenek çeşitliliğinin açıklanması', 'Tartışma ortamı ve bilgi birikiminin etkisinin açıklanması', 'Gelişimin tek nedene indirgenemeyeceğinin gösterilmesi'],
    'felsefi sorunun özellikleri ve felsefi soru sorma': ['Saat sorusunun olgusal niteliğinin ayrılması', 'Bilgi-bilgelik sorusunun kavramsal niteliğinin açıklanması', 'Cevaplanma biçimlerinin gerekçeli karşılaştırılması'],
    'felsefenin bilim, din ve sanatla ilişkisi': ['Bilim, sanat ve din örneklerinin yöntem ve amaçlarının ayrılması', 'Felsefi soruların dayanak sorgulama niteliğinin açıklanması', 'Alanlar arasındaki ilişkinin doğru kurulması'],
    'felsefenin bireysel ve toplumsal işlevleri': ['Kaynak sorgulamanın bireysel işlevinin açıklanması', 'Ortak karar tartışmasının toplumsal işlevinin açıklanması', 'İki işlevin gerekçeli ilişkilendirilmesi'],
    'düşünme ve dil arasındaki nedensel ilişkiler': ['Sözcüklerin düşünceyi ayrıntılandırma etkisinin açıklanması', 'Bisiklet örneğinin sözel olmayan yönünün ayrılması', 'Bütün düşünmeyi dile indirgemeden ilişki kurulması'],
    'düşünme ve dil ilişkisine yönelik uyumlu bir bütün oluşturma': ['Kavram ayrımının düşünceyi düzenleme etkisinin açıklanması', 'Şema ve sözel paylaşımın ilişkilendirilmesi', 'Karşılıklı ilişkiyi gösteren uyumlu yargı kurulması'],
    'mantık ve argümantasyonun temel kavramları': ['Atlas argümanındaki öncül ve sonucun ayrılması', 'Tümdengelim ve çelişki örneğinin doğru belirlenmesi', 'Mantıksal kavramların birbirine karıştırılmaması'],
    'ifadeleri bağlamını koruyarak öncül ve sonuca ayırma': ['Giriş için üyelik gerektiren birinci öncülün doğru yazılması', 'Denizin üye olmadığı ikinci öncülün doğru yazılması', 'Bu hafta giremeyeceği sonucunun bağlamı korunarak yazılması'],
  };
  if (analysisCriteria[f.focus]) tasks[4].criteria = analysisCriteria[f.focus];
  const stems = analysis[f.focus];
  if (stems) {
    tasks[4].stem = stems[0]; tasks[5].stem = stems[1];
    if (f.focus === 'ifadeleri anlamını değiştirmeden nesnel biçimde yeniden ifade etme') {
      tasks[4].key = `Örnek yeniden ifade: ${f.example} Korunan koşullar: ${a} ${b}`;
      tasks[4].criteria = ['Yağış koşulunun ve salon bilgisinin korunması', 'Yağış olmaması koşulunun ve bahçe bilgisinin korunması', 'Cuma gününün ve tek etkinlik kapsamının korunması'];
    }
  }
  return tasks;
}

export function earlyUnitCriterion(points: number, labels: [string, string, string]) {
  const shares = [Math.floor(points * .4), Math.floor(points * .4), 0];
  shares[2] = points - shares[0] - shares[1];
  return labels.map((label, i) => `${label}: ${shares[i]} puan. Tam: doğru ve eksiksiz; kısmi: doğru fakat eksik (${Math.floor(shares[i] / 2)} puan); yok/yanlış: 0 puan.`).join('\n') + '\nEşdeğer gerekçeli yanıtlar kabul edilir. Sunum biçimi ayrıca puan kaybettirmez.';
}
