import { sociology2026Package } from '../../../src/curriculum-packages/sociology-2026.ts';

// Öğretmen incelemesine sunulan özgün örneklerdir; resmî soru bankası değildir.
const contexts: Record<string, [string, string, string]> = {
 'SOS.11.1.1': ['Sanayileşme ile fabrikalar büyür ve kırdan kente göç artar. Fransız Devrimi siyasal düzeni tartışmaya açar. Comte toplumu bilimsel yöntemle incelemeyi, Durkheim toplumsal olguları açıklamayı önerir.', 'Sanayileşme iş bölümü ve kentleşmeyi, devrim yurttaşlık ve yönetim ilişkilerini dönüştürmüştür. Comte pozitivist bir toplum bilimi arar; Durkheim bireyi aşan toplumsal olgulara odaklanır. Bugünkü dijital dönüşümle ortak yön hızlı değişimdir; üretim ve iletişim araçları farklıdır.', 'sanayileşme, kentleşme, toplumsal olgu'],
 'SOS.11.1.2': ['Bir sınıfta öğrenciler okul kulüplerine katılımın neden farklılaştığını merak eder. Bir sosyal medya paylaşımı bunu yalnız kişisel isteğe bağlar. Öğrenciler anket, görüşme ve okul kayıtlarını birlikte incelemeyi planlar.', 'Araştırma sorusu, kulübe katılım ile zaman ve erişim olanaklarının ilişkisi olabilir. Anket yaygınlığı, görüşme deneyimleri, kayıtlar katılımı gösterir. Kaynak tarihi, örneklem ve yöntem denetlenmeden paylaşım güvenilir sayılmaz; farklı kaynaklarla desteklenen sonuç çıkarılır.', 'araştırma sorusu, örneklem, kaynak güvenilirliği'],
 'SOS.11.1.3': ['Araştırmacı yüz kişiye toplu taşıma kullanım sıklığını sorar. Ardından on kişiyle ulaşım deneyimleri üzerine ayrıntılı görüşme yapar. Sayısal sıklıklarla kişilerin deneyim anlatıları aynı sorun hakkında bilgi verir.', 'Nicel çalışma ölçülebilir sıklık ve değişken ilişkilerine; nitel çalışma deneyimlerin anlamına ve bağlamına odaklanır. İkisi de sistemli veri toplar. Standart anket karşılaştırılabilir sayılar, görüşme derinlik sağlar; tek başına küçük görüşme grubu tüm topluma genellenmez.', 'nicel yöntem, nitel yöntem, genelleme'],
 'SOS.11.2.1': ['Tanzimat döneminde hukuk ve yönetim reformları gündeme gelir. Cumhuriyet döneminde eğitim ve yurttaşlık kurumları yeniden düzenlenir. Bu dönüşümler farklı tarihsel koşullarda gerçekleşir.', 'Osmanlı reformları askerî, idarî ve ekonomik sorunlara çözüm arayışıyla bağlantılıdır. Cumhuriyet reformları ulus devlet ve yurttaşlık kurumlarının kuruluşuyla ilişkilidir. Eğitim ve hukuk değişimleri toplumsal rolleri etkiler; iki dönemin neden ve sonuçları kendi bağlamlarında değerlendirilir.', 'modernleşme, reform, yurttaşlık'],
 'SOS.11.2.2': ['Göç, savaş ve devletin yeniden kuruluşu Türkiye’de toplumsal sorunları gündeme getirir. Ziya Gökalp kültür ve uygarlık ilişkisini, Prens Sabahaddin bireysel girişim ve yönetimin örgütlenmesini tartışır.', 'Türkiye’de sosyoloji toplumsal dönüşüm sorunlarına yanıt arayışı içinde gelişmiştir. Gökalp kültürel bütünleşme ve dayanışmaya, Prens Sabahaddin bireysel girişim ve yerinden yönetime önem verir. Farklı yaklaşımlar dönemin toplum ve yönetim tartışmalarıyla birlikte açıklanır.', 'kültür, uygarlık, toplumsal dönüşüm'],
 'SOS.11.2.3': ['Kurgu bir roman sahnesinde köyden kente gelen aile ücretli işe başlar. Gençler eğitimle yeni mesleklere yönelirken aile büyükleri eski dayanışma ilişkilerini sürdürmeye çalışır.', 'Sahne kentleşme, ücretli emek ve kuşaklar arası rol değişimini gösterir. Aile içi dayanışma sürerken meslek ve eğitim beklentileri değişir. Edebî anlatı bu dönüşümleri anlamaya yardımcı olur; kurgu tüm toplumun istatistiksel kanıtı olarak kullanılmaz.', 'kentleşme, kuşak, rol'],
 'SOS.11.3.1': ['Bir mahallede bayram ziyaretleri ve ortak yemekler sürdürülür. Yeni gelen komşular kendi geleneklerini paylaşır. Ortak kurallar birlikte yaşarken yeniden yorumlanır.', 'Kültür değer, norm ve semboller aracılığıyla aidiyet ve dayanışma sağlar. Geleneklerin paylaşılması toplumsallaşmayı destekler; farklı yorumlar kültürel değişimi gösterir. Kültür durağan değildir ve toplumsal ilişkilerle karşılıklı etkileşir.', 'değer, norm, aidiyet'],
 'SOS.11.3.2': ['Bir yerleşimde aile, okul, belediye ve işletmeler birlikte çalışır. Bir kişi evde ebeveyn, okulda öğretmen, dernekte üye rollerini üstlenir.', 'Toplumsal yapı kurumları, grupları, statü ve rolleri içerir. Okul eğitim, işletme üretim, belediye hizmet işlevlerini yürütür. Aynı kişinin farklı rolleri kurumlar arasındaki bağlantıyı gösterir; bir kurumun değişmesi diğerlerini etkileyebilir.', 'kurum, statü, rol'],
 'SOS.11.3.3': ['Bir teknisyen farklı şehirde aynı işi yapar. Başka bir çalışan eğitimini tamamlayıp yönetici olur. Ailelerin gelirleri ve eğitim olanakları farklıdır.', 'Aynı konumdaki yer değişimi yatay, daha üst meslek konumuna geçiş dikey hareketliliktir. Gelir, eğitim ve meslek tabakalaşmanın göstergeleridir. Eğitim hareketlilik olanağı sağlayabilir; eşitsiz erişim fırsatları sınırlar.', 'tabakalaşma, yatay hareketlilik, dikey hareketlilik'],
 'SOS.11.4.1': ['Bir evde ebeveynler ve çocuklar, başka bir evde üç kuşak birlikte yaşar. Her iki aile bakım ve sorumlulukları paylaşır. Evlilik kararlarında rıza ve hukukî düzenlemeler önem taşır.', 'Çekirdek ve geniş aile hane yapıları farklıdır; bakım, dayanışma ve toplumsallaşma ortak işlevlerdir. Evlilik biçimleri tarihsel ve kültürel bağlamla değerlendirilir. Aile çeşitliliği bir biçimin üstünlüğünü kanıtlamaz; haklar ve rıza gözetilir.', 'çekirdek aile, geniş aile, toplumsallaşma'],
 'SOS.11.4.2': ['Bir okul temel bilgi ve meslek becerileri kazandırır. Öğrenciler birlikte çalışma kurallarını öğrenir. Ulaşım ve materyal olanakları öğrenciler arasında farklılaşır.', 'Eğitim bilgi ve beceri aktarır, toplumsallaşmayı ve ortak değerleri destekler. Meslek edinme hareketlilik sağlayabilir; eşitsiz olanaklar erişimi sınırlar. Eğitimin işlevleri bireysel başarı yanında toplumsal katılımla gerekçelendirilir.', 'eğitim, fırsat eşitliği, toplumsallaşma'],
 'SOS.11.4.3': ['Bir topluluk ortak dinî törenler düzenler ve ihtiyaç sahiplerine yardım eder. Aynı mahallede farklı inançlara sahip kişiler birlikte yaşar.', 'Din ortak sembol ve ritüellerle aidiyet, anlam ve dayanışma sağlayabilir. Yardımlaşma diğer kurumlarla ilişkiyi gösterir. İşlevler sosyolojik olarak açıklanır; inanç doğruluğu hakkında hüküm kurulmaz ve farklı inançların hakları gözetilir.', 'ritüel, dayanışma, aidiyet'],
 'SOS.11.4.4': ['Bir kentte özel işletmeler üretim yapar. Belediye ulaşım hizmeti sunar. Devlet iş güvenliği kuralları ve sosyal destekler uygular. Fiyat artışları ailelerin tüketim kararlarını etkiler.', 'Ekonomi üretim, dağıtım ve tüketimi düzenler. Piyasa sisteminde fiyat ve özel girişim, planlı sistemde merkezî kararlar öne çıkar; karma sistem farklı araçları birleştirir. Devlet müdahalesinin etkisi maliyet, erişim ve eşitlik kanıtlarıyla sınanır; tek gözlem kesin nedensellik kurmaz.', 'üretim, dağıtım, karma ekonomi'],
 'SOS.11.4.5': ['Bir belediye yeni park için bütçe ayırır. Mahalle sakinleri toplantıda farklı talepler sunar. Kararlar temsilciler ve hukukî kurallar aracılığıyla alınır.', 'Siyaset ortak karar, kaynak dağıtımı ve yönetim işlevlerini yürütür. Temsil, katılım ve meşruiyet kararların toplumla ilişkisini kurar. Taleplerin dinlenmesi katılımı, hukukî denetim yetkinin sınırlandırılmasını gösterir.', 'katılım, temsil, meşruiyet'],
 'SOS.11.4.6': ['İş saatleri değişince ailelerin bakım düzeni etkilenir. Okul ve belediye bakım desteği planlar. Çalışanların eğitime erişimi de yeniden düzenlenir.', 'Ekonomideki çalışma düzeni aile bakımını ve eğitim olanaklarını etkiler. Aile, okul ve yönetimin işlevleri karşılıklı bağımlıdır. Bakım desteği katılımı kolaylaştırabilir; kurumlar bağımsız adalar gibi açıklanamaz.', 'kurum, işlev, karşılıklı bağımlılık'],
 'SOS.11.5.1': ['Bir paylaşım tek bir kişinin davranışını bütün Müslümanlara mal eder. Mahallede bu paylaşıma dayanılarak bazı kişilerin hizmete erişimi engellenir. Başka sakinler doğrulanabilir bilgi ve eşit hakları savunur.', 'Tek kişinin davranışını bir inanç grubuna genellemek kanıtsız stereotipleştirmedir. İnanca dayalı hizmet engeli ayrımcılık oluşturur. İslamofobi önyargı ve dışlama ilişkisi içinde sorgulanır; doğrulanmış bilgi, eşit hak ve karşı örnekler kullanılarak gerekçeli çıkarım yapılır.', 'önyargı, stereotip, ayrımcılık'],
 'SOS.11.5.2': ['Yerel bir işletme başka ülkelerden malzeme alır ve çevrim içi satış yapar. Küresel ulaşım sorunu üretimi geciktirir. Müşteriler farklı kültürlerin ürünleriyle karşılaşır.', 'Küreselleşme ekonomi, iletişim ve kültür ağlarının etkileşimidir. Tedarik zinciri karşılıklı bağımlılığı, çevrim içi satış sınır aşan iletişimi gösterir. Kültürel etkileşim ve ekonomik kırılganlık birlikte değerlendirilir.', 'küreselleşme, tedarik zinciri, bağımlılık'],
 'SOS.11.5.3': ['Bir kurum işe alımda yapay zekâ kullanır. Sistem geçmiş kayıtlarla eğitilir. Bazı adaylar kararın gerekçesini öğrenemez ve itiraz yolu ister.', 'Geçmiş verideki eşitsizlik algoritmik kararlara taşınabilir. Şeffaflık, veri mahremiyeti ve insan denetimi toplumsal sorumlulukla ilişkilidir. Etki farklı grupların sonuçlarıyla incelenir; yapay zekânın otomatik olarak tarafsız olduğu varsayılmaz.', 'algoritmik yanlılık, mahremiyet, şeffaflık'],
 'SOS.12.1.1': ['Bir kentte hava kirliliği ölçülür. Araştırmacılar verileri açıklar, yurttaşlar ulaşım tercihlerinin etkisini tartışır. Belediye veriye dayalı düzenleme planlar.', 'Bilimsel araştırma toplumsal ihtiyaçlardan beslenir ve kararları etkiler. Ölçüm yöntemi, veri, yurttaş katılımı ve yönetim arasındaki ilişki bilgi üretimini açıklar. Toplumsal kullanımda belirsizlikler ve araştırmanın sınırları da paylaşılmalıdır.', 'bilim, veri, toplumsal ihtiyaç'],
 'SOS.12.1.2': ['Bir şirket araştırmayı finanse eder ve olumsuz sonuçların yayımlanmasını istemez. Araştırmacılar yöntem ve verileri bağımsız değerlendirmeye açmak ister.', 'Finansman araştırma gündemini ve yayımlanma koşullarını etkileyebilir. Çıkar çatışmasının açıklanması, bağımsız inceleme ve yayın özgürlüğü güvenilirliği destekler. Bilim ve iktidar ilişkisi somut kanıtlarla sorgulanır; finansman tek başına bulguyu yanlış kılmaz.', 'çıkar çatışması, bağımsızlık, iktidar'],
 'SOS.12.2.1': ['Bir kentte konut kiraları artar. Öğrenciler bunun göç, gelir ve konut arzıyla ilişkisini araştırır. Resmî istatistik ve farklı mahallelerdeki görüşmeler karşılaştırılır.', 'Kira artışı konut arzı, talep ve gelir ilişkisiyle sorgulanabilir. Tarihli istatistikler ve görüşmeler farklı kanıtlar sağlar. Mahalle farkları ve alternatif açıklamalar incelenir; korelasyon tek başına nedensellik değildir. Gerekçeli sonuç araştırmanın sınırlarını içerir.', 'toplumsal sorun, kanıt, nedensellik'],
};

// Bileşenlerin resmî sırasına bağlı, vakayı açıklayan özgün beklenen kanıtlar.
const componentAnswers: Record<string, string[]> = {
 'SOS.11.1.1': ['Comte toplumsal düzeni bilimsel yasalarla açıklamaya yönelirken Durkheim toplumsal olguların bireyi aşan etkisini vurgular.', 'Fabrikalaşma ekonomik, göç ve kentleşme sosyal, Fransız Devrimi siyasal dönüşümü gösterir.', 'Sanayileşme ile dijital dönüşüm hızlı toplumsal değişimde benzeşir; fabrika emeği ile dijital ağların örgütlenmesi farklılaşır.', 'Comte pozitivist toplum bilimini; Durkheim toplumsal olguların nesnel ve toplumsal nedenlerle incelenmesini savunur.'],
 'SOS.11.1.2': ['Merak edilen konu okul kulüplerine katılımın öğrenciler arasında neden farklılaştığıdır.', 'Araştırma sorusu: Ulaşım ve boş zaman olanakları kulübe katılımla nasıl ilişkilidir?', 'Katılım kayıtları, olanakları soran anket ve öğrenci deneyimlerine ilişkin görüşmeler birlikte kullanılabilir.', 'Paylaşımın yazarı, tarihi, örneklemi ve dayandığı veriler denetlenir; okul kayıtları ve görüşmelerle karşılaştırılır.', 'Katılımı yalnız kişisel istekle açıklamak yetersizdir; erişim ve zaman koşulları da doğrulanmış verilerle incelenmelidir.'],
 'SOS.11.1.3': ['Nicel yaklaşım ölçülebilir sıklıkları ve değişkenleri; nitel yaklaşım deneyimlerin anlam ve bağlamını inceler.', 'Anket ve görüşme araştırma sorusuna yönelik sistemli veri toplar; ikisi de yöntem açıklığı ve etik kurallar gerektirir.', 'Yüz kişilik anket kullanım sıklığını sayısallaştırır; on kişilik görüşme kullanım deneyimini derinleştirir ve aynı genelleme kapsamına sahip değildir.'],
 'SOS.11.2.1': ['Osmanlı reformlarında askerî ve idarî sorunlara çözüm arayışı, Cumhuriyet reformlarında yeni devlet ve yurttaşlık düzeninin kuruluşu etkilidir.', 'Hukuk ve yönetim reformları kurumları; eğitim düzenlemeleri meslek ve yurttaşlık rollerini değiştirmiştir.', 'Osmanlı reformları imparatorluk, Cumhuriyet reformları yeni ulus devlet bağlamında değerlendirilir; iki dönemin koşulları özdeş sayılmaz.', 'Modernleşme önce imparatorluğun sorunlarına reformlarla yanıt ararken Cumhuriyet döneminde yeni devletin eğitim ve yurttaşlık kurumlarıyla derinleşmiştir.'],
 'SOS.11.2.2': ['Göç, savaş ve devletin kuruluşu toplumun nasıl örgütleneceği sorununu doğurmuş; Gökalp ve Prens Sabahaddin farklı açıklamalar geliştirmiştir.', 'Tarihsel dönüşüm, toplumsal sorun ve düşünsel yanıt birlikte açıklanır: Gökalp kültürel dayanışmayı, Prens Sabahaddin girişim ve yerinden yönetimi öne çıkarır.'],
 'SOS.11.2.3': ['Kurgu sahnesindeki ücretli iş ve eğitimle yeni mesleğe yönelme modernleşmenin gündelik yaşamdaki görünümleridir.', 'Örnek yorum: Ailenin kentte ücretli işe geçmesi meslek rollerini değiştirirken kuşakların dayanışma beklentilerini yeniden düzenlemektedir.', 'Anlamı koruyan yeniden ifade: Kentte yeni işler ve eğitim olanakları ortaya çıkarken aile büyükleri alışılmış yardımlaşmayı sürdürmek istemektedir.'],
 'SOS.11.3.1': ['Bayram ziyaretleri aidiyet ve dayanışma sağlar; ortak kurallar birlikte yaşamı düzenler, yeni gelenlerin gelenekleri etkileşimi artırır.', 'Kültür ortak değer ve normlarla bütünleşme sağlar; yeni komşularla karşılaşma bu kültürün yorumlanmasına ve değişmesine yol açabilir.'],
 'SOS.11.3.2': ['Aile, okul, belediye ve işletme kurum; ebeveyn ve öğretmen konumları statü, bu konumlardaki beklentiler roldür.', 'Ebeveynin okulda öğretmen ve dernekte üye olması aile, eğitim ve grup ilişkilerinin aynı kişide bağlantı kurduğunu gösterir.'],
 'SOS.11.3.3': ['Gelir ve eğitim olanaklarının farklılaşması tabakalaşmayı, yer ve meslek konumu değişimleri hareketliliği gösterir.', 'Teknisyenin aynı işi başka şehirde yapması yatay, çalışanın yönetici olması dikey hareketliliktir.', 'Eğitim yönetici olma olanağı sağlayabilir; ailelerin farklı eğitim olanakları hareketlilik fırsatlarını eşitsizleştirebilir.'],
 'SOS.11.4.1': ['Bakım ve sorumluluk paylaşımı aile işlevleridir; iki kuşaklı hane çekirdek, üç kuşaklı hane geniş aile örneğidir. Vakada evlilik türünü sınıflandıracak bilgi yoktur; yalnız rıza ve hukuk koşulları belirtilmiştir.', 'Hane büyüklüğünün farklı olması bakım işlevinin yok olduğu anlamına gelmez; her iki ailede sorumluluk paylaşımı bu işlevi gösterir.', 'Sonuç: Aile biçimleri farklılaşabilir, bakım ve dayanışma ortak kalabilir; evlilik kararları rıza ve haklar çerçevesinde değerlendirilmelidir.'],
 'SOS.11.4.2': ['Okulun bilgi ve beceri kazandırması, birlikte çalışma kurallarını öğretmesi eğitim ve toplumsallaşma işlevlerini gösterir.', 'Ulaşım ve materyal eşitsizliği, aynı eğitimin öğrenciler için eşit erişilebilir olmadığına dayanak oluşturur.', 'Sonuç: Eğitim toplumsal katılım ve meslek edinmeyi destekler; fırsat eşitliği için erişim koşulları da iyileştirilmelidir.'],
 'SOS.11.4.3': ['Ortak törenler aidiyetle, ihtiyaç sahiplerine yardım dayanışmayla ilişkilidir; farklı inançların birlikte yaşaması hakların gözetilmesini gerektirir.', 'Din anlam ve dayanışma sağlayan bir kurum olarak açıklanır; bu sosyolojik işlev açıklaması herhangi bir inancın doğruluğu veya üstünlüğü iddiası değildir.'],
 'SOS.11.4.4': ['Varsayım: Üretim ve dağıtım koşulları değiştiğinde ailelerin tüketim tercihleri de değişebilir.', 'Üretim yapan işletme, hizmet dağıtan belediye ve tüketim kararı veren aile ekonomik işleyişteki yapısal unsurlardır.', 'Piyasada özel girişim ve fiyatlar, planlı ekonomide merkezî kararlar, karma sistemde farklı düzenleme araçları birlikte rol oynar.', 'Önerme: Kamu ulaşım desteği erişim maliyetini azaltabilir; iş güvenliği düzenlemesi çalışanların korunmasını destekleyebilir.', 'Önerme, müdahale öncesi/sonrası maliyet ve erişim verileriyle sınanır; fiyat artışı tek başına müdahalenin etkisini kanıtlamaz.'],
 'SOS.11.4.5': ['Park bütçesine kimin karar verdiği ve mahalle taleplerinin nasıl temsil edildiği siyasetin ortak karar ve kaynak dağıtımı işlevini sorgulatır.', 'Toplantıda taleplerin sunulması katılım, temsilcilerin karar alması temsil, hukukî kurallar yetkinin sınırlandırılmasıyla ilişkilidir.', 'Sonuç: Ortak kaynak kararı temsil ve katılım gerektirir; yetki hukukî denetimle sınırlandığında kararların meşruiyeti değerlendirilebilir.'],
 'SOS.11.4.6': ['İş saatlerinin değişmesi aile bakımını etkiler; okul ve belediyenin desteği ekonomi, aile, eğitim ve yönetim arasındaki ilişkiyi gösterir.', 'Kurumlar birlikte bir sistem oluşturur: çalışma düzeni bakım gereksinimini değiştirir, bakım desteği çalışmaya ve eğitime katılımı kolaylaştırabilir.'],
 'SOS.11.5.1': ['Bir kişinin davranışının bütün Müslümanlara genellenmesi ile inanç nedeniyle hizmet engellenmesi arasındaki ilişki sorgulanır.', 'Tek örnek bütün bir gruba ilişkin hüküm için yeterli değildir; genelleme stereotip, hizmet engeli ayrımcılık olarak gerekçelendirilir.', 'Sonuç: Davranışlar kişiye ve doğrulanmış kanıta göre değerlendirilmelidir; inanç grubunun eşit hakları korunmalıdır.'],
 'SOS.11.5.2': ['Uluslararası malzeme alımı, çevrim içi satış, ulaşım ağı ve kültürler arası ürün karşılaşması küreselleşmenin unsurlarıdır.', 'Ulaşım sorununun yerel üretimi geciktirmesi ekonomik bağımlılığı; çevrim içi satış ve ürün karşılaşması iletişim-kültür bağını gösterir.'],
 'SOS.11.5.3': ['İşe alım kararının gerekçesinin açıklanmaması ve geçmiş verinin eşitsizlik taşıma ihtimali şeffaflık ve yanlılık sorunlarını gündeme getirir.', 'Geçmiş kayıtlardaki eşitsizlik modelin kararlarına aktarılabilir; gerekçe ve itiraz yolu eksikliği denetimi zorlaştırır.', 'Sonuç: Farklı grupların sonuçları denetlenmeli, veri mahremiyeti gözetilmeli ve insan incelemesiyle itiraz olanağı sağlanmalıdır.'],
 'SOS.12.1.1': ['Araştırmacı, hava ölçümü, veri, yurttaş ve belediye bilim-toplum ilişkisinin unsurlarıdır.', 'Toplumsal kirlilik sorunu ölçüm araştırmasını yönlendirir; araştırma verisi yurttaş tercihleri ve belediye kararları üzerinde etkili olabilir.'],
 'SOS.12.1.2': ['Finansmanın araştırma gündemi ve olumsuz sonuçların yayımlanması üzerindeki etkisi bilim-güç ilişkisini sorgulatır.', 'Sonuçların bastırılması seçici bilgi sunumuna yol açabilir; bağımsız yöntem/veri incelemesi bu etkiyi sınamaya yardımcı olur.', 'Sonuç: Çıkar çatışması açıklanmalı ve yayın özgürlüğü korunmalıdır; bir araştırmanın fonlanması tek başına bulgusunun yanlış olduğunu göstermez.'],
 'SOS.12.2.1': ['Kira artışının göç, gelir ve konut arzıyla nasıl ilişkili olduğu araştırma problemi olarak belirlenir.', 'Mahalleler ve dönemler karşılaştırılarak arz-talep ve gelir değişimleri incelenir; yalnız birlikte değişim nedensellik kanıtı sayılmaz.', 'Sonuç: Kira artışı birden çok toplumsal koşulla açıklanabilir; tarihlenmiş verilerle desteklenen çıkarım alternatif açıklamaları ve sınırlarını içermelidir.'],
};

type ReasoningCase = { facts: [string, string]; counter: string; alternative: string; check: string; causal: string };
const reasoningCases: Record<string, ReasoningCase> = {
 'SOS.11.1.1': {facts:['fabrikalaşma ve kırdan kente göç','siyasal düzenin devrimle tartışmaya açılması'],counter:'Sanayileşme olmadan da siyasal dönüşüm yaşayan bir toplum düşünülebilir; değişim yalnız fabrikalaşmayla açıklanamaz.',alternative:'Siyasal kurumların değişimi de yeni toplum açıklamalarına duyulan ihtiyacı artırmış olabilir.',check:'Aynı dönemin nüfus, üretim ve hukuk kayıtları düşünürlerin metinleriyle karşılaştırılabilir.',causal:'Fabrika emeği ve kentleşme yeni ilişkiler doğurmuş, bu ilişkileri açıklama ihtiyacı toplum biliminin gelişimini desteklemiştir.'},
 'SOS.11.1.2': {facts:['kulüp katılım kayıtlarının incelenmesi','öğrencilerin zaman ve erişim koşullarının araştırılması'],counter:'Kulübe katılmak isteyen fakat ulaşımı olmayan bir öğrenci, katılımın yalnız istekle açıklanmasına karşı örnektir.',alternative:'Ulaşım ve aile sorumlulukları katılım farkını açıklıyor olabilir.',check:'İstek, ulaşım ve boş zaman bilgileri anket/görüşmeyle toplanıp katılım kayıtlarıyla karşılaştırılabilir.',causal:'Ulaşım engeli veya bakım sorumluluğu, istek bulunsa da kulübe ayrılabilecek zamanı sınırlayabilir.'},
 'SOS.11.1.3': {facts:['yüz kişiye kullanım sıklığının sorulması','on kişiyle deneyim görüşmesi yapılması'],counter:'Sıklık anketinde aynı cevabı veren iki kişinin kullanım gerekçeleri farklı olabilir; sayı tek başına anlamı açıklamaz.',alternative:'Ulaşım deneyimindeki farkı güzergâh ve erişilebilirlik açıklıyor olabilir.',check:'Anket örneklemi ve görüşme seçimi açıklanıp güzergâh bilgileriyle birlikte incelenebilir.',causal:'Soru ve örneklem seçimi elde edilen verinin türünü ve genellemenin kapsamını etkiler.'},
 'SOS.11.2.1': {facts:['Tanzimat dönemindeki hukuk ve yönetim reformları','Cumhuriyet dönemindeki eğitim ve yurttaşlık düzenlemeleri'],counter:'Aynı reformun farklı yerlerde farklı etkiler yaratması, modernleşmenin her yerde tek sonuç doğurduğu iddiasını sınırlar.',alternative:'Eğitim ve hukuk dönüşümünde savaş ve devletin kuruluş koşulları da etkili olabilir.',check:'Dönemlerin hukuk, eğitim ve yönetim belgeleri tarihleri ve uygulama koşullarıyla karşılaştırılabilir.',causal:'Kurumların yeniden düzenlenmesi meslek, yönetim ve yurttaşlık rollerini dönüştürebilir.'},
 'SOS.11.2.2': {facts:['Gökalp’in kültür ve uygarlığı tartışması','Prens Sabahaddin’in girişim ve yönetim örgütlenmesini tartışması'],counter:'Aynı tarihsel soruna iki düşünürün farklı çözüm önermesi, koşulların tek bir görüşü zorunlu kılmadığını gösterir.',alternative:'Düşünürlerin farklı toplum ve yönetim kabulleri görüş ayrılığını açıklayabilir.',check:'Düşünürlerin eserleri ve dönemin toplumsal sorunları tarihsel belgelerle birlikte karşılaştırılabilir.',causal:'Göç ve devletin yeniden kuruluşu toplumun örgütlenmesi sorununu gündeme getirmiş, farklı sosyolojik yanıtları teşvik etmiştir.'},
 'SOS.11.2.3': {facts:['ailenin kentte ücretli işe başlaması','gençlerin eğitimle yeni mesleklere yönelmesi'],counter:'Kentte yaşayıp eski dayanışmasını sürdüren bir aile, kentleşmenin bütün gelenekleri yok ettiği iddiasını sınırlar.',alternative:'Kuşakların farklı eğitim ve meslek deneyimleri aile içi beklenti değişimini açıklayabilir.',check:'Sahnedeki anlatıcı ve bağlam incelenebilir; toplumsal genelleme için ayrıca dönem araştırmaları ve kayıtlar gerekir.',causal:'Ücretli iş ve eğitim olanakları aile üyelerinin meslek rollerini ve beklentilerini değiştirebilir.'},
 'SOS.11.3.1': {facts:['bayram ziyaretleri ve ortak yemekler','yeni komşularla geleneklerin paylaşılması'],counter:'Aynı geleneği farklı biçimde yorumlayan komşular, ortak kültürün bütün davranışları aynılaştırdığı iddiasını sınırlar.',alternative:'Yeni komşularla karşılaşma ortak kuralların yeniden yorumlanmasını açıklayabilir.',check:'Eski ve yeni komşuların ortak etkinlik deneyimleri görüşme ve gözlemle karşılaştırılabilir.',causal:'Ortak etkinlikler etkileşimi artırarak aidiyet ve dayanışmayı destekleyebilir.'},
 'SOS.11.3.2': {facts:['aile, okul, belediye ve işletmelerin birlikte çalışması','bir kişinin ebeveyn, öğretmen ve üye rollerini üstlenmesi'],counter:'Aynı meslekteki kişilerin aile rollerinin farklı olması, tek statünün bütün davranışları belirlediği iddiasını sınırlar.',alternative:'Kurumların farklı beklentileri aynı kişinin rol davranışlarını açıklayabilir.',check:'Kurumların görev tanımları ve kişinin farklı ortamlardaki rol deneyimleri karşılaştırılabilir.',causal:'Bir kurumdaki görev veya zaman düzeni kişinin diğer kurumlardaki sorumluluklarını etkileyebilir.'},
 'SOS.11.3.3': {facts:['teknisyenin başka şehirde aynı işi yapması','çalışanın eğitimini tamamlayıp yönetici olması'],counter:'Diploma aldığı hâlde meslek konumu değişmeyen kişi, eğitimin her zaman dikey hareketlilik sağladığı iddiasını sınırlar.',alternative:'İş piyasasındaki açık pozisyonlar ve ailelerin olanakları hareketlilik farkını açıklayabilir.',check:'Eğitim, meslek ve gelir değişimleri zaman içinde izlenip farklı grupların olanaklarıyla karşılaştırılabilir.',causal:'Eğitime eşitsiz erişim meslek ilerlemesi fırsatlarını da eşitsizleştirebilir.'},
 'SOS.11.4.1': {facts:['iki kuşaklı ve üç kuşaklı haneler','her iki ailede bakım ve sorumluluk paylaşımı'],counter:'Çekirdek bir ailenin yakınlarıyla yoğun dayanışması, bakımın yalnız geniş ailede bulunduğu iddiasını sınırlar.',alternative:'Hane biçiminin yanında gelir, çalışma zamanı ve yakınlık ilişkileri bakım paylaşımını açıklayabilir.',check:'Farklı hanelerde bakım görevleri ve zaman kullanımı görüşmelerle karşılaştırılabilir; evlilik türü için ayrıca bilgi toplanmalıdır.',causal:'Hane ve çalışma düzenindeki değişim bakım sorumluluklarının paylaşımını etkileyebilir.'},
 'SOS.11.4.2': {facts:['okulun bilgi ve meslek becerileri kazandırması','ulaşım ve materyal olanaklarının farklılaşması'],counter:'Becerili olduğu hâlde ulaşım nedeniyle okula erişemeyen öğrenci, başarının yalnız bireysel çabaya bağlı olduğu iddiasını sınırlar.',alternative:'Erişim ve materyal olanakları katılım ve başarı farkını açıklayabilir.',check:'Ulaşım, materyal erişimi ve katılım verileri farklı öğrenci gruplarında birlikte incelenebilir.',causal:'Ulaşım engelleri ve materyal eksikliği eğitim olanaklarından yararlanmayı sınırlayabilir.'},
 'SOS.11.4.3': {facts:['ortak dinî törenler','ihtiyaç sahiplerine yardım'],counter:'Farklı inançlara sahip kişilerin ortak yardımlaşması, dayanışmanın yalnız aynı inanç içinde mümkün olduğu iddiasını sınırlar.',alternative:'Komşuluk ve ortak ihtiyaçlar da yardımlaşmayı açıklayabilir.',check:'Tören ve yardım deneyimleri farklı inanç gruplarının gönüllü görüşmeleriyle incelenebilir.',causal:'Ortak ritüel ve yardımlaşma etkileşimi artırarak topluluğa aidiyeti destekleyebilir.'},
 'SOS.11.4.4': {facts:['özel işletmelerin üretim yapması','belediye ulaşımı ve devlet düzenlemeleri'],counter:'Fiyat artarken tüketimini azaltan bir aile, tüketimin değişen maliyetten bağımsız olduğu iddiasını sınırlar.',alternative:'Gelir ve tedarik koşulları da tüketim değişimini açıklayabilir.',check:'Gelir, fiyat, erişim ve tüketim verileri müdahale öncesi/sonrası ve benzer gruplar arasında karşılaştırılabilir.',causal:'Ulaşım maliyeti veya fiyat artışı ailelerin ayırabildiği bütçeyi ve tüketim tercihlerini etkileyebilir.'},
 'SOS.11.4.5': {facts:['park için bütçe ayrılması','mahalle taleplerinin toplantıda sunulması'],counter:'Talebini sunabildiği hâlde karar gerekçesini öğrenemeyen yurttaş, toplantıya katılmanın tek başına etkili temsil sağladığı iddiasını sınırlar.',alternative:'Temsil kuralları ve bütçe sınırlılıkları hangi talebin karşılandığını açıklayabilir.',check:'Toplantı tutanakları, karar gerekçeleri ve bütçe belgeleri taleplerle karşılaştırılabilir.',causal:'Katılım ve temsil süreçleri ortak kaynak kararlarının kimleri ve hangi ihtiyaçları gözettiğini etkileyebilir.'},
 'SOS.11.4.6': {facts:['iş saatleri değişince bakım düzeninin etkilenmesi','okul ve belediyenin bakım desteği planlaması'],counter:'Çalışma saati değiştiğinde bakım düzenini koruyabilen bir aile, aynı ekonomik değişimin her haneyi aynı etkilediği iddiasını sınırlar.',alternative:'Ailelerin yakın desteği ve gelir farkı bakım gereksinimini açıklayabilir.',check:'Çalışma saatleri, bakım zamanı ve destek erişimi farklı hanelerde karşılaştırılabilir.',causal:'İş saatlerinin değişmesi bakım gereksinimini artırabilir; kurum desteği çalışmaya ve eğitime katılımı kolaylaştırabilir.'},
 'SOS.11.5.1': {facts:['tek davranışın bütün Müslümanlara genellenmesi','inanç nedeniyle hizmet erişiminin engellenmesi'],counter:'İddia edilen davranışı göstermeyen Müslüman kişiler, tek örnekten bütün gruba hüküm çıkarılmasını geçersizleştirir.',alternative:'Yanlış bilgi ve dışlayıcı grup söylemleri hizmet engelini açıklayabilir.',check:'Paylaşımın kaynağı ve hizmet engeline ilişkin somut kayıtlar incelenerek iddia ile uygulama ayrılabilir.',causal:'Kanıtsız genelleme önyargıyı güçlendirip dışlayıcı uygulamaları meşrulaştırmaya çalışabilir.'},
 'SOS.11.5.2': {facts:['başka ülkelerden malzeme alınması','küresel ulaşım sorununun yerel üretimi geciktirmesi'],counter:'Yerel tedarikle üretimini sürdüren bir işletme, bütün işletmelerin aynı küresel kesintiden eşit etkilendiği iddiasını sınırlar.',alternative:'Tedarik çeşitliliği ve stok düzeyi işletmelerin etkilenme farkını açıklayabilir.',check:'Tedarik kaynakları, stok ve gecikme kayıtları farklı işletmeler arasında karşılaştırılabilir.',causal:'Sınır aşan tedarik bağımlılığı, ulaşım kesintisinin yerel üretime aktarılmasına yol açabilir.'},
 'SOS.11.5.3': {facts:['sistemin geçmiş işe alım kayıtlarıyla eğitilmesi','adayların gerekçeyi öğrenememesi ve itiraz istemesi'],counter:'İnsan denetimiyle düzeltilen bir algoritmik karar, otomatik kararın değişmez veya her zaman tarafsız olduğu iddiasını sınırlar.',alternative:'Eğitim verisinin eksik temsil edilmesi veya kullanılan ölçütler grup farklarını açıklayabilir.',check:'Model ölçütleri ve farklı aday gruplarının sonuçları kişisel veriler korunarak denetlenebilir.',causal:'Geçmiş kayıttaki eşitsizlik öğrenilen örüntülerle yeni kararlara aktarılabilir; itiraz eksikliği hatanın düzeltilmesini zorlaştırır.'},
 'SOS.12.1.1': {facts:['hava kirliliğinin ölçülüp verilerin açıklanması','yurttaş ve belediyenin ulaşım düzenlemesini tartışması'],counter:'Bilimsel bilgi açıklandığı hâlde ulaşım tercihini değiştiremeyen yurttaş, bilginin tek başına davranış değişimi sağladığı iddiasını sınırlar.',alternative:'Ulaşım maliyeti ve seçeneklerin erişilebilirliği tercihleri açıklayabilir.',check:'Ölçüm yöntemleri ile ulaşım erişimi ve kullanım verileri birlikte karşılaştırılabilir.',causal:'Toplumsal kirlilik sorunu araştırma ihtiyacı doğurur; açıklanan veri kamu kararlarına dayanak sağlayabilir.'},
 'SOS.12.1.2': {facts:['şirketin olumsuz sonuçların yayımlanmasını istememesi','araştırmacıların bağımsız inceleme istemesi'],counter:'Fonlanan fakat yöntem ve verisi bağımsız incelemede doğrulanan araştırma, fonlanan her bulgunun yanlış olduğu iddiasını sınırlar.',alternative:'Yayın kısıtları ve çıkar çatışması kamuya ulaşan bilginin seçilmesini açıklayabilir.',check:'Finansman koşulları, yayınlanan/yayımlanmayan sonuçlar ve yöntemler bağımsız incelemeyle karşılaştırılabilir.',causal:'Yayın baskısı olumsuz sonuçların görünürlüğünü azaltarak bilimsel bilginin toplumsal kullanımını etkileyebilir.'},
 'SOS.12.2.1': {facts:['konut kiralarının artması','göç, gelir ve konut arzının birlikte araştırılması'],counter:'Göç artmadan kira yükselen bir mahalle, kira artışının yalnız göçle açıklanması iddiasını sınırlar.',alternative:'Konut arzı ve gelir değişimi kira artışını açıklayabilir.',check:'Mahallelere ve dönemlere ait kira, gelir, göç ve konut arzı verileri karşılaştırılabilir.',causal:'Talebin arzdan hızlı artması kira baskısı yaratabilir; ancak bu ilişki gelir ve diğer koşullarla birlikte sınanmalıdır.'},
};


const caseInstitutions: Record<string, string> = {
 'SOS.11.1.1':'üretim ve yönetim', 'SOS.11.1.2':'okul', 'SOS.11.1.3':'ulaşım hizmeti',
 'SOS.11.2.1':'hukuk ve eğitim', 'SOS.11.2.2':'devlet ve yönetim', 'SOS.11.2.3':'aile ve eğitim',
 'SOS.11.3.1':'aile ve mahalle toplulukları', 'SOS.11.3.2':'aile, okul ve belediye', 'SOS.11.3.3':'eğitim ve ekonomi',
 'SOS.11.4.1':'aile', 'SOS.11.4.2':'eğitim', 'SOS.11.4.3':'din', 'SOS.11.4.4':'ekonomi ve kamu yönetimi',
 'SOS.11.4.5':'siyaset ve belediye', 'SOS.11.4.6':'aile, ekonomi ve eğitim', 'SOS.11.5.1':'hizmet sunumu ve hukuk',
 'SOS.11.5.2':'ekonomi', 'SOS.11.5.3':'ekonomi ve işe alım', 'SOS.12.1.1':'bilim ve kamu yönetimi',
 'SOS.12.1.2':'bilim ve finansman', 'SOS.12.2.1':'ekonomi ve konut hizmetleri',
};
const caseSolutions: Record<string, string> = {
 'SOS.11.1.1':'Toplumsal dönüşüm farklı tarihsel kayıtlarla birlikte incelenmeli; değişimin tek nedene indirgenmesi önlenmelidir.',
 'SOS.11.1.2':'Kulüp saatleri ve ulaşım desteği katılım koşulları incelenerek düzenlenebilir; etkisi katılım verileriyle izlenmelidir.',
 'SOS.11.1.3':'Sıklık anketi ve deneyim görüşmesi birlikte kullanılabilir; sonuçların kapsamı örnekleme göre açıklanmalıdır.',
 'SOS.11.2.1':'Reformları açıklarken her dönemin koşullarını gösteren karşılaştırma tablosu kullanılabilir; tek tip modernleşme genellemesi sınırlanır.',
 'SOS.11.2.2':'Farklı düşünürlerin yanıtları tarihsel sorunlarla birlikte karşılaştırılabilir; görüşlerden biri bütün toplumun tek açıklaması sayılmaz.',
 'SOS.11.2.3':'Edebî yorum dönem bilgisiyle desteklenebilir; kurgu ile topluma ilişkin genellenebilir kanıt ayrılır.',
 'SOS.11.3.1':'Ortak etkinliklerde farklı geleneklere katılım olanağı sağlanabilir; aidiyet kadar dışlanma deneyimleri de izlenmelidir.',
 'SOS.11.3.2':'Kurumlar arasındaki görev ve zaman düzeni birlikte planlanabilir; bir roldeki değişimin diğer sorumluluklara etkisi değerlendirilir.',
 'SOS.11.3.3':'Eğitime erişim desteği fırsat farkını azaltabilir; meslek hareketliliği farklı gruplarda zaman içinde izlenmelidir.',
 'SOS.11.4.1':'Bakım desteği hane biçimine üstünlük atfetmeden gereksinime göre düzenlenebilir; rıza ve eşit haklar korunmalıdır.',
 'SOS.11.4.2':'Ulaşım ve materyal desteği sağlanabilir; katılım ve erişim üzerindeki etkisi farklı öğrenci gruplarında izlenmelidir.',
 'SOS.11.4.3':'Yardımlaşma farklı inançların hakları gözetilerek düzenlenebilir; katılımın gönüllülüğü ve dışlanma yaşanmaması değerlendirilmelidir.',
 'SOS.11.4.4':'Ulaşım desteği ve düzenlemeler maliyet, erişim ve kamu bütçesine etkileriyle değerlendirilerek uygulanabilir.',
 'SOS.11.4.5':'Karar gerekçeleri ve bütçe açık paylaşılabilir, farklı mahallelerin talepleri temsil edilebilir; erişim ve katılım izlenmelidir.',
 'SOS.11.4.6':'Okul ve belediye bakım desteğini çalışma saatleriyle birlikte planlayabilir; ailelerin çalışmaya/eğitime katılımı değerlendirilir.',
 'SOS.11.5.1':'Kanıtsız paylaşım düzeltilmeli ve hizmete eşit erişim sağlanmalıdır; uygulamanın ayrımcılığı giderip gidermediği izlenmelidir.',
 'SOS.11.5.2':'Tedarik kaynakları çeşitlendirilebilir; maliyet ve gecikmeye etkisi işletme kayıtlarıyla karşılaştırılmalıdır.',
 'SOS.11.5.3':'Karar gerekçesi ve itiraz yolu sağlanabilir; insan denetimi, veri mahremiyeti ve grup sonuçları birlikte değerlendirilmelidir.',
 'SOS.12.1.1':'Ölçüm sonuçları açık paylaşılabilir ve erişilebilir ulaşım seçenekleri geliştirilebilir; kullanım ve kirlilik değişimi izlenmelidir.',
 'SOS.12.1.2':'Çıkar çatışması açıklanmalı, sonuçların bağımsız incelemesi ve yayımlanması korunmalıdır; veri seçiciliği denetlenmelidir.',
 'SOS.12.2.1':'Konut arzı ve erişim desteği gereksinim verilerine göre planlanabilir; kira, bütçe ve farklı gruplara etkiler birlikte değerlendirilmelidir.',
};

function expectedVariation(index: number, evidence: ReasoningCase, concepts: string, baseAnswer: string, institution: string, solution: string) {
 const [first, second] = evidence.facts;
 const [conceptA, conceptB] = concepts.split(', ');
 const responses = [
  `İki dayanak: (1) ${first}; (2) ${second}. Bu bilgiler şu açıklamayı destekler: ${evidence.causal}`,
  `Karşı örnek: ${evidence.counter} Bu nedenle açıklama bütün durumlara koşulsuz genellenemez.`,
  `Alternatif açıklama: ${evidence.alternative} Sınama: ${evidence.check}`,
  `Neden–sonuç ilişkisi: ${evidence.causal} Dayanak: ${first}; ${second}. Bu bağın kesin nedensellik sayılması ek kanıt gerektirir.`,
  `Başka bir toplumsal bağlam için karşılaştırma: ${evidence.counter} Bu örnek, ${first} bilgisinden çıkarılan sonucun farklı koşullarda sınırlandırılması gerektiğini gösterir.`,
  `Gözlem bilgisi: ${first}. Açıklayıcı iddia: ${evidence.causal} İddia, gözlemin aktarılmasından farklıdır; doğrulanması için ${evidence.check}`,
  `Eksik bilgi: ${evidence.alternative} açıklamasını diğer açıklamadan ayıracak veriler vakada verilmemiştir. Toplama yolu: ${evidence.check}`,
  `Sonucu değiştirebilecek koşul: ${evidence.counter} Bu koşulda ilk genelleme daraltılır; ${evidence.alternative} açıklaması ayrıca incelenir.`,
  `Kavram ilişkisi (${conceptA} – ${conceptB}): ${baseAnswer} Somut örnek: ${first}; ${second}.`,
  `Varsayım: ${evidence.alternative} Veriyle karşılaştırma: ${evidence.check} Varsayım veri desteklemezse değiştirilir; başlangıçta doğrulanmış olgu sayılmaz.`,
  `Farklı grubun deneyimi için karşılaştırma: ${evidence.counter} Bu deneyim, ${first} bilgisinin herkes için aynı sonuç doğurmadığını gösteren bir bakış açısıdır.`,
  `Değişim ve süreklilik için ilk değerlendirme: ${baseAnswer} ${first} ile ${second} birlikte ele alınır. Zaman içindeki devamlılığı kesinleştirmek için dönem karşılaştırması gerekir: ${evidence.check}`,
  `Bireysel açıklama kişinin tercihini merkeze alır; toplumsal açıklama ${institution} koşullarını da içerir. Vakadaki yapısal ilişki: ${evidence.causal} Tek kişilik açıklamanın sınırı: ${evidence.counter}`,
  `Kurum etkisi (${institution}): ${evidence.causal} Somut dayanak: ${first}; ${second}. Kurumun etkisi yalnız kişisel özelliklere indirgenmez.`,
  `Destekleyen bilgi: ${first}. Sınırlayan karşı örnek: ${evidence.counter} Destek belirli bağlamı açıklarken karşı örnek koşulsuz genellemeyi sınırlar.`,
  `İlk gözlenen etki ${first} ile ilgilidir. Daha uzun süreçte sınanacak olası etki: ${evidence.causal} Uzun dönem sonucu vakadan kesinleştirilemez; ${evidence.check}`,
  `İki kaynak: ${first} hakkında birincil kayıt/deneyim bilgisi ve ${second} hakkında bağımsız karşılaştırma verisi. Birincil kaynak doğrudan bağlam sağlar ama temsil sınırı olabilir; bağımsız kaynak denetim sağlar ama farklı yöntem kullanabilir. Tarih, yöntem ve örneklem açıklığı karşılaştırılır. Sınama yolu: ${evidence.check}`,
  `Genelleme, örneklemin ilgili grupları temsil ettiği ve benzer koşulların bulunduğu durumlarla sınırlandırılmalıdır. Sınır örneği: ${evidence.counter} Kapsamı denetleme: ${evidence.check}`,
  `Çözüm önerisi ve etki değerlendirmesi: ${solution} Kanıt yolu: ${evidence.check}`,
  `Araştırma sorusu: Bu vakada ${conceptA} ile ${conceptB} arasındaki ilişki hangi koşullarda değişir? Yanıtlama yolu: ${evidence.check} Önerilen açıklama: ${evidence.alternative}`,
 ];
 const response = responses[index];
 if (!response) throw new Error('Soru varyantına ait cevap anahtarı bulunamadı.');
 return response;
}

type Input = { unitCode: string; outcomeCode: string; ordinal: number; kind: string; level: string; points: number; datasetVersion: string; mode: string; profile: string };
export function generateSociologyExamContent(input: Input) {
 if (input.datasetVersion !== sociology2026Package.manifest.datasetVersion) throw new Error('Sosyoloji sınavı için doğrulanmış 2026.1 gerekir.');
 if (!['text','short','open','scenario'].includes(input.kind) || !['standard','bep'].includes(input.mode)) throw new Error('Geçersiz soru türü veya sınav modu.');
 const unit = sociology2026Package.units.find(u=>u.code === input.unitCode);
 const outcome = unit?.outcomes.find(o=>o.code === input.outcomeCode);
 const components = outcome?.processComponents;
 const content = contexts[input.outcomeCode];
 if (!components?.length || !content || !Number.isInteger(input.ordinal) || input.ordinal < 0) throw new Error('Geçersiz Sosyoloji ünite/çıktı/bileşen eşleşmesi.');
 const componentIndex = input.ordinal % components.length;
 const component = components[componentIndex];
 const expectedComponent = componentAnswers[input.outcomeCode]?.[componentIndex];
 const evidence = reasoningCases[input.outcomeCode];
 const institution = caseInstitutions[input.outcomeCode];
 const solution = caseSolutions[input.outcomeCode];
 if (componentAnswers[input.outcomeCode]?.length !== components.length || !expectedComponent || !evidence || !institution || !solution) throw new Error('Sosyoloji bileşenine ait değerlendirme kanıtı eksik.');
 const [context, answer, concepts] = content;
 const tasks: Record<string,string> = {understand:'İlgili kavramları açıklayınız.',apply:'Kavramları bu örneğe uygulayınız.',analyze:'İlişkileri ve dayanaklarını çözümleyiniz.',evaluate:'Kanıtın yeterliğini ve alternatif açıklamayı değerlendiriniz.',create:'Bu konuda kanıtla sınanabilecek bir araştırma sorusu ve veri toplama planı oluşturunuz.'};
 if (!tasks[input.level]) throw new Error('Geçersiz bilişsel düzey.');
 const variations = ['Örnekten iki dayanak seçiniz.', 'Olası bir karşı örnekle açıklamanızın sınırını belirtiniz.', 'Bir alternatif açıklama ve onu sınayacak kanıt belirtiniz.', 'Bir neden ile bir sonucu ayırarak açıklayınız.', 'Örneğin başka bir toplumsal bağlama taşınmasını tartışınız.', 'Bir iddia ile gözlem bilgisini ayırınız.', 'Eksik bilgiyi ve onu toplama yolunu belirtiniz.', 'Sonucun hangi koşullarda değişebileceğini tartışınız.', 'İki kavram arasındaki ilişkiyi bir örnekle açıklayınız.', 'Bir varsayımı açıkça belirtip verilerle karşılaştırınız.', 'Farklı bir toplumsal grubun bakış açısını gerekçelendiriniz.', 'Örnekteki değişim ile sürekliliği ayırt ediniz.', 'Bireysel açıklama ile toplumsal açıklamayı karşılaştırınız.', 'Bir kurumun etkisini somut kanıtla tartışınız.', 'İddianızı destekleyen ve sınırlayan birer bilgi seçiniz.', 'Kısa vadeli ve uzun vadeli etkileri ayırt ediniz.', 'Kullanılabilecek iki bilgi kaynağını güvenilirlik açısından karşılaştırınız.', 'Bir genellemenin geçerli olabileceği koşulları belirtiniz.', 'Bir çözüm önerisini olası toplumsal etkileriyle değerlendiriniz.', 'Örneğe ilişkin bir soru oluşturup onu yanıtlama yolunu açıklayınız.'];
 const variationIndex = Math.floor(input.ordinal / components.length);
 const variation = variations[variationIndex];
 if (!variation) throw new Error('Bu çıktı için tekrarsız soru kapasitesi aşıldı. Soru kapsamını genişletiniz.');
 const expectedTask = expectedVariation(variationIndex, evidence, concepts, answer, institution, solution);
 const levelEvidence: Record<string, string> = {
  understand: `Kavram açıklaması: ${answer}`,
  apply: `Vaka uygulaması: ${expectedComponent}`,
  analyze: `Çözümleme: ${evidence.causal} Dayanaklar: ${evidence.facts.join('; ')}.`,
  evaluate: `Değerlendirme: ${evidence.facts.join('; ')} açıklamayı destekler. Sınır: ${evidence.counter} Alternatif: ${evidence.alternative}`,
  create: `Araştırma örneği: ${concepts.split(', ')[0]} ile ${concepts.split(', ')[1]} ilişkisi hangi koşullarda değişir? Veri planı: ${evidence.check} Farklı durumlar karşılaştırılır; kişilerden veri toplanıyorsa gönüllülük, anonimlik ve mahremiyet korunur.`,
 };
 const scenarioTasks: Record<string, string> = {
  understand: `Vakada ${institution} ile ilgili durumu açıklayınız ve metinden bir kanıt seçiniz. Öneri: “${solution}” Hangi ihtiyaca yanıt verdiğini belirtiniz.`,
  apply: `Vakada ${institution} ile ilgili duruma uygun kavramı uygulayınız; somut kanıt kullanarak uygulanabilecek bir öneri belirtiniz.`,
  analyze: `Vakada ${institution} ile ilgili durumu neden ve sonuçlarıyla çözümleyiniz; somut kanıt kullanarak bir önerinin hangi ilişkiyi etkileyebileceğini açıklayınız.`,
  evaluate: `Vakaya ilişkin şu öneriyi inceleyiniz: “${solution}” Somut kanıt kullanarak önerinin güçlü yönünü, sınırını ve etkisini değerlendirmek için gereken bilgiyi belirtiniz.`,
  create: `Vakada ${institution} ile ilgili duruma somut kanıt kullanarak bir öneri geliştiriniz; olası etkisini ve bu etkiyi sınayacak veri toplama yolunu tasarlayınız.`,
 };
 const scenarioTask = input.kind === 'scenario' ? `Vaka görevi: ${scenarioTasks[input.level]}` : '';
 const scenarioAnswer = input.kind === 'scenario'
  ? `\nVaka değerlendirmesi: ${expectedComponent} Dayanaklar: ${evidence.facts.join('; ')}. İlişki: ${evidence.causal}\nÖneri ve olası etkileri: ${solution} Değerlendirmenin sınırı: ${evidence.counter} Etkiyi sınama yolu: ${evidence.check}`
  : '';
 const focus = `İnceleme odağı: ${component.description}`;
 let passage = input.kind === 'text' ? context : '';
 let text = `${input.kind === 'text' ? '' : `${context}\n`}${focus}\n${tasks[input.level]} Yanıtınızı örnekteki bilgilerle gerekçelendiriniz. ${variation}${input.kind === 'short' ? ' Kısa ve öz yanıt veriniz.' : ''}`;
 if (scenarioTask) text += `\n${scenarioTask}`;
 let fontSize = 22;
 if (input.mode === 'bep') {
  switch(input.profile) {
   case 'reading': passage = passage.replaceAll('. ', '.\n\n'); text = text.replaceAll('. ', '.\n'); text = `${text}\n1. Örneği bölüm bölüm okuyunuz.\n2. Odağı izleyip yanıtınızı veriniz.`; break;
   case 'writing': text += '\nYanıtınızı maddelerle veya öğretmeninizin kaydettiği sözlü anlatımla verebilirsiniz. Cümle başlatıcı: Bu örnekte … çünkü …'; break;
   case 'attention': text += '\nÖnce örneği inceleyiniz. Ardından yalnız bu soruya yanıt veriniz. Gerektiğinde öğretmeninizle kısa ara planlayınız.'; break;
   case 'cognitive': text += `\nKavram desteği: ${concepts}. Önce ilgili kavramı seçiniz; ardından örnekle bağlantısını kurunuz.`; break;
   case 'visual': fontSize = 32; break;
   default: throw new Error('Geçersiz BEP sunum profili.');
  }
 }
 return {passage,text,answer:`Bileşen ${component.step} için örnek yanıt: ${expectedComponent}\n${levelEvidence[input.level]}\nVaryant görevi için beklenen yanıt: ${expectedTask}${scenarioAnswer}`,
  criterion:`${focus} • Kavram ve vaka kanıtı: %40 • Bileşene ve bilişsel göreve ilişkin gerekçeli açıklama${scenarioTask ? `; ${scenarioTask}` : ''}: %40 • Varyant görevinin (${variation}) gerekçeli tamamlanması: %20. Eşdeğer gerekçeli yanıtlar kabul edilir; sunum biçimi ayrıca puan kaybettirmez.`,
  contentOrdinal:input.ordinal,componentStep:component.step,componentDescription:component.description,fontSize};
}
export function validSociologyExamTrace(unitCode: string, outcomeCode: string, step?: string, description?: string) {
 return sociology2026Package.units.find(u=>u.code === unitCode)?.outcomes.find(o=>o.code === outcomeCode)?.processComponents?.some(c=>c.step === step && c.description === description) ?? false;
}

// B kitapçığı için A sorusunun karşılığı: aynı çıktı ve süreç bileşeni, A'da ve B'de daha önce kullanılmamış sonraki varyant.
export function sociologyParallelOrdinal(unitCode: string, outcomeCode: string, ordinal: number, usedOrdinals: Iterable<number>) {
  const components = sociology2026Package.units.find(u=>u.code === unitCode)?.outcomes.find(o=>o.code === outcomeCode)?.processComponents;
  if (!components?.length || !Number.isInteger(ordinal) || ordinal < 0) throw new Error('Geçersiz Sosyoloji ünite/çıktı/bileşen eşleşmesi.');
  const used = new Set(usedOrdinals);
  const component = ordinal % components.length;
  let variation = Math.floor(ordinal / components.length) + 1;
  while (used.has(variation * components.length + component)) variation += 1;
  return variation * components.length + component;
}
