import { sociology2026Package } from '../../../src/curriculum-packages/sociology-2026.ts';

// Öğretmen incelemesine sunulan özgün örneklerdir; resmî soru bankası değildir.
const contexts: Record<string, [string, string, string]> = {
 'SOS.11.1.1': ['Sanayileşme ile fabrikalar büyür ve kırdan kente göç artar. Fransız Devrimi siyasal düzeni tartışmaya açar. Comte toplumu bilimsel yöntemle incelemeyi, Durkheim toplumsal olguları açıklamayı önerir.', 'Sanayileşme iş bölümü ve kentleşmeyi, devrim yurttaşlık ve yönetim ilişkilerini dönüştürmüştür. Comte pozitivist bir toplum bilimi arar; Durkheim bireyi aşan toplumsal olgulara odaklanır. Bugünkü dijital dönüşümle ortak yön hızlı değişimdir; üretim ve iletişim araçları farklıdır.', 'sanayileşme, kentleşme, toplumsal olgu'],
 'SOS.11.1.2': ['Bir sınıfta öğrenciler okul kulüplerine katılımın neden farklılaştığını merak eder. Bir sosyal medya paylaşımı bunu yalnız kişisel isteğe bağlar. Öğrenciler anket, görüşme ve okul kayıtlarını birlikte incelemeyi planlar.', 'Araştırma sorusu, kulübe katılım ile zaman ve erişim olanaklarının ilişkisi olabilir. Anket yaygınlığı, görüşme deneyimleri, kayıtlar katılımı gösterir. Kaynak tarihi, örneklem ve yöntem denetlenmeden paylaşım güvenilir sayılmaz; farklı kaynaklarla desteklenen sonuç çıkarılır.', 'araştırma sorusu, örneklem, kaynak güvenilirliği'],
 'SOS.11.1.3': ['Araştırmacı yüz kişiye toplu taşıma kullanım sıklığını sorar. Ardından on kişiyle ulaşım deneyimleri üzerine ayrıntılı görüşme yapar. Sayısal sıklıklarla kişilerin deneyim anlatıları aynı sorun hakkında bilgi verir.', 'Nicel çalışma ölçülebilir sıklık ve değişken ilişkilerine; nitel çalışma deneyimlerin anlamına ve bağlamına odaklanır. İkisi de sistemli veri toplar. Standart anket karşılaştırılabilir sayılar, görüşme derinlik sağlar; tek başına küçük görüşme grubu tüm topluma genellenmez.', 'nicel yöntem, nitel yöntem, genelleme'],
 'SOS.11.2.1': ['Tanzimat döneminde hukuk ve yönetim reformları gündeme gelir. Cumhuriyet döneminde eğitim ve yurttaşlık kurumları yeniden düzenlenir. Bu dönüşümler farklı tarihsel koşullarda gerçekleşir.', 'Osmanlı reformları askerî, idarî ve ekonomik sorunlara çözüm arayışıyla bağlantılıdır. Cumhuriyet reformları ulus devlet ve yurttaşlık kurumlarının kuruluşuyla ilişkilidir. Eğitim ve hukuk değişimleri toplumsal rolleri etkiler; iki dönemin neden ve sonuçları kendi bağlamlarında değerlendirilir.', 'modernleşme, reform, yurttaşlık'],
 'SOS.11.2.2': ['Göç, savaş ve devletin yeniden kuruluşu Türkiye’de toplumsal sorunları gündeme getirir. Ziya Gökalp kültür ve uygarlık ilişkisini, Prens Sabahaddin bireysel girişim ve yönetimin örgütlenmesini tartışır.', 'Türkiye’de sosyoloji toplumsal dönüşüm sorunlarına yanıt arayışı içinde gelişmiştir. Gökalp kültürel bütünleşme ve dayanışmaya, Prens Sabahaddin bireysel girişim ve yerinden yönetime önem verir. Farklı yaklaşımlar dönemin toplum ve yönetim tartışmalarıyla birlikte açıklanır.', 'kültür, uygarlık, toplumsal dönüşüm'],
 'SOS.11.2.3': ['Kurgu bir roman sahnesinde köyden kente gelen aile ücretli işe başlar. Gençler eğitimle yeni mesleklere yönelirken aile büyükleri eski dayanışma ilişkilerini sürdürmeye çalışır.', 'Sahne kentleşme, ücretli emek ve kuşaklar arası rol değişimini gösterir. Aile içi dayanışma sürerken meslek ve eğitim beklentileri değişir. Edebî anlatı bu dönüşümleri anlamaya yardımcı olur; kurgu tüm toplumun istatistiksel kanıtı olarak kullanılmaz.', 'kentleşme, kuşak, rol'],
 'SOS.11.3.1': ['Bir mahallede bayram ziyaretleri ve ortak yemekler sürdürülür. Yeni gelen komşular kendi geleneklerini paylaşır. Ortak kurallar birlikte yaşarken yeniden yorumlanır.', 'Kültür değer, norm ve semboller aracılığıyla aidiyet ve dayanışma sağlar. Geleneklerin paylaşılması toplumsallaşmayı destekler; farklı yorumlar kültürel değişimi gösterir. Kültür durağan değildir ve toplumsal ilişkilerle karşılıklı etkileşir.', 'değer, norm, aidiyet'],
 'SOS.11.3.2': ['Bir yerleşimde aile, okul, belediye ve işletmeler birlikte çalışır. Bir kişi evde ebeveyn, okulda öğretmen, dernekte üye rollerini üstlenir.', 'Toplumsal yapı kurumları, grupları, statü ve rolleri içerir. Okul eğitim, işletme üretim, belediye hizmet işlevlerini yürütür. Aynı kişinin farklı rolleri kurumlar arasındaki bağlantıyı gösterir; bir kurumun değişmesi diğerlerini etkileyebilir.', 'kurum, statü, rol'],
 'SOS.11.3.3': ['Bir teknisyen farklı şehirde aynı işi yapar. Başka bir çalışan eğitimini tamamlayıp yönetici olur. Ailelerin gelirleri ve eğitim olanakları farklıdır.', 'Aynı konumdaki yer değişimi yatay, daha üst meslek konumuna geçiş dikey hareketliliktir. Gelir, eğitim ve meslek tabakalaşmanın göstergeleridir. Eğitim hareketlilik olanağı sağlayabilir; eşitsiz erişim fırsatları sınırlar.', 'tabakalaşma, yatay hareketlilik, dikey hareketlilik'],
 'SOS.11.4.1': ['Bir evde ebeveynler ve çocuklar, başka bir evde üç kuşak birlikte yaşar. Her iki aile bakım ve sorumlulukları paylaşır. Evlilik kararlarında rıza ve hukukî düzenlemeler önem taşır.', 'Çekirdek ve geniş aile hane yapıları farklıdır; bakım, dayanışma ve toplumsallaşma ortak işlevlerdir. Evlilik biçimleri tarihsel ve kültürel bağlamla değerlendirilir. Aile çeşitliliği bir biçimin üstünlüğünü kanıtlamaz; haklar ve rıza gözetilir.', 'çekirdek aile, geniş aile, toplumsallaşma'],
 'SOS.11.4.2': ['Bir okul temel bilgi ve meslek becerileri kazandırır. Öğrenciler birlikte çalışma kurallarını öğrenir. Ulaşım ve materyal olanakları öğrenciler arasında farklılaşır.', 'Eğitim bilgi ve beceri aktarır, toplumsallaşmayı ve ortak değerleri destekler. Meslek edinme hareketlilik sağlayabilir; eşitsiz olanaklar erişimi sınırlar. Eğitimin işlevleri bireysel başarı yanında toplumsal katılımla gerekçelendirilir.', 'eğitim, fırsat eşitliği, toplumsallaşma'],
 'SOS.11.4.3': ['Bir topluluk ortak dinî törenler düzenler ve ihtiyaç sahiplerine yardım eder. Aynı mahallede farklı inançlara sahip kişiler birlikte yaşar.', 'Din ortak sembol ve ritüellerle aidiyet, anlam ve dayanışma sağlayabilir. Yardımlaşma diğer kurumlarla ilişkiyi gösterir. İşlevler sosyolojik olarak açıklanır; inanç doğruluğu hakkında hüküm kurulmaz ve farklı inançların hakları gözetilir.', 'ritüel, dayanışma, aidiyet'],
 'SOS.11.4.4': ['Bir kentte özel işletmeler üretim yapar. Belediye ulaşım hizmeti sunar. Devlet iş güvenliği kuralları ve sosyal destekler uygular. Fiyat artışları ailelerin tüketim kararlarını etkiler.', 'Ekonomi üretim, dağıtım ve tüketimi düzenler. Piyasa sisteminde fiyat ve özel girişim, planlı sistemde merkezî kararlar öne çıkar; karma sistem farklı araçları birleştirir. Devlet müdahalesinin etkisi maliyet, erişim ve eşitlik kanıtlarıyla sınanır; tek gözlem kesin nedensellik kurmaz.', 'üretim, dağıtım, karma ekonomi'],
 'SOS.11.4.5': ['Bir belediye yeni park için bütçe ayırır. Mahalle sakinleri toplantıda farklı talepler sunar. Kararlar temsilciler ve hukukî kurallar aracılığıyla alınır.', 'Siyaset ortak karar, kaynak dağıtımı ve yönetim işlevlerini yürütür. Temsil, katılım ve meşruiyet kararların toplumla ilişkisini kurar. Taleplerin dinlenmesi katılımı, hukukî denetim yetkinin sınırlandırılmasını gösterir.', 'katılım, temsil, meşruiyet'],
 'SOS.11.4.6': ['İş saatleri değişince ailelerin bakım düzeni etkilenir. Okul ve belediye bakım desteği planlar. Çalışanların eğitime erişimi de yeniden düzenlenir.', 'Ekonomideki çalışma düzeni aile bakımını ve eğitim olanaklarını etkiler. Aile, okul ve yönetimin işlevleri karşılıklı bağımlıdır. Bakım desteği katılımı kolaylaştırabilir; kurumlar bağımsız adalar gibi açıklanamaz.', 'kurum, işlev, karşılıklı bağımlılık'],
 'SOS.11.5.1': ['Bir paylaşım tek bir kişinin davranışını bütün Müslümanlara mal eder. Mahallede bu paylaşıma dayanılarak bazı kişilerin hizmete erişimi engellenir. Başka sakinler doğrulanabilir bilgi ve eşit hakları savunur.', 'Tek kişinin davranışını bir inanç grubuna genellemek kanıtsız stereotipleştirmedir. İnanca dayalı hizmet engeli ayrımcılık oluşturur. İslamofobi önyargı ve dışlama ilişkisi içinde sorgulanır; doğrulanmış bilgi, eşit hak ve karşı örnekler kullanılarak gerekçeli çıkarım yapılır.', 'önyargı, stereotip, ayrımcılık'],
 'SOS.11.5.2': ['Yerel bir işletme başka ülkelerden malzeme alır ve çevrim içi satış yapar. Küresel ulaşım sorunu üretimi geciktirir. Müşteriler farklı kültürlerin ürünleriyle karşılaşır.', 'Küreselleşme ekonomi, iletişim ve kültür ağlarının etkileşimidir. Tedarik zinciri karşılıklı bağımlılığı, çevrim içi satış sınır aşan iletişimi gösterir. Kültürel etkileşim ve ekonomik kırılganlık birlikte değerlendirilir.', 'küreselleşme, tedarik zinciri, bağımlılık'],
 'SOS.11.5.3': ['Bir kurum işe alımda yapay zekâ kullanır. Sistem geçmiş kayıtlarla eğitilir. Bazı adaylar kararın gerekçesini öğrenemez ve itiraz yolu ister.', 'Geçmiş verideki eşitsizlik algoritmik kararlara taşınabilir. Şeffaflık, veri mahremiyeti ve insan denetimi toplumsal sorumlulukla ilişkilidir. Etki farklı grupların sonuçlarıyla incelenir; yapay zekânın otomatik olarak tarafsız olduğu varsayılmaz.', 'algoritmik yanlılık, mahremiyet, şeffaflık'],
 'SOS.12.1.1': ['Bir kentte hava kirliliği ölçülür. Araştırmacılar verileri açıklar, yurttaşlar ulaşım tercihlerinin etkisini tartışır. Belediye veriye dayalı düzenleme planlar.', 'Bilimsel araştırma toplumsal ihtiyaçlardan beslenir ve kararları etkiler. Ölçüm yöntemi, veri, yurttaş katılımı ve yönetim arasındaki ilişki bilgi üretimini açıklar. Toplumsal kullanımda belirsizlikler ve araştırmanın sınırları da paylaşılmalıdır.', 'bilim, veri, toplumsal ihtiyaç'],
 'SOS.12.1.2': ['Bir şirket araştırmayı finanse eder ve olumsuz sonuçların yayımlanmasını istemez. Araştırmacılar yöntem ve verileri bağımsız değerlendirmeye açmak ister.', 'Finansman araştırma gündemini ve yayımlanma koşullarını etkileyebilir. Çıkar çatışmasının açıklanması, bağımsız inceleme ve yayın özgürlüğü güvenilirliği destekler. Bilim ve iktidar ilişkisi somut kanıtlarla sorgulanır; finansman tek başına bulguyu yanlış kılmaz.', 'çıkar çatışması, bağımsızlık, iktidar'],
 'SOS.12.2.1': ['Bir kentte konut kiraları artar. Öğrenciler bunun göç, gelir ve konut arzıyla ilişkisini araştırır. Resmî istatistik ve farklı mahallelerdeki görüşmeler karşılaştırılır.', 'Kira artışı konut arzı, talep ve gelir ilişkisiyle sorgulanabilir. Tarihli istatistikler ve görüşmeler farklı kanıtlar sağlar. Mahalle farkları ve alternatif açıklamalar incelenir; korelasyon tek başına nedensellik değildir. Gerekçeli sonuç araştırmanın sınırlarını içerir.', 'toplumsal sorun, kanıt, nedensellik'],
};
type Input = { unitCode: string; outcomeCode: string; ordinal: number; kind: string; level: string; points: number; datasetVersion: string; mode: string; profile: string };
export function generateSociologyExamContent(input: Input) {
 if (input.datasetVersion !== sociology2026Package.manifest.datasetVersion) throw new Error('Sosyoloji sınavı için doğrulanmış 2026.1 gerekir.');
 if (!['text','short','open','scenario'].includes(input.kind) || !['standard','bep'].includes(input.mode)) throw new Error('Geçersiz soru türü veya sınav modu.');
 const unit = sociology2026Package.units.find(u=>u.code === input.unitCode);
 const outcome = unit?.outcomes.find(o=>o.code === input.outcomeCode);
 const components = outcome?.processComponents;
 const content = contexts[input.outcomeCode];
 if (!components?.length || !content || !Number.isInteger(input.ordinal) || input.ordinal < 0) throw new Error('Geçersiz Sosyoloji ünite/çıktı/bileşen eşleşmesi.');
 const component = components[input.ordinal % components.length];
 const [context, answer, concepts] = content;
 const tasks: Record<string,string> = {understand:'İlgili kavramları açıklayınız.',apply:'Kavramları bu örneğe uygulayınız.',analyze:'İlişkileri ve dayanaklarını çözümleyiniz.',evaluate:'Kanıtın yeterliğini ve alternatif açıklamayı değerlendiriniz.',create:'Bu konuda kanıtla sınanabilecek bir araştırma sorusu ve veri toplama planı oluşturunuz.'};
 if (!tasks[input.level]) throw new Error('Geçersiz bilişsel düzey.');
 const variations = ['Örnekten iki dayanak seçiniz.', 'Olası bir karşı örnekle açıklamanızın sınırını belirtiniz.', 'Bir alternatif açıklama ve onu sınayacak kanıt belirtiniz.', 'Bir neden ile bir sonucu ayırarak açıklayınız.', 'Örneğin başka bir toplumsal bağlama taşınmasını tartışınız.', 'Bir iddia ile gözlem bilgisini ayırınız.', 'Eksik bilgiyi ve onu toplama yolunu belirtiniz.', 'Sonucun hangi koşullarda değişebileceğini tartışınız.'];
 const variation = variations[Math.floor(input.ordinal / components.length) % variations.length];
 const focus = `İnceleme odağı: ${component.description}`;
 let passage = input.kind === 'text' ? context : '';
 let text = `${input.kind === 'text' ? '' : `${context}\n`}${focus}\n${tasks[input.level]} Yanıtınızı örnekteki bilgilerle gerekçelendiriniz. ${variation}${input.kind === 'short' ? ' Kısa ve öz yanıt veriniz.' : ''}`;
 let fontSize = 22;
 if (input.mode === 'bep') {
  switch(input.profile) {
   case 'reading': passage = passage.replaceAll('. ', '.\n\n'); text = text.replaceAll('. ', '.\n'); text = `${text}\n1. Örneği bölüm bölüm okuyunuz.\n2. Odağı izleyip yanıtınızı veriniz.`; break;
   case 'writing': text += '\nYanıtınızı maddelerle veya öğretmeninizin kaydettiği sözlü anlatımla verebilirsiniz. Cümle başlatıcı: Bu örnekte … çünkü …'; break;
   case 'attention': text += '\nÖnce örneği inceleyiniz. Ardından yalnız bu soruya yanıt veriniz. Gerektiğinde öğretmeninizle kısa ara planlayınız.'; break;
   case 'cognitive': text += `\nKavram desteği: ${concepts}. Önce ilgili kavramı seçiniz; ardından örnekle bağlantısını kurunuz.`; break;
   case 'visual': fontSize = 32; break;
   default: throw new Error('Geçersiz BEP sunum profili.');
  }
 }
 return {passage,text,answer:`Örnek yanıt: ${answer} ${input.level === 'create' ? 'Araştırma planı bir soru, uygun örneklem, veri toplama yolu ve etik önlem içermelidir.' : ''}`.trim(),
  criterion:`${focus} • İlgili kavram ve örnek kanıtı: %40 • Bileşene ilişkin gerekçeli açıklama: %40 • Tutarlı sonuç ve sorunun tamamlanması: %20. Eşdeğer gerekçeli yanıtlar kabul edilir; sunum biçimi ayrıca puan kaybettirmez.`,
  componentStep:component.step,componentDescription:component.description,fontSize};
}
export function validSociologyExamTrace(unitCode: string, outcomeCode: string, step?: string, description?: string) {
 return sociology2026Package.units.find(u=>u.code === unitCode)?.outcomes.find(o=>o.code === outcomeCode)?.processComponents?.some(c=>c.step === step && c.description === description) ?? false;
}
